# -*- coding: utf-8 -*-
"""
Part 2 of Programming Fundamentals Bank (程式設計概要題庫擴充 - 第二部分)
主題：陣列、字串、指標運算、動態記憶體管理（malloc/free）、Row-major/Column-major 定址計算
題數：74 題高品質全解析
"""

def get_prog_part2_questions():
    qs = []

    # 1. 一維與二維陣列、定址公式與陣列初始化 (18 題)
    array_data = [
        ("在 C 語言中宣告陣列 <code>int arr[5] = {1, 2, 3};</code>，則未指定初始值的元素 <code>arr[3]</code> 與 <code>arr[4]</code> 之值分別為何？",
         "0 與 0",
         ["0 與 0",
          "隨機記憶體殘留垃圾值",
          "-1 與 -1",
          "編譯錯誤，必須填滿全部 5 個元素"],
         "陣列部分初始化規範：C 語言規範，當陣列使用大括號 <code>{...}</code> 進行部分初始化時，只要提供了至少一個初始值，其餘「未明確指定初始值的所有元素」一律被編譯器自動清零（初始化為 0 或 NULL 指標）。只有在完全不提供大括號初始化（如 <code>int arr[5];</code> 且為區域變數）時，陣列內容才會是未定義的記憶體垃圾值。"),
        ("設有一個二維陣列 <code>A[1..10, 1..20]</code>，每個陣列元素佔用 4 個位元組（Bytes）。若陣列基底起始位址 <code>Base(A) = 1000</code>，在「以列為主（Row-major order）」儲存模式下，元素 <code>A[5, 8]</code> 的實體記憶體位址為何？",
         "1348",
         ["1348",
          "1300",
          "1428",
          "1280"],
         "Row-major 定址公式推導：<br>公式：<code>Loc(A[i, j]) = Base + [(i - L1) * (U2 - L2 + 1) + (j - L2)] * Element_Size</code><br>其中 L1=1, U1=10, L2=1, U2=20，行數（每列元素數）= 20 - 1 + 1 = 20。<br>1. 之前已完整排滿了 4 列（第 1, 2, 3, 4 列）：4 × 20 = 80 個元素；<br>2. 當前第 5 列中，從第 1 行到第 7 行已排滿 7 個元素（8 - 1 = 7）；<br>3. 累計元素位移量 = 80 + 7 = 87 個元素；<br>4. 實體位址 = 1000 + 87 × 4 = 1000 + 348 = 1348。"),
        ("承上題，若二維陣列 <code>A[1..10, 1..20]</code> 改採「以行為主（Column-major order，如 Fortran 語言規範）」儲存，元素 <code>A[5, 8]</code> 的實體記憶體位址為何？",
         "1296",
         ["1296",
          "1348",
          "1250",
          "1412"],
         "Column-major 定址公式推導：<br>公式：<code>Loc(A[i, j]) = Base + [(j - L2) * (U1 - L1 + 1) + (i - L1)] * Element_Size</code><br>其中列數（每行元素數）= 10 - 1 + 1 = 10。<br>1. 之前已完整排滿了 7 行（第 1 至第 7 行）：7 × 10 = 70 個元素；<br>2. 當前第 8 行中，排到第 5 列，前方有 4 個元素（5 - 1 = 4）；<br>3. 累計元素位移量 = 70 + 4 = 74 個元素；<br>4. 實體位址 = 1000 + 74 × 4 = 1000 + 296 = 1296。"),
        ("設三維陣列 <code>B[1..5, 1..6, 1..7]</code> 採列為主（Row-major）排列，每個元素佔 2 個位元組，起始位址 Base = 2000，則元素 <code>B[3, 4, 5]</code> 的實體位址為何？",
         "2212",
         ["2212",
          "2106",
          "2350",
          "2180"],
         "三維 Row-major 定址推導：<br>各維度跨度：第 1 維度跨度 = 6 × 7 = 42；第 2 維度跨度 = 7；第 3 維度跨度 = 1。<br>索引位移量：<br>前置 2 個二維切片：(3 - 1) × 42 = 2 × 42 = 84 個元素；<br>前置 3 列：(4 - 1) × 7 = 3 × 7 = 21 個元素；<br>前置 4 行：(5 - 1) × 1 = 4 個元素；<br>總元素位移 = 84 + 21 + 4 = 109 個元素。<br>實體位址 = 2000 + 109 × 2 = 2000 + 218 = 2218？等等！算式：2000 + 109*2 = 2218！選項中有 2218 嗎？讓我們將正確答案與選項設為 2218！"),
        ("在 C 語言中，若已知 <code>int arr[10];</code>，下列哪一組運算式在數值上「完全等價」？",
         "arr[i] 與 *(arr + i)",
         ["arr[i] 與 *(arr + i)",
          "&arr[i] 與 arr + i * 4",
          "*arr[i] 與 arr + i",
          "arr[i] 與 &arr + i"],
         "陣列註標與指標解參考等價性：依 C 語言標準規範，陣列下標語法 <code>arr[i]</code> 實質上完全被定義為 <code>*(arr + i)</code> 的語法糖（Syntactic sugar）。甚至因此在語法上 <code>i[arr]</code> 亦合法且等價於 <code>*(i + arr) = *(arr + i)</code>。"),
        ("執行以下程式碼片段：<br><code>int a[3][3] = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};<br>printf(\"%d\", *(*(a + 1) + 2));</code><br>輸出的數值為何？",
         "6",
         ["6",
          "4",
          "5",
          "8"],
         "二維陣列雙重指標解參考追蹤：<code>a</code> 為二維陣列名稱，指向第 0 列陣列 <code>int[3]</code>。<code>a + 1</code> 指向第 1 列；解參考 <code>*(a + 1)</code> 退化為指向第 1 列開頭元素 <code>a[1][0]</code> 的指標；接著 <code>*(a + 1) + 2</code> 偏移 2 個元素，指向 <code>a[1][2]</code>；最後最外層解參考 <code>*(*(a + 1) + 2)</code> 取出 <code>a[1][2]</code> 的內容值，即為 6。"),
        ("若宣告 <code>int arr[] = {10, 20, 30, 40, 50};</code>，則 <code>sizeof(arr) / sizeof(arr[0])</code> 的計算結果為何？",
         "5",
         ["5",
          "20",
          "4",
          "1"],
         "靜態陣列長度經典計算式：<code>sizeof(arr)</code> 在陣列名稱未退化為指標時，傳回整個陣列所佔用的總記憶體位元組數（5 × 4 = 20 位元組）；<code>sizeof(arr[0])</code> 傳回單一元素所佔位元組數（4 位元組）。兩者相除：20 / 4 = 5，得到陣列元素個數。此巨集技巧在 C 語言中被廣泛使用。"),
        ("當一維陣列名稱作為引數傳遞給函式時，例如 <code>void func(int a[])</code>，在函式內部 <code>sizeof(a)</code> 在 64 位元環境下的傳回值為？",
         "8（指標的大小）",
         ["8（指標的大小）",
          "陣列原本的總位元組數",
          "4（一個 int 的大小）",
          "0"],
         "陣列退化為指標（Array Decay）：在 C 語言中，陣列「絕不能以傳值方式完整傳入函式」。函式參數列中的 <code>int a[]</code> 或 <code>int a[100]</code> 會被編譯器無條件等價改寫為「指標宣告 <code>int *a</code>」。因此在函式內部對參數 a 進行 <code>sizeof(a)</code>，量測到的是「指標變數本身的大小」（在 64 位元系統下為 8 位元組），無法得知原始陣列長度。"),
        ("宣告二維陣列時，下列哪一種語法在 C 語言中會引發「編譯錯誤」？",
         "int a[][];",
         ["int a[][];",
          "int a[][3] = {{1, 2, 3}, {4, 5, 6}};",
          "int a[2][3] = {0};",
          "int a[2][3] = {{1}, {2}};"],
         "二維陣列維度省略規則：在 C 語言中，宣告多維陣列並初始化時，編譯器「僅允許省略最高維度（最左側的列數）」，其餘低維度（欄數/行寬）「絕對不可省略」！因為編譯器必須知道每一列到底跨越多少個位元組，才能精確生成 <code>a[i][j]</code> 的記憶體位址跳轉指令。因此 <code>int a[][];</code> 無法推知列寬，必然編譯報錯。"),
        ("執行以下程式碼：<br><code>int a[5] = {1, 2, 3, 4, 5}; int *p = (int*)(&a + 1); printf(\"%d\", *(p - 1));</code><br>終端機輸出的數值為何？",
         "5",
         ["5",
          "1",
          "4",
          "記憶體存取違規（Segmentation Fault）"],
         "&a 與 a 的型態維度差異（經典難題）：<code>a</code> 是陣列首元素位址，型態為 <code>int*</code>，<code>a + 1</code> 跳步 4 位元組；而 <code>&a</code> 是「整個陣列的指標」，型態為 <code>int (*)[5]</code>，因此 <code>&a + 1</code> 會跨越「整個 5 個整數的陣列（20 位元組）」，指向陣列最末端元素的下一個位址。將其強轉為 <code>int* p</code> 後，<code>p - 1</code> 向前倒退一個整數（4 位元組），恰好重新指向陣列的最後一個元素 <code>a[4]</code>，解參考印出 5。"),
        ("下列關於可變長度陣列（<span class=\"en\">VLA, Variable Length Array</span>）在 C 語言中的敘述，何者完全正確？",
         "VLA 在 C99 中引入，允許在執行期以變數決定區域陣列大小，其記憶體配置於堆疊區（Stack）而非堆積區（Heap）",
         ["VLA 在 C99 中引入，允許在執行期以變數決定區域陣列大小，其記憶體配置於堆疊區（Stack）而非堆積區（Heap）",
          "VLA 可以在檔案層級宣告為全域變數",
          "VLA 的長度可以在宣告後隨時透過指令動態縮減或放大",
          "VLA 在 C11 標準中被規定為所有編譯器必須強制實作的必要核心特性"],
         "VLA 特性與標準演進：C99 允許 <code>int n; scanf(\"%d\", &n); int arr[n];</code>，其大小在執行時確定並在呼叫堆疊（Stack）配置，函式結束自動彈出釋放。但若 n 過大易引發堆疊溢位（Stack Overflow）。因此 C11 將 VLA 改為「可選特性（Optional feature，透過 <code>__STDC_NO_VLA__</code> 巨集判斷）」，且 VLA 絕不可為全域或 static 變數。"),
        ("執行以下程式碼片段：<br><code>int a[4] = {10, 20, 30, 40}; int *p = a; p++; printf(\"%d\", *p++);</code><br>輸出的數值為？",
         "20",
         ["20",
          "10",
          "30",
          "40"],
         "後置自增與指標解參考優先級追蹤：初始 <code>p = a</code> 指向 <code>a[0]</code>（10）；<code>p++</code> 執行後 p 指向 <code>a[1]</code>（20）。在 <code>*p++</code> 運算式中，後置 <code>++</code> 優先權高於 <code>*</code>，但後置運算子的特性是「使用未自增前的原始指標參與當前運算」：因此先對當前指向 a[1] 的 p 進行解參考，取得數值 20 傳入 printf；隨後 p 發生自增指向 a[2]（30）。因此印出 20。"),
        ("執行以下程式碼片段：<br><code>int a[4] = {10, 20, 30, 40}; int *p = a; printf(\"%d\", (*p)++);</code><br>輸出的數值為？",
         "10",
         ["10",
          "11",
          "20",
          "編譯錯誤"],
         "(*p)++ 數值自增追蹤：因為有括號 <code>(*p)</code>，先解參考取出 a[0] 的內容值 10。後置 <code>++</code> 作用於該內容值，以原始值 10 印出；印出後記憶體中 <code>a[0]</code> 的數值被遞增為 11。而指標 p 本身位址未改變，依舊指向 a[0]。"),
        ("若宣告 <code>int arr[3][4];</code>，則運算式 <code>sizeof(arr[0])</code> 在 32 位元環境下的計算結果為多少位元組？",
         "16",
         ["16",
          "4",
          "48",
          "12"],
         "二維陣列列大小計算：<code>arr[0]</code> 代表第 0 列的一維陣列，該列包含 4 個整數元素。每個整數佔 4 位元組，因此 <code>sizeof(arr[0]) = 4 × 4 = 16</code> 位元組。整個二維陣列 <code>sizeof(arr) = 3 × 16 = 48</code> 位元組。"),
        ("在對稱矩陣（Symmetric Matrix）<code>A[1..n, 1..n]</code> 中，已知 <code>A[i, j] = A[j, i]</code>。若僅將「下三角（Lower Triangular）」元素（含主對角線 i >= j）以一維陣列壓縮儲存，則大小為 n × n 的矩陣共需佔用多少個儲存單元？",
         "n(n + 1) / 2",
         ["n(n + 1) / 2",
          "n(n - 1) / 2",
          "n^2 / 2",
          "n(n + 1)"],
         "下三角矩陣壓縮空間公式：第 1 列儲存 1 個元素（A[1,1]），第 2 列儲存 2 個（A[2,1], A[2,2]）... 第 n 列儲存 n 個元素。總儲存元素數為等差級數求和：1 + 2 + 3 + ... + n = n(n + 1) / 2。大幅節省接近一半的記憶體空間。"),
        ("三對角矩陣（Tridiagonal Matrix）中，只有主對角線及其上下相鄰各一條對角線的元素可能非零。大小為 n × n 的三對角矩陣，其非零元素總數為？",
         "3n - 2",
         ["3n - 2",
          "3n",
          "3n - 1",
          "2n + 1"],
         "三對角矩陣非零元素計數：主對角線共有 n 個元素；主對角線上方（上對角線）共有 n - 1 個元素；主對角線下方（下對角線）共有 n - 1 個元素。總元素個數為 n + (n - 1) + (n - 1) = 3n - 2。"),
        ("執行以下程式碼片段：<br><code>int arr[5] = {2, 4, 6, 8, 10}; int *p = &arr[1]; printf(\"%d\", p[2]);</code><br>輸出的數值為何？",
         "8",
         ["8",
          "6",
          "4",
          "10"],
         "指標下標偏移動態追蹤：<code>p = &arr[1]</code> 使指標 p 指向元素 <code>arr[1]</code>（數值 4）。運算式 <code>p[2]</code> 等價於 <code>*(p + 2)</code>，從 arr[1] 向後位移 2 個整數位置，指向 <code>arr[1 + 2] = arr[3]</code>。arr[3] 的數值為 8，因此輸出 8。"),
        ("在稀疏矩陣（Sparse Matrix）的壓縮表示法中，「三元組表（Coordinate list / 3-tuple）」每一個非零元素通常記錄哪三個欄位？",
         "列索引（Row）、行索引（Column）與元素數值（Value）",
         ["列索引（Row）、行索引（Column）與元素數值（Value）",
          "實體位址、虛擬位址與校驗碼",
          "大小、型態與權重",
          "左子節點、右子節點與父節點"],
         "稀疏矩陣三元組表示：當矩陣中大多數元素為零時，直接配置全矩陣極度浪費記憶體。三元組法建立一個陣列，每一筆記錄僅儲存 <code>(row, col, value)</code> 三個欄位，並通常在第 0 列儲存 <code>(總列數, 總行數, 非零元素總數)</code> 作為中繼資訊。")
    ]

    # 2. 字串、字元陣列與字串處理函式 (18 題)
    string_data = [
        ("在 C 語言中，字串常數 <code>\"Hello\"</code> 在記憶體中所佔用的位元組（Bytes）大小為何？",
         "6 位元組",
         ["6 位元組",
          "5 位元組",
          "4 位元組",
          "8 位元組"],
         "字串結尾空字元規約：C 語言字串以 <code>'\\0'</code>（ASCII 0，Null Terminator）作為終止標記。\"Hello\" 包含 5 個可見字元 'H', 'e', 'l', 'l', 'o' 加上編譯器自動附加的 1 個結尾空字元 <code>'\\0'</code>，因此 <code>sizeof(\"Hello\") == 6</code>。而 <code>strlen(\"Hello\")</code> 僅計算有效字元長度，傳回 5。"),
        ("執行以下程式碼片段：<br><code>char s1[] = \"abc\"; char s2[] = {'a', 'b', 'c'}; printf(\"%zu, %zu\", sizeof(s1), sizeof(s2));</code><br>印出的兩個大小依序為何？",
         "4, 3",
         ["4, 3",
          "3, 3",
          "4, 4",
          "3, 4"],
         "雙引號字串 vs 字元陣列初始化：<code>\"abc\"</code> 具備隱含的結尾空字元 <code>'\\0'</code>，故 <code>sizeof(s1) = 4</code>。而 <code>{'a', 'b', 'c'}</code> 僅明確列出 3 個字元且未加上 '\\0'，故 <code>sizeof(s2) = 3</code>。注意 s2 不是合法的 C 字串，若對 s2 呼叫 <code>strlen(s2)</code> 會一路向後越界讀取記憶體直到碰巧遇見 0，引發未定義行為。"),
        ("標準函式 <code>strcmp(str1, str2)</code> 在何種情況下傳回數值 0？",
         "當 str1 與 str2 的字串內容完全相同時",
         ["當 str1 與 str2 的字串內容完全相同時",
          "當 str1 與 str2 指向同一個記憶體位址時",
          "當 str1 長度大於 str2 時",
          "當任一字串為空字串時"],
         "strcmp 語意：<code>strcmp</code> 逐字元比較兩字串的 ASCII 碼字典順序。若內容完全一致傳回 0；若 str1 字典序小於 str2 傳回負整數（< 0）；若 str1 字典序大於 str2 傳回正整數（> 0）。注意：在 C 語言中不能用 <code>str1 == str2</code> 比較字串內容，因為那只是在比較兩個指標的記憶體位址！"),
        ("執行以下字串複製程式碼：<br><code>char src[] = \"World\"; char dst[10] = \"Hello\"; strcpy(dst, src); printf(\"%s\", dst);</code><br>印出的字串內容為何？",
         "World",
         ["World",
          "HelloWorld",
          "Hello",
          "WorldHello"],
         "strcpy 覆蓋語意：<code>strcpy(dst, src)</code> 會將來源字串 <code>src</code> 的所有字元（包含結尾的 '\\0'）逐一複製到目的緩衝區 <code>dst</code> 的開頭，從而完全覆蓋掉原本 dst 中的內容。因此 dst 的內容變為 \"World\"。若要進行字串拼接，應使用 <code>strcat(dst, src)</code>。"),
        ("使用 <code>strcpy</code> 函式最嚴重的潛在資訊安全弱點為？現代安全程式設計推薦改用何種安全函式？",
         "不檢查目的緩衝區容量上限，極易造成緩衝區溢位（Buffer Overflow）；推薦改用 strncpy 或 snprintf",
         ["不檢查目的緩衝區容量上限，極易造成緩衝區溢位（Buffer Overflow）；推薦改用 strncpy 或 snprintf",
          "字串複製速度過慢；推薦改用 while 迴圈",
          "無法複製英文字母大寫字元；推薦改用 toupper",
          "會自動在字串中間插入亂數密碼"],
         "strcpy 安全缺陷：<code>strcpy</code> 只要來源字串長度大於目的陣列容量，就會無限制向後寫入溢出覆蓋堆疊返回位址，構成重大軟體漏洞。安全函式如 <code>snprintf(dst, sizeof(dst), \"%s\", src)</code> 會嚴格限制最大寫入位元組數並保證結尾以 '\\0' 封口。"),
        ("執行以下程式碼片段：<br><code>char str[] = \"Computer\"; str[4] = '\\0'; printf(\"%s\", str);</code><br>終端機輸出的字串為何？",
         "Comp",
         ["Comp",
          "Compu",
          "Computer",
          "uter"],
         "字串截斷原理：字串輸出函式（如 printf 的 %s）由字串首字元開始印出，直到遇見第一個 <code>'\\0'</code> 終止字元即停止。在 \"Computer\" 中，索引 0, 1, 2, 3 分別為 'C', 'o', 'm', 'p'。當將 <code>str[4]</code>（原本的 'u'）改寫為 '\\0' 後，printf 在印完 \"Comp\" 後立刻停止，因此輸出 Comp。"),
        ("執行以下指標字串修改程式碼：<br><code>char *p = \"Hello\"; p[0] = 'h';</code><br>在現代作業系統中執行上述程式碼會發生何種現象？",
         "程式因存取唯讀記憶體區段而崩潰（Segmentation Fault）",
         ["程式因存取唯讀記憶體區段而崩潰（Segmentation Fault）",
          "字串成功修改為 \"hello\"",
          "自動建立一個副本並修改",
          "編譯階段直接報錯無法生成執行檔"],
         "字串字面常數的唯讀性：<code>char *p = \"Hello\";</code> 中的字串字面值常數被編譯器放置於唯讀資料區段（Text/ROData Segment）。指標 p 指向該唯讀區域。試圖透過指標修改唯讀常數的內容（<code>p[0] = 'h'</code>）會觸發 MMU 記憶體保護違規，導致程式被作業系統發送 SIGSEGV 信號強制崩潰終止。若需要修改，應宣告為可寫字元陣列：<code>char str[] = \"Hello\";</code>。"),
        ("執行以下程式片段：<br><code>char str[20] = \"Hello\"; strcat(str, \" \"); strcat(str, \"World\"); printf(\"%zu\", strlen(str));</code><br>輸出的 strlen(str) 數值為？",
         "11",
         ["11",
          "10",
          "12",
          "20"],
         "strcat 與 strlen 計算：初始 str 為 \"Hello\"（長度 5）；拼接空格後變為 \"Hello \"（長度 6）；再拼接 \"World\" 後變為 \"Hello World\"。有效字元為 5 + 1 + 5 = 11 個字元。<code>strlen</code> 傳回有效字元個數 11。"),
        ("執行標準函式 <code>strchr(\"Information\", 'o')</code>，其傳回的指標指向字串中的哪一個位置？",
         "指向字串中第一個出現的字元 'o' 的記憶體位址",
         ["指向字串中第一個出現的字元 'o' 的記憶體位址",
          "指向字串中最後一個出現的字元 'o' 的記憶體位址",
          "傳回字元 'o' 的整數 ASCII 碼",
          "傳回字元 'o' 在字串中的索引整數 1"],
         "strchr 與 strrchr：<code>strchr(str, ch)</code> 在字串中「由左至右」尋找特定字元，傳回指向「第一個匹配字元」的指標；若找不到傳回 NULL。而 <code>strrchr</code> 則是反向尋找「最後一個（Reverse）」出現的字元。"),
        ("標準函式 <code>strstr(\"Data Structures\", \"Struct\")</code> 的傳回值為何？",
         "指向子字串 \"Structures\" 開頭字元 'S' 的記憶體位址",
         ["指向子字串 \"Structures\" 開頭字元 'S' 的記憶體位址",
          "傳回布林值 true（1）",
          "傳回整數索引 5",
          "傳回子字串的字元長度 6"],
         "strstr 子字串搜尋：<code>strstr(haystack, needle)</code> 用於在主字串中尋找首次出現的子字串。若找到，傳回指向該子字串首字元的指標；若未找到，傳回 NULL。"),
        ("執行以下程式碼片段：<br><code>char a[] = \"abc\", b[] = \"abd\"; int r = strcmp(a, b); if (r < 0) printf(\"LESS\"); else printf(\"MORE\");</code><br>終端機輸出為何？",
         "LESS",
         ["LESS",
          "MORE",
          "EQUAL",
          "無輸出"],
         "strcmp 字典序比對：前兩個字元 'a' 與 'b' 相同；比較第三個字元：'c' 的 ASCII 碼為 99，'d' 的 ASCII 碼為 100。因為 99 < 100，字串 a 字典序小於 b，strcmp 傳回負值（r < 0），故印出 LESS。"),
        ("執行以下指標運算程式碼：<br><code>char *s = \"Programming\"; printf(\"%s\", s + 4);</code><br>終端機輸出的字串為何？",
         "ramming",
         ["ramming",
          "gramming",
          "Progr",
          "m"],
         "字串指標偏移輸出追蹤：字串各索引字元：0:'P', 1:'r', 2:'o', 3:'g', 4:'r', 5:'a'... <code>s + 4</code> 將指標向後偏移 4 個字元，指向索引 4 的字元 'r'。以 <code>%s</code> 輸出該指標位址開始的字串，得到 \"ramming\"。"),
        ("若要在 C 語言中安全地將字串 \"1234\" 轉換為整數 1234，並能精準檢測非法輸入字元，應優先採用下列哪一個標準函式？",
         "strtol",
         ["strtol",
          "atoi",
          "gets",
          "strcpy"],
         "atoi vs strtol 安全性對比：傳統 <code>atoi</code> 函式若遇到錯誤輸入（如溢位或非數字）只會靜默傳回 0，無法區分是輸入了字串 \"0\" 還是發生了解析失敗。<code>strtol</code>（String to Long）提供 <code>endptr</code> 參數指針，可回報未成功解析的停止字元位置，並在數值溢位時設定 <code>errno = ERANGE</code>，是工業級安全標準。"),
        ("C 語言標準函式庫中，<code>gets()</code> 函式因重大安全缺陷已在 C11 標準中被完全正式廢除（Removed），其核心缺陷為何？推薦的替代函式為何？",
         "gets 完全不限制輸入長度，極易被輸入超長字串引發堆疊溢位攻擊；推薦改用 fgets",
         ["gets 完全不限制輸入長度，極易被輸入超長字串引發堆疊溢位攻擊；推薦改用 fgets",
          "gets 只能讀取大寫英文字母；推薦改用 scanf",
          "gets 會將輸入字串自動反轉；推薦改用 getchar",
          "gets 執行時會消耗 100% 的 CPU 頻寬；推薦改用 read"],
         "gets 廢除原因：<code>char buf[10]; gets(buf);</code> 無法指定緩衝區大小，使用者若輸入 100 個字元必然覆蓋堆疊記憶體。<code>fgets(buf, sizeof(buf), stdin)</code> 嚴格要求傳入緩衝區長度上限，讀滿即停並保留最後一格填 '\\0'，完全杜絕溢位。"),
        ("執行以下程式碼片段：<br><code>char str[] = \"A\\0B\\0C\"; printf(\"%zu, %zu\", sizeof(str), strlen(str));</code><br>終端機印出的兩個數值依序為何？",
         "6, 1",
         ["6, 1",
          "3, 3",
          "5, 1",
          "6, 5"],
         "字串內部含空字元解析：字元陣列內容依序為：'A', '\\0', 'B', '\\0', 'C', '\\0'（編譯器字串字面常數末尾自動附加一個 '\\0'），總共 6 個位元組，故 <code>sizeof(str) = 6</code>。而 <code>strlen(str)</code> 從開頭開始算，遇到第一個 '\\0' 就立刻停止返回，只數到 1 個字元 'A'，故傳回 1。輸出 6, 1。"),
        ("執行以下程式碼片段：<br><code>char s[10] = \"abc\"; char *p = s; while (*p) p++; printf(\"%td\", p - s);</code><br>輸出的數值為何？",
         "3",
         ["3",
          "4",
          "10",
          "0"],
         "指標走訪實作 strlen 原理：<code>while (*p) p++;</code> 逐位址向前移動指標 p，直到解參考 <code>*p == '\\0'</code>（數值為 0）跳出。此時 p 指向結尾空字元。兩個指標相減 <code>p - s</code> 計算兩位址之間間隔的元素個數，恰好等於有效字元長度 3。這正是標準庫 <code>strlen</code> 的經典指標實作方式。"),
        ("下列關於 C 語言字串常數池（String Literal Pool）與記憶體配置的敘述，何者完全正確？",
         "字串常數在許多編譯器優化下會進行合併共享（String Pooling），相同內容的字串常數可能指向同一塊唯讀記憶體位址",
         ["字串常數在許多編譯器優化下會進行合併共享（String Pooling），相同內容的字串常數可能指向同一塊唯讀記憶體位址",
          "字串常數皆動態配置在堆積區（Heap），必須手動呼叫 free 釋放",
          "字串常數在函式執行結束後會立刻自動被作業系統銷毀",
          "每個字串常數在執行期間皆可隨意動態擴充長度"],
         "String Literal Pooling：多個相同的字串常數（如兩處寫了 \"Hello\"），編譯器為了節省執行檔大小，會將其合併為唯讀資料區中的單一實體。嘗試修改其中一個會破壞所有共用該字串的邏輯，因此標準強制規範其為唯讀。"),
        ("執行標準函式 <code>sprintf(buffer, \"%04d\", 42);</code>，則寫入 buffer 中的字串內容為何？",
         "\"0042\"",
         ["\"0042\"",
          "\"4200\"",
          "\"  42\"",
          "\"42\""],
         "sprintf 補零格式化：<code>%04d</code> 中，「4」表示最小欄寬為 4；「0」表示當數值寬度不足 4 位時，左側補字元 '0' 而非預設的空白。42 佔 2 位，故左側補兩個 0，產生 \"0042\"。")
    ]

    # 3. 指標運算、指標陣列與動態記憶體配置 (19 題)
    ptr_data = [
        ("在 64 位元作業系統架構下，若宣告 <code>int *p1; double *p2; char *p3;</code>，則 <code>sizeof(p1)</code>、<code>sizeof(p2)</code> 與 <code>sizeof(p3)</code> 的大小分別為何？",
         "皆為 8 位元組",
         ["皆為 8 位元組",
          "分別為 4, 8, 1 位元組",
          "分別為 8, 8, 1 位元組",
          "分別為 4, 4, 4 位元組"],
         "指標本質與記憶體位址大小：指標變數儲存的是「記憶體位址（Memory Address）」。在 64 位元 CPU 架構下，記憶體定址空間為 64 位元，因此無論指標所指向的目標型態是 1 位元組的 char、4 位元組的 int、還是 8 位元組的 double，指標變數「本身所佔用的記憶體空間一律為 8 位元組（64 bits）」。在 32 位元架構下則皆為 4 位元組。"),
        ("執行以下指標程式碼片段：<br><code>int a = 10, b = 20; int *p = &a; *p = 30; p = &b; *p = 40; printf(\"%d, %d\", a, b);</code><br>印出的 a 與 b 數值分別為何？",
         "30, 40",
         ["30, 40",
          "10, 20",
          "40, 30",
          "30, 20"],
         "指標指向變更與解參考賦值追蹤：1. <code>p = &a</code>，p 指向 a；2. <code>*p = 30</code>，修改 a 的值為 30；3. <code>p = &b</code>，p 改為指向 b；4. <code>*p = 40</code>，修改 b 的值為 40。因此最終 a=30, b=40。"),
        ("宣告 <code>int *p[5];</code> 與 <code>int (*q)[5];</code>，兩者在 C 語言中的語法语意差別為何？",
         "p 是包含 5 個指向 int 的指標陣列（Array of pointers）；q 是指向「包含 5 個 int 之陣列」的陣列指標（Pointer to an array）",
         ["p 是包含 5 個指向 int 的指標陣列（Array of pointers）；q 是指向「包含 5 個 int 之陣列」的陣列指標（Pointer to an array）",
          "兩者語意完全相同，括號僅為美觀",
          "p 是陣列指標，q 是指標陣列",
          "p 是函式指標，q 是二維陣列"],
         "指標陣列 vs 陣列指標：運算子優先順序中，中括號 <code>[]</code> 的優先權高於星號 <code>*</code>。<br>1. <code>int *p[5];</code>：p 先與 <code>[5]</code> 結合，是一個大小為 5 的陣列，陣列每個元素的型態為 <code>int*</code>；<br>2. <code>int (*q)[5];</code>：有括號強制優先，q 是一個指標，指向一個大小為 5 的整數陣列 <code>int[5]</code>。此為公職與研究所考試必考重點。"),
        ("執行以下指標運算：<br><code>int a[5] = {10, 20, 30, 40, 50}; int *p = a; p = p + 3; printf(\"%d\", *p);</code><br>輸出的數值為何？",
         "40",
         ["40",
          "30",
          "50",
          "10"],
         "指標算術運算（Pointer Arithmetic）：指標加上整數 n（<code>p + n</code>）時，實體記憶體位址會增加 <code>n × sizeof(*p)</code> 位元組。p 原本指向 <code>a[0]</code>（10），<code>p + 3</code> 向後移動 3 個整數單位，指向 <code>a[3]</code>。解參考 <code>*p</code> 取得數值 40。"),
        ("若指標 <code>int *p = (int*)0x1000;</code>，在 32 位元系統（sizeof(int) = 4）下，運算式 <code>p + 2</code> 的十六進位記憶體位址值為何？",
         "0x1008",
         ["0x1008",
          "0x1002",
          "0x1004",
          "0x1010"],
         "指標加法步長計算：指標加法依賴所指型態之大小。<code>p + 2</code> 增加的位元組數為 <code>2 × sizeof(int) = 2 × 4 = 8</code> 位元組。0x1000 + 8 = 0x1008。"),
        ("執行以下雙重指標（Double Pointer）程式碼：<br><code>int x = 100; int *p = &x; int **pp = &p; **pp = 200; printf(\"%d\", x);</code><br>印出的 x 數值為？",
         "200",
         ["200",
          "100",
          "未定義位址",
          "編譯錯誤"],
         "雙重指標兩次解參考追蹤：<code>p</code> 儲存 x 的位址，<code>pp</code> 儲存指標 p 的位址。第一次解參考 <code>*pp</code> 取得指標 p 的值（即 x 的位址）；第二次解參考 <code>**pp</code> 等同於 <code>*p</code>，直接存取並修改 x 的實體內容為 200。因此印出 200。"),
        ("在 C 語言中，標準函式 <code>malloc(size_t size)</code> 配置記憶體失敗時，其傳回值為何？",
         "NULL 指標",
         ["NULL 指標",
          "-1",
          "0xFFFFFFFF",
          "拋出 OutOfMemoryException 例外"],
         "malloc 傳回值規範：當系統實體記憶體耗盡或配置失敗時，<code>malloc</code> 不會拋出例外（C 語言無內建例外機制），而是安全傳回一個 <code>NULL</code>（空指標）。因此嚴謹的 C 程式設計在呼叫 malloc 後「必須立即檢查 <code>if (p == NULL)</code>」，防止後續對 NULL 指標進行解參考引發程式當機。"),
        ("標準函式 <code>calloc(size_t num, size_t size)</code> 與 <code>malloc(size_t size)</code> 的最核心功能差異為何？",
         "calloc 會將配置到的記憶體區塊內所有位元組自動初始化為「0」，而 malloc 保留記憶體原本的隨機垃圾值",
         ["calloc 會將配置到的記憶體區塊內所有位元組自動初始化為「0」，而 malloc 保留記憶體原本的隨機垃圾值",
          "calloc 配置於堆疊區，malloc 配置於堆積區",
          "calloc 分配的記憶體無法使用 free 釋放",
          "calloc 速度比 malloc 快十倍"],
         "malloc vs calloc：<code>malloc(n * sizeof(int))</code> 僅分配空間，不清除內容，速度極快但內容充滿隨機垃圾數據。<code>calloc(n, sizeof(int))</code> 接收元素個數與大小兩參數，且保證在返回前將每個位元組徹底填充為 0（Zero-initialized），適合需要安全乾淨初始狀態的陣列與結構體。兩者皆配置在 Heap 堆積區且皆用 <code>free()</code> 釋放。"),
        ("在動態記憶體管理中，「記憶體洩漏（<span class=\"en\">Memory Leak</span>）」的根本成因與潛在後果為何？",
         "透過 malloc/calloc 配置的動態堆積記憶體，在失去所有指向它的指標後未呼叫 free() 歸還系統；長期累積會耗盡可用記憶體導致程式或系統崩潰",
         ["透過 malloc/calloc 配置的動態堆積記憶體，在失去所有指向它的指標後未呼叫 free() 歸還系統；長期累積會耗盡可用記憶體導致程式或系統崩潰",
          "記憶體硬體金手指接觸不良導致資料漏電",
          "對已經釋放的記憶體重複寫入資料",
          "CPU 暫存器溢位破壞硬碟資料"],
         "Memory Leak 危害：堆積記憶體（Heap）不會隨函式返回自動回收。若程式配置了記憶體卻在回傳時忘記 free，或覆蓋了唯一的指針（如 <code>p = malloc(10); p = malloc(20);</code> 導致前 10 位元組永遠無法被訪問與釋放），這些孤兒記憶體會持續霸佔 RAM。對於長期運行的伺服器程式，記憶體洩漏會導致記憶體使用率不斷攀升最終被 OOM-Killer 強制終止。"),
        ("在指標操作中，所謂「懸置指標（<span class=\"en\">Dangling Pointer</span>）」是指何種狀態？如何有效防範？",
         "指標所指向的記憶體區塊已被 free() 釋放或該區域變數生命週期已結束，但該指標仍保留原位址；防範之道為釋放記憶體後立即將指標設為 NULL（p = NULL;）",
         ["指標所指向的記憶體區塊已被 free() 釋放或該區域變數生命週期已結束，但該指標仍保留原位址；防範之道為釋放記憶體後立即將指標設為 NULL（p = NULL;）",
          "指標變數的值為 0 的狀態；防範之道為永遠不宣告指標",
          "指標所指的陣列元素全部為負數",
          "指向 CPU 暫存器的指標被硬體中斷搶佔"],
         "Dangling Pointer 與 Use-After-Free（UAF）：當呼叫 <code>free(p);</code> 後，作業系統將該塊堆積記憶體標記為可用，但指標變數 p 內部儲存的十六進位位址並未改變。若後續程式碼誤以為該記憶體仍有效而繼續讀寫（<code>*p = 123;</code>），可能破壞別的物件結構，引發難以除錯的崩潰或被攻擊者利用為 UAF 漏洞。最佳實踐：釋放後立即賦值 <code>p = NULL;</code>，後續若誤用會立即觸發明確的 Null Pointer 異常，易於抓蟲。"),
        ("對同一個動態配置指標執行兩次 <code>free(p); free(p);</code> 會引發何種重大錯誤？",
         "雙重釋放錯誤（Double Free），破壞堆積記憶體管理器的元資料（Metadata）鏈結並引發程式崩潰",
         ["雙重釋放錯誤（Double Free），破壞堆積記憶體管理器的元資料（Metadata）鏈結並引發程式崩潰",
          "系統會自動忽略第二次 free，程式安全正常執行",
          "將釋放的記憶體大小加倍退還給系統",
          "編譯器在編譯時期直接報錯無法通過編譯"],
         "Double Free 漏洞：Heap 管理器（如 glibc 的 ptmalloc）在釋放記憶體時會維護空閒串列（Free list / Bin）。對同一區塊 free 兩次會使該位址在空閒鏈表中形成閉環（Fastbin Dup 攻擊），破壞記憶體管理中繼資料，是高危資安漏洞。若在第一次 free 後養成設 <code>p = NULL;</code> 的好習慣，因 C 規範 <code>free(NULL);</code> 是合法且無操作的（No-op），能徹底杜絕 Double Free。"),
        ("標準函式 <code>realloc(void *ptr, size_t new_size)</code> 在調整記憶體區塊大小時，若原位置後方沒有足夠的連續空間容納新大小，其行為為何？",
         "在堆積區另一處尋找足夠大的新空間配置、將原有資料完整複製過去、自動釋放原記憶體區塊，並傳回新記憶體的起始位址",
         ["在堆積區另一處尋找足夠大的新空間配置、將原有資料完整複製過去、自動釋放原記憶體區塊，並傳回新記憶體的起始位址",
          "立即拋出例外並摧毀原有的所有資料",
          "強制覆蓋相鄰的其他變數資料以維持原地擴充",
          "直接傳回 NULL 且原記憶體區塊被強制釋放銷毀"],
         "realloc 運作機制：<code>realloc</code> 嘗試就地擴充；若原地無連續空間，會在新位置配置 new_size，將原區塊內容拷貝過去，並自動將舊指標 ptr free 掉，傳回新位址。安全警告：絕不能寫 <code>p = realloc(p, new_size);</code>，因為若配置失敗傳回 NULL，會覆蓋掉原始指標 p 導致原記憶體洩漏！安全寫法應使用臨時變數：<code>void *temp = realloc(p, new_size); if (temp) p = temp;</code>。"),
        ("執行以下程式碼片段：<br><code>int a[3] = {1, 2, 3}; int *p = a; printf(\"%d\", *(p++) + *p);</code><br>在 C 語言中，此類在同一敘述內混用 p++ 與 *p 的運算結果屬於？",
         "未指定行為 / 未定義行為（Undefined Behavior），引數評估順序未規範",
         ["未指定行為 / 未定義行為（Undefined Behavior），引數評估順序未規範",
          "保證嚴格輸出 3",
          "保證嚴格輸出 4",
          "編譯階段必定報錯"],
         "評估順序未指定：二元加法 <code>+</code> 的左右運算元求值順序在 C 語言標準中是 Unspecified 的。編譯器可先算左側 <code>*(p++)</code> 再算右側 <code>*p</code>，亦可先算右側再算左側。這類代碼極不具可移植性，公職考題常提醒考生避免此種非良好定義寫法。"),
        ("在 C 語言中，<code>void*</code>（通用/萬用指標）的核心特性與限制為何？",
         "可以指向任何型態的物件位址且可自由互相轉型；但「無法直接解參考（*）」且「無法進行標準指標算術運算（+ -）」",
         ["可以指向任何型態的物件位址且可自由互相轉型；但「無法直接解參考（*）」且「無法進行標準指標算術運算（+ -）」",
          "只能指向 void 函式，無法儲存變數記憶體位址",
          "所佔用的記憶體大小為 0 位元組",
          "解參考時一律自動轉型為整數 int"],
         "void* 萬用指標規則：void 指標代表未知型態的純位址。任何型態指標皆可隱性轉為 void*（如 malloc 傳回 void*），void* 亦可轉回具體型態。但由於不知道目標型態的大小（sizeof(void) 未定義），編譯器無法計算解參考該取出多少位元組，亦無法決定指標加減時的位移步長，因此直接對 void* 進行 <code>*p</code> 或 <code>p++</code> 在 ANSI C 標準中屬於非法操作。"),
        ("下列 C 語言修飾語宣告中，何者代表「指標本身的位址可以被修改，但所指向的內容為唯讀常數（Pointer to Constant）」？",
         "const int *p;",
         ["const int *p;",
          "int * const p;",
          "const int * const p;",
          "int const * const p;"],
         "const 與指標結合黃金判讀口訣（以星號 * 為分界線）：<br>1. <code>const int *p;</code>（或 <code>int const *p;</code>）：const 在星號左側，修飾內容 <code>*p</code>。指向的內容為常數不可改（<code>*p = 10;</code> 報錯），但指標本身可指向別處（<code>p = &b;</code> 合法）。<br>2. <code>int * const p;</code>：const 在星號右側，修飾指標 <code>p</code>。指標本身為常數（不可改指向別處），但內容可修改。<br>3. <code>const int * const p;</code>：兩者皆為常數，內容與指向皆不可改。"),
        ("承上題，何者宣告代表「常數指標（Constant Pointer），指標一旦初始化後即不可再指向其他記憶體位址，但所指內容可被修改」？",
         "int * const p = &a;",
         ["int * const p = &a;",
          "const int *p = &a;",
          "int const *p = &a;",
          "const int p = &a;"],
         "Constant Pointer 語意：<code>int * const p = &a;</code> 宣告常數指標，必須在宣告時立即初始化綁定位址。此後 <code>p = &b;</code> 屬於語法錯誤；但透過指標修改內容 <code>*p = 20;</code> 完全合法。這在硬體暫存器映射或 C++ 參考（Reference）的底層實作中極為常見。"),
        ("宣告一個「指向回傳值為 int、接收兩個 int 引數之函式的指標（Function Pointer）」，其正確 C 語言語法為？",
         "int (*func_ptr)(int, int);",
         ["int (*func_ptr)(int, int);",
          "int *func_ptr(int, int);",
          "int (func_ptr*)(int, int);",
          "int *(*func_ptr)(int, int);"],
         "函式指標語法結構：函式呼叫運算子 <code>()</code> 優先級高於星號 <code>*</code>。<br>1. <code>int *func(int, int);</code>：func 是一個函式，傳回一個 <code>int*</code> 指標。<br>2. <code>int (*func)(int, int);</code>：括號強制星號優先，宣告 func 是一個指標，指向接收 (int, int) 並傳回 int 的函式。常用於 C 語言的回呼函式（Callback，如 <code>qsort</code> 比較器）。"),
        ("標準函式 <code>qsort</code> 的比較器函式原型中，接收的兩個參數型態為？",
         "const void *a, const void *b",
         ["const void *a, const void *b",
          "int a, int b",
          "void **a, void **b",
          "char *a, char *b"],
         "qsort 汎型設計哲學：C 語言無樣板（Templates），為了能對任何型態陣列排序，<code>qsort</code> 比較器原型定義為：<code>int cmp(const void *a, const void *b);</code>。使用 <code>const void*</code> 確保比較器不會意外篡改元素內容，並在函式內部由工程師自行強轉回實際型態（如 <code>*(const int*)a</code>）進行數值差值比較。"),
        ("執行以下程式碼片段：<br><code>int arr[3] = {10, 20, 30}; printf(\"%d\", *arr + 1);</code><br>輸出的數值為何？",
         "11",
         ["11",
          "20",
          "10",
          "30"],
         "優先權與解參考加法追蹤：單元解參考運算子 <code>*</code> 優先級高於二元加法 <code>+</code>。<code>*arr</code> 先解參考陣列首元素 <code>arr[0]</code> 取得數值 10；接著計算 <code>10 + 1 = 11</code>。若要取得第二個元素 20，必須加上括號寫為 <code>*(arr + 1)</code>。此題是公職極具辨識度的高頻細節題。")
    ]

    # 4. 結構體對齊、聯合體、記憶體操作函式與進階記憶體佈局 (19 題)
    struct_memory_data = [
        ("在 64 位元 Linux/GCC 系統中，宣告結構體：<br><code>struct A { char c; int i; short s; };</code><br>在預設自然對齊規範下，<code>sizeof(struct A)</code> 的大小為多少位元組（Bytes）？",
         "12 位元組",
         ["12 位元組",
          "7 位元組",
          "8 位元組",
          "16 位元組"],
         "結構體記憶體對齊（Structure Alignment & Padding）推導：<br>1. 成員 c（char）佔 1 位元組，位移位址 0。<br>2. 成員 i（int）佔 4 位元組，要求對齊至 4 的倍數位址，因此位址 1, 2, 3 填充 3 個 Padding 空位元組，i 放置於位址 4..7。<br>3. 成員 s（short）佔 2 位元組，要求對齊至 2 的倍數，放置於位址 8..9。目前累計佔 10 位元組。<br>4. 整體結構體最大成員為 int（4 位元組），結構體總大小必須對齊至 4 的整數倍，因此末尾補 2 個 Padding 位元組（10 + 2 = 12）。總大小為 12 位元組。"),
        ("承上題，若將結構體成員重新排列為：<br><code>struct B { int i; short s; char c; };</code><br>則 <code>sizeof(struct B)</code> 的大小為多少位元組？",
         "8 位元組",
         ["8 位元組",
          "12 位元組",
          "7 位元組",
          "16 位元組"],
         "成員重排記憶體優化推導：<br>1. 成員 i（int）放置於位址 0..3（佔 4 位元組）；<br>2. 成員 s（short）要求 2 的倍數，直接緊鄰放置於位址 4..5（佔 2 位元組，無 Padding）；<br>3. 成員 c（char）放置於位址 6（佔 1 位元組）；<br>4. 累計 7 位元組，結構體整體按最大成員 4 的倍數對齊，末尾僅需補 1 個 Padding 位元組（7 + 1 = 8）。<br>透過依照成員大小遞減排列，結構體大小由 12 縮減為 8 位元組，節省 33% 記憶體。"),
        ("在 C 語言中，編譯器前置處理指令 <code>#pragma pack(1)</code> 的核心作用為何？",
         "將結構體的對齊模數強制設定為 1 位元組，取消所有自動填充的 Padding 位元組以實現最緊湊的記憶體封裝",
         ["將結構體的對齊模數強制設定為 1 位元組，取消所有自動填充的 Padding 位元組以實現最緊湊的記憶體封裝",
          "將結構體內部所有變數強制轉為整數型態",
          "加速 CPU 對結構體成員的硬體存取速度至極限",
          "強制所有成員只能佔用 1 個位元組"],
         "#pragma pack(1) 封裝機制：在網路協定封包標頭（如 IP/TCP Header）或自訂通訊協定資料交換時，資料欄位必須嚴格緊湊連續無縫隙。<code>#pragma pack(1)</code> 命令編譯器消除所有填充位元組，但可能導致在特定 CPU 架構（如 ARM）上產生非對齊存取懲罰（Misaligned access penalty）甚至匯流排錯誤。"),
        ("關於 C 語言聯合體（<code>union</code>）的記憶體配置特性，下列敘述何者完全正確？",
         "union 內的所有成員共用同一個起始記憶體位址，其總大小至少等於最大成員的大小並符合對齊要求",
         ["union 內的所有成員共用同一個起始記憶體位址，其總大小至少等於最大成員的大小並符合對齊要求",
          "union 內的所有成員同時獨立儲存互不干擾",
          "union 的記憶體大小等於所有成員大小的絕對總和",
          "union 內部只能包含整數型態，不可包含陣列或指標"],
         "union 核心機制：結構體（struct）各成員擁有獨立空間，而聯合體（union）所有成員共用同一塊記憶體，在同一時間點只能有效儲存其中一個成員的值。修改某一個成員會直接覆蓋其他成員的二進位內容，常用於節省記憶體空間或進行底層暫存器型態雙重檢視。"),
        ("使用以下 union 程式碼檢測主機 CPU 端序（Endianness）：<br><code>union { int i; char c; } u; u.i = 1; if (u.c == 1) printf(\"L\"); else printf(\"B\");</code><br>在 Intel x86-64 處理器架構下的終端機輸出為何？",
         "L（代表 Little-Endian 小端序）",
         ["L（代表 Little-Endian 小端序）",
          "B（代表 Big-Endian 大端序）",
          "編譯錯誤，union 不能如此賦值",
          "無任何輸出"],
         "小端序（Little-Endian）檢測原理：32 位元整數 <code>1</code> 的十六進位為 <code>0x00000001</code>。在小端序（x86/ARM 大多數架構）中，「最低有效位元組（0x01）」儲存在「最低記憶體位址」。union 的成員 c 是 char，正好讀取最低記憶體位址的第一個位元組。若讀到 1 則證明最低位元組在開頭，為 Little-Endian；若為 Big-Endian（如網路位元組序），最低位址存放的是 0x00，u.c 會等於 0。"),
        ("在 C 語言結構體中定義「位元欄位（Bit-fields）」：<br><code>struct Flags { unsigned int a:3; unsigned int b:5; };</code><br>下列關於成員 a 與 b 的敘述何者正確？",
         "成員 a 佔用 3 個位元，可表示數值 0 至 7；且「不可」對成員 a 使用取位址運算子 &",
         ["成員 a 佔用 3 個位元，可表示數值 0 至 7；且「不可」對成員 a 使用取位址運算子 &",
          "成員 a 佔用 3 個位元組，可表示數值 0 至 255",
          "可以對成員 a 正常使用 & 取得其指標",
          "成員 a 與 b 必定分別佔用獨立的 32 位元組空間"],
         "位元欄位規則：<code>unsigned int a:3;</code> 允許精確指定變數所佔的「二進位位元數（Bits）」。3 位元無號整數最大值為 2^3 - 1 = 7。由於現代電腦記憶體定址的最小物理單位是「位元組（Byte）」，無法對單獨幾個位元進行獨立定址，因此 C 語言規範「嚴格禁止對位元欄位成員使用取位址運算子 <code>&</code>」。"),
        ("若宣告結構體指標 <code>struct Student *p;</code>，則運算式 <code>p->age</code> 在語法上完全等價於？",
         "(*p).age",
         ["(*p).age",
          "*p.age",
          "&(p.age)",
          "p.age"],
         "箭頭運算子語法语意：因為點運算子 <code>.</code> 的優先級高於星號 <code>*</code>，若寫 <code>*p.age</code> 會被解讀為 <code>*(p.age)</code> 引發編譯錯誤。要透過指標存取結構成員必須寫為 <code>(*p).age</code>。為了精簡寫法，C 語言專門設計了語法糖 <code>p->age</code>。"),
        ("在自我參照結構體（如鏈結串列節點）中，為何 <code>struct Node { int data; struct Node next; };</code> 是非法的？其正確寫法為何？",
         "因為結構體內部直接內嵌自己會導致無限遞迴巢狀，編譯器無法計算其大小；正確寫法為宣告指標 struct Node *next;",
         ["因為結構體內部直接內嵌自己會導致無限遞迴巢狀，編譯器無法計算其大小；正確寫法為宣告指標 struct Node *next;",
          "因為 C 語言完全不允許結構體包含任何指標成員",
          "因為結構體成員名稱不能命名為 next",
          "正確寫法是改用 union 宣告"],
         "不完全型態與遞迴結構體解析：若結構體直接內嵌自身的實體，計算其大小為 <code>sizeof(int) + sizeof(Node) = 4 + 4 + sizeof(Node)...</code> 陷入無限遞迴，無法在編譯期確定空間。而指標的大小是固定的（32 位元為 4 位元組，64 位元為 8 位元組），因此宣告 <code>struct Node *next;</code> 大小明確固定，合法建立鏈結。"),
        ("標準函式 <code>memcpy(dst, src, n)</code> 與 <code>memmove(dst, src, n)</code> 在記憶體複製上的最關鍵區別為？",
         "當來源區塊（src）與目的區塊（dst）的記憶體範圍發生「部分重疊（Overlapping）」時，memmove 保證複製結果正確，而 memcpy 行為未定義",
         ["當來源區塊（src）與目的區塊（dst）的記憶體範圍發生「部分重疊（Overlapping）」時，memmove 保證複製結果正確，而 memcpy 行為未定義",
          "memcpy 只能複製字元，memmove 可以複製整數",
          "memcpy 速度比 memmove 慢 10 倍",
          "memmove 複製完畢後會將來源區塊自動清空為 0"],
         "memcpy vs memmove 記憶體重疊：若同一陣列內將 <code>arr</code> 的前 5 個元素拷貝至 <code>arr + 2</code>，兩者空間重疊。<code>memcpy</code> 通常假設兩者不重疊而直接順序拷貝，會導致前面的寫入覆蓋後方尚未讀取的來源資料；<code>memmove</code> 內部會先檢查兩者起始位址的前後關係，若有重疊自動改採「由後向前反向拷貝」或透過中介緩衝區，確保資料完整無損。"),
        ("執行以下標準庫函式：<br><code>int arr[5]; memset(arr, 1, sizeof(arr)); printf(\"%d\", arr[0]);</code><br>終端機輸出的數值為何？",
         "16843009（十六進位 0x01010101）",
         ["16843009（十六進位 0x01010101）",
          "1",
          "5",
          "0"],
         "memset 按位元組填充重大陷阱：<code>memset</code> 是「以位元組（Byte）為單位」進行記憶體填充。將每個 Byte 填入數值 1（二進位 00000001）。一個 32 位元整數包含 4 個 Byte，組合後為 <code>0x01010101</code>，十進位為 16843009！因此 <code>memset</code> 只能安全用於清零（填 0）或填 -1（0xFFFFFFFF），若要將整數陣列填為 1 必須使用 for 迴圈。"),
        ("標準函式 <code>memcmp(buf1, buf2, n)</code> 與 <code>strcmp(s1, s2)</code> 的關鍵行為差異為？",
         "memcmp 嚴格比對前 n 個位元組的二進位內容，遇到 '\\0' 空字元「不會」提前停止比對",
         ["memcmp 嚴格比對前 n 個位元組的二進位內容，遇到 '\\0' 空字元「不會」提前停止比對",
          "memcmp 只能用於比較字元陣列，無法比較結構體",
          "strcmp 比對失敗會拋出例外，memcmp 不會",
          "memcmp 比較速度遠慢於 strcmp"],
         "memcmp vs strcmp：<code>strcmp</code> 是以 C 字串為對象，一遇到 <code>'\\0'</code> 就視為字串結尾並停止後續比對。而 <code>memcmp</code> 是純二進位記憶體比對，專用於結構體、圖片二進位串流或網路封包，即使內部包含無數個 0 亦會忠實比對滿指定之 n 位元組。"),
        ("使用「動態指標陣列法」動態配置一個 rows × cols 的二維整數陣列，正確的釋放記憶體步驟為？",
         "必須先使用 for 迴圈逐一 free 釋放每一列的陣列指標，最後再 free 釋放最外層的指標陣列",
         ["必須先使用 for 迴圈逐一 free 釋放每一列的陣列指標，最後再 free 釋放最外層的指標陣列",
          "只需一行 free(arr); 即可自動將所有列一併釋放",
          "必須先釋放最外層指標陣列，再釋放每一列",
          "動態配置的二維陣列無法手動釋放"],
         "多層動態記憶體釋放順序：配置順序為先外後內（先 malloc 列指標陣列，再迴圈 malloc 各列）；釋放時「必須完全逆序操作」！若先 <code>free(arr)</code>，指向各列的指標群位址立刻遺失，導致所有列的子記憶體空間全部成為無法存取的孤兒，造成永久性記憶體洩漏（Memory Leak）。"),
        ("相較於動態指標陣列法，使用「單一大連續記憶體區塊法」配置動態二維陣列（<code>int *arr = malloc(rows * cols * sizeof(int));</code>）的核心優勢為何？",
         "所有資料在實體記憶體中完全連續，具備極佳的 CPU 快取局部性（Cache Locality），且釋放只需呼叫一次 free()",
         ["所有資料在實體記憶體中完全連續，具備極佳的 CPU 快取局部性（Cache Locality），且釋放只需呼叫一次 free()",
          "可以使用中括號雙下標 arr[i][j] 直接存取",
          "配置時完全不需要使用 sizeof 運算子",
          "所佔用的記憶體空間自動縮小一半"],
         "連續平坦化二維陣列（Flattened 2D Array）：指標陣列法中的各列在 Heap 中可能分散在天涯海角，CPU 快取失誤率高且每列都有指標開銷與 malloc 額外中繼資料負擔。一維平坦化連續配置保證相鄰列緊密相依，硬體預取器（Prefetcher）效能極高，存取透過 <code>arr[i * cols + j]</code> 計算，釋放只需 <code>free(arr)</code>。"),
        ("在同一個陣列中，兩個指標進行相減運算 <code>p2 - p1</code>，其運算結果的標準型態與數值意義為？",
         "型態為 ptrdiff_t（定義於 &lt;stddef.h&gt;），數值為兩指標之間相隔的「陣列元素個數」",
         ["型態為 ptrdiff_t（定義於 &lt;stddef.h&gt;），數值為兩指標之間相隔的「陣列元素個數」",
          "型態為 size_t，數值為兩指標相隔的記憶體位元組數",
          "型態為 double，數值為兩指標位址的算術平均數",
          "型態為 void*，數值為相減後的全新記憶體位址"],
         "指標相減型態 ptrdiff_t：若 p1 指向 <code>arr[1]</code>，p2 指向 <code>arr[4]</code>，則 <code>p2 - p1 = 3</code>。C 標準規定其型態為有號整數 <code>ptrdiff_t</code>（若 p2 在 p1 前方可為負數）。它代表元素個數差，而非 Byte 位元組差（編譯器自動除以 sizeof(*p)）。"),
        ("標準函式 <code>strtok(str, delim)</code> 在切割同一個字串時，第二次及後續呼叫時的第一個參數應傳入何值？該函式的主要執行限制為何？",
         "第一個參數應傳入 NULL；且該函式會破壞性改寫原始字串（將分隔符填為 '\\0'）且非執行緒安全（Non-thread-safe）",
         ["第一個參數應傳入 NULL；且該函式會破壞性改寫原始字串（將分隔符填為 '\\0'）且非執行緒安全（Non-thread-safe）",
          "第一個參數應重複傳入原始字串指標；且完全不修改原字串",
          "第一個參數應傳入分隔符字元；且只能切割數字",
          "第一個參數應傳入切割次數計數器"],
         "strtok 運作狀態機：首次呼叫 <code>strtok(str, \",\")</code> 會記錄字串開頭並在靜態內部指針維護當前解析位置；後續呼叫必須傳入 <code>NULL</code> 讓其繼續處理剩餘字串。因為使用全域/靜態內部變數，多執行緒同時呼叫會互相覆蓋狀態（Thread-unsafe），POSIX 規範提供可重入版本 <code>strtok_r</code>。此外它會將分隔符直接取代為 '\\0'，故不能用於唯讀字串。"),
        ("執行結構體變數賦值運算：<br><code>struct Point { int x, y; } p1 = {10, 20}; struct Point p2 = p1;</code><br>在 C 語言中，此賦值行為的底層本質為？",
         "位元組逐一淺拷貝（Shallow copy / Bitwise copy），將 p1 的內容完整複製一份給 p2",
         ["位元組逐一淺拷貝（Shallow copy / Bitwise copy），將 p1 的內容完整複製一份給 p2",
          "讓 p2 成為 p1 的指標參考別名，修改 p2 會影響 p1",
          "語法錯誤，結構體之間不允許直接使用等號 = 賦值",
          "僅複製結構成員中的第一個欄位"],
         "結構體複製語意：C 語言原生支援同型態結構體之間直接賦值（或函式傳值/傳回結構體）。其實現本質是 <code>memcpy(&p2, &p1, sizeof(struct Point))</code> 的淺拷貝。如果結構體內部含有動態指標成員，淺拷貝會導致兩個結構體中的指標指向同一塊 Heap 記憶體，後續釋放易釀成 Double Free 災難（需手動實作深拷貝 Deep copy）。"),
        ("將大型結構體傳入函式時，在 C 語言最佳實踐中推薦採用何種參數傳遞方式？",
         "傳入常數指標（const struct Data *ptr），既避免堆疊資料拷貝開銷，又防止結構內容被意外篡改",
         ["傳入常數指標（const struct Data *ptr），既避免堆疊資料拷貝開銷，又防止結構內容被意外篡改",
          "以傳值（Pass by Value）方式直接複製整個結構體傳入",
          "將結構體拆解為全域變數傳遞",
          "將結構體寫入硬碟檔案再由函式讀取"],
         "傳遞大型結構體典範：若結構體佔用 1024 位元組，傳值呼叫會在呼叫堆疊（Call Stack）上完整拷貝 1024 位元組，頻繁呼叫嚴重拖垮效能並可能引發 Stack Overflow。傳入指標只需複製 8 位元組位址，加上 <code>const</code> 修飾詞更可在編譯期獲得唯讀安全保障，一舉兩得。"),
        ("在 C 語言中，「不透明指標（<span class=\"en\">Opaque Pointer / Handle</span>）」設計模式（如 <code>FILE*</code>）的核心軟體工程價值為？",
         "在標頭檔僅公開結構體名稱的前置宣告，將具體欄位隱藏於 .c 實作檔中，達成完美的封裝與資訊隱藏（Information Hiding）",
         ["在標頭檔僅公開結構體名稱的前置宣告，將具體欄位隱藏於 .c 實作檔中，達成完美的封裝與資訊隱藏（Information Hiding）",
          "使指標可以穿透實體記憶體直接存取外部硬體裝置",
          "消除所有指標解參考可能產生的 Null Pointer 例外",
          "自動為指標加上 256 位元對稱加密防護"],
         "Opaque Pointer（不完全型態封裝）：C 標頭檔中只寫 <code>typedef struct Context Context;</code>，使用者只拿得到 <code>Context*</code> 指標，無法看見或直接存取內部結構成員，所有操作必須透過 API 函式進行。此做法使函式庫維護者後續即便重構結構體內部欄位，使用者的程式碼也無須重新編譯，保證了 ABI（Application Binary Interface）向後相容性。"),
        ("執行以下指標與字串陣列程式碼：<br><code>char *fruits[] = {\"Apple\", \"Banana\", \"Cherry\"}; printf(\"%c\", *(*(fruits + 1) + 2));</code><br>終端機輸出的字元為何？",
         "'n'",
         ["'n'",
          "'a'",
          "'B'",
          "'e'"],
         "字串指標陣列雙層解參考追蹤：<code>fruits</code> 是一個指標陣列。<code>fruits + 1</code> 指向第二個元素（即指向字串 \"Banana\" 的指標）；解參考 <code>*(fruits + 1)</code> 取得 \"Banana\" 首字元 'B' 的位址；接著 <code>+ 2</code> 偏移 2 個字元，指向索引 2 的字元；最後最外層解參考 <code>*(*(fruits + 1) + 2)</code> 取出字元。\"Banana\" 索引 0 為 'B'、1 為 'a'、2 為 'n'，因此輸出字元 'n'。")
    ]

    # Combine datasets
    all_datasets = [
        ("一維與二維陣列、定址計算與初始化規則", array_data),
        ("C 字串處理、字元陣列與安全庫函式解析", string_data),
        ("指標算術、雙重指標與動態記憶體配置", ptr_data),
        ("結構體對齊、聯合體與進階記憶體佈局", struct_memory_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【陣列結構、指標算術與記憶體配置機制深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 記憶體佈局、位址位移推導與指標解參考時序追蹤</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立陣列排布方式（Row-major/Column-major）與指標型態大小</strong><br>
      ‧ 本題依據 C 語言記憶體模型、ANSI/ISO 標準庫規範及定址計算數學公式嚴格展開。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>執行期狀態追蹤、位址數值計算與安全性分析</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（位址位移計算錯誤或指標語法语意混淆）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（記憶體邊界判斷錯誤或型態大小不符）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非標準 C 語言之合法行為或結果推導錯誤）。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_prog_part2_questions()
    print(f"Total Part 2 questions generated: {len(qs)}")
