# -*- coding: utf-8 -*-
"""
Part 4 of Junior Network Bank (資通網路與安全概要題庫擴充 - 第四部分)
主題：路由協定（RIP/OSPF/BGP）、傳輸層（TCP交握狀態機/壅塞控制、UDP與DNS/DHCP）
題數：72 題高品質全解析
"""

def get_junior_net_part4_questions():
    qs = []

    # 1. 路由基礎、靜態路由與距離向量 RIP (18 題)
    rip_data = [
        ("在自治系統（<span class=\"en\">AS, Autonomous System</span>）劃分中，「內部閘道協定（IGP）」與「外部閘道協定（EGP）」的代表性協定歸屬何者完全正確？",
         "IGP 代表協定包含 RIP、OSPF、IS-IS；EGP 代表協定為 BGP（邊界閘道協定）",
         ["IGP 代表協定包含 RIP、OSPF、IS-IS；EGP 代表協定為 BGP（邊界閘道協定）",
          "IGP 代表協定為 BGP；EGP 代表協定為 OSPF",
          "IGP 只能用於無線網路；EGP 只能用於有線網路",
          "IGP 代表 TCP；EGP 代表 UDP"],
         "路由協定階層體系：<br>1. IGP（Interior Gateway Protocol）：在單一組織或企業自治系統內部運作，追求收斂快速與路徑最優，如 RIP（小型網）、OSPF（中大型企業網）、IS-IS（電信骨幹網）。<br>2. EGP（Exterior Gateway Protocol）：在不同 ISP 自治系統之間交換路由資訊，追求跨國策略控制（Policy-based Routing）與穩定性，BGP-4 是全球網際網路的唯一霸主。"),
        ("路由器在決定將封包由哪一條路由來源轉發時，「管理距離（<span class=\"en\">AD, Administrative Distance</span>）」代表的核心意義為？下列常見路由來源的預設 AD 數值由低到高（可信度由高到低）排序何者正確？",
         "AD 代表「路由來源的相對可信度（數值越小越優先越可信）」；直連路由（AD = 0） < 靜態路由（AD = 1） < eBGP（AD = 20） < OSPF（AD = 110） < RIP（AD = 120）",
         ["AD 代表「路由來源的相對可信度（數值越小越優先越可信）」；直連路由（AD = 0） < 靜態路由（AD = 1） < eBGP（AD = 20） < OSPF（AD = 110） < RIP（AD = 120）",
          "AD 數值越大代表該路由越優秀越優先",
          "RIP（AD = 120）優先於 OSPF（AD = 110）",
          "所有路由來源的 AD 數值固定皆為 100"],
         "Cisco 體系 AD 必考數值：<br>‧ 直連介面（Connected）：0<br>‧ 靜態路由（Static）：1<br>‧ eBGP（外部 BGP）：20<br>‧ EIGRP（內部）：90<br>‧ OSPF：110<br>‧ IS-IS：115<br>‧ RIP：120<br>‧ iBGP（內部 BGP）：200。當不同協定學到「同一個網段」時，路由器優先挑選 AD 最小者寫入最終 RIB（路由資訊庫）。"),
        ("「浮動靜態路由（<span class=\"en\">Floating Static Route</span>）」在企業備援網路中的核心配置技巧為？",
         "將該靜態路由的手動管理距離（AD）刻意調高至大於主要動態路由協定（例如設為 130，高於 OSPF 的 110），平時靜態路由隱身，僅當 OSPF 斷線時才「浮現」接管流量",
         ["將該靜態路由的手動管理距離（AD）刻意調高至大於主要動態路由協定（例如設為 130，高於 OSPF 的 110），平時靜態路由隱身，僅當 OSPF 斷線時才「浮現」接管流量",
          "將路由器放置在水中以浮動散熱",
          "讓靜態路由的 IP 位址隨機漂移變化",
          "將靜態路由設定為只在下雨天生效"],
         "Floating Static Route 實務：主線路跑 OSPF（AD 110）。備援線路配置 `ip route 0.0.0.0 0.0.0.0 203.0.113.2 130`（末尾的 130 即覆寫 AD）。平時路由表只顯示 OSPF 路由；當主線光纖斷裂，OSPF 鄰居死滅路由被拔除，AD 為 130 的浮動靜態路由立刻浮上檯面接管預設閘道，實現低成本無縫自動容災。"),
        ("路由資訊協定（<span class=\"en\">RIP, Routing Information Protocol</span>）所採用的核心演算法與度量值（Metric）計算依據為？",
         "基於貝爾曼-福特（Bellman-Ford）距離向量演算法；以「跳數（Hop Count，經過的路由器數量）」作為唯一的度量值",
         ["基於貝爾曼-福特（Bellman-Ford）距離向量演算法；以「跳數（Hop Count，經過的路由器數量）」作為唯一的度量值",
          "基於 Dijkstra 最短路徑演算法；以光纖頻寬為度量值",
          "以網路纜線的長度公尺數為度量值",
          "以封包的傳輸延遲毫秒數為度量值"],
         "RIP 本質特性：標準的 Distance Vector 協定。度量值純粹數 Hop：直連網段 Hop=0，經過 1 台路由器 Hop=1。缺點是「對頻寬完全盲目」：若一條路徑是 1 跳的 56 kbps 烏龜撥接電話線，另一條路徑是 2 跳的 10 Gbps 超高速光纖，RIP 依然會死板地挑選 1 跳的 56 kbps 爛線路！"),
        ("RIP 協定在設計上規定其「最大有效跳數為 15 跳」，當某一網段的跳數累加達到「16 跳」時代表何種狀態？",
         "代表該目的網路為「無法抵達（Unreachable / Infinite Metric）」，該路由條目將被宣告死亡並從路由表中清除",
         ["代表該目的網路為「無法抵達（Unreachable / Infinite Metric）」，該路由條目將被宣告死亡並從路由表中清除",
          "代表該網路處於最佳超高速狀態",
          "代表封包將被發送到外太空",
          "代表路由器需要重開機"],
         "16 跳即無窮大（Infinity）：由於距離向量演算法存在嚴重的「計數至無窮大（Count-to-Infinity）」迴圈隱患，RIP 人為將無窮大定義為小數值 16。這限制了 RIP 只能部署在直徑小於 15 台路由器的小型園區網，任何超過 15 跳的節點皆被判定為斷網不可達。"),
        ("RIPv1 與 RIPv2 在協定功能上的最重大演進差異，下列何者完全正確？",
         "RIPv1 為有類別（Classful）協定，以廣播發送且「不攜帶子網路遮罩」，不支援 VLSM；RIPv2 為無類別（Classless）協定，以多播 224.0.0.9 發送且「攜帶子網路遮罩」，支援 VLSM、CIDR 與 MD5 認證",
         ["RIPv1 為有類別（Classful）協定，以廣播發送且「不攜帶子網路遮罩」，不支援 VLSM；RIPv2 為無類別（Classless）協定，以多播 224.0.0.9 發送且「攜帶子網路遮罩」，支援 VLSM、CIDR 與 MD5 認證",
          "RIPv1 速度比 RIPv2 快十倍",
          "RIPv1 支援 IPv6，RIPv2 不支援",
          "兩者皆使用 TCP 連線發送路由資訊"],
         "RIP 兩代對比考點：<br>1. 廣播 vs 多播：v1 用 255.255.255.255 吵醒全網所有主機；v2 用專屬多播 224.0.0.9，僅監聽該組播的 RIP 路由器接收處理。<br>2. 遮罩支援：v1 封包無 Mask，無法支援子網切割（VLSM）；v2 完整支援變長遮罩。<br>3. 安全性：v2 支援純文字與 MD5 密鑰認證防偽造。兩者皆基於 UDP 520 埠運作。"),
        ("距離向量路由協定在網路故障時容易遭遇「計數至無窮大（Count-to-Infinity）」路由迴圈問題。下列何者是專門防範此問題的「水平分割（<span class=\"en\">Split Horizon</span>）」技術規則？",
         "規定路由器「絕不把從某個介面學習到的路由條目，再反向通告回該同一個介面」",
         ["規定路由器「絕不把從某個介面學習到的路由條目，再反向通告回該同一個介面」",
          "將路由器的物理天線水平放置",
          "禁止任何兩台路由器相互連線超過 1 小時",
          "強制所有路由器在同一條水平線上記錄數據"],
         "Split Horizon 原理：若 Router A 告訴 Router B「我有網段 X（1 跳）」，B 記錄「經由 A 可達 X（2 跳）」。若 X 突然斷線，若無水平分割，B 會在下一個更新週期向 A 通告「經由我可以到 X（2 跳）」，A 以為 B 有別條路到 X，修改為「經由 B 可達 X（3 跳）」... 雙方互相欺騙，跳數一路累加到 16！水平分割禁止 B 把學自 A 的路由再回吐給 A，直接扼殺此低級迴圈。"),
        ("「毒性反轉（<span class=\"en\">Poison Reverse</span>）」作為水平分割的積極改良版本，其運作方式為？",
         "路由器依然將從某介面學到的路由反向通告回去，但將該路由的度量值直接強制標記為「16 跳（不可達度量 Infinite Metric）」以明確撲滅任何潛在誤解",
         ["路由器依然將從某介面學到的路由反向通告回去，但將該路由的度量值直接強制標記為「16 跳（不可達度量 Infinite Metric）」以明確撲滅任何潛在誤解",
          "在封包中注入惡意電腦病毒使對手當機",
          "將對手路由器的 IP 封鎖進黑名單",
          "把路由器的電源極性反接"],
         "Poison Reverse（毒殺反轉）：俗稱「好心辦壞事不如直接說死」。A 告訴 B 網段 X，B 反向回覆 A 說「網段 X 的 Cost 是 16（別指望我，我到 X 走的是你這條路）」。這在多路存取（Multi-Access）網段中能比單純沉默的水平分割更快破除三方環路。"),
        ("RIP 協定中，為了在鏈路發生故障時立即通知鄰居而無須苦等下一個 30 秒週期更新計時器，所採用的機制為？",
         "觸發更新（Triggered Updates / Flash Updates），一旦路由狀態發生變更立刻非同步發送更新報文",
         ["觸發更新（Triggered Updates / Flash Updates），一旦路由狀態發生變更立刻非同步發送更新報文",
          "定期重新開機（Periodic Reboot）",
          "人工手動電話通報",
          "將所有封包轉發至微軟更新伺服器"],
         "Triggered Update 價值：RIP 正常每 30 秒定期發送完整路由表。若網段中斷，若死等 30 秒，這段空窗期極易產生短暫迴圈。觸發更新規定只要介面狀態改變，立即不等待計時器直接發射變更通告，將網路收斂時間縮短至毫秒級。"),
        ("RIP 協定的四大標準計時器中，定期更新計時器（Update Timer）與無效計時器（Invalid Timer）的預設時間值分別為？",
         "定期更新計時器為 30 秒；無效計時器為 180 秒",
         ["定期更新計時器為 30 秒；無效計時器為 180 秒",
          "定期更新計時器為 1 秒；無效計時器為 5 秒",
          "定期更新計時器為 10 分鐘；無效計時器為 1 小時",
          "兩者皆為 60 秒"],
         "RIP 四大計時器標準值：<br>1. Update: 30 秒（定期泛洪路由表）。<br>2. Invalid: 180 秒（連續 6 個週期未聽見某條路由，將其標記為 16 跳不可達並啟動抑制）。<br>3. Holddown: 180 秒（收到不可達通告後，拒絕接受任何度量較差的新通告）。<br>4. Flush: 240 秒（逾期未聞，徹底將該條目自路由表中抹除刪除）。"),
        ("靜態路由（Static Route）相較於動態路由協定（如 OSPF/RIP），在現代網路維運中的最顯著優勢為？",
         "精準可控、配置簡單、不消耗任何網路頻寬發送通告、且「極致節省路由器 CPU 與 RAM 運算資源」，安全性高（外部無法透過路由投毒攻擊）",
         ["精準可控、配置簡單、不消耗任何網路頻寬發送通告、且「極致節省路由器 CPU 與 RAM 運算資源」，安全性高（外部無法透過路由投毒攻擊）",
          "拓撲發生故障時能自動自適應重新計算最佳備援路徑",
          "適合在全球數萬台路由器的超大型網路中部署",
          "可以自動將網路線路頻寬擴展為兩倍"],
         "靜態路由優缺點：<br>‧ 優點：零 CPU 開銷、零頻寬佔用、預測性 100%、適合末梢殘餘網路（Stub Network）與預設閘道指向。<br>‧ 缺點：缺乏自適應彈性，一旦鏈路中斷無法自動繞道，需網管手動排障修復；網路規模龐大時人工維護成本呈幾何級數暴增。"),
        ("在 Cisco IOS 路由器中，配置靜態路由的指令 `ip route 192.168.2.0 255.255.255.0 10.0.0.2` 中，最後的「10.0.0.2」代表何種參數？",
         "下一跳 IP 位址（Next-Hop IP Address，即相鄰路由器的接收介面 IP）",
         ["下一跳 IP 位址（Next-Hop IP Address，即相鄰路由器的接收介面 IP）",
          "本機路由器的輸出介面 IP",
          "目的網路的 DNS 伺服器 IP",
          "該條路由的管理距離（AD）"],
         "靜態路由語法：`ip route [目的網段] [子網路遮罩] [下一跳IP 或 本地出介面] [可選管理距離]`。若指定下一跳 IP，路由器在轉發時還需進行遞迴路由查詢（Recursive Lookup）以確定該下一跳 IP 接在哪個實體出介面上。"),
        ("若某路由器在靜態路由中直接指定「本地廣播型乙太網路輸出介面（如 GigabitEthernet0/0）」而未指定下一跳 IP，在未開啟 CEF 的環境下可能導致的嚴重效能隱患為？",
         "路由器會對每一個前往未知目的 IP 的封包在該乙太網介面上「發起高頻的 ARP 廣播請求」，迅速塞滿本機 ARP 快取表與消耗廣播頻寬",
         ["路由器會對每一個前往未知目的 IP 的封包在該乙太網介面上「發起高頻的 ARP 廣播請求」，迅速塞滿本機 ARP 快取表與消耗廣播頻寬",
          "路由器會立即當機並清除所有作業系統檔案",
          "該介面傳輸速度會被強行降至 10 Mbps",
          "導致網路電壓升高燒毀網卡"],
         "出介面指定陷阱：在點對點（Serial/HDLC）介面上只指定出介面完全沒問題；但在多路存取乙太網上，若只配出介面，路由器會誤以為該目的網段上的「每一個主機都直連在該乙太網線上」，對每個不同 IP 都發送 ARP Request 尋找 MAC，引發 ARP 風暴與記憶體耗盡。最佳實務是「永遠指定下一跳 IP」。"),
        ("距離向量路由協定中的「路由毒化（<span class=\"en\">Route Poisoning</span>）」是指？",
         "當某路由器偵測到直連網段中斷故障時，立即主動向鄰居發送廣播，將該失效網段的度量值顯式標記為「16 跳（不可達）」，主動通告死訊",
         ["當某路由器偵測到直連網段中斷故障時，立即主動向鄰居發送廣播，將該失效網段的度量值顯式標記為「16 跳（不可達）」，主動通告死訊",
          "駭客向路由器發送特製木馬程式使路由表紊亂",
          "將路由器的快取記憶體全部寫入亂碼",
          "在路由表中隨機刪除 50% 的條目"],
         "主動毒化機制：與被動等待 180 秒超時不同，Route Poisoning 採取主動出擊。當 R1 的 G0/1 介面拔線，R1 立即在下一個更新或觸發更新中，對該網段廣播 Hop = 16。鄰居 R2 收到後立刻知道該網段已死，將該條目置於抑制狀態（Holddown），避免任何誤解。"),
        ("在 RIPv2 中，路由更新封包的底層傳輸層協定與連接埠號碼為？",
         "UDP 協定，連接埠 520",
         ["UDP 協定，連接埠 520",
          "TCP 協定，連接埠 179",
          "直接封裝於 IP，協定號 89",
          "ICMP 協定，連接埠 80"],
         "協定封裝常考題：<br>‧ RIP: UDP 520（RIPng 使用 UDP 521）。<br>‧ OSPF: 原始 IP 協定號 89（不依賴 TCP/UDP）。<br>‧ BGP: TCP 179（利用 TCP 保證跨國傳輸極致可靠）。<br>‧ EIGRP: 原始 IP 協定號 88。"),
        ("RIP 協定的水平分割（Split Horizon）在下列哪種實體網路拓撲環境中可能會「意外導致路由無法完整傳播」，因而常被網管手動關閉？",
         "非廣播多路存取（NBMA，如 Frame Relay 或 Hub-and-Spoke 點對多點星狀拓撲）的單一實體介面環境",
         ["非廣播多路存取（NBMA，如 Frame Relay 或 Hub-and-Spoke 點對多點星狀拓撲）的單一實體介面環境",
          "雙絞線點對點直連環境",
          "光纖環狀網路環境",
          "單一交換機連接 10 台電腦的環境"],
         "NBMA 水平分割失效經典案例：在 Hub-and-Spoke 拓撲中，中心 Hub 路由器的單一 Serial 介面同時連接 Spoke A 與 Spoke B。Spoke A 的路由傳給 Hub 的 Serial0，Hub 欲將此路由轉發給 Spoke B 時，因為「入介面也是 Serial0，出介面也是 Serial0」，觸發水平分割規則被硬生生阻斷！導致 Spoke B 永遠學不到 Spoke A 的路由。解法：在該介面執行 `no ip split-horizon` 或配置子介面（Sub-interfaces）。"),
        ("次世代路由資訊協定「RIPng」專門用於支援何種網路環境？其更新封包發送的目的多播位址為？",
         "專門支援 IPv6 網路；更新封包發送至 IPv6 專屬多播位址 `ff02::9`",
         ["專門支援 IPv6 網路；更新封包發送至 IPv6 專屬多播位址 `ff02::9`",
          "支援量子運算網路；發送至 `::1`",
          "支援 5G 基地台；發送至廣播位址",
          "支援衛星通訊；發送至 `fe80::1`"],
         "RIPng（RFC 2080）：RIP for IPv6。核心演算法仍為 Bellman-Ford，最大跳數仍為 15。傳輸改採 UDP 521 埠，更新多播位址改為 `ff02::9`（所有 RIP 路由器多播群組），且路由條目完整包含 128 位元 IPv6 前綴與長度。"),
        ("如果某路由器同時自 OSPF（學得 10.1.0.0/16，Cost 20）與 RIP（學得 10.1.0.0/16，Hop 2）學到了「完全相同的網段與遮罩」，則路由器最終將挑選哪一條寫入路由表？",
         "挑選 OSPF 路由，因為 OSPF 的管理距離（AD = 110）小於 RIP 的管理距離（AD = 120），可信度更高",
         ["挑選 OSPF 路由，因為 OSPF 的管理距離（AD = 110）小於 RIP 的管理距離（AD = 120），可信度更高",
          "挑選 RIP 路由，因為跳數僅有 2 跳小於 Cost 20",
          "兩條路由同時寫入進行負載平衡",
          "兩條路由皆被丟棄並報錯"],
         "路由裁決標準流程（Tie-breaker）：<br>1. 第一關：先比前綴遮罩長度（最長匹配原則，若前綴長度不同則長者直接勝出）。<br>2. 第二關：若前綴與遮罩「完全一模一樣」，比管理距離（AD）。OSPF 的 AD 為 110，RIP 的 AD 為 120。110 < 120，故 OSPF 完勝！<br>3. 只有當 AD 也相同（來自同一協定）時，才去比 Metric 度量值。")
    ]

    # 2. 鏈路狀態 OSPF、BGP 與 Dijkstra 演算法 (18 題)
    ospf_bgp_data = [
        ("開放最短路徑優先協定（<span class=\"en\">OSPF, Open Shortest Path First</span>）的核心演算法為？各路由器在收斂後建立的資料庫為？",
         "基於 Dijkstra（狄克斯特拉）最短路徑優先（SPF）演算法；全網區域內所有路由器皆擁有「完全相同且一致的鏈路狀態資料庫（LSDB, Link-State Database）」",
         ["基於 Dijkstra（狄克斯特拉）最短路徑優先（SPF）演算法；全網區域內所有路由器皆擁有「完全相同且一致的鏈路狀態資料庫（LSDB, Link-State Database）」",
          "基於 Bellman-Ford 演算法；擁有路由向量表",
          "基於 Floyd 演算法；擁有鄰居名冊",
          "基於深度優先搜尋；擁有雜湊表"],
         "Link-State 理念革命：不同於距離向量「道聽塗說傳言式更新（Routing by Rumor）」，OSPF 路由器互相廣播 LSA（鏈路狀態通告，包含本機有哪些介面、介面狀態、頻寬與鄰居是誰）。所有路由器收集齊全後組裝出全網拓撲地圖（LSDB）。每台路由器以自身為樹根，獨立執行 Dijkstra 演算法計算出一棵無環路的最短路徑樹，收斂速度極快且理論保證絕無迴圈。"),
        ("OSPF 採用階層式區域（Area）劃分架構，其中所有非骨幹區域（Non-Backbone Areas）在邏輯上必須直接連接至哪一個核心區域？",
         "骨幹區域（Backbone Area，即 Area 0 或 Area 0.0.0.0）",
         ["骨幹區域（Backbone Area，即 Area 0 或 Area 0.0.0.0）",
          "邊界區域（Area 100）",
          "虛擬區域（Area 255）",
          "隨便連接至任意區域皆可"],
         "兩層階層設計防環：OSPF 規定全網所有跨區域流量「必須經由 Area 0 骨幹區域中轉」（星狀拓撲架構），嚴禁非骨幹區域之間繞過 Area 0 直接串聯，此舉在架構設計上徹底根絕了跨區域路由迴圈。若某個非骨幹區域因物理線路問題無法直連 Area 0，必須配置「虛擬鏈路（Virtual Link）」穿透中間區域邏輯縫合至 Area 0。"),
        ("在 OSPF 路由器分類中，「區域邊界路由器（<span class=\"en\">ABR, Area Border Router</span>）」與「自治系統邊界路由器（<span class=\"en\">ASBR, Autonomous System Boundary Router</span>）」的職責差異為？",
         "ABR 連接著兩個或多個不同區域（其中至少一個介面屬於 Area 0），負責區域間路由摘要與 LSA 轉發；ASBR 則負責將外部其他路由協定（如 BGP、靜態路由）重分配（Redistribute）注入進 OSPF 網路",
         ["ABR 連接著兩個或多個不同區域（其中至少一個介面屬於 Area 0），負責區域間路由摘要與 LSA 轉發；ASBR 則負責將外部其他路由協定（如 BGP、靜態路由）重分配（Redistribute）注入進 OSPF 網路",
          "ABR 負責上網，ASBR 負責列印",
          "兩者職責完全相同無區別",
          "ABR 只能安裝在 Cisco 設備上，ASBR 只能安裝在 Linux 上"],
         "路由器角色辨析：<br>1. IR（內部路由器）：所有介面皆在同一個 Area 內。<br>2. ABR（Area Border Router）：橫跨 Area 0 與其他 Area，維護多個獨立 LSDB，生成 Type 3 LSA。<br>3. ASBR（Autonomous System Border Router）：位處 OSPF 邊界，執行雙向路由重分配（Redistribution），生成 Type 5 外部 LSA。"),
        ("在多路存取廣播網路（如乙太網路）中，OSPF 為了防止 N 台路由器相互建立鄰接關係導致鄰接數（N(N-1)/2）與 LSA 泛洪量爆炸，所引入的選舉機制為？",
         "選舉指定路由器（DR, Designated Router）與備份指定路由器（BDR），其餘所有普通路由器（DROther）僅與 DR 和 BDR 建立鄰接關係",
         ["選舉指定路由器（DR, Designated Router）與備份指定路由器（BDR），其餘所有普通路由器（DROther）僅與 DR 和 BDR 建立鄰接關係",
          "每隔 5 分鐘強制隨機關閉一半的路由器",
          "禁止在乙太網路上運行 OSPF",
          "由網路管理員手動指定所有封包傳送順序"],
         "DR / BDR 機制效益：若無 DR，10 台路由器在同一交換機上需建立 10×9/2 = 45 個完全鄰接關係，泛洪 LSA 複製 45 份引發廣播塞車。引入 DR 後，大家只跟 DR/BDR 建鄰接（只需 2N - 3 個關係），DROther 之間保持 2-Way 狀態，所有 LSA 由 DR 統籌集中轉發。"),
        ("OSPF 選舉 DR 與 BDR 的具體評判準則依序為？",
         "先比介面 OSPF 優先權（Priority 0~255，數值最高者獲選；Priority 為 0 者直接喪失參選資格）；若優先權相同，則比「Router ID（RID）數值最高者」獲選",
         ["先比介面 OSPF 優先權（Priority 0~255，數值最高者獲選；Priority 為 0 者直接喪失參選資格）；若優先權相同，則比「Router ID（RID）數值最高者」獲選",
          "優先權最小者獲選為 DR",
          "最先開機的路由器永遠直接被淘汰",
          "Router ID 最小者獲選"],
         "DR 選舉關鍵細節（比大不比小！）：<br>1. Priority 預設為 1。若配置 `ip ospf priority 0`，代表永遠當平民（DROther）。<br>2. 核心考點：DR 選舉具備「非搶佔性（Non-preemptive）」！一旦 DR 和 BDR 選出，即使後續接入一台優先權為 255 的全新旗艦路由器，現任 DR 亦「絕不退位」，直到現任 DR 當機或 OSPF 進程重啟才會重新洗牌。"),
        ("OSPF 路由器的 Router ID（RID）是 32 位元的唯一識別碼，在未手動配置時，系統自動選舉 RID 的預設優先順序為？",
         "優先挑選數值最大的「Loopback 邏輯介面 IP」；若無 Loopback，則挑選數值最大的「活動中實體介面 IP」",
         ["優先挑選數值最大的「Loopback 邏輯介面 IP」；若無 Loopback，則挑選數值最大的「活動中實體介面 IP」",
          "優先挑選數值最小的實體介面 IP",
          "隨機生成一個 32 位元整數",
          "固定使用 192.168.1.1 作為 RID"],
         "RID 確定規則：<br>1. 首選：手動靜態配置 `router-id 1.1.1.1`（最穩定推薦）。<br>2. 次選：所有已啟用的 Loopback 介面中 IP 數值最高者（因為 Loopback 永不拔線斷線，極度穩定）。<br>3. 末選：所有處於 up 狀態的實體介面 IP 數值最高者。RID 一旦被選定即鎖定，實體介面斷線亦不改變，除非重啟 OSPF。"),
        ("OSPF 鄰居狀態機（Neighbor State Machine）從發現鄰居到完全同步完成，依序經歷的標準狀態轉換為？",
         "Down -> Init -> 2-Way -> ExStart -> Exchange -> Loading -> Full",
         ["Down -> Init -> 2-Way -> ExStart -> Exchange -> Loading -> Full",
          "Down -> 2-Way -> Full",
          "Init -> Loading -> Full -> Down",
          "Listening -> Learning -> Forwarding -> Blocking"],
         "OSPF 七大狀態機精析：<br>1. Down: 未收到 Hello。<br>2. Init: 收到鄰居 Hello，但其清單內尚未包含我自身的 RID。<br>3. 2-Way: 雙向通訊建立（在鄰居 Hello 清單內看見自己），DROther 之間在此狀態停步，DR/BDR 繼續前進。<br>4. ExStart: 協商主從關係（Master/Slave）與初始 DBD 序列號。<br>5. Exchange: 交換 DBD（資料庫描述摘要）。<br>6. Loading: 發送 LSR 請求缺失的 LSA，接收 LSU 回覆，回送 LSAck。<br>7. Full: 雙方 LSDB 達到 100% 完全同步吻合！"),
        ("OSPF 在廣播網段中發送更新時，發往「224.0.0.5」與「224.0.0.6」兩個多播位址的流量接收對象分別為？",
         "224.0.0.5 監聽對象為「所有 OSPF 路由器（AllSPFRouters）」；224.0.0.6 監聽對象為「僅 DR 與 BDR 路由器（AllDRouters）」",
         ["224.0.0.5 監聽對象為「所有 OSPF 路由器（AllSPFRouters）」；224.0.0.6 監聽對象為「僅 DR 與 BDR 路由器（AllDRouters）」",
          "224.0.0.5 專供微軟伺服器監聽；224.0.0.6 專供 Linux 監聽",
          "兩者皆為所有普通電腦監聽",
          "224.0.0.5 用於傳輸文字；224.0.0.6 用於傳輸圖片"],
         "多播流向考點：<br>1. DROther 主機有任何鏈路變更時，向 224.0.0.6 發送 LSU 通知 DR 與 BDR。<br>2. DR 收集後，統一向 224.0.0.5 泛洪轉發 LSU 通知全網所有路由器。各路由器回送 LSAck 確認。此架構極致精簡了多路存取網段的廣播風暴。"),
        ("OSPF 計算介面度量值（Cost）的標準公式為？當網路升級為 10 Gbps 高速光纖時，為什麼網管必須手動調整「參考頻寬（<span class=\"en\">Reference Bandwidth</span>）」？",
         "Cost = 參考頻寬 / 介面頻寬；預設參考頻寬為 100 Mbps，導致 100 Mbps、1 Gbps 與 10 Gbps 的計算結果皆為 Cost = 1（無法區分優劣），必須將參考頻寬調大為 10000 Mbps 或更高",
         ["Cost = 參考頻寬 / 介面頻寬；預設參考頻寬為 100 Mbps，導致 100 Mbps、1 Gbps 與 10 Gbps 的計算結果皆為 Cost = 1（無法區分優劣），必須將參考頻寬調大為 10000 Mbps 或更高",
          "Cost = 介面頻寬 / 參考頻寬，越寬成本越高",
          "OSPF 的 Cost 是由跳數決定",
          "參考頻寬必須永遠固定在 10 Mbps 不准修改"],
         "Cost 經典計算考點：預設公式 Cost = 10^8 / Bandwidth(bps)。<br>‧ 10 Mbps: Cost = 100M / 10M = 10。<br>‧ 100 Mbps: Cost = 100M / 100M = 1。<br>‧ 1 Gbps (1000M): 100M / 1000M = 0.1，因 Cost 必須是整數，四捨五入為 1！<br>‧ 10 Gbps: 也被折算為 1！結果百兆、千兆、萬兆鏈路在 OSPF 眼中成本完全一樣，引發次優路由。解法：配置 `auto-cost reference-bandwidth 100000`（改為 100 Gbps 基準）。"),
        ("常見的 OSPF LSA 類型中，「Type 1（Router LSA）」與「Type 2（Network LSA）」的生成者與泛洪範圍為？",
         "Type 1 由區域內「每台路由器」各自產生，描述本機鏈路與成本；Type 2 由廣播網段上的「DR」產生，描述網段成員；兩者的泛洪範圍皆「嚴格限制在單一區域內部（不跨區域）」",
         ["Type 1 由區域內「每台路由器」各自產生，描述本機鏈路與成本；Type 2 由廣播網段上的「DR」產生，描述網段成員；兩者的泛洪範圍皆「嚴格限制在單一區域內部（不跨區域）」",
          "Type 1 與 Type 2 皆會泛洪擴散至全世界網際網路",
          "Type 1 由 ABR 產生，Type 2 由 ASBR 產生",
          "兩者皆只能在 Area 0 內部存在"],
         "LSA 類型深度剖析：<br>1. Type 1 (Router LSA)：每台路由器皆發，泛洪限本 Area。<br>2. Type 2 (Network LSA)：DR 代表發送，宣告網段接了哪些 Router，泛洪限本 Area。<br>3. Type 3 (Network Summary LSA)：由 ABR 產生，將某 Area 的網段摘要宣告給其他 Area。<br>4. Type 4 (ASBR Summary LSA)：由 ABR 產生，通告「如何前往 ASBR」。<br>5. Type 5 (AS External LSA)：由 ASBR 產生，攜帶重分配進來的外部路由，泛洪至全網所有標準區域。"),
        ("OSPF 特殊區域中，「末梢區域（<span class=\"en\">Stub Area</span>）」與「完全末梢區域（<span class=\"en\">Totally Stub Area</span>）」對 LSA 的過濾規則為？",
         "Stub Area 過濾所有 Type 4 與 Type 5 外部 LSA，改由 ABR 注入一條 Type 3 預設路由；Totally Stub Area 則更進一步連 Type 3 區域間 LSA 也一併過濾（僅保留 ABR 注入的單一預設路由），極致縮減 LSDB 與路由表大小",
         ["Stub Area 過濾所有 Type 4 與 Type 5 外部 LSA，改由 ABR 注入一條 Type 3 預設路由；Totally Stub Area 則更進一步連 Type 3 區域間 LSA 也一併過濾（僅保留 ABR 注入的單一預設路由），極致縮減 LSDB 與路由表大小",
          "Stub Area 允許所有 LSA 通過無任何過濾",
          "Totally Stub Area 禁止任何電腦存取內部伺服器",
          "特殊區域內不能有任何路由器存在"],
         "特殊區域節省資源神技：邊緣辦公室路由器 RAM 和 CPU 孱弱，承受不起數萬條外部龐大路由。將該區域設為 Stub，ABR 築起高牆阻擋 Type 4/5 外部垃圾，只留一條預設路由對外；Totally Stub（Cisco 擴充）更絕，將其他 Area 的明細路由（Type 3）也全擋在門外，路由器表只剩直連加一條 `0.0.0.0/0`，運行無比輕巧流暢。"),
        ("邊界閘道協定（<span class=\"en\">BGP-4</span>）在網際網路核心中運作時，所使用的底層傳輸層協定與連接埠為？",
         "TCP 協定，連接埠 179",
         ["TCP 協定，連接埠 179",
          "UDP 協定，連接埠 520",
          "IP 原始協定，協定號 89",
          "ICMP 協定，連接埠 80"],
         "BGP 採用 TCP 的深層考量：網際網路全域 BGP 路由表目前高達近 100 萬條條目。在跨越數千公里的跨國海纜上交換如此海量的路由資料，BGP 自身不具備重傳與流量控制機制，直接借助 TCP Port 179 提供的強大滑動視窗、三向交握與保證可靠重傳能力，確保路由同步絕不丟失。"),
        ("BGP 屬於「路徑向量協定（<span class=\"en\">Path Vector Protocol</span>）」，其用來徹底防止跨自治系統路由迴圈的核心路徑屬性為？",
         "AS-Path 屬性，記錄該路由沿途穿越過的所有 AS 號碼清單；若路由器收到更新發現 AS-Path 中「已包含自身的 AS 號碼」，則立即判定為迴圈直接拋棄該更新",
         ["AS-Path 屬性，記錄該路由沿途穿越過的所有 AS 號碼清單；若路由器收到更新發現 AS-Path 中「已包含自身的 AS 號碼」，則立即判定為迴圈直接拋棄該更新",
          "Hop-Count 跳數屬性",
          "路由器製造商名稱屬性",
          "光纖延遲毫秒屬性"],
         "AS-Path 防環數學證明：例如 AS 100 發出路由，經過 AS 200、AS 300，AS-Path 為 (300, 200, 100)。若此路由繞回 AS 100，AS 100 的 BGP 路由器檢查路徑列表，赫然看見「100」赫然在列！證明該路由繞了一圈又回到發源地，形成跨國閉環，路由器立刻無情拒收丟棄。AS-Path 同時也是 BGP 選路的核心度量標準（AS-Path 越短越優先）。"),
        ("BGP 路由屬性中，「本地偏好（<span class=\"en\">Local Preference</span>）」與「多結束點鑑別值（<span class=\"en\">MED, Multi-Exit Discriminator</span>）」分別控制何種方向的流量？",
         "Local Preference 用於控制自治系統內流量「如何流出（出站流量 Outbound Traffic）」的最佳路徑；MED 用於向相鄰 AS 宣告建議其進入本 AS 的流量「如何流入（入站流量 Inbound Traffic）」",
         ["Local Preference 用於控制自治系統內流量「如何流出（出站流量 Outbound Traffic）」的最佳路徑；MED 用於向相鄰 AS 宣告建議其進入本 AS 的流量「如何流入（入站流量 Inbound Traffic）」",
          "兩者皆用於控制出站流量",
          "兩者皆用於控制入站流量",
          "Local Preference 只在路由器內部加密使用"],
         "BGP 流量工程（Traffic Engineering）必考：<br>1. Local Preference（預設 100，數值越大越優先）：在 AS 內部全體 iBGP 傳播，決定自家員工「從哪條 ISP 出境」。<br>2. MED（Metric，數值越小越優先）：發送給對端 AS，建議對方「從我的哪條線路入境」。但對端 ISP 可以自行配置策略忽略你的 MED 建議。"),
        ("在同一個自治系統內部運行的 BGP 稱為 iBGP（內部 BGP）。iBGP 為了防範 AS 內部路由迴圈，實施了何種嚴格的水平分割規則？該規則帶來的全網狀（Full-Mesh）擴展性難題通常如何解決？",
         "iBGP 水平分割規定「從某 iBGP 鄰居學到的路由，絕不轉發給其他 iBGP 鄰居」；導致所有 iBGP 路由器必須兩兩建立全互聯連線，業界通常採用「路由反射器（Route Reflector, RR）」或「聯邦（Confederation）」技術解決",
         ["iBGP 水平分割規定「從某 iBGP 鄰居學到的路由，絕不轉發給其他 iBGP 鄰居」；導致所有 iBGP 路由器必須兩兩建立全互聯連線，業界通常採用「路由反射器（Route Reflector, RR）」或「聯邦（Confederation）」技術解決",
          "iBGP 規定每台路由器只能連接單一鄰居",
          "全面改用 RIPv1 取代 iBGP",
          "在 AS 內部強制作業系統每隔一小時重啟"],
         "Route Reflector（RR）架構：因為 iBGP 封包穿越時不修改 AS-Path，無法靠 AS-Path 防環，故施加嚴厲的「只傳一跳禁轉他人」規則。100 台 iBGP 需建 4950 條 TCP 連線！部署 Route Reflector 後，指定少數核心路由器為 RR，客戶端只跟 RR 建立對等體，由 RR 打破規則代為反射轉發（透過 Cluster-ID 與 Originator-ID 防環），連線數降至 O(N)，完美解決超大規模擴展問題。"),
        ("BGP 路由選路決策決策流程（BGP Best-Path Selection Algorithm）中，在所有候選路徑中首先比較的第一項屬性為？",
         "權重（Weight，Cisco 專有，本機有效，數值最高者優先）與本地偏好（Local Preference，標準屬性，AS 內有效，數值最高者優先）",
         ["權重（Weight，Cisco 專有，本機有效，數值最高者優先）與本地偏好（Local Preference，標準屬性，AS 內有效，數值最高者優先）",
          "AS-Path 最長者優先",
          "Router ID 最小者優先",
          "隨機挑選一條路徑"],
         "BGP 經典 13 步選路口訣：<br>1. 最高 Weight（Cisco 專用）。<br>2. 最高 Local Preference（全 AS 控制出境）。<br>3. 本機起源（Local Originated）。<br>4. 最短 AS-Path（跳過最少 AS）。<br>5. 最低 Origin Code（IGP < EGP < Incomplete）。<br>6. 最低 MED（控制入境）。<br>7. eBGP 優於 iBGP。<br>8. 最小 IGP Metric 抵達 Next-Hop... BGP 透過層層策略完全掌控全球流量走向。"),
        ("OSPF 虛擬鏈路（<span class=\"en\">Virtual Link</span>）在何種特殊拓撲結構下必須被配置使用？",
         "當某個非骨幹區域因物理實體隔離「無法直接直連到 Area 0 骨幹區域」，或當 Area 0 因鏈路中斷被割裂為兩個孤島時，穿透一個過渡非骨幹區域建立邏輯虛擬通道",
         ["當某個非骨幹區域因物理實體隔離「無法直接直連到 Area 0 骨幹區域」，或當 Area 0 因鏈路中斷被割裂為兩個孤島時，穿透一個過渡非骨幹區域建立邏輯虛擬通道",
          "當需要連線至國際太空站時",
          "當所有光纖纜線全部被老鼠咬斷時",
          "當網路管理員忘記 OSPF 密碼時"],
         "Virtual Link 原理與約束：OSPF 核心法則是非骨幹區域必須直連 Area 0。若公司併購新網絡，Area 2 只能接在 Area 1 上（Area 2 - Area 1 - Area 0）。此時在兩端 ABR 之間穿越 Area 1 配置 Virtual Link，單播傳輸 OSPF 報文，邏輯上將 Area 2 直接拉到 Area 0 邊緣。約束條件：穿透的過渡區域（Transit Area）絕不能是 Stub 特殊區域！"),
        ("若兩台直連的 OSPF 路由器介面配置就緒，但鄰居狀態始終卡在「Init 狀態」或「2-Way 狀態」無法進入 Full，下列何者為最可能的故障原因？",
         "若卡在 Init 代表單向通訊（對端未收到本機 Hello，可能被防火牆 ACL 阻擋單向流量）；若卡在 2-Way 代表兩台路由器在廣播網路上皆為「DROther」身份（屬於正常的非 DR/BDR 關係）",
         ["若卡在 Init 代表單向通訊（對端未收到本機 Hello，可能被防火牆 ACL 阻擋單向流量）；若卡在 2-Way 代表兩台路由器在廣播網路上皆為「DROther」身份（屬於正常的非 DR/BDR 關係）",
          "路由器硬體即將報廢",
          "光纖纜線被反向插接",
          "作業系統版本過新"],
         "OSPF 狀態排錯精華：<br>1. 卡在 2-Way：若兩台交換機上的路由器都是 DROther，彼此不建立完全鄰接是 100% 正確的正常現象！無需驚慌。<br>2. 卡在 ExStart / Exchange：90% 機率是兩端介面的 MTU 不匹配（MTU Mismatch，DBD 封包超出大小被丟棄）。<br>3. 無法到 2-Way（卡在 Init/Down）：檢查 Hello/Dead Timer 是否相同、Area ID 是否相同、認證密碼是否一致、Subnet Mask 是否一致。")
    ]

    # 3. 傳輸層 TCP 三向交握、狀態機與滑動視窗 (18 題)
    tcp_state_data = [
        ("傳輸控制協定（<span class=\"en\">TCP</span>）建立連線所採用的「三向交握（Three-Way Handshake）」過程中，各次封包交換的旗標（Flags）與序號（Sequence Number）邏輯依序為？",
         "第一次：客戶端發送 SYN（seq = x）；第二次：伺服器回送 SYN + ACK（seq = y, ack = x + 1）；第三次：客戶端發送 ACK（seq = x + 1, ack = y + 1）",
         ["第一次：客戶端發送 SYN（seq = x）；第二次：伺服器回送 SYN + ACK（seq = y, ack = x + 1）；第三次：客戶端發送 ACK（seq = x + 1, ack = y + 1）",
          "第一次：發送 ACK；第二次：回送 SYN；第三次：發送 FIN",
          "第一次：發送 HELLO；第二次：回送 OK；第三次：發送 START",
          "兩次握手即可完全建立連線，第三次純屬多餘浪費"],
         "三向交握步進時序：<br>1. Client -> Server: SYN=1, seq=x（宣告自己的初始序號 ISN，進入 SYN_SENT）。<br>2. Server -> Client: SYN=1, ACK=1, seq=y, ack=x+1（確認 Client 序號並宣告自己的 ISN，進入 SYN_RCVD）。<br>3. Client -> Server: ACK=1, seq=x+1, ack=y+1（確認 Server 序號，雙方進入 ESTABLISHED 成功建立全雙工連線！第三次交握封包即可攜帶應用層數據）。"),
        ("TCP 為何「必須採用三次交握」建立連線，而不能僅採用兩次交握？",
         "防止網路中滯留的老舊失效連線請求封包（Stale / Duplicate SYN）突然傳送至伺服器，導致伺服器單方面誤判建立無效連線而長期浪費資源",
         ["防止網路中滯留的老舊失效連線請求封包（Stale / Duplicate SYN）突然傳送至伺服器，導致伺服器單方面誤判建立無效連線而長期浪費資源",
          "因為電腦晶片只能執行奇數次的運算",
          "為了讓通訊過程耗費更多時間",
          "兩次交握無法在光纖中傳輸"],
         "RFC 793 經典核心證明：假設 Client 發出 SYN_1 在網路路由器隊列中被滯留了數分鐘，Client 超時後重新發出 SYN_2 建立連線並結束關閉。過後滯留的老舊 SYN_1 終於抵達 Server。若只需兩次握手，Server 回覆 ACK 後立刻認定連線建立，傻傻等待 Client 發送數據；但 Client 根本無此連線意圖，不理會 Server。三次交握下，Server 回送 SYN+ACK，Client 發現 ack 號碼不對，發送 RST 強制取消，防止 Server 資源被殭屍連線鎖死。"),
        ("TCP 連線終止釋放（Connection Teardown）通常需要經過「四次揮手（Four-Way Wave）」，其根本原因為？",
         "TCP 是「全雙工（Full-Duplex）」連線，兩個方向的資料通道必須獨立個別關閉；當一端發送 FIN 僅代表其自身不再發送資料，但其依然能繼續接收對端尚未發送完畢的資料（半關閉狀態 TCP Half-Close）",
         ["TCP 是「全雙工（Full-Duplex）」連線，兩個方向的資料通道必須獨立個別關閉；當一端發送 FIN 僅代表其自身不再發送資料，但其依然能繼續接收對端尚未發送完畢的資料（半關閉狀態 TCP Half-Close）",
          "因為終止連線比建立連線複雜兩倍",
          "四次揮手是由微軟公司專有規定的",
          "為了向通訊雙方各自收取兩次通話費用"],
         "四次揮手時序分析：<br>1. A -> B: FIN（A 說：「我寫完了，準備關閉我的發送通道」），A 進入 FIN_WAIT_1。<br>2. B -> A: ACK（B 說：「收到你的關閉請求，但我手頭還有資料沒傳完，你先聽著」），A 進入 FIN_WAIT_2，B 進入 CLOSE_WAIT。<br>3. B 把剩下資料發完後 -> A: FIN（B 說：「我也傳完了，關閉我的發送通道」），B 進入 LAST_ACK。<br>4. A -> B: ACK（A 確認收悉），A 進入 TIME_WAIT，B 收到立刻 CLOSED。"),
        ("主動關閉 TCP 連線的一方在發送最後一個 ACK 後，必須在「TIME_WAIT」狀態停留長達 2MSL（最長封包存活時間，通常為 1~2 分鐘）的時間，該狀態存在的兩大核心意義為？",
         "確保最後發送的 ACK 能可靠送達對端（若對端未收到重發 FIN，本機能在 2MSL 內重送 ACK 防止對端卡死），以及讓網路中殘留的所有老舊封包在 2MSL 內自然消亡，防止干擾未來建立的新連線",
         ["確保最後發送的 ACK 能可靠送達對端（若對端未收到重發 FIN，本機能在 2MSL 內重送 ACK 防止對端卡死），以及讓網路中殘留的所有老舊封包在 2MSL 內自然消亡，防止干擾未來建立的新連線",
          "為了等待電腦主機板降溫冷卻",
          "防止駭客在 2 分鐘內再次連線",
          "讓使用者有時間反悔重新打開連線"],
         "TIME_WAIT 兩大生死考點（RFC 793）：<br>1. 保證可靠終止：若 A 最後的 ACK 遺失，B 在逾時後會重發 FIN。A 必須停留在 TIME_WAIT 才能接收此重發 FIN 並再次回送 ACK；若 A 早就 CLOSED，會回送 RST 導致 B 異常報錯。<br>2. 封包自然消亡：MSL（Maximum Segment Lifetime）是封包在網路上存活的最大極限。等待 2MSL（一個往返）保證此連線的所有殘留幽靈封包全數在網路上徹底湮滅，絕不會在同一個四元組 (IP, Port) 的未來新連線中冒充出現。"),
        ("伺服器遭遇常見的「SYN Flood 拒絕服務攻擊」時，其微觀崩潰機制為？業界普遍採用的防禦技術為？",
         "攻擊者偽造巨量隨機 IP 發送 SYN 請求，伺服器分配 TCB 控制塊後在「半連線佇列（SYN Queue）」苦等第三次 ACK 直到緩衝區爆滿拒絕合法連線；解法為啟用「SYN Cookies」技術",
         ["攻擊者偽造巨量隨機 IP 發送 SYN 請求，伺服器分配 TCB 控制塊後在「半連線佇列（SYN Queue）」苦等第三次 ACK 直到緩衝區爆滿拒絕合法連線；解法為啟用「SYN Cookies」技術",
          "攻擊者發送病毒指令讓伺服器硬碟短路",
          "關閉伺服器的所有 TCP 埠",
          "將伺服器的 IP 位址修改為中文"],
         "SYN Flood 攻擊與 SYN Cookies 防禦：<br>1. 攻擊本質：伺服器收到 SYN 進入 SYN_RCVD，分配記憶體維護半連接，並等待 3 次握手的 ACK（逾時長達數十秒）。攻擊者只發 SYN 不回 ACK，半連接隊列秒級被塞爆。<br>2. SYN Cookies 絕妙破法：伺服器收到 SYN 時「完全不分配任何記憶體緩衝區」，而是將來源IP、目的IP、埠號與時間戳加密雜湊算成一個魔法數值作為自己的初始序號 y（ISN）。若合法客戶端回送 ACK（ack = y + 1），伺服器只需反算確認 Cookie 合法，此時才正式分配連線結構，徹底免疫半連接隊列耗盡攻擊！"),
        ("TCP 標頭中的「確認號（<span class=\"en\">Acknowledgment Number</span>，32 bits）」在累積確認（Cumulative ACK）架構下的語意為？",
         "期望收到對端的「下一個位元組序號（Next Expected Byte Sequence Number）」，同時隱含宣告該序號之前的所有資料已經全數成功正確接收",
         ["期望收到對端的「下一個位元組序號（Next Expected Byte Sequence Number）」，同時隱含宣告該序號之前的所有資料已經全數成功正確接收",
          "剛剛成功收到的最後一個位元組序號",
          "發送端自己的目前序號",
          "通訊雙方已傳輸的封包總個數"],
         "TCP 序號與確認號本質：TCP 是「位元組串流（Byte Stream）」協定，其序號是按字節編號的。若接收端回傳 `ack = 5001`，其精確語意是：「第 0 到 5000 號位元組我已經完好無損收到了，請你接下來從第 5001 號位元組開始發送！」。如果收到 5001~6000 號但遺失了 4001~5000 號，接收端依然只能回傳 `ack = 4001`。"),
        ("TCP 滑動視窗（<span class=\"en\">Sliding Window</span>）機制中，「接收視窗（<span class=\"en\">rwnd, Receive Window</span>）」欄位長度為 16 位元，主要負責實現何種傳輸控制功能？",
         "流量控制（Flow Control），接收端透過宣告自身的剩餘緩衝區可用空間，嚴格限制發送端的發送速率，防止發送過快灌爆接收端緩衝區導致丟包",
         ["流量控制（Flow Control），接收端透過宣告自身的剩餘緩衝區可用空間，嚴格限制發送端的發送速率，防止發送過快灌爆接收端緩衝區導致丟包",
          "壅塞控制（Congestion Control），防止骨幹路由器塞車",
          "資料加密控制，防止封包被竊聽",
          "計算網路訊號的光速傳播時間"],
         "Flow Control vs Congestion Control 必考辨析：<br>‧ 流量控制（Flow Control）：端對端機制（接收端控制發送端）。接收端在 TCP 標頭的 Window Size 欄位宣告 `rwnd` 大小（告知自己還有多少 Buffer）。若接收端處理緩慢，rwnd 逐漸縮減為 0（零視窗 Zero Window），發送端必須停止發送。<br>‧ 壅塞控制（Congestion Control）：全域機制（防止發送端灌爆整個網際網路骨幹路由器）。"),
        ("當 TCP 接收端向發送端宣告「零視窗（Zero Window，rwnd = 0）」後，發送端將暫停發送。為了防止後續接收端發送的「非零視窗更新 ACK」在網路上意外遺失而導致雙方陷入永久死結，TCP 採取的解決機制為？",
         "啟動堅持計時器（Persist Timer），定期向接收端發送僅含 1 位元組資料的「視窗探測封包（Zero Window Probe）」，強迫接收端回傳當前最新視窗大小",
         ["啟動堅持計時器（Persist Timer），定期向接收端發送僅含 1 位元組資料的「視窗探測封包（Zero Window Probe）」，強迫接收端回傳當前最新視窗大小",
          "直接發送 RST 終止連線並報警",
          "強制作業系統重新開機",
          "無限期等待直到通訊合約到期"],
         "死結破解原理：接收端 Buffer 空出後發送 `rwnd = 2000` 的 ACK，此 ACK 若不幸丟失，接收端在等發送端傳資料，發送端在等接收端開放視窗，雙方永久互相等待（Deadlock）。Persist Timer 逾時後發送 Probe 探針（不含有效資料），接收端收到必須回覆 ACK 告知當前 window，成功化解死結。"),
        ("在高速寬頻長延遲網路（LFN）中，TCP 標頭原本 16 位元的 Window Size 最大僅能宣告 65535 位元組（64 KB），嚴重限制了吞吐量。為此 RFC 1323 引入的 TCP 選項為？",
         "視窗縮放選項（Window Scale Option），允許將視窗大小左移最多 14 位元（乘數因子最大 2^14 = 16384），將最大視窗容量擴展至 1 GB（2^30 位元組）",
         ["視窗縮放選項（Window Scale Option），允許將視窗大小左移最多 14 位元（乘數因子最大 2^14 = 16384），將最大視窗容量擴展至 1 GB（2^30 位元組）",
          "將 TCP 標頭擴展為 1000 位元組",
          "強制所有封包使用光纖傳輸",
          "將所有的資料分割為 1 位元大小"],
         "Window Scale 應用：在三向交握的 SYN 封包中雙方協商 Scale Factor（shift.cnt）。若協商 shift = 7，標頭中宣告 window = 1000 實際代表 1000 × 2^7 = 128,000 Bytes。此選項是現代萬兆網路、衛星通訊跑滿頻寬延遲積（BDP）的絕對必備前提。"),
        ("「糊塗視窗症候群（<span class=\"en\">Silly Window Syndrome</span>）」是指通訊雙方反覆傳輸極小資料量（如 1 個位元組資料卻附帶 40 位元組標頭）導致頻寬嚴重浪費的低效現象。針對「發送端」的標準解決演算法為？",
         "納格演算法（Nagle's Algorithm）",
         ["納格演算法（Nagle's Algorithm）",
          "克拉克演算法（Clark's Algorithm）",
          "戴克斯特拉演算法（Dijkstra）",
          "彼得森演算法（Peterson）"],
         "Silly Window 解決方案雙劍合璧：<br>1. 發送端解法（Nagle 演算法）：若應用程式每次只產生微小數據（如 Telnet 按鍵 1 Byte），發送端先發第 1 個 byte，隨後將後續產生的小數據在緩衝區內累積拼裝；直到「收到前一個封包的 ACK」或「積滿一個滿額 MSS」時才一次性打包發出！<br>2. 接收端解法（Clark 演算法 / 延遲 ACK）：視窗若只空出小空間（如小於 MSS 且小於緩衝區一半）時宣告 rwnd=0，直到空出足夠大空間才宣告開放。"),
        ("在即時網路遊戲（如 FPS 電競）或遠端鍵盤互動中，開發者通常會在 Socket 連線中設定 `TCP_NODELAY` 選項，其具體作用為？",
         "停用納格演算法（Nagle's Algorithm），確保微小封包（如滑鼠移動、單一按鍵）能夠立即發送，以犧牲少許頻寬效率為代價換取極致的「超低互動延遲」",
         ["停用納格演算法（Nagle's Algorithm），確保微小封包（如滑鼠移動、單一按鍵）能夠立即發送，以犧牲少許頻寬效率為代價換取極致的「超低互動延遲」",
          "將網路延遲強制鎖定為 0 毫秒",
          "關閉 TCP 的校驗碼檢查",
          "將網路連線自動切換為 UDP"],
         "TCP_NODELAY 實務考點：Nagle 演算法會將小資料扣留在本地等待 ACK。而接收端又有「延遲確認（Delayed ACK，延遲 40~200ms）」機制。當 Nagle 撞上 Delayed ACK，兩者互等，滑鼠按鍵將遭遇高達 200ms 的嚴重遲滯！因此遊戲通訊與低延遲微服務必開 `TCP_NODELAY`（直接 flush 輸出）。"),
        ("TCP 標頭中如果將「RST（Reset）」旗標置位為 1，代表的通訊語意為？",
         "強制異常終止連線（Abrupt Connection Teardown），或拒絕一個發往未開啟監聽連接埠的無效連線請求",
         ["強制異常終止連線（Abrupt Connection Teardown），或拒絕一個發往未開啟監聽連接埠的無效連線請求",
          "請求對方將網路速度重新設定為 1000 Mbps",
          "通知對方本機準備重新開機",
          "請求對方重新傳送全部歷史網頁檔案"],
         "RST 典型觸發情境：<br>1. 連線至關閉的連接埠：發送 SYN 到某主機 Port 8080，但該主機未運行任何服務，作業系統核心直接回送 RST+ACK 拒絕連線（等同 Connection Refused）。<br>2. 異常崩潰恢復：主機當機重開後，收到舊連線的封包，回送 RST 通知對方本機已無此連線記憶。<br>3. 惡意連線阻斷：防火牆或 GFW 偽造 RST 封包雙向注入，強制切斷通訊雙方的連線。"),
        ("TCP「選擇性確認（<span class=\"en\">SACK, Selective Acknowledgment</span>，RFC 2018）」選項帶來的核心效能革新為？",
         "允許接收端在 ACK 標頭中精確回報已接收到的多個「非連續資料區間區塊（Blocks）」，使發送端僅需針對真正遺失的特定空洞資料進行重傳，避免盲目重傳已到達的後續數據",
         ["允許接收端在 ACK 標頭中精確回報已接收到的多個「非連續資料區間區塊（Blocks）」，使發送端僅需針對真正遺失的特定空洞資料進行重傳，避免盲目重傳已到達的後續數據",
          "允許接收端自由選擇是否要傳送 ACK",
          "將 TCP 傳輸速率提高至光速的十倍",
          "完全消除網路丟包現象"],
         "SACK 終結 Go-Back-N 悲劇：傳統累積確認下，發送端發了 1~10 號封包，若只有第 3 號丟失，接收端只能反覆回傳 `ack = 3`，發送端無奈之下必須把 3~10 號全部重發一遍（即使 4~10 號完好到達）。啟用 SACK 選項後，接收端回報 `ack = 3, SACK=(4-10)`，發送端一目了然，只單獨重傳第 3 號封包，在高延遲高速鏈路中大幅挽救吞吐量。"),
        ("TCP 標頭中的「PSH（Push）」旗標的作用為？",
         "通知接收端 TCP 協定棧在收到此區段後「應立即將緩衝區資料提交給應用程式處理」，無需等待緩衝區填滿或計時器超時",
         ["通知接收端 TCP 協定棧在收到此區段後「應立即將緩衝區資料提交給應用程式處理」，無需等待緩衝區填滿或計時器超時",
          "強制向發送端推送推播廣告通知",
          "將封包以物理推力加速傳輸",
          "將資料永久儲存在硬碟的回收筒中"],
         "PSH 語意：正常情況下 TCP 為了效率會暫存一批資料才呼叫 socket read() 喚醒應用程式。若設定 PSH=1（如 HTTP 請求發送完畢最後一個字節，或交易提交指令），指示接收端作業系統內核「立刻把資料推上樓給應用軟體，別在緩衝區耽擱！」。"),
        ("TCP 逾時重傳計時器（<span class=\"en\">RTO, Retransmission TimeOut</span>）在計算時，必須動態追蹤與平滑估算「往返時間（<span class=\"en\">RTT, Round-Trip Time</span>）」，其採用的著名標準平滑公式為？",
         "雅各布森演算法（Jacobson / Karels Algorithm），依據加權平滑 RTT（SRTT）與 RTT 變異偏差（RTTVAR）動態計算 RTO",
         ["雅各布森演算法（Jacobson / Karels Algorithm），依據加權平滑 RTT（SRTT）與 RTT 變異偏差（RTTVAR）動態計算 RTO",
          "簡單算術平均值公式",
          "固定設定 RTO = 1 秒鐘永不改變",
          "牛頓運動定律求解公式"],
         "Van Jacobson 演算法（RFC 6298）：若 RTO 設太大，丟包時空等浪費頻寬；若設太小，網路稍有延遲即觸發偽重傳。RFC 6298 經典公式：<br>1. RTTVAR = (1 - β) × RTTVAR + β × |SRTT - RTT_sample|<br>2. SRTT = (1 - α) × SRTT + α × RTT_sample（α 常用 1/8）。<br>3. RTO = SRTT + max(G, 4 × RTTVAR)。考慮了波動方差，極度適應網際網路抖動特性。"),
        ("卡恩演算法（<span class=\"en\">Karn's Algorithm</span>）在計算 TCP 逾時重傳時間 RTO 時，解決的關鍵難題為？",
         "重傳歧義性問題（Retransmission Ambiguity）：規定「在封包重傳後收到的 ACK，絕不用於更新 RTT 樣本計算」，並在每次逾時重傳時將 RTO 直接翻倍（指數退避 Exponential Backoff）",
         ["重傳歧義性問題（Retransmission Ambiguity）：規定「在封包重傳後收到的 ACK，絕不用於更新 RTT 樣本計算」，並在每次逾時重傳時將 RTO 直接翻倍（指數退避 Exponential Backoff）",
          "計算光纖中光的折射角度",
          "判斷使用者的密碼是否安全",
          "解決 TCP 埠號不足的問題"],
         "Karn 演算法精髓：發送封包 1 逾時，發送重傳封包 1'。過後收到 ACK。此 ACK 到底是確認原本的 1 還是重傳的 1'？若算錯 RTT 會導致 RTO 崩潰。Phil Karn 規定：重傳過的封包採樣一律丟棄不計；且每次超時直接 `RTO = RTO × 2`，迅速抑制擁塞發送。"),
        ("若某主機的 TCP 連線狀態處於「CLOSE_WAIT」，代表的具體含義為？若伺服器出現成千上萬個 CLOSE_WAIT 連線，根因通常為？",
         "本機已收到對端的 FIN 並回覆了 ACK，正在等待本地應用程式呼叫 `close()` 關閉連線；大量堆積代表「應用程式程式碼有 Bug（漏寫 socket close 或執行緒阻塞無法釋放連線）」",
         ["本機已收到對端的 FIN 並回覆了 ACK，正在等待本地應用程式呼叫 `close()` 關閉連線；大量堆積代表「應用程式程式碼有 Bug（漏寫 socket close 或執行緒阻塞無法釋放連線）」",
          "網路實體線路被惡意剪斷",
          "伺服器遭到了 SYN Flood 攻擊",
          "客戶端電腦已經關機"],
         "維運排錯黃金考點：<br>‧ TIME_WAIT 多：多出現在主動關閉端（通常為客戶端或 Web 反向代理），屬正常協定狀態，可調優 tcp_tw_reuse。<br>‧ CLOSE_WAIT 多：多出現在被動關閉端（伺服器）。對端已經說再見了，伺服器內核也確認了，但伺服器軟體程式碼（如 Java, Python 後端代碼）沒有執行 `client.close()`！連線永遠卡在 CLOSE_WAIT 佔死檔案描述符（FD），導致伺服器報出 `Too many open files` 癱瘓崩潰。"),
        ("TCP 的「保活計時器（<span class=\"en\">Keepalive Timer</span>，RFC 1122 規範預設通常為 2 小時）」之核心設計目的為？",
         "偵測並清理長時間無任何資料傳輸的 TCP 連線中，對端客戶端是否已經無預警斷電、死機崩潰或網路中斷，防止伺服器連線結構長期淪為殭屍資源",
         ["偵測並清理長時間無任何資料傳輸的 TCP 連線中，對端客戶端是否已經無預警斷電、死機崩潰或網路中斷，防止伺服器連線結構長期淪為殭屍資源",
          "強制所有連線在 2 小時後必須中斷重新登入",
          "每隔 2 小時向電信公司通報在線狀態",
          "將連線的資料速度每隔 2 小時翻倍一次"],
         "Keepalive 機制：若連線空閒達 7200 秒（2小時），TCP 自動向對端發送探針（Probe）。若連續數次（如 9 次，間隔 75 秒）無任何 ACK 回應，核心判定對端已死亡，主動釋放該連線。在長連線即時通訊中，應用層通常會自行實作更高頻率（如數十秒一次）的應用層心跳包（Heartbeat）。")
    ]

    # 4. TCP 壅塞控制、UDP 與 DNS/DHCP 運作機制 (18 題)
    cong_udp_data = [
        ("TCP 壅塞控制（Congestion Control）經典四大核心演算法為？",
         "慢啟動（Slow Start）、壅塞避免（Congestion Avoidance）、快重傳（Fast Retransmit）與快恢復（Fast Recovery）",
         ["慢啟動（Slow Start）、壅塞避免（Congestion Avoidance）、快重傳（Fast Retransmit）與快恢復（Fast Recovery）",
          "快速開機、安全關機、硬碟重組、檔案備份",
          "流量分類、優先佇列、加權輪詢、隨機丟棄",
          "對稱加密、非對稱加密、雜湊校驗、數位簽章"],
         "Van Jacobson 挽救網際網路的四大基石（RFC 5681）：發送端維護「壅塞窗口（cwnd, Congestion Window）」。發送端在任意時刻的實際發送窗口上限為 W = min(cwnd, rwnd)（既不超過接收端承受力，亦不超過網路骨幹承受力）。四大演算法協同調節 cwnd。"),
        ("TCP「慢啟動（<span class=\"en\">Slow Start</span>）」階段中，壅塞窗口（cwnd）的增長特徵為？",
         "每經過一個往返時間（RTT），若發送的所有封包皆順利收到 ACK，壅塞窗口大小呈現「指數級翻倍增長（Exponential Growth，cwnd = cwnd × 2）」",
         ["每經過一個往返時間（RTT），若發送的所有封包皆順利收到 ACK，壅塞窗口大小呈現「指數級翻倍增長（Exponential Growth，cwnd = cwnd × 2）」",
          "每個 RTT 僅固定增加 1 個 MSS（線性增長）",
          "壅塞窗口大小保持固定不變",
          "每個 RTT 窗口大小減半"],
         "慢啟動名不副實：名稱叫「慢（Slow）」，僅僅是因為它起步時保守（初始 cwnd = 1 至 10 個 SMSS），但它的增長速率是極其狂暴的「指數增長」！每收到 1 個合法 ACK，`cwnd += 1 SMSS`；一個 RTT 內窗口所有的封包被 ACK，cwnd 直接乘以 2（1 -> 2 -> 4 -> 8 -> 16...）。快速探測出網路的最大可用頻寬。"),
        ("當 TCP 慢啟動階段的壅塞窗口 cwnd 增長達到或超過「慢啟動閾值（<span class=\"en\">ssthresh, Slow Start Threshold</span>）」時，演算法將切換至何種階段？該階段的增長特徵為？",
         "切換至「壅塞避免（Congestion Avoidance）」階段；每個 RTT 窗口僅增加 1 個 MSS，呈現平緩的「線性增長（Additive Increase）」",
         ["切換至「壅塞避免（Congestion Avoidance）」階段；每個 RTT 窗口僅增加 1 個 MSS，呈現平緩的「線性增長（Additive Increase）」",
          "切換至快恢復階段，窗口直接歸零",
          "停止發送資料並中斷連線",
          "窗口增長速度再次翻倍為四次方"],
         "加法增大（Additive Increase）：當 cwnd ≥ ssthresh 時，代表已經接近先前發生過擁塞的警戒水位。為了防止指數狂飆瞬間撞牆丟包，TCP 轉入「壅塞避免」：每收到 1 個 ACK 僅增加 `1/cwnd` 個 MSS，一個 RTT 累積增長恰好為 1 個 MSS（16 -> 17 -> 18 -> 19...），小心翼翼地試探頻寬邊界。"),
        ("在 TCP Reno 演算法中，當發送端連續收到「3 個重複的確認（Triple Duplicate ACKs）」時，將觸發何種機制？其處置方式為？",
         "觸發「快重傳與快恢復」；判定僅為個別封包丟失（網路未嚴重崩潰），立刻重傳該遺失封包，將 ssthresh 設為當前 cwnd 的一半，並將 cwnd 設為 ssthresh 進入快恢復，無需退回慢啟動",
         ["觸發「快重傳與快恢復」；判定僅為個別封包丟失（網路未嚴重崩潰），立刻重傳該遺失封包，將 ssthresh 設為當前 cwnd 的一半，並將 cwnd 設為 ssthresh 進入快恢復，無需退回慢啟動",
          "判定網路徹底癱瘓，將 cwnd 強制歸 1 重新慢啟動",
          "忽略重複確認，繼續發送新資料",
          "立刻關閉連線"],
         "快重傳與快恢復（Fast Retransmit & Fast Recovery）：若封包在中途丟失，後續到達的封包會強迫接收端反覆回傳重複 ACK。連收 3 個 Dup-ACK 證明「後續封包還能送達，網路並非完全堵死」。發送端不等逾時計時器，秒級重傳丟失封包（快重傳），並將 cwnd 乘法減半（Multiplicative Decrease），維持高速吞吐量。若為「RTO 逾時丟包」，則代表嚴重堵死，必須硬性將 cwnd 歸 1 跌回慢啟動！"),
        ("加法增大、乘法減小（<span class=\"en\">AIMD, Additive Increase Multiplicative Decrease</span>）原則在網際網路穩定性中的數學核心意義為？",
         "數學證明保證多個競爭同條瓶頸鏈路的 TCP 連線在長期運作下，能夠動態收斂至「全域最佳的頻寬利用率與絕對的公平性（Fairness & Efficiency）」",
         ["數學證明保證多個競爭同條瓶頸鏈路的 TCP 連線在長期運作下，能夠動態收斂至「全域最佳的頻寬利用率與絕對的公平性（Fairness & Efficiency）」",
          "保證傳輸速度永遠達到光速",
          "使所有電腦的記憶體大小保持完全相等",
          "消滅所有的網路延遲"],
         "Chiu & Jain 向量空間收斂定理：若兩個連線共享頻寬，在二維坐標系中，Additive Increase（斜率為 1 的直線，雙方各 +1）將狀態拉向高利用率邊界；Multiplicative Decrease（指向原點的射線，雙方等比例減半）將狀態拉向 y = x 的 45 度絕對公平線。兩者交替振盪，系統最終完美收斂收斂於公平高效平衡點。"),
        ("使用者資料報協定（<span class=\"en\">UDP, User Datagram Protocol</span>）相較於 TCP，最顯著的架構特徵為？",
         "無連線、不保證可靠送達、無流量控制與壅塞控制、標頭開銷極小（僅 8 位元組）、傳輸延遲極低且支援多播與廣播",
         ["無連線、不保證可靠送達、無流量控制與壅塞控制、標頭開銷極小（僅 8 位元組）、傳輸延遲極低且支援多播與廣播",
          "具備比 TCP 更嚴格的三向交握與滑動視窗",
          "標頭長度為 60 位元組",
          "只能在局域網路中傳輸，無法跨越網際網路"],
         "UDP 輕量哲學（RFC 768）：UDP 幾乎就是 IP 協定的第四層薄薄封裝，僅僅增加了埠號（多工解多工）與可選的校和。它不建立連線、不維護狀態、不重傳、不限速，應用層給多少就發多少。適合：<br>1. 即時影音/語音（VoIP, 視訊會議，寧可丟幾幀也不能容忍 TCP 重傳延遲）。<br>2. 簡單一問一答請求（DNS, NTP, SNMP）。<br>3. 多播廣播應用。"),
        ("UDP 標頭的長度固定為多少位元組（Bytes）？其內部包含哪四個欄位？",
         "固定為 8 位元組；包含來源連接埠（Source Port）、目的連接埠（Destination Port）、長度（Length）與校驗和（Checksum）",
         ["固定為 8 位元組；包含來源連接埠（Source Port）、目的連接埠（Destination Port）、長度（Length）與校驗和（Checksum）",
          "固定為 20 位元組；包含序號與確認號",
          "長度可變在 8 至 64 位元組之間",
          "固定為 4 位元組；僅包含 IP 位址"],
         "UDP 標頭極簡結構（各佔 16 bits = 2 Bytes）：<br>1. Source Port（2B）：可選，若無需回覆可填 0。<br>2. Destination Port（2B）：必填。<br>3. Length（2B）：包含標頭與資料在內的總長度（最小為 8）。<br>4. Checksum（2B）：在 IPv4 中可選（若不計算填全0），在 IPv6 中強制必算！"),
        ("網域名稱系統（<span class=\"en\">DNS, Domain Name System</span>）在標準運作時，何時使用 UDP 53 埠？何時使用 TCP 53 埠？",
         "一般客戶端網域名稱查詢與解析採用 UDP 53 埠（速度快開銷小）；DNS 主從伺服器之間進行「區域轉移（Zone Transfer）」或回應封包超過 512 位元組時採用 TCP 53 埠",
         ["一般客戶端網域名稱查詢與解析採用 UDP 53 埠（速度快開銷小）；DNS 主從伺服器之間進行「區域轉移（Zone Transfer）」或回應封包超過 512 位元組時採用 TCP 53 埠",
          "DNS 永遠只使用 TCP，絕不使用 UDP",
          "DNS 永遠只使用 UDP，絕不使用 TCP",
          "平日使用 UDP，週末使用 TCP"],
         "DNS 雙協定設計：<br>1. UDP 53：標準客戶端解析（如查 `www.google.com`），一次發送一次回應，UDP 零交握延遲極佳。若傳統 UDP 回應 > 512 Bytes（TC 截斷旗標置位），客戶端退回改用 TCP 重新查詢（現代 EDNS0 擴展了 UDP 緩衝區）。<br>2. TCP 53：Secondary DNS 向 Primary DNS 同步完整區域資料庫（Zone Transfer，AXFR / IXFR），資料量龐大且要求 100% 可靠無失真，強制使用 TCP。"),
        ("DNS 查詢模式中，「遞迴查詢（<span class=\"en\">Recursive Query</span>）」與「反覆/迭代查詢（<span class=\"en\">Iterative Query</span>）」的運作差別為？",
         "遞迴查詢要求受詢伺服器「必須代替客戶端一路追查到底並回傳最終 IP 結果」；迭代查詢則是伺服器「告知客戶端下一跳該去問哪一台更權威的 DNS 伺服器」，由客戶端自行一步步追問",
         ["遞迴查詢要求受詢伺服器「必須代替客戶端一路追查到底並回傳最終 IP 結果」；迭代查詢則是伺服器「告知客戶端下一跳該去問哪一台更權威的 DNS 伺服器」，由客戶端自行一步步追問",
          "遞迴查詢速度慢十倍，迭代查詢速度快十倍",
          "遞迴查詢只能查詢中文網址",
          "兩者運作機制完全相同無差異"],
         "DNS 查詢階層架構：<br>1. 客戶端 PC -> 本地快取 DNS（如 168.95.1.1 或 8.8.8.8）：採用「遞迴查詢」（PC 說：「請務必把最終答案給我，我不管你怎麼查」）。<br>2. 本地 DNS -> 根網域名稱伺服器（Root） -> 頂級網域名稱伺服器（TLD，如 .com / .tw） -> 權威伺服器（Authoritative）：採用「迭代查詢」（Root 回應：「我不知道 www 的 IP，但我知道 .tw 的伺服器是誰，你去問它吧」）。"),
        ("常見的 DNS 資源記錄（<span class=\"en\">RR, Resource Record</span>）型態中，A 記錄、AAAA 記錄、CNAME 記錄與 MX 記錄分別代表什麼含義？",
         "A 代表 IPv4 位址、AAAA 代表 IPv6 位址、CNAME 代表別名（Canonical Name）、MX 代表郵件交換伺服器（Mail Exchange）",
         ["A 代表 IPv4 位址、AAAA 代表 IPv6 位址、CNAME 代表別名（Canonical Name）、MX 代表郵件交換伺服器（Mail Exchange）",
          "A 代表管理員姓名、AAAA 代表密碼、CNAME 代表電腦編號、MX 代表音樂檔案",
          "A 代表文字、AAAA 代表圖片、CNAME 代表影片、MX 代表軟體",
          "四者皆代表不同種類的網頁網址"],
         "DNS 記錄類型必考清單：<br>‧ A（Address）：主機名稱 -> IPv4 位址。<br>‧ AAAA（Quad-A）：主機名稱 -> IPv6 位址。<br>‧ CNAME（Canonical Name）：別名映射至正規真名（如 `ftp.example.com` CNAME 到 `server1.example.com`）。<br>‧ MX（Mail Exchanger）：指向該網域的收信郵件伺服器（附帶優先級數字，數值越小越優先）。<br>‧ PTR（Pointer）：反向解析（IP -> 主機名稱）。<br>‧ NS（Name Server）：宣告該區域的授權名稱伺服器。<br>‧ SOA（Start of Authority）：宣告區域起始權威參數。"),
        ("動態主機設定協定（<span class=\"en\">DHCP</span>）自動獲取 IP 位址的標準「DORA」四步驟交換流程依序為？",
         "DHCP Discover（客戶端廣播發現） -> DHCP Offer（伺服器回送提供） -> DHCP Request（客戶端廣播請求） -> DHCP Pack / Acknowledge（伺服器回送確認）",
         ["DHCP Discover（客戶端廣播發現） -> DHCP Offer（伺服器回送提供） -> DHCP Request（客戶端廣播請求） -> DHCP Pack / Acknowledge（伺服器回送確認）",
          "DHCP Request -> DHCP Response -> DHCP Start -> DHCP End",
          "DHCP Hello -> DHCP Welcome -> DHCP IP -> DHCP Bye",
          "DHCP Login -> DHCP Auth -> DHCP Grant -> DHCP Confirm"],
         "DORA 四部曲深度剖析：<br>1. Discover: 客戶端無 IP（Src 0.0.0.0, Dst 255.255.255.255, UDP 68->67），大喊「誰有 IP？」。<br>2. Offer: 伺服器預留一個可用 IP，回送 Offer 提供建議 IP、遮罩與租期。<br>3. Request: 客戶端（若收到多個 Offer）挑選第一個，向全網廣播「我決定接受 Server A 的 192.168.1.50」（廣播是為了禮貌通知其他提供 Offer 的伺服器釋放保留）。<br>4. ACK: Server A 正式發出確認，客戶端綁定 IP 開始使用。"),
        ("DHCP 客戶端在租約時間（<span class=\"en\">Lease Time, T</span>）進行到何種時刻時，會主動向發放該租約的原 DHCP 伺服器發起「單播續約（Unicast Renewal）」？",
         "租約時間達到 50%（T1 計時器，即 0.5 × T）時",
         ["租約時間達到 50%（T1 計時器，即 0.5 × T）時",
          "租約時間達到 100% 徹底過期時",
          "租約時間達到 87.5% 時",
          "每隔 10 秒鐘續約一次"],
         "DHCP 續約雙階計時器（RFC 2131）：<br>1. T1（50% 租期，例如 8 天中的第 4 天）：客戶端向原 DHCP 伺服器單播發送 DHCP Request。若原伺服器回送 ACK，租期重置回 100%（續約成功！）。<br>2. T2（87.5% 租期，即 7/8 租期）：若原伺服器當機一直沒回覆，客戶端進入 Rebinding 狀態，向全網廣播 DHCP Request，向「網路上任意一台 DHCP 伺服器」求助續約。<br>3. 若達到 100% 依然無果，立即放棄該 IP 並回到 Discover 狀態。"),
        ("當 DHCP 客戶端與 DHCP 伺服器處於「不同實體子網路（中間隔著第三層路由器）」時，為了讓廣播的 DHCP Discover 能跨越路由器抵達伺服器，路由器介面上必須配置的技術為？",
         "DHCP 中繼代理（DHCP Relay Agent / Cisco 的 `ip helper-address` 指令）",
         ["DHCP 中繼代理（DHCP Relay Agent / Cisco 的 `ip helper-address` 指令）",
          "關閉路由器的防火牆",
          "在路由器兩端拉一條電話線",
          "將路由器設定為透明集線器模式"],
         "DHCP Relay 機制：因為路由器預設嚴格阻斷廣播（255.255.255.255）。配置 `ip helper-address 10.10.10.1` 後，路由器截獲客戶端 UDP 67 廣播，將其封裝為「單播 IP 封包」，來源設為本地介面 IP（以告知伺服器該指派哪個子網的池子），發送給遠端的 DHCP 伺服器；伺服器處理後單播回覆路由器，由路由器在本地以廣播/單播交付給終端客戶端。"),
        ("簡易網路管理協定（<span class=\"en\">SNMP, Simple Network Management Protocol</span>）的架構中，管理站（NMS）主動查詢被管設備，以及被管設備在突發故障時「主動向管理站發送告警」所採用的訊息類型分別為？",
         "主動查詢採用 Get / GetNext 請求（使用 UDP 161 埠）；主動非同步告警採用 Trap 訊息（使用 UDP 162 埠）",
         ["主動查詢採用 Get / GetNext 請求（使用 UDP 161 埠）；主動非同步告警採用 Trap 訊息（使用 UDP 162 埠）",
          "查詢採用 Trap，告警採用 Get",
          "兩者皆使用 TCP 80 埠",
          "SNMP 只能發送電子郵件告警"],
         "SNMP 通訊埠關鍵對比：<br>‧ UDP 161: NMS 向 Agent 發送 GetRequest, SetRequest，Agent 回送 GetResponse。<br>‧ UDP 162: 被管設備（Agent）發生介面斷線（Link Down）、電源故障時，不等管理員輪詢，主動噴射 Trap 或 Inform 訊息給 NMS 監控螢幕觸發即時報警。"),
        ("網路時間協定（<span class=\"en\">NTP, Network Time Protocol</span>）在校準全球電腦時鐘時，底層採用的傳輸協定與連接埠為？其分層時鐘結構稱為？",
         "採用 UDP 協定，連接埠 123；分層結構稱為層級（Stratum，Stratum 0 為原子鐘/GPS，Stratum 1 為直連主時鐘伺服器）",
         ["採用 UDP 協定，連接埠 123；分層結構稱為層級（Stratum，Stratum 0 為原子鐘/GPS，Stratum 1 為直連主時鐘伺服器）",
          "採用 TCP 協定，連接埠 80；分層結構稱為 Level",
          "採用 ICMP 協定；分層結構稱為 Tier",
          "採用 HTTP 協定；分層結構稱為 Layer"],
         "NTP 精準校時（RFC 5905）：Stratum 0 是高精度物理時鐘源（銫原子鐘、GPS 衛星）。Stratum 1 伺服器直連 Stratum 0，Stratum 2 透過網路同步 Stratum 1... 數字越大代表離精確時鐘源越遠。透過四個時間戳（T1, T2, T3, T4）精確消除單向網路延遲，校準精度在區域網達微秒級、網際網路達數毫秒級。"),
        ("動態主機設定協定（DHCP）與開機協定（BOOTP）最本質的演進改進為？",
         "DHCP 支援「動態租約分配（Dynamic Lease Allocation）」，IP 位址具有使用期限，用畢後自動回收至位址池重新循環使用；BOOTP 僅支援靜態固定綁定分配",
         ["DHCP 支援「動態租約分配（Dynamic Lease Allocation）」，IP 位址具有使用期限，用畢後自動回收至位址池重新循環使用；BOOTP 僅支援靜態固定綁定分配",
          "BOOTP 支援光纖，DHCP 只支援雙絞線",
          "DHCP 完全不需要伺服器",
          "BOOTP 可以自動破解 Wi-Fi 密碼"],
         "BOOTP vs DHCP：BOOTP（無碟工作站開機協定）需要管理員手動在伺服器上建立表格，將每個 MAC 靜態死綁定一個固定 IP。若員工離職，IP 仍被死霸佔。DHCP 引入「租約（Lease）」概念，主機關機或拔線離開後，IP 自動釋放回池，徹底解決了行動裝置與筆電在不同會議室移動時 IP 資源枯竭的難題。"),
        ("在 DNS 查詢中，若客戶端向 DNS 伺服器查詢 `www.example.com`，伺服器回覆了一個 CNAME 記錄指向 `lb.example.net`，則接下來客戶端的標準處理為？",
         "客戶端（或遞迴 DNS 伺服器）必須以該別名對應的新網域名稱 `lb.example.net` 重新發起查詢，直到最終解析出真實的 A（IPv4）或 AAAA（IPv6）位址為止",
         ["客戶端（或遞迴 DNS 伺服器）必須以該別名對應的新網域名稱 `lb.example.net` 重新發起查詢，直到最終解析出真實的 A（IPv4）或 AAAA（IPv6）位址為止",
          "立即停止查詢並向使用者顯示錯誤頁面",
          "直接將別名字串當作 IP 位址連線",
          "將該 CNAME 記錄直接丟入回收筒"],
         "CNAME 鏈條解析：CNAME 僅是別名（Alias）。瀏覽器在建立 TCP 連線時，底層 socket 必須要拿到具體的二進位 IP 位址。因此 DNS 解析器會順藤摸瓜，遞歸追查 CNAME 指向的目標主機，CDN（如 Cloudflare, Akamai）廣泛利用 CNAME 鏈將全球用戶透明調度引流至離用戶最近的邊緣節點。"),
        ("SNMPv3 相較於早期 SNMPv1 與 SNMPv2c，在資安防護架構上的最關鍵突破為？",
         "徹底廢棄了傳統以明文傳輸且極易遭竊聽偽造的「社群字串（Community String）」，全面引入基於使用者的安全模型（USM，支援 SHA/HMAC 認證與 AES 密碼加密）",
         ["徹底廢棄了傳統以明文傳輸且極易遭竊聽偽造的「社群字串（Community String）」，全面引入基於使用者的安全模型（USM，支援 SHA/HMAC 認證與 AES 密碼加密）",
          "將通訊速度提升 100 倍",
          "取消了所有網路設備的管理功能",
          "強制所有網路設備使用藍牙通訊"],
         "SNMP 安全演進：SNMPv1/v2c 僅使用明文 Community String（如惡名昭彰的預設密碼 `public` 與 `private`）。任何人在局域網抓包即可直接獲取讀寫權限，甚至能遠端重啟交換機或修改 VLAN。SNMPv3 引入 USM（User-based Security Model）與 VACM（View-based Access Control Model），提供 AuthPriv（認證 + 加密），確保網管監控資料的高度機密性與防篡改。")
    ]

    all_datasets = [
        ("靜態路由配置、距離向量 RIP 與防環機制", rip_data),
        ("鏈路狀態 OSPF、Dijkstra 演算法與邊界 BGP 路由", ospf_bgp_data),
        ("傳輸層 TCP 三向交握、四次揮手與狀態機機制", tcp_state_data),
        ("TCP 壅塞控制演算法、UDP 特性與 DNS/DHCP 服務", cong_udp_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【動態路由協定、傳輸層連線控制與核心應用服務深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 路由演算法推導、TCP 狀態轉移與網路應用協定運作時序</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立網際網路工程任務組（IETF RFC）協定標準與狀態機模型</strong><br>
      ‧ 本題依據動態路由（RIP/OSPF/BGP）、傳輸層（RFC 793/5681）與網路核心服務標準規範嚴格推導。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>狀態機轉移、演算法收斂與資料封包時序深度剖析</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（狀態轉換錯誤或計時器數值混淆）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（演算法運作邏輯顛倒）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非國際標準或不符合網路工程實際設計規範）。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_junior_net_part4_questions()
    print(f"Total Junior Net Part 4 questions generated: {len(qs)}")
