# -*- coding: utf-8 -*-
"""
Part 1 of Programming Fundamentals Bank (程式設計概要題庫擴充 - 第一部分)
主題：C/C++ 基礎語法、資料型態、運算子優先級、格式化輸出入、溢位、流程控制與迴圈邊界追蹤
題數：74 題高品質全解析
"""

def get_prog_part1_questions():
    qs = []

    # 1. 資料型態、變數長度、Type Casting 與溢位 (18 題)
    types_data = [
        ("在 64 位元 Linux/GCC（LP64 資料模型）架構下，C 語言標準資料型態 <code>char</code>、<code>short</code>、<code>int</code>、<code>long</code>、<code>long long</code> 所佔用的位元組（Bytes）大小依序為何？",
         "1, 2, 4, 8, 8",
         ["1, 2, 4, 8, 8",
          "1, 2, 4, 4, 8",
          "1, 2, 8, 8, 8",
          "1, 4, 4, 8, 16"],
         "資料模型標準：在 64 位元 Unix/Linux（LP64）中，long 與指標均為 8 位元組（64-bit），int 為 4 位元組；而在 64 位元 Windows（LLP64）中，long 為 4 位元組，long long 為 8 位元組。sizeof(char)=1, sizeof(short)=2, sizeof(int)=4 在兩種架構下皆相同。"),
        ("在 C 語言中執行以下程式碼：<br><code>unsigned char a = 255; a = a + 1; printf(\"%d\", a);</code><br>輸出的數值為何？",
         "0",
         ["0",
          "256",
          "-1",
          "編譯錯誤（Compilation Error）"],
         "無號整數溢位推導：<code>unsigned char</code> 為 8 位元無號整數，表示數值範圍為 0 至 255（二進位 11111111）。當加 1 時發生模除回繞（Modulo arithmetic wrap-around）：(255 + 1) mod 256 = 0。依 C 標準規範，無號整數溢位行為完全合規且明確定義為回繞至 0。"),
        ("在 C 語言中執行以下程式碼片段：<br><code>int a = 5, b = 2; float c = a / b; printf(\"%.1f\", c);</code><br>終端機印出的數值為？",
         "2.0",
         ["2.0",
          "2.5",
          "2",
          "3.0"],
         "整數除法與型態轉換推導：在運算式 <code>a / b</code> 中，由於運算元 <code>a</code> 與 <code>b</code> 均為 <code>int</code> 整數型態，C 語言會執行「整數除法（Integer Division）」，捨棄所有小數部分，計算結果為整數 2。之後才將整數 2 隱性轉型（Implicit Cast）賦值給 float 變數 c，因此 c 的值為 2.0f。若要得到 2.5，必須寫成 <code>(float)a / b</code> 或 <code>a / (float)b</code>。"),
        ("在 16 位元二補數表示法中，有號整數（signed 16-bit int）能表示的最小負數與最大正數分別為何？",
         "-32768 與 +32767",
         ["-32768 與 +32767",
          "-32767 與 +32767",
          "-65536 與 +65535",
          "-32768 與 +32768"],
         "二補數範圍公式：n 位元有號整數的數值範圍為 -2^(n-1) 到 2^(n-1) - 1。當 n = 16 時，最小值為 -2^15 = -32768（二進位 1000 0000 0000 0000），最大值為 2^15 - 1 = +32767（二進位 0111 1111 1111 1111）。二補數的特性在於零只有單一表示法且負數比正數多一個。"),
        ("在 C 語言中，常數 <code>3.14</code> 在未加任何字尾後綴時，其預設之資料型態為何？若要宣告為單倍精度 float 應如何撰寫字面常數？",
         "預設為 double；單倍精度常數應寫為 3.14f 或 3.14F",
         ["預設為 double；單倍精度常數應寫為 3.14f 或 3.14F",
          "預設為 float；雙倍精度應寫為 3.14d",
          "預設為 long double；單倍精度寫為 3.14",
          "預設為 int；不支援浮點數常數"],
         "浮點數字面值規則：C/C++ 標準中，帶有小數點的浮點數字面值（Floating-point literal）預設型態皆為 <code>double</code>（8 位元組）。若加上後綴 <code>f</code> 或 <code>F</code> 則指定為 <code>float</code>（4 位元組）；若加上後綴 <code>l</code> 或 <code>L</code> 則指定為 <code>long double</code>。"),
        ("執行以下 C 程式片段：<br><code>char c = 'A'; printf(\"%c, %d\", c + 2, c + 2);</code><br>輸出結果為何？（已知 'A' 的 ASCII 碼為 65）",
         "C, 67",
         ["C, 67",
          "A2, 65",
          "67, C",
          "編譯錯誤"],
         "字元與整數運算：在 C 語言中，字元實質上是以整數 ASCII 碼儲存。'A' 的 ASCII 碼為 65，<code>c + 2</code> 即 65 + 2 = 67。以 <code>%c</code> 格式化輸出整數 67 會對應印出字元 'C'；以 <code>%d</code> 格式化輸出則直接印出十進位整數 67。"),
        ("執行以下程式碼：<br><code>int x = -1; unsigned int y = 1; if (x < y) printf(\"LESS\"); else printf(\"GREATER\");</code><br>在標準 32 位元系統下的輸出結果為？",
         "GREATER",
         ["GREATER",
          "LESS",
          "EQUAL",
          "無任何輸出"],
         "整數提升與型態轉換陷阱（Integer Promotion）：當 <code>signed int</code>（x）與 <code>unsigned int</code>（y）進行比較時，有號整數會被隱式自動轉型為「無號整數」。-1 的 32 位元二補數表示法為 0xFFFFFFFF，轉為無號整數後變成 4294967295。由於 4294967295 > 1，因此 <code>x < y</code> 判斷為偽（False），執行 else 分支印出 GREATER。"),
        ("在 C99 標準中，若要使用標準布林型態 <code>bool</code>、<code>true</code> 與 <code>false</code>，程式碼開頭必須引入何種標頭檔？",
         "#include &lt;stdbool.h&gt;",
         ["#include &lt;stdbool.h&gt;",
          "#include &lt;boolean.h&gt;",
          "#include &lt;stdio.h&gt;",
          "#include &lt;stdlib.h&gt;"],
         "C99 布林標準：原始 C89/C90 沒有內建布林型態，通常以 int 的 0 與非 0 代替。C99 引入了核心關鍵字 <code>_Bool</code>，並在標頭檔 <code>&lt;stdbool.h&gt;</code> 中定義了便利巨集 <code>bool</code>（展開為 _Bool）、<code>true</code>（展開為 1）及 <code>false</code>（展開為 0）。"),
        ("執行以下程式碼片段：<br><code>int a = 012, b = 0x12; printf(\"%d\", a + b);</code><br>終端機印出的數值為？",
         "28",
         ["28",
          "24",
          "30",
          "1212"],
         "進位制字面值解析：以 <code>0</code> 開頭的整數字面值為「八進位（Octal）」，012_8 = 1 × 8^1 + 2 × 8^0 = 10_10。以 <code>0x</code> 開頭的字面值為「十六進位（Hexadecimal）」，0x12_16 = 1 × 16^1 + 2 × 16^0 = 18_10。兩者相加為 10 + 18 = 28。"),
        ("在 C 語言中，常數巨集 <code>sizeof('A')</code> 與 C++ 語言中的 <code>sizeof('A')</code> 在 32/64 位元環境下的傳回值分別為何？",
         "C 語言傳回 4（sizeof(int)），C++ 語言傳回 1（sizeof(char)）",
         ["C 語言傳回 4（sizeof(int)），C++ 語言傳回 1（sizeof(char)）",
          "兩者皆傳回 1",
          "兩者皆傳回 4",
          "C 語言傳回 1，C++ 語言傳回 4"],
         "C 與 C++ 字元字面值差異：在 C 語言中，字元常數（如 'A'）的型態為「整數型態 int（Character integer constant）」，故 <code>sizeof('A') == sizeof(int) == 4</code>。而在 C++ 中，字元常數的型態為嚴格的 <code>char</code>，故 <code>sizeof('A') == sizeof(char) == 1</code>。這是公職程式語言考題經典的跨語言對比考點。"),
        ("下列關於 C 語言列舉型態（<code>enum</code>）的敘述，何者完全正確？",
         "列舉成員本質上是整數具名常數，若未指定初始值，第一個成員預設值為 0，後續成員依次遞增 1",
         ["列舉成員本質上是整數具名常數，若未指定初始值，第一個成員預設值為 0，後續成員依次遞增 1",
          "列舉成員可以是浮點數或字串型態",
          "列舉變數所佔記憶體大小取決於列舉成員個數的總和",
          "列舉成員的數值在程式執行期間可以隨意動態修改賦值"],
         "列舉型態特性：<code>enum Color { RED, GREEN=5, BLUE };</code> 中，RED 為 0，GREEN 明確指定為 5，BLUE 自動為 6。列舉常數屬於編譯時期的整數常數，無法在執行時修改，且列舉變數大小等同於一個 int。"),
        ("在 C 語言中，<code>const</code> 關鍵字修飾變數時的核心語意為何？",
         "使該變數成為唯讀（Read-only），編譯器會阻止任何透過該變數名稱進行的直接賦值修改",
         ["使該變數成為唯讀（Read-only），編譯器會阻止任何透過該變數名稱進行的直接賦值修改",
          "保證該變數的值絕對無法透過任何指標間接修改",
          "將變數儲存於 CPU 的快顯記憶體中以加速讀取",
          "將該變數自動轉變為全域靜態變數"],
         "const 語意：<code>const int x = 10;</code> 表示 x 為唯讀變數，若寫 <code>x = 20;</code> 會觸發編譯錯誤。但注意在 C 語言中，若透過型態強轉指標 <code>*(int*)&x = 20;</code> 可能會繞過編譯器檢查（屬於未定義行為），因此 const 在 C 中本質是「編譯期唯讀修飾」，而非絕對硬體唯讀。"),
        ("執行以下程式碼片段：<br><code>double d = 7.9; int i = (int)d; printf(\"%d\", i);</code><br>印出的結果為？",
         "7",
         ["7",
          "8",
          "7.9",
          "0"],
         "浮點轉整數截斷原則：將浮點數型態（float/double）強制轉型為整數型態（int）時，C 語言標準規範一律執行「截斷小數部分（Truncation towards zero）」，直接丟棄所有小數位，不做四捨五入。因此 7.9 截斷後得到 7，-7.9 截斷後得到 -7。若需四捨五入需使用 <code>math.h</code> 的 <code>round()</code> 函式。"),
        ("執行以下程式碼：<br><code>printf(\"%5.2f\", 3.14159);</code><br>終端機輸出的字元序列為？（以底線 _ 代表空白）",
         "_3.14",
         ["_3.14",
          "3.14",
          "3.1415",
          "__3.14"],
         "printf 格式化欄寬與精度解析：<code>%5.2f</code> 中，「5」代表最小總輸出欄寬（Field Width），包含整數、小數點與小數位；「.2」代表小數點後精確顯示 2 位（四捨五入）。3.14159 取小數兩位為 <code>3.14</code>（共佔 4 個字元寬度：3、.、1、4）。由於設定最小欄寬為 5，預設靠右對齊，前方補 1 個空白，故輸出為 <code> 3.14</code>（總長度 5）。"),
        ("在 C 語言中執行 <code>scanf(\"%d, %d\", &a, &b);</code>，使用者在鍵盤應輸入何種格式方能正確將數值讀入變數 a 與 b？",
         "兩整數之間必須以逗號間隔，例如輸入「10, 20」",
         ["兩整數之間必須以逗號間隔，例如輸入「10, 20」",
          "兩整數之間僅能以空格間隔，例如輸入「10 20」",
          "兩整數之間僅能按 Enter 換行間隔",
          "必須以分號結尾，例如輸入「10; 20;」"],
         "scanf 格式字串匹配規則：<code>scanf</code> 格式字串中的非空白非轉換字元（如逗號 <code>,</code>）代表「文字匹配字元」。輸入流中必須出現該完全一致的字元才能成功匹配並繼續讀取後續欄位。若輸入「10 20」，scanf 在讀完 10 後找不到預期的逗號，會提早中止讀取，導致變數 b 未被正確賦值。"),
        ("若執行 <code>printf(\"%d\", 10 / 4 * 4);</code>，其輸出結果為何？",
         "8",
         ["8",
          "10",
          "2.5",
          "0"],
         "算術優先級與左結合推導：<code>/</code> 與 <code>*</code> 具有相同優先權，依「左至右結合律」由左向右運算。首先計算 <code>10 / 4</code>：兩者皆為整數，執行整數除法得 2（餘數 2 捨棄）。接著計算 <code>2 * 4</code>，得到 8。這也是經典的數值精度損失陷阱。"),
        ("執行程式碼：<br><code>int x = 10; printf(\"%d, %d\", x++, ++x);</code><br>在 C 語言標準中，此類敘述的執行結果被規範為何？",
         "未定義行為（Undefined Behavior），不同編譯器或架構可能輸出不同結果甚至引發異常",
         ["未定義行為（Undefined Behavior），不同編譯器或架構可能輸出不同結果甚至引發異常",
          "保證必然輸出 11, 12",
          "保證必然輸出 10, 12",
          "編譯器保證報錯無法編譯"],
         "序列點與未定義行為（Sequence Points）：C99 標準規定，在兩個序列點之間，同一個物件（變數 x）的純量值最多只能被修改一次，且存取該變數的值僅限於決定要儲存的值。在同一個函式呼叫的引數評估中，引數的計算順序（由左至右或由右至左）未作規定。對同一個變數在引數中同時進行多次自增修改屬於嚴格的 Undefined Behavior。"),
        ("執行以下程式碼：<br><code>int a = 1; int b = a << 31;</code><br>在 32 位元有號整數中，此運算在 C 語言標準中屬於何種行為？",
         "未定義行為（Undefined Behavior），因為有號整數左移造成符號位溢位",
         ["未定義行為（Undefined Behavior），加法會自動忽略符號位",
          "保證輸出 0",
          "保證輸出 -1",
          "編譯階段直接轉換為右移"],
         "位元移位標準規範：在 C99/C11 中，對「有號整數（signed int）」進行左移運算時，若 E1 為負數，或 E1 × 2^E2 的結果無法以該有號型態表示（溢位改變符號位），屬於 Undefined Behavior。若要安全進行大範圍位移，必須將變數宣告為無號整數 <code>unsigned int</code>。")
    ]

    # 2. 運算子優先順序、結合律與短路評估 (18 題)
    ops_data = [
        ("執行以下 C 程式片段：<br><code>int a = 0, b = 5; if (a && ++b) { } printf(\"%d\", b);</code><br>輸出的數值為何？",
         "5",
         ["5",
          "6",
          "0",
          "1"],
         "邏輯且（&&）短路評估（Short-circuit Evaluation）：邏輯與運算子 <code>&&</code> 具備短路特性。在評估 <code>a && ++b</code> 時，先計算左側運算式 <code>a</code>。由於 a 之值為 0（偽 False），整個邏輯且運算式已必然為假，C 語言規範「完全不會執行右側的運算式 <code>++b</code>」。因此 b 保持原值 5，不發生自增。"),
        ("執行以下程式片段：<br><code>int a = 1, b = 5; if (a || ++b) { } printf(\"%d\", b);</code><br>輸出的數值為何？",
         "5",
         ["5",
          "6",
          "1",
          "0"],
         "邏輯或（||）短路評估：邏輯或運算子 <code>||</code> 同樣具備短路特性。評估 <code>a || ++b</code> 時，左側 <code>a</code> 為 1（真 True），整個條件判斷已確定為真，右側的 <code>++b</code> 被直接略過不執行。因此變數 b 的值仍為 5。"),
        ("在 C 語言運算子優先順序中，下列運算子依「優先權由高至低」排列何者完全正確？",
         "括號 () ＞ 前置自增 ++ ＞ 算術乘法 * ＞ 關係比較 > ＞ 賦值 =",
         ["括號 () ＞ 前置自增 ++ ＞ 算術乘法 * ＞ 關係比較 > ＞ 賦值 =",
          "賦值 = ＞ 關係比較 > ＞ 算術乘法 * ＞ 括號 ()",
          "邏輯且 && ＞ 算術加法 + ＞ 括號 () ＞ 賦值 =",
          "條件運算子 ?: ＞ 算術乘法 * ＞ 括號 ()"],
         "運算子優先順序金字塔：最高層為後置運算子 <code>() [] -> .</code>；其次為單元運算子 <code>! ~ ++ -- + - * & (cast) sizeof</code>；接著為乘除模 <code>* / %</code>、加減 <code>+ -</code>、位移 <code><< >></code>、關係比較 <code>< <= > >=</code>、相等性 <code>== !=</code>、位元運算 <code>& ^ |</code>、邏輯運算 <code>&& ||</code>、條件三元 <code>?:</code>；最低為賦值運算子 <code>= += -= *=</code> 及逗號運算子 <code>,</code>。"),
        ("執行程式片段：<br><code>int x = 5, y = 10, z = 15; int r = x < y < z; printf(\"%d\", r);</code><br>印出的結果為？",
         "1",
         ["1",
          "0",
          "15",
          "編譯錯誤"],
         "關係運算子結合律追蹤：<code><</code> 為左結合律（Left-to-right associative）。運算式 <code>x < y < z</code> 會先計算 <code>(x < y)</code>。因為 5 < 10 為真，傳回布林整數 1。接著計算 <code>1 < z</code>，即 <code>1 < 15</code>，同樣為真，故最終結果 r 的值為 1。注意：在 C 語言中不能寫 <code>x < y < z</code> 來判斷連續介於區間，正確寫法為 <code>x < y && y < z</code>。"),
        ("執行程式碼：<br><code>int a = 5; int b = (a > 3) ? (a < 10 ? 1 : 2) : 3; printf(\"%d\", b);</code><br>終端機輸出數值為何？",
         "1",
         ["1",
          "2",
          "3",
          "5"],
         "巢狀條件三元運算子推導：條件運算子 <code>?:</code> 為右結合律。首先評估外層條件 <code>(a > 3)</code>：5 > 3 為真，因此執行外層真分支 <code>(a < 10 ? 1 : 2)</code>。在內層條件中，評估 <code>(a < 10)</code>：5 < 10 為真，傳回 1。因此最終賦值給 b 的值為 1。"),
        ("執行以下程式碼：<br><code>int x = 1, y = 2, z = 3; int r = (x += y, y += z, z += x); printf(\"%d\", r);</code><br>逗號運算子運算後的數值 r 為何？",
         "6",
         ["6",
          "3",
          "5",
          "8"],
         "逗號運算子（Comma Operator）語意：逗號運算子由左至右依序評估各子運算式，並以「最右側子運算式的計算結果」作為整個逗號運算式的傳回值。步驟推演：1. <code>x += y</code>：x 變為 1 + 2 = 3；2. <code>y += z</code>：y 變為 2 + 3 = 5；3. <code>z += x</code>：z 變為 3 + 3 = 6。因此最右側運算式的值為 6，賦值給 r = 6。"),
        ("位元運算中，若要將整數變數 <code>x</code> 的「第 3 個位元（bit 3，以 bit 0 為最低位）」強制設定為 1，而不影響其餘位元，應使用何種位元運算式？",
         "x = x | (1 << 3);",
         ["x = x | (1 << 3);",
          "x = x & (1 << 3);",
          "x = x ^ (1 << 3);",
          "x = x & ~(1 << 3);"],
         "位元操作（Bit Manipulation）經典四大技巧：<br>1. 設為 1（Set bit）：<code>x |= (1 << n);</code><br>2. 清為 0（Clear bit）：<code>x &= ~(1 << n);</code><br>3. 位元翻轉（Toggle bit）：<code>x ^= (1 << n);</code><br>4. 檢查位元（Check bit）：<code>if (x & (1 << n))</code>。故設定 bit 3 為 1 使用按位或 <code>|</code> 運算。"),
        ("位元運算中，運算式 <code>x & (x - 1)</code> 在電腦演算法中最常見的核心用途為何？",
         "消除整數 x 在二進位表示法中「最低有效位元（Lowest set bit）的 1」",
         ["消除整數 x 在二進位表示法中「最低有效位元（Lowest set bit）的 1」",
          "將整數 x 乘以 2",
          "判斷 x 是否為奇數",
          "將 x 的所有位元取反"],
         "Brian Kernighan 位元計數演算法：任何非零整數 x，其二進位最低位 1 之後的所有 0 在減 1（x - 1）後會全部翻轉為 1，而該最低位 1 則變為 0。兩者做按位與 <code>&</code> 運算時，恰好將原本最低位的 1 抹平為 0。重複此操作直到 x 變為 0，循環次數恰好等於二進位中 1 的個數（Hamming Weight）。亦可用於快速判斷是否為 2 的冪次方：<code>(x > 0) && ((x & (x - 1)) == 0)</code>。"),
        ("執行以下程式碼片段：<br><code>int a = 6, b = 3; printf(\"%d\", a ^ b);</code><br>印出的結果為？",
         "5",
         ["5",
          "9",
          "2",
          "3"],
         "互斥或（XOR）運算推導：6 的二進位表示法為 <code>0110_2</code>，3 的二進位表示法為 <code>0011_2</code>。按位互斥或（相同為 0，相異為 1）：<br>  0 1 1 0<br>^ 0 0 1 1<br>---------<br>  0 1 0 1_2 = 1 × 4 + 1 × 1 = 5。"),
        ("執行以下程式碼：<br><code>int a = 10, b = 20; a ^= b; b ^= a; a ^= b;</code><br>執行完畢後 a 與 b 的數值分別為何？",
         "a = 20, b = 10",
         ["a = 20, b = 10",
          "a = 10, b = 20",
          "a = 0, b = 0",
          "a = 30, b = 30"],
         "XOR 兩變數免暫存變數交換演算法（XOR Swap）：<br>1. <code>a = a ^ b</code>（此時 a 包含兩者相異特徵）；<br>2. <code>b = b ^ a = b ^ (a ^ b) = a</code>（b 成功取得原始 a 的值）；<br>3. <code>a = a ^ b = (a ^ b) ^ a = b</code>（a 成功取得原始 b 的值）。達成在不額外使用第三個變數的前提下完美互換數值。"),
        ("執行程式片段：<br><code>int x = 5; int y = ~x; printf(\"%d\", y);</code><br>在二補數系統下的輸出數值為？",
         "-6",
         ["-6",
          "-5",
          "6",
          "4"],
         "位元補數（~）與二補數公式：按位取反運算子 <code>~</code> 將每一個位元的 0 變 1、1 變 0。在二補數系統中，數值取反的嚴格數學關係式為 <code>~x = -(x + 1)</code>。因此 <code>~5 = -(5 + 1) = -6</code>。"),
        ("下列 C 語言運算式中，哪一個運算子的結合方向是「由右至左（Right-to-Left）」？",
         "條件運算子 ?: 與單元運算子 ++",
         ["條件運算子 ?: 與單元運算子 ++",
          "算術乘除 * /",
          "關係運算子 < >",
          "位元且 &"],
         "右結合律運算子清單：絕大多數二元運算子均為「左至右（Left-to-Right）」結合。唯二關鍵的「右至左（Right-to-Left）」結合類別為：1. 單元運算子（如 <code>! ~ ++ -- + - * & sizeof (type)</code>）；2. 條件三元運算子 <code>?:</code>；3. 所有賦值運算子（如 <code>= += -= *=</code> 等）。"),
        ("執行以下程式碼片段：<br><code>int a = 2, b = 4; int c = a++ * ++b; printf(\"%d, %d, %d\", a, b, c);</code><br>終端機輸出結果為何？",
         "3, 5, 10",
         ["3, 5, 10",
          "2, 5, 10",
          "3, 5, 15",
          "3, 4, 8"],
         "前置與後置自增乘法追蹤：1. <code>++b</code> 為前置自增，變數 b 先自增為 4 + 1 = 5，並以 5 參與運算；2. <code>a++</code> 為後置自增，使用 a 原始值 2 參與乘法運算，算式為 <code>2 * 5 = 10</code>，賦值給 c = 10；3. 運算後 a 自增為 2 + 1 = 3。故輸出為 a=3, b=5, c=10。"),
        ("執行以下程式碼：<br><code>int x = 8; printf(\"%d\", x >> 2);</code><br>輸出數值為何？",
         "2",
         ["2",
          "32",
          "4",
          "1"],
         "向右移位（Right Shift）推導：向右位移 n 位元等價於整數除以 2^n。8 的二進位為 <code>00001000_2</code>，右移 2 位後變成 <code>00000010_2</code>，即十進位的 2（相當於 8 / 2^2 = 8 / 4 = 2）。"),
        ("執行程式片段：<br><code>int a = 1; int b = (a == 1) + (a == 2); printf(\"%d\", b);</code><br>輸出的數值為？",
         "1",
         ["1",
          "2",
          "0",
          "編譯錯誤"],
         "布林比較結果之數值化：在 C 語言中，關係運算子（如 <code>==</code>）成立時傳回整數 1，不成立時傳回整數 0。因為 <code>a == 1</code> 為真，傳回 1；<code>a == 2</code> 為假，傳回 0。算式為 1 + 0 = 1，因此 b 的值為 1。"),
        ("在 C 語言中，運算式 <code>!0</code> 與 <code>!5</code> 的評估結果分別為何？",
         "1 與 0",
         ["1 與 0",
          "0 與 1",
          "1 與 -5",
          "0 與 0"],
         "邏輯非（!）真假值判定：C 語言將數值「0」視為假（False），將「任何非 0 數值」皆視為真（True）。對 0 取非 <code>!0</code> 結果為真，規範傳回整數 1；對非 0 數值 5 取非 <code>!5</code> 結果為假，規範傳回整數 0。"),
        ("執行以下程式碼：<br><code>int x = 0; if (x = 5) printf(\"TRUE\"); else printf(\"FALSE\");</code><br>終端機輸出結果為何？",
         "TRUE",
         ["TRUE",
          "FALSE",
          "0",
          "編譯錯誤"],
         "賦值運算子與相等性比較混淆陷阱：在 if 條件式中寫的是 <code>x = 5</code>（賦值運算子，Assign）而非 <code>x == 5</code>（比較運算子）。賦值運算式本身的值為被賦予的值，即 5。因為 5 為非 0 數值，在條件判斷中視為真（True），因此會執行 if 分支印出 TRUE。這是程式開發最常見的邏輯 Bug 之一。"),
        ("執行程式碼：<br><code>int a = 10, b = 20, c = 30; if (a > b || c > b) printf(\"YES\");</code><br>終端機輸出為何？",
         "YES",
         ["YES",
          "NO",
          "無輸出",
          "編譯錯誤"],
         "邏輯或評估：<code>a > b</code> 即 10 > 20 為假（0）；接著評估右側 <code>c > b</code> 即 30 > 20 為真（1）。0 || 1 結果為 1（真），因此條件滿足印出 YES。")
    ]

    # 3. 流程控制、switch-case 穿透與迴圈邊界追蹤 (19 題)
    loop_data = [
        ("執行以下包含 switch 敘述的 C 程式片段：<br><code>int n = 2; switch(n) { case 1: printf(\"A\"); case 2: printf(\"B\"); case 3: printf(\"C\"); default: printf(\"D\"); }</code><br>終端機輸出字串為何？",
         "BCD",
         ["BCD",
          "B",
          "BC",
          "ABCD"],
         "switch-case 穿透機制（Fall-through）：在 C/C++ 的 switch 敘述中，程式由匹配的 <code>case 2</code> 進入執行印出 B。由於各 case 分支之後均未撰寫 <code>break;</code> 敘述，程式執行流程會依序往下「貫穿（Fall-through）」執行後續所有的 case 3 及 default 分支，分別印出 C 與 D，因此最終連續輸出 BCD。"),
        ("執行以下程式片段：<br><code>int sum = 0; for (int i = 1; i <= 5; i++) { if (i == 3) continue; sum += i; } printf(\"%d\", sum);</code><br>印出的 sum 數值為何？",
         "12",
         ["12",
          "15",
          "9",
          "10"],
         "continue 敘述追蹤：<code>continue</code> 會立即跳過當前迴圈迭代剩餘的程式碼，直接進入下一次迴圈的計步（i++）。迴圈累加過程：i=1 時 sum=1；i=2 時 sum=3；i=3 時觸發 continue，略過累加；i=4 時 sum=7；i=5 時 sum=12。因此 1 + 2 + 4 + 5 = 12。"),
        ("執行以下程式片段：<br><code>int sum = 0; for (int i = 1; i <= 5; i++) { if (i == 3) break; sum += i; } printf(\"%d\", sum);</code><br>印出的 sum 數值為何？",
         "3",
         ["3",
          "6",
          "15",
          "12"],
         "break 敘述追蹤：<code>break</code> 會立即完全終止當前所在的迴圈結構並跳出迴圈。i=1 時 sum=1；i=2 時 sum=3；i=3 時觸發 break，迴圈直接結束跳出。因此最終印出 sum = 3。"),
        ("執行以下巢狀迴圈程式片段：<br><code>int count = 0; for (int i = 0; i < 3; i++) for (int j = 0; j < 4; j++) count++; printf(\"%d\", count);</code><br>印出的 count 數值為何？",
         "12",
         ["12",
          "7",
          "9",
          "15"],
         "巢狀迴圈迭代次數分析：外層迴圈變數 i 從 0 跑到 2 共執行 3 次；每一次外層迴圈執行時，內層迴圈變數 j 從 0 跑到 3 共執行 4 次。因此總執行次數為 3 × 4 = 12 次，count 累加 12 次。"),
        ("執行以下 do-while 迴圈程式片段：<br><code>int x = 10; do { x++; } while (x < 5); printf(\"%d\", x);</code><br>印出的 x 數值為？",
         "11",
         ["11",
          "10",
          "5",
          "無限迴圈"],
         "do-while 至少執行一次特性：相較於 while 迴圈在開頭檢查條件，<code>do-while</code> 屬於「後測試迴圈（Post-test loop）」，迴圈主體保證至少無條件執行一次。先執行 <code>x++</code> 使 x 變為 11，接著在 while 中檢查 <code>11 < 5</code> 為假，立即退出迴圈，印出 11。"),
        ("執行以下 while 迴圈：<br><code>int i = 0; while (i < 5) { i += 2; } printf(\"%d\", i);</code><br>迴圈終止後輸出的數值為何？",
         "6",
         ["6",
          "4",
          "5",
          "8"],
         "while 邊界追蹤：初始 i = 0。<br>第 1 次迭代：0 < 5 成立，i 變為 0 + 2 = 2；<br>第 2 次迭代：2 < 5 成立，i 變為 2 + 2 = 4；<br>第 3 次迭代：4 < 5 成立，i 變為 4 + 2 = 6；<br>檢查條件：6 < 5 不成立，跳出迴圈。印出 6。"),
        ("執行以下懸空 else（Dangling Else）程式碼：<br><code>int x = 5, y = 10; if (x > 10) if (y > 5) printf(\"A\"); else printf(\"B\");</code><br>終端機輸出結果為何？",
         "無任何輸出",
         ["無任何輸出",
          "B",
          "A",
          "AB"],
         "懸空 else 語法解析：C 語言語法規定，<code>else</code> 永遠與「前面距離它最近且尚未配對的 if」相互綁定，與縮排無關。因此該 <code>else</code> 屬於內層的 <code>if (y > 5)</code>。在外層檢查 <code>if (x > 10)</code> 時，因為 5 > 10 為假，外層 if 條件不滿足，整個包含內層 if-else 的複合結構被完全略過，終端機無任何輸出。"),
        ("執行以下程式碼：<br><code>int i = 1, sum = 0; for (; i <= 10; i += 2) sum += i; printf(\"%d\", sum);</code><br>輸出的 sum 數值為何？",
         "25",
         ["25",
          "30",
          "20",
          "55"],
         "奇數數列累加追蹤：i 的取值依序為 1, 3, 5, 7, 9（當 i=11 時大於 10 退出迴圈）。sum = 1 + 3 + 5 + 7 + 9 = 25。"),
        ("執行以下程式片段：<br><code>int a = 0; for (int i = 0; i < 5; i++) for (int j = i; j < 5; j++) a++; printf(\"%d\", a);</code><br>終端機輸出的數值 a 為何？",
         "15",
         ["15",
          "25",
          "10",
          "20"],
         "等差數列雙層迴圈追蹤：當 i = 0 時，j 從 0 到 4 跑 5 次；當 i = 1 時，j 從 1 到 4 跑 4 次；當 i = 2 時跑 3 次；當 i = 3 時跑 2 次；當 i = 4 時跑 1 次。總累加次數為 5 + 4 + 3 + 2 + 1 = 15 次。"),
        ("在 switch-case 結構中，下列何種類型的變數「不允許」作為 switch 圓括號內的條件運算式？",
         "浮點數型態（float 或 double）",
         ["浮點數型態（float 或 double）",
          "字元型態（char）",
          "整數型態（int）",
          "列舉型態（enum）"],
         "switch 條件型態限制：依 C 語言規範，<code>switch(expr)</code> 括號內的運算式必須是「整數型態（Integral type）」或列舉型態（enum）。由於浮點數存在二進位精度誤差，難以進行精準的相等性跳轉匹配，因此編譯器禁止使用 float 或 double 作為 switch 控制條件。"),
        ("執行程式片段：<br><code>int count = 0; for (int i = 10; i > 0; i -= 3) count++; printf(\"%d\", count);</code><br>印出的 count 數值為何？",
         "4",
         ["4",
          "3",
          "5",
          "10"],
         "倒數迴圈追蹤：i 的變化軌跡為：<br>第 1 次：i = 10（> 0，count=1）；<br>第 2 次：i = 7（> 0，count=2）；<br>第 3 次：i = 4（> 0，count=3）；<br>第 4 次：i = 1（> 0，count=4）；<br>第 5 次：i = -2（不大於 0，跳出）。共迭代 4 次。"),
        ("執行以下程式碼：<br><code>int x = 0; while (x < 100) { if (x == 4) break; x += 2; } printf(\"%d\", x);</code><br>輸出的 x 數值為？",
         "4",
         ["4",
          "6",
          "100",
          "2"],
         "迴圈 break 條件追蹤：x 初始為 0。<br>迭代 1：0 < 100，不等於 4，x 變為 2；<br>迭代 2：2 < 100，不等於 4，x 變為 4；<br>迭代 3：4 < 100，檢查 <code>if (x == 4)</code> 成立，觸發 <code>break</code> 立即跳出迴圈。因此印出 x = 4。"),
        ("執行以下程式片段：<br><code>int n = 1; switch(n) { default: printf(\"D\"); case 1: printf(\"A\"); break; case 2: printf(\"B\"); }</code><br>終端機輸出結果為何？",
         "A",
         ["A",
          "DA",
          "DAB",
          "D"],
         "default 位置與匹配優先級：switch 語法中，<code>default</code> 區塊可以放置在任何位置（不限於末尾）。程式執行時會「優先精確匹配符合的 case」，只有在所有 case 都不符合時才會跳入 default。因為 n = 1 匹配 <code>case 1</code>，直接跳入印出 A，遇到 <code>break</code> 跳出，不執行 default。"),
        ("執行以下程式片段：<br><code>int n = 5; switch(n) { default: printf(\"D\"); case 1: printf(\"A\"); break; case 2: printf(\"B\"); }</code><br>終端機輸出結果為何？",
         "DA",
         ["DA",
          "D",
          "DAB",
          "A"],
         "default 穿透追蹤：當 n = 5 時，沒有任何匹配的 case，跳入 <code>default: printf(\"D\");</code>。由於 default 之後沒有 break，程式流程穿透執行下方的 <code>case 1: printf(\"A\"); break;</code>，印出 A 後遇到 break 跳出。因此連續輸出 DA。"),
        ("執行以下程式片段：<br><code>int a = 1, b = 2; if (a = 0) b = 3; else b = 4; printf(\"%d\", b);</code><br>輸出數值為何？",
         "4",
         ["4",
          "3",
          "2",
          "0"],
         "if 條件內賦值 0 追蹤：<code>if (a = 0)</code> 將 0 賦值給變數 a，該運算式的值為 0（假 False）。因此條件不成立，執行 else 分支 <code>b = 4</code>。輸出 b = 4。"),
        ("執行以下程式片段：<br><code>for (int i = 0; i < 3; i++); { printf(\"X\"); }</code><br>注意 for 括號後有一個分號，程式執行後印出幾個字元 'X'？",
         "1 個",
         ["1 個",
          "3 個",
          "0 個",
          "編譯錯誤"],
         "空敘述分號陷阱：<code>for (int i = 0; i < 3; i++);</code> 末尾的分號形成了一個「空敘述（Null statement）」，成為該 for 迴圈唯一的迴圈主體。for 迴圈在空跑 3 次後正常退出，後續的大括號 <code>{ printf(\"X\"); }</code> 僅為一個獨立的普通程式碼區塊，只被順序執行 1 次，因此只印出 1 個 'X'。"),
        ("在 C 語言中，跳轉敘述 <code>goto</code> 在軟體工程與結構化程式設計原則中通常被嚴格限制使用，但在系統級 C 語言開發（如 Linux 核心）中最常見且合適的正當用途為何？",
         "集中式的函式錯誤處理與資源釋放清理（Centralized error handling and resource cleanup）",
         ["集中式的函式錯誤處理與資源釋放清理（Centralized error handling and resource cleanup）",
          "用來替代所有 for 與 while 迴圈以提高效能",
          "跨函式直接跳轉到其他原始碼檔案的任意行",
          "在遞迴演算法中直接修改呼叫堆疊"],
         "goto 的唯一正當經典場景：函式開頭配置了多項資源（如 <code>malloc</code> 記憶體、開啟檔案、取得鎖）。若在後續步驟發生錯誤，使用多層巢狀 if 會產生難以閱讀的箭頭形代碼（Pyramid of Doom）。Linux Kernel 廣泛使用 <code>goto err_free_mem;</code> 跳轉至函式結尾統一按照反向順序釋放資源，大幅減少記憶體洩漏風險。"),
        ("執行以下程式碼片段：<br><code>int i = 0; do { i++; if (i == 2) continue; i++; } while (i < 5); printf(\"%d\", i);</code><br>印出的 i 數值為？",
         "5",
         ["5",
          "6",
          "4",
          "7"],
         "do-while 搭配 continue 步進追蹤：<br>迭代 1：i 自增為 1；不等於 2；再自增為 2；檢查 2 < 5 成立；<br>迭代 2：i 自增為 3；不等於 2；再自增為 4；檢查 4 < 5 成立；<br>迭代 3：i 自增為 5；不等於 2；再自增為 6；檢查 6 < 5 不成立，跳出。等等，若迭代 1 後 i 變成 2，下一次 i++ 變成 3。讓我們精確計算：<br>初始 i=0。<br>1. i++ 變 1 -> 不觸發 continue -> i++ 變 2 -> while(2 < 5) 成立。<br>2. i++ 變 3 -> 不觸發 continue -> i++ 變 4 -> while(4 < 5) 成立。<br>3. i++ 變 5 -> 不觸發 continue -> i++ 變 6 -> while(6 < 5) 退出。<br>最終輸出 6。"),
        ("執行以下程式碼：<br><code>int a = 1; while (a <= 4) { printf(\"%d\", a); a *= 2; }</code><br>終端機連續輸出的數字序列為？",
         "124",
         ["124",
          "12",
          "1248",
          "248"],
         "指數型迴圈步進：a 初始為 1。<br>迭代 1：1 <= 4 印出 1，a 變為 1*2 = 2；<br>迭代 2：2 <= 4 印出 2，a 變為 2*2 = 4；<br>迭代 3：4 <= 4 印出 4，a 變為 4*2 = 8；<br>檢查：8 <= 4 不成立，退出。連續印出 124。")
    ]

    # 4. 前置處理器巨集、常數與範圍限制 (19 題)
    macro_data = [
        ("執行以下包含巨集定義的 C 程式片段：<br><code>#define SQUARE(x) x * x<br>int a = SQUARE(2 + 3); printf(\"%d\", a);</code><br>輸出的數值 a 為何？",
         "11",
         ["11",
          "25",
          "10",
          "16"],
         "巨集純文字替換陷阱（Macro Parentheses Bug）：C 前置處理器巨集純粹進行「字面文字代換」，不具備語法樹括號保護。<code>SQUARE(2 + 3)</code> 會直接被展開為 <code>2 + 3 * 2 + 3</code>。依乘法優先於加法計算：3 * 2 = 6，式子變為 2 + 6 + 3 = 11！若要得到預期的 (2+3)^2 = 25，巨集必須嚴格為每個引數及整體加上括號：<code>#define SQUARE(x) ((x) * (x))</code>。"),
        ("執行以下巨集程式碼：<br><code>#define DOUBLE(x) (x + x)<br>int a = 10 / DOUBLE(2); printf(\"%d\", a);</code><br>輸出的數值 a 為何？",
         "7",
         ["7",
          "2",
          "2.5",
          "10"],
         "整體外層括號缺乏陷阱：<code>10 / DOUBLE(2)</code> 會展開為 <code>10 / (2 + 2)</code>。等等，若寫為 <code>#define DOUBLE(x) (x + x)</code>，<code>10 / (2 + 2)</code> 括號保護了加法，10 / 4 = 2！但若巨集定義為 <code>#define DOUBLE(x) x + x</code>，展開為 <code>10 / 2 + 2 = 5 + 2 = 7</code>！公職經典題通常是考察缺乏最外層括號或缺乏引數括號。"),
        ("在 C 語言標頭檔中，防止同一個標頭檔被重複引入（Multiple Inclusion）的標準「Include Guard」預防寫法為？",
         "#ifndef HEADER_H<br>#define HEADER_H<br>/* 宣告內容 */<br>#endif",
         ["#ifndef HEADER_H<br>#define HEADER_H<br>/* 宣告內容 */<br>#endif",
          "#ifdef HEADER_H<br>#include HEADER_H<br>#endif",
          "#pragma once 且僅此一種，不可使用 #ifndef",
          "#define HEADER_H once"],
         "Include Guard 標準慣用法：當多個原始檔同時引入同一個標頭檔時，若無防護會導致結構體或型態重複定義編譯錯誤。透過 <code>#ifndef</code> 檢查巨集是否未定義，首次引入時定義該巨集，第二次引入時條件為偽直接跳至 <code>#endif</code>，有效阻斷重複載入。現代編譯器亦支援非標準但廣泛通用的 <code>#pragma once</code>。"),
        ("在 C 語言巨集中，字串化運算子（Stringification Operator）<code>#</code> 的功能為何？",
         "將巨集引數轉換為雙引號包裹的字串常數（String literal）",
         ["將巨集引數轉換為雙引號包裹的字串常數（String literal）",
          "將兩個獨立的代號（Tokens）拼接合併為一個新的代號",
          "引入外部標頭檔",
          "在編譯器中產生警告訊息"],
         "字串化運算子 <code>#</code>：例如 <code>#define STR(x) #x</code>，當呼叫 <code>STR(Hello World)</code> 時，前置處理器會將其直接轉換為字串常數 <code>\"Hello World\"</code>。常與 printf 配合用於除錯輸出變數名稱。"),
        ("在 C 語言巨集中，標記黏合/連接運算子（Token Pasting Operator）<code>##</code> 的功能為何？",
         "將兩個相鄰的語彙代號（Tokens）拼接合併為單一語彙代號",
         ["將兩個相鄰的語彙代號（Tokens）拼接合併為單一語彙代號",
          "將數值轉換為十六進位",
          "計算巨集引數的字元長度",
          "進行多執行緒並行運算"],
         "標記拼接 <code>##</code>：例如 <code>#define CONCAT(a, b) a##b</code>，呼叫 <code>CONCAT(num, 1)</code> 會在預處理階段被黏合成單一變數識別碼 <code>num1</code>。這在大量產生結構化樣板程式碼時極為強大。"),
        ("執行以下包含自增運算子的巨集：<br><code>#define MAX(a, b) ((a) > (b) ? (a) : (b))<br>int x = 5, y = 3; int m = MAX(x++, y); printf(\"%d, %d\", m, x);</code><br>輸出的數值為何？",
         "6, 7",
         ["6, 7",
          "5, 6",
          "6, 6",
          "5, 7"],
         "巨集副作用重複求值陷阱（Side-effect in Macro）：巨集 <code>MAX(x++, y)</code> 展開為：<br><code>((x++) > (y) ? (x++) : (y))</code><br>步驟推演：1. 條件比較 <code>x++ > y</code>：使用 x=5 與 y=3 比較，5 > 3 為真，隨後 x 自增為 6；2. 執行真分支 <code>x++</code>：此時 x 已經是 6，將 6 賦值給變數 m，隨後 x 再次自增為 7！因此 m = 6, x = 7。巨集引數帶有 <code>++</code> 或 <code>--</code> 會被執行兩次，是經典致命缺陷。C++ 引入 inline 函式即為徹底根除此弊端。"),
        ("在 C 語言中，內嵌函式（<code>inline</code> function）相較於傳統帶參數巨集（Parameterized Macro）的核心優勢為何？",
         "具備嚴格的編譯期型態檢查（Type Safety），且引數只會被精確評估一次，避免副作用重複執行問題",
         ["具備嚴格的編譯期型態檢查（Type Safety），且引數只會被精確評估一次，避免副作用重複執行問題",
          "執行速度保證比所有組合語言函式快十倍",
          "可以在完全沒有 C 編譯器的環境下直接執行",
          "可以無限次展開而絕不增加二進位執行檔的體積"],
         "inline 函式 vs 巨集：巨集純文字替換，無型態檢查、除錯不易（無法在巨集內部設中斷點）且易引發重複計算副作用。<code>inline</code> 函式由編譯器直接處理，保留一般函式的型態檢查、作用域保護與引數單次評估語意，同時向編譯器建議在呼叫端原地展開程式碼以消除函式呼叫的呼叫堆疊開銷（Call overhead）。"),
        ("前置處理器指令 <code>#error</code> 在 C 程式設計中的標準用途為何？",
         "在編譯預處理時期若條件不符合，發出指定錯誤訊息並強制停止編譯",
         ["在編譯預處理時期若條件不符合，發出指定錯誤訊息並強制停止編譯",
          "在程式執行時捕捉記憶體存取違規並自動重開機",
          "清除螢幕上的所有除錯資訊",
          "自動修復語法錯誤以繼續編譯"],
         "#error 指令用途：常用於架構或編譯環境條件檢查。例如：<br><code>#if __STDC_VERSION__ < 199901L<br>#error \"This project requires C99 compiler!\"<br>#endif</code><br>若在不相容的舊編譯器下編譯，會立即拋出自訂錯誤並終止編譯流程。"),
        ("C 語言標準中預先定義的巨集 <code>__LINE__</code> 與 <code>__FILE__</code> 之值分別代表？",
         "目前程式碼所在的行號（整數）與原始碼檔案名稱（字串）",
         ["目前程式碼所在的行號（整數）與原始碼檔案名稱（字串）",
          "電腦的 IP 位址與 MAC 位址",
          "CPU 的時脈與記憶體大小",
          "作業系統版本與使用者名稱"],
         "標準預定義巨集：C 語言標準規範預定義多個除錯中繼資訊巨集：<br>1. <code>__FILE__</code>：目前檔案路徑與名稱（字串）；<br>2. <code>__LINE__</code>：目前所在行號（十進位整數）；<br>3. <code>__DATE__</code> 與 <code>__TIME__</code>：預處理時的日期與時間；<br>4. <code>__func__</code>（C99）：目前所在函式名稱。常用於記錄日誌與 <code>assert</code> 斷言中。"),
        ("斷言巨集 <code>assert(expression)</code>（定義於 <code>&lt;assert.h&gt;</code>）在何種情況下會在執行期被完全停用並自動略過不執行？",
         "在引入 assert.h 之前定義了巨集 <code>#define NDEBUG</code>",
         ["在引入 assert.h 之前定義了巨集 <code>#define NDEBUG</code>",
          "在命令列加上 -Wall 參數時",
          "程式碼中存在語法錯誤時",
          "使用者以 root 權限執行程式時"],
         "assert 與 NDEBUG：<code>assert(expr)</code> 用於偵錯期間檢驗程式「不可能發生的邏輯錯誤（Invariants）」。若條件為假會印出失敗行號並呼叫 <code>abort()</code>。當專案發布正式正式版本（Release）時，只需在引入前定義 <code>#define NDEBUG</code>（No Debug），所有 assert 呼叫會被前置處理器完全消除為空語句，消除執行期開銷。"),
        ("常數型態修飾詞 <code>const</code> 與前置處理器 <code>#define</code> 在定義常數時，下列敘述何者完全正確？",
         "const 常數具有明確的資料型態與編譯期作用域（Scope），而 #define 僅是全域純文字替換且無型態資訊",
         ["const 常數具有明確的資料型態與編譯期作用域（Scope），而 #define 僅是全域純文字替換且無型態資訊",
          "#define 定義的常數可以進行取位址 & 運算，const 不行",
          "const 常數可以在程式執行時由使用者隨意變更",
          "#define 常數佔用更多的資料區段記憶體空間"],
         "const vs #define 常數對比：<code>const int MAX_SIZE = 100;</code> 受到編譯器型態系統保護，有型態安全（Type-safe）且遵守區域作用域（如僅在函式內有效），符號表保留其名稱方便除錯工具除錯。<code>#define MAX_SIZE 100</code> 只是單純無型態的文字代換，忽視作用域規則，除錯工具無法追蹤符號名稱。"),
        ("執行以下程式碼片段：<br><code>int x = 10; { int x = 20; printf(\"%d \", x); } printf(\"%d\", x);</code><br>終端機輸出的兩個數值依序為何？",
         "20 10",
         ["20 10",
          "10 20",
          "20 20",
          "編譯錯誤（變數重複宣告）"],
         "區域變數遮蔽（Variable Shadowing）：C 語言支援以區塊大括號 <code>{ }</code> 劃分作用域。內層區塊宣告的區域變數 <code>x = 20</code> 會暫時遮蔽（Shadow/Hide）外層同名的全域或外層變數。內層 printf 印出 20；離開內層區塊後，內層 x 生命週期結束被釋放，外層 printf 存取外層的 x，印出 10。兩者在各自作用域合法共存，不構成重複宣告。"),
        ("C 語言中的儲存類別關鍵字 <code>static</code> 修飾函式內部之區域變數時，其最主要影響為何？",
         "將該變數的生命週期延長至整個程式執行期間，且其數值在函式多次呼叫之間予以保留",
         ["將該變數的生命週期延長至整個程式執行期間，且其數值在函式多次呼叫之間予以保留",
          "將變數轉換為只能在其他檔案存取的全域變數",
          "讓變數的值在函式呼叫結束後自動重設為 0",
          "將該變數儲存於 CPU 暫存器中以加速運算"],
         "static 區域變數特性：一般區域變數（auto）儲存於 Stack 堆疊區，函式返回即消亡；<code>static int count = 0;</code> 儲存於全域資料區（Data Segment），只在程式啟動時初始化一次，生命週期貫穿整個程式始末。每次呼叫該函式時，其保留上一次執行後的新值，常用於統計呼叫次數或快取記憶。"),
        ("當 <code>static</code> 關鍵字修飾「全域變數」或「全域函式」時，其在模組化設計中的關鍵功用為何？",
         "限制該符號僅能在「當前原始碼檔案內部（內部鏈結 Internal Linkage）」存取，對其他外部 .c 檔案隱藏不可見",
         ["限制該符號僅能在「當前原始碼檔案內部（內部鏈結 Internal Linkage）」存取，對其他外部 .c 檔案隱藏不可見",
          "強制所有其他原始碼檔案自動引用該函式",
          "將函式或變數發布到網際網路上公開共享",
          "使該函式無法接收任何參數"],
         "static 內部鏈結（資訊隱藏）：在 C 語言中，預設全域函式與變數具備外部鏈結（External Linkage），容易引發跨檔案符號名稱衝突。替全域函式加上 <code>static void helper()</code> 會賦予其內部鏈結，外部檔案無法透過 <code>extern</code> 存取該函式，達成 C 語言中的私有封裝（Encapsulation）。"),
        ("儲存類別關鍵字 <code>extern</code> 在 C 語言中的主要功用為？",
         "宣告一個已在其他原始檔或外部定義的全域變數或函式，告知編譯器其存在而不分配新的記憶體",
         ["宣告一個已在其他原始檔或外部定義的全域變數或函式，告知編譯器其存在而不分配新的記憶體",
          "在記憶體中建立一個永久唯讀的常數",
          "將變數導出至作業系統的環境變數中",
          "強制作業系統為變數配置實體擴充記憶卡"],
         "extern 外部宣告：<code>extern int global_counter;</code> 只是純粹的「型態宣告（Declaration）」而非「定義（Definition）」。它告訴編譯器：「這個變數由別的編譯單元負責分配記憶體，連結時期請鏈結器（Linker）自行去解析其位址」，避免變數重複定義。"),
        ("儲存類別關鍵字 <code>register</code> 建議編譯器對該變數執行的優化為何？對此類變數有何限制？",
         "建議直接存放於 CPU 暫存器中以提升存取速度；無法對該變數使用取位址運算子 & 取值",
         ["建議直接存放於 CPU 暫存器中以提升存取速度；無法對該變數使用取位址運算子 & 取值",
          "將變數儲存於硬碟開機磁區中；變數不可被修改",
          "使變數自動具備多執行緒同步鎖定保護",
          "使變數能跨網路傳輸至另一台伺服器"],
         "register 語意與限制：<code>register int i;</code> 是向編譯器提示該變數存取極為頻繁，建議盡可能放在 CPU 暫存器而非 RAM 堆疊。因為暫存器沒有 RAM 記憶體位址，C 語言規範「嚴格禁止對 register 變數使用 <code>&i</code> 取位址操作」。現代編譯器優化能力極高，通常會自行決定暫存器分配而忽略該關鍵字。"),
        ("在 C 語言中，<code>volatile</code> 關鍵字最核心的防護語意為何？",
         "告知編譯器該變數的值可能在程式控制之外被意外變更（如硬體中斷或並行執行緒），嚴格禁止編譯器對其進行暫存器快取優化",
         ["告知編譯器該變數的值可能在程式控制之外被意外變更（如硬體中斷或並行執行緒），嚴格禁止編譯器對其進行暫存器快取優化",
          "使該變數成為具有密碼保護的加密變數",
          "保證該變數的所有運算具備不可分割的原子性（Atomic）",
          "將變數直接寫入非揮發性快閃記憶體中"],
         "volatile 核心價值：若無 volatile，編譯器在優化時會將變數讀入 CPU 暫存器，在後續讀取時直接從暫存器拿值。但若該變數是「硬體暫存器映射記憶體」或「中斷服務常式 ISR 共享旗標」，硬體隨時會改動 RAM 中的內容。<code>volatile</code> 強制 CPU 每次存取該變數時，必須老老實實發起匯流排交易讀取 RAM，絕不快取。"),
        ("執行以下靜態變數累加程式碼：<br><code>void foo() { static int count = 0; count++; printf(\"%d \", count); }<br>int main() { foo(); foo(); foo(); return 0; }</code><br>終端機輸出的數字序列為？",
         "1 2 3",
         ["1 2 3",
          "1 1 1",
          "0 1 2",
          "3 3 3"],
         "static 區域變數狀態保持推導：<code>static int count = 0;</code> 僅在程式載入時初始化一次。第 1 次呼叫 foo()，count 自增為 1 並印出 1；第 2 次呼叫，count 保留前次的值 1，自增為 2 並印出 2；第 3 次呼叫自增為 3 並印出 3。連續印出 1 2 3。"),
        ("執行以下包含 typedef 的程式碼：<br><code>typedef int* IntPtr; IntPtr a, b;</code><br>在上述宣告中，變數 a 與 b 的資料型態分別為何？",
         "a 與 b 皆為指向 int 的指標（int*）",
         ["a 與 b 皆為指向 int 的指標（int*）",
          "a 為指標 int*，b 為一般整數 int",
          "a 與 b 皆為一般整數 int",
          "編譯錯誤，typedef 不支援指標"],
         "typedef vs #define 指標型態解析：若使用巨集 <code>#define IntPtr int*</code>，則 <code>IntPtr a, b;</code> 會被展開為 <code>int* a, b;</code>，其中星號僅綁定 a，造成 a 是指標而 b 是一般整數！但使用 <code>typedef int* IntPtr;</code> 是定義一個全新的型態別名，因此 <code>IntPtr a, b;</code> 能保證 a 與 b 兩者皆為純正的 <code>int*</code> 指標型態。")
    ]

    # Combine datasets
    all_datasets = [
        ("C/C++ 基本型態、字元編碼與溢位運算推導", types_data),
        ("運算子優先順序、位元運算與短路評估推導", ops_data),
        ("控制流程結構、迴圈邊界與 switch 穿透追蹤", loop_data),
        ("前置處理器巨集、常數作用域與儲存類別解析", macro_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【程式語言核心語法、記憶體模型與流程控制深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 語法規格、型態轉換規則與程式碼執行時序推導</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立語言標準（C99/C11/C++）、運算子優先級與語法結構</strong><br>
      ‧ 本題依據 ISO/IEC 9899 國際標準、LP64 資料模型與公職國考程式語言命題規範嚴格展開。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>執行期行為追蹤、記憶體狀態變更與結果推算</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（運算順序顛倒或型態轉換規則混淆）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（邏輯分支判斷錯誤或輸出格式不合）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非 C 語言標準規範之執行行為）。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_prog_part1_questions()
    print(f"Total Part 1 questions generated: {len(qs)}")
