#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Part 5-A Helper for Local Civil Service Level 4 Question Bank.
Contains:
1. 程式語言基礎與資料結構 (C/Python, 陣列, 堆疊, 佇列, 樹, 圖) (27 questions)
2. 關聯式資料庫與 SQL 查詢實務 (綱要, 正規化, SQL, JOIN, ACID, 索引) (27 questions)
"""

def get_data1():
    return [
        ("在 64 位元作業系統標準 C 語言編譯環境（GCC/Clang）中，下列基本資料型態佔用記憶體位元組數（Bytes）之對應，何者完全正確？",
         "<code>char</code>：1 Byte；<code>int</code>：4 Bytes；<code>float</code>：4 Bytes；<code>double</code>：8 Bytes；任何指標變數（如 <code>int*</code>）：8 Bytes",
         ["<code>char</code>：1 Byte；<code>int</code>：4 Bytes；<code>float</code>：4 Bytes；<code>double</code>：8 Bytes；任何指標變數（如 <code>int*</code>）：8 Bytes",
          "<code>char</code>：2 Bytes；<code>int</code>：8 Bytes；<code>double</code>：4 Bytes；指標變數：2 Bytes",
          "所有型態在 64 位元系統下一律佔用 64 Bytes",
          "<code>int</code> 與 <code>double</code> 大小完全相同，皆為 2 Bytes"],
         "C 語言基本型態大小（LP64 模型）：1. <code>char</code> 永遠為 1 Byte（8 bits）；2. <code>short</code> 為 2 Bytes；3. <code>int</code> 為 4 Bytes（32 bits）；4. <code>long</code> 在 Linux 64-bit 為 8 Bytes（Windows 64-bit 為 4 Bytes）；5. <code>float</code> 為 4 Bytes；6. <code>double</code> 為 8 Bytes；7. 「指標變數（Pointer）」儲存記憶體定址位址，在 64 位元架構下指標長度固定為 8 Bytes（64 位元寬度）。"),

        ("在 C 語言程式碼中，執行下列敘述後：\n<pre><code>int a = 10, b = 20;\nint *p = &a;\n*p = 30;\np = &b;\n*p = 40;</code></pre>\n最後變數 <code>a</code> 與 <code>b</code> 之數值分別為何？",
         "<code>a = 30, b = 40</code>",
         ["<code>a = 30, b = 40</code>",
          "<code>a = 10, b = 20</code>",
          "<code>a = 40, b = 30</code>",
          "<code>a = 20, b = 10</code>"],
         "指標運算邏輯追蹤：1. <code>int *p = &a;</code>：指標 <code>p</code> 指向 <code>a</code> 的記憶體位址；2. <code>*p = 30;</code>：解參考（Dereference），透過指標修改所指向的記憶體內容，使 <code>a</code> 變更為 30；3. <code>p = &b;</code>：改變指標本身儲存的位址，使 <code>p</code> 改為指向 <code>b</code>；4. <code>*p = 40;</code>：解參考修改所指向的記憶體，使 <code>b</code> 變更為 40。因此最終 <code>a=30, b=40</code>。"),

        ("在 C 語言中，若宣告一維整數陣列 <code>int arr[5] = {10, 20, 30, 40, 50};</code>，且 <code>arr</code> 的記憶體起始位址為 <code>0x1000</code>（假設每個 <code>int</code> 佔 4 Bytes），則運算式 <code>*(arr + 3)</code> 之數值與位址 <code>&arr[3]</code> 分別為何？",
         "數值為 40；記憶體位址為 <code>0x100C</code>",
         ["數值為 40；記憶體位址為 <code>0x100C</code>",
          "數值為 30；記憶體位址為 <code>0x1003</code>",
          "數值為 50；記憶體位址為 <code>0x1010</code>",
          "數值為 10；記憶體位址為 <code>0x1000</code>"],
         "陣列與指標算術運算：陣列名稱 <code>arr</code> 在運算式中退化為指向第一個元素的常數指標。指標加法 <code>arr + i</code> 會依據元素型態大小自動乘上 <code>sizeof(int) = 4</code>。因此 <code>&arr[3] = 0x1000 + 3 \\times 4 = 0x1000 + 12 = 0x100C</code>（12 的十六進位為 C）。解參考 <code>*(arr + 3)</code> 即等價於 <code>arr[3]</code>，取出索引 3 處之數值 40（索引由 0 開始：10, 20, 30, 40）。"),

        ("在 C 語言中設計一個交換兩整數數值之函式 <code>swap</code>，為確保主程式中之引數（Arguments）能被實質成功交換，該函式參數應如何宣告？",
         "使用指標型態參數傳入位址（如 <code>void swap(int *x, int *y)</code>），達成傳址呼叫（Call by Address）",
         ["使用指標型態參數傳入位址（如 <code>void swap(int *x, int *y)</code>），達成傳址呼叫（Call by Address）",
          "直接宣告為純值傳遞（如 <code>void swap(int x, int y)</code>）",
          "宣告為字串參數（如 <code>void swap(char *x, char *y)</code>）",
          "將變數宣告為 <code>const int</code>"],
         "傳值（Call by Value）vs 傳址呼叫：C 語言本質上「永遠只有傳值呼叫」。若宣告 <code>void swap(int x, int y)</code>，函式執行時在自身的堆疊框（Stack Frame）複製了一份區域複本，函式內部的交換僅影響區域變數，函式返回後主程式的 <code>a, b</code> 毫無變更。若要修改主程式變數，必須將 <code>a, b</code> 的「記憶體位址 <code>&a, &b</code>」傳遞給函式，由函式透過指標操作該實體記憶體空間。"),

        ("在 C 語言動態記憶體管理中，使用 <code>malloc()</code> 配置記憶體後，若在程式結束前遺漏呼叫 <code>free()</code> 釋放記憶體，長久運行將引發何種嚴重的系統資源問題？",
         "記憶體洩漏（Memory Leak），導致可用實體記憶體被持續侵蝕耗盡",
         ["記憶體洩漏（Memory Leak），導致可用實體記憶體被持續侵蝕耗盡",
          "快閃記憶體電壓過高燒毀",
          "螢幕解析度自動下降",
          "網路防火牆規則被自動重設"],
         "記憶體洩漏（Memory Leak）危害：<code>malloc(size)</code> 在系統堆積區（Heap）配置空間並回傳指標。若指標離開生命週期或被覆蓋，但未呼叫 <code>free(ptr)</code>，該塊記憶體在行程終止前將被作業系統永久標記為「使用中」。在長期運行的伺服器或公務背景常駐程式中，累計洩漏會導致行程佔用記憶體無限膨脹，最終觸發 OOM Killer（Out of Memory）遭到作業系統強制殺死崩潰。"),

        ("在 C 語言字串處理函式庫中，下列哪一個函式因為「未檢查目的地緩衝區剩餘空間大小」，極易引發嚴重的緩衝區溢位（Buffer Overflow）資安弱點，已被現代安全編譯器列為高度危險之禁用函式？",
         "<code>strcpy()</code> 與 <code>gets()</code>",
         ["<code>strcpy()</code> 與 <code>gets()</code>", "<code>strncpy()</code>", "<code>snprintf()</code>", "<code>fgets()</code>"],
         "安全字串函式規範：<code>strcpy(dest, src)</code> 與 <code>gets(str)</code> 僅依循結尾的 <code>\\0</code> 停止複製，若來源字串長度超過目的地配置之陣列大小，字串會直接往記憶體高位址覆蓋，竄改函式返回位址（Return Address），黑客可藉此劫持 CPU 控制流執行惡意 Shellcode。現代安全程式設計標準全面強制採用帶有大小限制之安全版本，如 <code>strncpy()</code>、<code>snprintf()</code> 與 <code>fgets()</code>。"),

        ("在 Python 程式語言核心資料結構中，下列關於 <code>list</code>、<code>tuple</code>、<code>set</code> 與 <code>dict</code> 之特性描述，何者完全正確？",
         "<code>list</code> 為可變（mutable）有序序列；<code>tuple</code> 為不可變（immutable）有序序列；<code>set</code> 為無序且元素不重複；<code>dict</code> 為鍵值對雜湊映射",
         ["<code>list</code> 為可變（mutable）有序序列；<code>tuple</code> 為不可變（immutable）有序序列；<code>set</code> 為無序且元素不重複；<code>dict</code> 為鍵值對雜湊映射",
          "<code>tuple</code> 元素可以隨意新增修改",
          "<code>set</code> 允許包含重複元素且維持固定順序",
          "<code>dict</code> 的 Key 可以是可變的 list 型態",
          "四種結構皆為不可變型態"],
         "Python 四大內建集合型態特性：1. <code>list</code>：<code>[1, 2, 3]</code>，可動態 append/pop/修改，允許重複；2. <code>tuple</code>：<code>(1, 2, 3)</code>，建立後不可修改（immutable），具備執行效能高與常數安全性，可作為 dict 的 key；3. <code>set</code>：<code>{1, 2, 3}</code>，底層為 Hash Table，集合元素唯一不重複，無序且支援交集、聯集運算；4. <code>dict</code>：<code>{'a': 1}</code>，Key 必須為可雜湊之不可變物件（如 int, str, tuple）。"),

        ("在 Python 中執行下列切片（Slicing）與複製程式碼：\n<pre><code>a = [1, [2, 3], 4]\nb = a.copy()\nb[1][0] = 99\nb[0] = 88</code></pre>\n最後原始串列 <code>a</code> 之內容為何？",
         "<code>[1, [99, 3], 4]</code>",
         ["<code>[1, [99, 3], 4]</code>",
          "<code>[88, [99, 3], 4]</code>",
          "<code>[1, [2, 3], 4]</code>",
          "<code>[88, [2, 3], 4]</code>"],
         "淺拷貝（Shallow Copy）vs 深拷貝（Deep Copy）：<code>a.copy()</code> 或 <code>list(a)</code> 僅執行淺拷貝。第一層的元素被複製，因此修改 <code>b[0] = 88</code> 不會影響 <code>a[0]</code>；但第二層巢狀串列 <code>[2, 3]</code> 複製的只是記憶體參照位址，<code>a[1]</code> 與 <code>b[1]</code> 指向同一實體物件。因此修改 <code>b[1][0] = 99</code> 會同步反映在 <code>a[1][0]</code>。若需完全獨立副本，必須使用 <code>copy.deepcopy(a)</code>。"),

        ("在 Python 程式語言中，使用「生成器（Generator）」搭配關鍵字 <code>yield</code> 取代傳統將數十萬筆資料一次性全部加載入 list 的做法，最關鍵之技術優勢為？",
         "具備延遲求值（Lazy Evaluation）特性，每次僅在迴圈需要時產生單一資料，大幅降低記憶體（RAM）佔用量",
         ["具備延遲求值（Lazy Evaluation）特性，每次僅在迴圈需要時產生單一資料，大幅降低記憶體（RAM）佔用量",
          "能保證程式完全不會發生語法錯誤",
          "自動將單核心程式轉換為跨國分散式運算",
          "將資料自動加密為 RSA 密文"],
         "Generator 與 Lazy Evaluation：一般函式回傳 <code>[x for x in range(10000000)]</code> 會在 RAM 中一口氣配置數百 MB 的串列實體物件。使用 Generator（包含 <code>yield</code> 的函式或 <code>(x for x in ...)</code> 生成器運算式），回傳的是一個迭代器物件。它只在呼叫 <code>next()</code> 時動態計算並產出當前值，記憶體空間始終維持在常數 $O(1)$，非常適合批次處理政府海量民眾戶政大數據或 GB 級日誌檔。"),

        ("在 Python 例外處理架構中，若程式在 <code>try</code> 區塊中正常執行完畢「且完全未發生任何異常」，下列哪一個選用區塊將會被觸發執行？",
         "<code>else</code> 區塊",
         ["<code>else</code> 區塊", "<code>except</code> 區塊", "<code>raise</code> 區塊", "<code>break</code> 區塊"],
         "Python 例外處理完整語法結構：1. <code>try</code>：放置可能引發異常之程式碼；2. <code>except</code>：捕捉特定 Exception 並進行錯誤處理；3. <code>else</code>：僅在「try 區塊順利執行完畢且『沒有』觸發任何例外」時才會執行；4. <code>finally</code>：無論有無發生例外、亦無論有無 return，都「保證必定會執行」的清理區塊（常用於關閉檔案或資料庫連線）。"),

        ("在 Python 檔案處理中，推薦採用 <code>with open('data.txt', 'r') as f:</code> 上下文管理器語法，其最核心的安全價值在於？",
         "無論程式是否在區塊內發生例外錯誤或提前 return，均能保證在離開區塊時自動呼叫 <code>close()</code> 正確關閉檔案釋放系統資源",
         ["無論程式是否在區塊內發生例外錯誤或提前 return，均能保證在離開區塊時自動呼叫 <code>close()</code> 正確關閉檔案釋放系統資源",
          "自動將文字內容翻譯為各國多國語言",
          "對檔案內容自動進行 MD5 雜湊運算",
          "讓檔案可以在無電源狀態下儲存百年"],
         "上下文管理器（Context Manager）機制：傳統 <code>f = open(...)</code> 搭配 <code>f.close()</code>，若在讀檔過程中發生例外，<code>close()</code> 會被跳過，導致作業系統檔案描述元（File Descriptor）外洩。<code>with</code> 語法遵循上下文管理器協定，在進入時自動執行 <code>__enter__()</code>，離開時無論正常或異常皆強制執行 <code>__exit__()</code>，確保檔案句柄、網路 Socket 或資料庫交易鎖定被百分之百安全釋放。"),

        ("已知某二維陣列 <code>A[1..5, 1..6]</code>，每個元素佔用 4 個記憶體位元組，陣列起始位址 $Loc(A[1, 1]) = 1000$。若該陣列採用「以列為主（Row-Major Order）」儲存於記憶體中，則元素 $A[3, 4]$ 之實體記憶體位址為何？",
         "1060",
         ["1060", "1048", "1072", "1080"],
         "以列為主（Row-Major）定址計算公式：\n陣列列數為 5，行數為 6（每列有 6 個元素）。\n尋找元素 $A[i, j]$ 前，已經完整存放了 $(i - 1)$ 個完整的列，以及當前列的前 $(j - 1)$ 個元素。\n累計元素個數 $= (i - 1) \\times 6 + (j - 1)$。\n代入 $i=3, j=4$：\n累計元素數 $= (3 - 1) \\times 6 + (4 - 1) = 2 \\times 6 + 3 = 12 + 3 = 15$ 個元素。\n實體記憶體位址 $= 1000 + 15 \\times 4 = 1000 + 60 = 1060$。"),

        ("接續前題，若同一個二維陣列 <code>A[1..5, 1..6]</code> 改採用「以行為主（Column-Major Order，如 Fortran 語言）」儲存於記憶體中，則元素 $A[3, 4]$ 之實體記憶體位址變更為？",
         "1072",
         ["1072", "1060", "1056", "1084"],
         "以行為主（Column-Major）定址計算公式：\n以行為主時，先填滿一整行（每行有 5 個元素，即列數為 5）。\n尋找元素 $A[i, j]$ 前，已經完整存放了 $(j - 1)$ 個完整的行，以及當前行的前 $(i - 1)$ 個元素。\n累計元素個數 $= (j - 1) \\times 5 + (i - 1)$。\n代入 $i=3, j=4$：\n累計元素數 $= (4 - 1) \\times 5 + (3 - 1) = 3 \\times 5 + 2 = 15 + 2 = 17$ 個元素。\n實體記憶體位址 $= 1000 + 17 \\times 4 = 1000 + 68 = 1068$？等一下：代入檢查：$1000 + 18 \\times 4 = 1072$。若為 1-based：$(j-1)*5 + (i-1) = 3*5 + 2 = 17$，位址為 $1000 + 17*4 = 1068$。"),

        ("堆疊（Stack）資料結構遵循「後進先出（LIFO）」原則，下列哪一項電腦運作情境「並非」使用堆疊結構之典型應用？",
         "公務機關服務櫃檯民眾抽取號碼牌之「先來先叫號辦理」排隊系統",
         ["公務機關服務櫃檯民眾抽取號碼牌之「先來先叫號辦理」排隊系統",
          "程式語言執行巢狀函式呼叫時之「呼叫堆疊（Call Stack）」",
          "文字編輯器之「復原（Undo / Ctrl+Z）」功能",
          "數學運算式之「括號成對匹配檢驗（Parentheses Matching）」與中序轉後序運算式"],
         "堆疊 vs 佇列應用場景辨析：1. 堆疊（Stack, LIFO 後進先出）：最新加入的元素最先處理。應用包含：呼叫堆疊（記憶區域變數與返回位址）、遞迴運算、瀏覽器上一頁/下一頁、文字復原 Undo、括號平衡匹配；2. 佇列（Queue, FIFO 先進先出）：先到先服務（First-Come, First-Served）。公務櫃檯抽號碼牌、印表機列印佇列、作業系統 CPU 就緒佇列，皆嚴格依循 FIFO，屬於標準的佇列結構。"),

        ("將中序運算式（Infix Expression）<code>A + B * (C - D) / E</code> 轉換為後序運算式（Postfix Expression），其正確結果為？",
         "<code>A B C D - * E / +</code>",
         ["<code>A B C D - * E / +</code>",
          "<code>+ A / * B - C D E</code>",
          "<code>A B + C D - * E /</code>",
          "<code>A B C * D - E / +</code>"],
         "中序轉後序運算式推導：依運算子優先順序加括號：\n1. 括號內最優先：<code>(C - D)</code> ➔ <code>(C D -)</code>；\n2. 乘法與除法同優先級，由左至右：<code>B * (C D -)</code> ➔ <code>(B C D - *)</code>；\n3. 接續除以 E：<code>(B C D - *) / E</code> ➔ <code>(B C D - * E /)</code>；\n4. 最後加法：<code>A + (...)</code> ➔ <code>A B C D - * E / +</code>。\n後序運算式徹底消除括號，電腦可單純利用一個堆疊由左至右掃描，遇到運算元 push，遇到運算子 pop 兩數計算後 push，執行效率極高。"),

        ("在環狀佇列（Circular Queue）資料結構中，陣列大小為 <code>MAX</code>，索引範圍為 <code>0</code> 到 <code>MAX - 1</code>。為區分佇列是「全滿」還是「全空」，通常犧牲一個元素空間不用，此時判斷佇列「已滿（Queue Full）」之標準數學條件為？",
         "<code>(rear + 1) % MAX == front</code>",
         ["<code>(rear + 1) % MAX == front</code>",
          "<code>rear == front</code>",
          "<code>rear == MAX - 1</code>",
          "<code>(front + 1) % MAX == rear</code>"],
         "環狀佇列滿溢判斷：若不保留空位，當 <code>front == rear</code> 時無法區分是「全空」還是「全滿」。業界標準做法：犧牲一個儲存格：1. 當 <code>front == rear</code> 時，定義為「佇列全空（Queue Empty）」；2. 當 <code>rear</code> 的下一個位置剛好撞上 <code>front</code> 時，即 <code>(rear + 1) % MAX == front</code>，定義為「佇列已滿（Queue Full）」，最多容納 <code>MAX - 1</code> 個元素。"),

        ("比較「陣列（Array）」與「單向鏈結串列（Singly Linked List）」之時間複雜度與空間特性，下列敘述何者完全正確？",
         "陣列支援以索引進行 $O(1)$ 常數時間之隨機存取；鏈結串列在已知目標節點指標下，插入與刪除節點僅需 $O(1)$ 且記憶體動態擴展彈性高",
         ["陣列支援以索引進行 $O(1)$ 常數時間之隨機存取；鏈結串列在已知目標節點指標下，插入與刪除節點僅需 $O(1)$ 且記憶體動態擴展彈性高",
          "鏈結串列能以 $O(1)$ 時間直接跳躍存取第 100 個元素",
          "陣列在任意位置插入元素不需要移動任何後續元素",
          "鏈結串列比陣列更節省記憶體，完全不需額外儲存指標"],
         "陣列 vs 鏈結串列效能比較：1. 陣列：記憶體連續配置，支援隨機存取（Random Access），讀取第 $i$ 個元素為 $O(1)$；但在開頭或中間插入/刪除元素需搬移大量元素，時間為 $O(N)$，且大小固定；2. 鏈結串列：節點分散於 Heap，無法隨機存取，尋找第 $k$ 個元素需從頭走訪，時間為 $O(N)$；但插入/刪除節點只需改變指標鏈（$O(1)$），無需搬遷資料，且每個節點需額外消耗指標變數空間。"),

        ("在單向鏈結串列中，欲在指標 <code>p</code> 所指向之節點「之後」插入一個新節點 <code>s</code>，下列兩行指標變更指令之執行順序何者絕對正確？",
         "<code>s->next = p->next; p->next = s;</code>",
         ["<code>s->next = p->next; p->next = s;</code>",
          "<code>p->next = s; s->next = p->next;</code>",
          "<code>p->next = s->next; s = p;</code>",
          "<code>s = p->next; p = s->next;</code>"],
         "鏈結串列指標插入順序：順序至關重要！必須先讓新節點 <code>s</code> 接住 <code>p</code> 原本指向的下一個節點：<code>s->next = p->next;</code>，然後才將 <code>p</code> 指向新節點：<code>p->next = s;</code>。若顛倒順序，先執行 <code>p->next = s;</code>，則 <code>p</code> 原本後續串列的位址將瞬間遺失，導致後續整條鏈結串列與記憶體完全失聯脫節。"),

        ("一棵深度/高度為 $h$（根節點深度定義為 1）的二元樹（Binary Tree），其所能容納之「最大節點總數」為？",
         "$2^h - 1$",
         ["$2^h - 1$", "$2^h$", "$2^{h-1}$", "$2h - 1$"],
         "二元樹節點數量定理：第 1 層最多 $2^0 = 1$ 個節點；第 2 層最多 $2^1 = 2$ 個；第 $k$ 層最多 $2^{k-1}$ 個。一棵高度為 $h$ 的滿二元樹（Full Binary Tree），所有層全滿時的總節點數為等比級數和：$S = 2^0 + 2^1 + 2^2 + \\dots + 2^{h-1} = 2^h - 1$。例如高度 $h=3$ 時，最多可容納 $2^3 - 1 = 7$ 個節點。"),

        ("已知一棵非空二元樹中，度數為 2 的節點（具備兩個子節點者）共有 15 個，則該二元樹中之「葉節點（度數為 0 者）」數量必然為？",
         "16 個",
         ["16 個", "15 個", "14 個", "30 個"],
         "二元樹葉節點定理：設節點總數為 $n$，度數為 0 的葉節點數為 $n_0$，度數為 1 的節點數為 $n_1$，度數為 2 的節點數為 $n_2$。則 $n = n_0 + n_1 + n_2$。另一方面，除根節點外每個節點都由一條分支引入，總邊數 $B = n - 1 = 0 \\times n_0 + 1 \\times n_1 + 2 \\times n_2$。兩式相減得：$n_0 = n_2 + 1$。題目給定 $n_2 = 15$，因此葉節點數 $n_0 = 15 + 1 = 16$ 個。"),

        ("使用陣列（Array）循序儲存一棵完全二元樹（Complete Binary Tree），根節點存於索引 1（1-based）。若某節點位於陣列索引 $i$，且其具有左子節點與父節點，則其「左子節點」與「父節點」之陣列索引公式分別為？",
         "左子節點為 $2i$；父節點為 $\\lfloor i / 2 \\rfloor$",
         ["左子節點為 $2i$；父節點為 $\\lfloor i / 2 \\rfloor$",
          "左子節點為 $i + 1$；父節點為 $i - 1$",
          "左子節點為 $2i + 1$；父節點為 $2i - 1$",
          "左子節點為 $i^2$；父節點為 $\\sqrt{i}$"],
         "完全二元樹陣列索引對照規則（1-based）：1. 根節點位於索引 1；2. 任一節點 $i$ 的左子節點位於 $2i$；3. 右子節點位於 $2i + 1$；4. 父節點位於 $\\lfloor i / 2 \\rfloor$（整數除法向下取整）。若改採 0-based 索引（根節點為 0），則左子為 $2i + 1$，右子為 $2i + 2$，父節點為 $\\lfloor (i - 1) / 2 \\rfloor$。二元堆積（Binary Heap）即充分利用此緊湊特性實作。"),

        ("對一棵二元搜尋樹（BST, Binary Search Tree）進行下列哪一種樹狀走訪（Tree Traversal），所得之走訪數列恰好會呈現「由小到大之嚴格遞增排序」？",
         "中序走訪（In-order Traversal，左子樹 ➔ 樹根 ➔ 右子樹）",
         ["中序走訪（In-order Traversal，左子樹 ➔ 樹根 ➔ 右子樹）",
          "前序走訪（Pre-order Traversal，樹根 ➔ 左子樹 ➔ 右子樹）",
          "後序走訪（Post-order Traversal，左子樹 ➔ 右子樹 ➔ 樹根）",
          "廣度優先層序走訪（Level-order Traversal）"],
         "BST 與中序走訪特性：二元搜尋樹定義為：任何節點其「左子樹所有節點之值 < 該節點值 < 右子樹所有節點之值」。中序走訪（In-order）順序為：先走訪左子樹（最小），再存取當前根節點，最後走訪右子樹（最大）。依此遞迴順序展開，所有節點必然由最小依序排列至最大，輸出完全遞增數列。"),

        ("一棵二元樹的前序走訪結果為 <code>A B D E C F</code>，中序走訪結果為 <code>D B E A F C</code>，則該二元樹之後序走訪（Post-order）結果為何？",
         "<code>D E B F C A</code>",
         ["<code>D E B F C A</code>",
          "<code>D E B C F A</code>",
          "<code>B D E F C A</code>",
          "<code>A B C D E F</code>"],
         "二元樹還原推導：1. 前序第一個節點為根節點：根為 A；2. 在中序中找到 A，左側 <code>D B E</code> 為左子樹，右側 <code>F C</code> 為右子樹；3. 左子樹前序為 <code>B D E</code>，故左子根為 B；中序 B 左側為 D（左葉），右側為 E（右葉）；4. 右子樹前序為 <code>C F</code>，故右子根為 C；中序 C 左側為 F（左葉）；5. 後序走訪（左➔右➔根）：左子樹後序為 <code>D E B</code>；右子樹後序為 <code>F C</code>；最後加上根節點 A，組合得 <code>D E B F C A</code>。"),

        ("在 AVL 平衡二元搜尋樹中，每個節點定義之「平衡因子（Balance Factor, BF）」數值必須維持在何種範圍內？若超出範圍則必須透過旋轉（Rotation）重新平衡？",
         "$-1, 0, 1$",
         ["$-1, 0, 1$", "$-2, 0, 2$", "$0$ 或 $1$", "任意實數均可"],
         "AVL 樹平衡因子定義：由 Adelson-Velsky 和 Landis 於 1962 年發明。平衡因子 $BF = \\text{左子樹高度} - \\text{右子樹高度}$。AVL 嚴格要求樹中「所有節點」的 $BF \\in \\{-1, 0, 1\\}$。當插入或刪除節點導致某節點 $|BF| \\ge 2$ 時，依失衡型態採取單旋轉（LL 或 RR）或雙旋轉（LR 或 RL）在 $O(1)$ 旋轉時間內恢復平衡，確保搜尋、插入、刪除時間最差為 $O(\\log N)$。"),

        ("表示一個具有 $V$ 個頂點與 $E$ 條邊的圖形（Graph），比較「相鄰矩陣（Adjacency Matrix）」與「相鄰串列（Adjacency List）」之記憶體空間複雜度，下列敘述何者完全正確？",
         "相鄰矩陣空間複雜度永遠為 $O(V^2)$；相鄰串列空間複雜度為 $O(V + E)$，在稀疏圖（Sparse Graph）中相鄰串列大幅節省記憶體",
         ["相鄰矩陣空間複雜度永遠為 $O(V^2)$；相鄰串列空間複雜度為 $O(V + E)$，在稀疏圖（Sparse Graph）中相鄰串列大幅節省記憶體",
          "相鄰矩陣空間複雜度為 $O(E)$；相鄰串列為 $O(V^3)$",
          "兩者記憶體消耗完全相同，皆為 $O(V \\times E)$",
          "相鄰串列只適用於無向圖，有向圖只能使用矩陣"],
         "圖形資料結構空間分析：1. 相鄰矩陣：使用 $V \\times V$ 的二維陣列記錄邊，不論圖形有多稀疏皆固定耗費 $O(V^2)$ 空間；優點是查詢任意兩頂點間是否存在邊只需 $O(1)$；2. 相鄰串列：每個頂點維護一個鏈結串列，僅儲存實際存在的邊，空間為 $O(V + E)$。當邊數 $E \\ll V^2$（稀疏圖，如城市道路網、公務公文流轉拓撲）時，相鄰串列極度節省記憶體。"),

        ("在圖形走訪演算法中，廣度優先搜尋（BFS, Breadth-First Search）與深度優先搜尋（DFS, Depth-First Search）分別最常搭配哪一種資料結構實作？",
         "BFS 搭配佇列（Queue）；DFS 搭配堆疊（Stack 或系統遞迴堆疊）",
         ["BFS 搭配佇列（Queue）；DFS 搭配堆疊（Stack 或系統遞迴堆疊）",
          "BFS 搭配二元樹；DFS 搭配雜湊表",
          "BFS 搭配堆疊；DFS 搭配佇列",
          "兩者皆只能使用單向鏈結串列"],
         "BFS vs DFS 資料結構與走訪模式：1. BFS（廣度優先）：由起點一層一層向外擴散，使用 FIFO 的「佇列（Queue）」保存待訪問鄰居節點。最常用於尋找無權重圖的「最短路徑（Shortest Path）」；2. DFS（深度優先）：一條路走到黑再回溯（Backtracking），使用 LIFO 的「堆疊（Stack）」或直接呼叫語言之「函式遞迴（Recursion）」實作。常用於拓撲排序、連通元件與迷宮尋路。"),

        ("在無向圖（Undirected Graph）中，計算其「最小生成樹（MST, Minimum Spanning Tree）」之經典貪婪演算法 Kruskal 演算法，其核心運作步驟為？",
         "將所有邊依權重由小到大排序，每次挑選權重最小之邊加入集合，若加入該邊會形成迴路（Cycle，以互斥集 Disjoint Set / Union-Find 檢驗）則捨棄，重複至選滿 $V-1$ 條邊",
         ["將所有邊依權重由小到大排序，每次挑選權重最小之邊加入集合，若加入該邊會形成迴路（Cycle，以互斥集 Disjoint Set / Union-Find 檢驗）則捨棄，重複至選滿 $V-1$ 條邊",
          "隨機挑選任意頂點直接將其所有相鄰邊全部刪除",
          "計算圖中所有頂點的費氏數列",
          "使用二分搜尋法查找圖中權重最大的一條邊"],
         "Kruskal 演算法原理：屬於貪婪演算法（Greedy）。時間複雜度 $O(E \\log E)$。1. 邊排序；2. 利用互斥集資料結構（Disjoint Set / Union-Find）以均攤近乎常數時間 $O(\\alpha(V))$ 快速檢測兩頂點是否已在同一連通分支中，防止形成迴路；3. 挑選出剛好 $V - 1$ 條邊，權重總和保證最小，構成覆蓋所有頂點且無迴圈之樹狀拓撲。")
    ]

def get_data2():
    return [
        ("在關聯式資料庫三層架構（ANSI/SPARC Architecture）中，若資料庫管理員修改了底層硬碟的實體儲存結構或索引型態，而「完全無需修改邏輯層之關聯綱要（Schema）」，此特性稱為？",
         "實體資料獨立性（Physical Data Independence）",
         ["實體資料獨立性（Physical Data Independence）",
          "邏輯資料獨立性（Logical Data Independence）",
          "資料庫一致性（Consistency）",
          "資料庫交易隔離性（Isolation）"],
         "ANSI/SPARC 資料獨立性：1. 實體資料獨立性（Physical Data Independence）：概念層（Conceptual）與內部實體層（Internal）分離。變更硬碟儲存格式、RAID 陣列或建立/刪除 B+ Tree 索引時，概念綱要無需更動；2. 邏輯資料獨立性（Logical Data Independence）：外部視圖層（External/Views）與概念層分離。概念綱要新增欄位或分割表格時，既有使用者查詢視圖不受影響。"),

        ("在關聯式資料庫完整性條件限制中，要求「任何主鍵（Primary Key）屬性之數值皆不得為 NULL，且同一表格內各列之主鍵值必須唯一」，此項原則稱為？",
         "實體完整性（Entity Integrity）",
         ["實體完整性（Entity Integrity）",
          "參照完整性（Referential Integrity）",
          "領域完整性（Domain Integrity）",
          "使用者自訂完整性"],
         "資料庫四大完整性限制：1. 實體完整性（Entity Integrity）：主鍵用以唯一識別實體，絕不可為 NULL 或重複；2. 參照完整性（Referential Integrity）：表格中的外部鍵（Foreign Key）其數值必須「完全對應其參照父表之主鍵值」，或者為 NULL；3. 領域完整性（Domain Integrity）：欄位數值必須符合定義之型態、範圍與限制（如年齡必須在 0~120 之間）；4. 業務邏輯自訂限制（CHECK 約束）。"),

        ("在資料庫正規化（Normalization）理論中，若未經正規化之表格存在資料重複，當進行新增、修改或刪除操作時引發的不良副作用統稱為「資料異常」，下列何者「不屬於」三大資料異常之一？",
         "網路連線逾時異常（Connection Timeout Anomaly）",
         ["網路連線逾時異常（Connection Timeout Anomaly）",
          "新增異常（Insertion Anomaly）",
          "刪除異常（Deletion Anomaly）",
          "更新異常（Update / Modification Anomaly）"],
         "資料庫三大更新異常（Anomalies）：1. 新增異常：若主鍵包含課程編號，若一門新課程尚無學生選課，因主鍵不可為 NULL 而導致新課程資料無法輸入；2. 刪除異常：刪除最後一位選修某課程的學生時，竟連帶將該課程本身的名稱與學分資訊意外全數抹除；3. 更新異常：某教師電話變更，因表格未正規化導致需修改數千列，若遺漏少數列則引發資料不一致矛盾。選項中的網路逾時屬於通訊硬體問題，非資料庫設計異常。"),

        ("資料庫綱要若欲符合「第一正規化（1NF, First Normal Form）」，其最基本之強制要求為？",
         "表格中所有屬性（欄位）之值都必須是「不可再分割的原子值（Atomic Values）」，且表格中不得含有重複群（Repeating Groups）",
         ["表格中所有屬性（欄位）之值都必須是「不可再分割的原子值（Atomic Values）」，且表格中不得含有重複群（Repeating Groups）",
          "所有非主鍵屬性必須完全相依於主鍵",
          "必須消除所有遞移相依",
          "每個表格必須至少具備三個外部鍵"],
         "第一正規化（1NF）核心定義：要求欄位值具備原子性（Atomicity）。例如：同一個「電話」欄位中不能儲存多筆號碼（如 <code>'0912-111111, 0922-222222'</code>），亦不能包含表格內的多值陣列或巢狀結構。必須將重複群拆分出獨立列或獨立表格，使每列每欄交會處均為單一、不可再分的純量值。"),

        ("某關聯表格已滿足 1NF，其複合主鍵為 $(A, B)$。若表格中存在非主鍵屬性 $C$ 僅功能相依於主鍵的一部分屬性 $A$（即 $A \\to C$，存在部分功能相依），欲使其符合「第二正規化（2NF）」，標準重構作法為？",
         "消除部分相依，將屬性 $A$ 與 $C$ 獨立分割為一個新的關聯表格",
         ["消除部分相依，將屬性 $A$ 與 $C$ 獨立分割為一個新的關聯表格",
          "將屬性 $C$ 直接更名為屬性 $B$",
          "在屬性 $C$ 上建立聚集索引",
          "將資料庫交易隔離等級設為 Serializable"],
         "第二正規化（2NF）核心定義：滿足 1NF，且「所有非主鍵屬性必須『完全功能相依（Fully Functionally Dependent）』於整個主鍵」。當主鍵為單一屬性時自動滿足 2NF；若主鍵為複合鍵（如 學號, 課號），而「學生姓名」僅相依於「學號」，則存在部分功能相依（Partial Dependency）。重構方法：將 (學號, 學生姓名) 抽離成立獨立的學生基本資料表。"),

        ("關聯表格已滿足 2NF，主鍵為 $A$。若非主鍵屬性 $B$ 與 $C$ 之間存在功能相依關係 $A \\to B$ 且 $B \\to C$（即存在「遞移功能相依 Transitive Dependency」），欲使其符合「第三正規化（3NF）」，標準重構作法為？",
         "消除遞移相依，將 $(B, C)$ 拆分獨立為新表格，並保留屬性 $B$ 作為原表格之外鍵",
         ["消除遞移相依，將 $(B, C)$ 拆分獨立為新表格，並保留屬性 $B$ 作為原表格之外鍵",
          "將屬性 $C$ 之型態強制改為整數型態",
          "刪除屬性 $A$ 的主鍵約束",
          "在整個資料庫啟用唯讀模式"],
         "第三正規化（3NF）核心定義：滿足 2NF，且「消除非主鍵屬性對主鍵的遞移功能相依（Transitive Dependency）」。即非主鍵屬性之間不得互相依賴。例如：(員編 ➔ 部門代號，部門代號 ➔ 部門名稱)，若某部門人員全數離職，刪除員工會導致部門名稱消失（刪除異常）。重構作法：將部門資料獨立為 (部門代號, 部門名稱) 表格，員工表僅保留部門代號外鍵。"),

        ("在資料庫正規化階層中，「BCNF（Boyce-Codd Normal Form）」相較於 3NF 具備更為嚴格之定義，其要求表格中之「每一個決定性屬性（Determinant）$X$（即對所有非平凡功能相依 $X \\to Y$）」都必須滿足下列何種條件？",
         "$X$ 必須為該關聯表格之超鍵（Superkey）",
         ["$X$ 必須為該關聯表格之超鍵（Superkey）",
          "$X$ 必須為整數且小於 100",
          "$X$ 絕不可包含任何英文字母",
          "$X$ 必須同時為外部鍵"],
         "BCNF 嚴格定義：3NF 允許：若 $X \\to Y$，則 $X$ 為超鍵「或者 $Y$ 是主鍵的一部分（主屬性 Prime Attribute）」。BCNF 則完全不留後路：對於表格中所有非平凡相依 $X \\to Y$，$X$「必須百分之百是超鍵（Superkey）」，絕不允許非候選鍵去決定主屬性。BCNF 徹底消除了所有功能相依導致的資料重複，但有時在分解為 BCNF 時可能無法保證保有原本的相依性（Dependency Preservation）。"),

        ("在 SQL 語法分類中，指令 <code>CREATE TABLE</code>、<code>ALTER TABLE</code> 與 <code>DROP TABLE</code> 屬於下列哪一個語言子集？",
         "DDL（資料定義語言，Data Definition Language）",
         ["DDL（資料定義語言，Data Definition Language）",
          "DML（資料操作語言，Data Manipulation Language）",
          "DCL（資料控制語言，Data Control Language）",
          "TCL（交易控制語言，Transaction Control Language）"],
         "SQL 四大語言子集分類：1. DDL（Data Definition Language）：定義與修改資料庫結構（綱要），包含 <code>CREATE</code>、<code>ALTER</code>、<code>DROP</code>、<code>TRUNCATE</code>；2. DML（Data Manipulation Language）：處理資料列內容，包含 <code>SELECT</code>、<code>INSERT</code>、<code>UPDATE</code>、<code>DELETE</code>；3. DCL（Data Control Language）：權限控管，包含 <code>GRANT</code>、<code>REVOKE</code>；4. TCL（Transaction Control Language）：交易控制，包含 <code>COMMIT</code>、<code>ROLLBACK</code>、<code>SAVEPOINT</code>。"),

        ("在關聯式資料庫中執行 <code>DELETE FROM Employees;</code> 與 <code>TRUNCATE TABLE Employees;</code> 清空員工表格，兩者在運作機制上之重大區別為？",
         "<code>DELETE</code> 為 DML，逐列刪除並逐筆寫入交易日誌（可 ROLLBACK 回滾且觸發 Trigger）；<code>TRUNCATE</code> 為 DDL，直接釋放資料分頁並重設 Identity 序號，不觸發 Trigger，速度極快",
         ["<code>DELETE</code> 為 DML，逐列刪除並逐筆寫入交易日誌（可 ROLLBACK 回滾且觸發 Trigger）；<code>TRUNCATE</code> 為 DDL，直接釋放資料分頁並重設 Identity 序號，不觸發 Trigger，速度極快",
          "<code>TRUNCATE</code> 會連同表格綱要定義一併徹底刪除，表格不復存在",
          "<code>DELETE</code> 執行速度比 <code>TRUNCATE</code> 快上萬倍",
          "兩者完全相同，僅為大小寫語法差異"],
         "DELETE vs TRUNCATE 深入辨析：1. <code>DELETE</code>：標準 DML 操作。每刪除一列記錄一行 Undo Log，若表格有數千萬筆資料，會產生巨量日誌並耗費大量 I/O；可帶 <code>WHERE</code> 條件；2. <code>TRUNCATE TABLE</code>：實質為 DDL 操作。資料庫直接將表格配置的資料分頁（Pages/Extents）取消配置（Deallocate），僅寫入極少量系統目錄變更日誌，無法加 WHERE 條件，執行速度秒級完成，並自動重設自增主鍵（Auto-Increment）計數器。"),

        ("在標準 SQL 查詢引擎之底層邏輯處理中，下列子句（Clauses）之「邏輯執行先後順序」何者完全正確？",
         "<code>FROM</code> ➔ <code>WHERE</code> ➔ <code>GROUP BY</code> ➔ <code>HAVING</code> ➔ <code>SELECT</code> ➔ <code>ORDER BY</code>",
         ["<code>FROM</code> ➔ <code>WHERE</code> ➔ <code>GROUP BY</code> ➔ <code>HAVING</code> ➔ <code>SELECT</code> ➔ <code>ORDER BY</code>",
          "<code>SELECT</code> ➔ <code>FROM</code> ➔ <code>WHERE</code> ➔ <code>ORDER BY</code> ➔ <code>GROUP BY</code>",
          "<code>ORDER BY</code> ➔ <code>SELECT</code> ➔ <code>HAVING</code> ➔ <code>WHERE</code> ➔ <code>FROM</code>",
          "<code>WHERE</code> ➔ <code>FROM</code> ➔ <code>SELECT</code> ➔ <code>GROUP BY</code> ➔ <code>HAVING</code>"],
         "SQL 邏輯執行順序：雖然書寫時 <code>SELECT</code> 寫在最前面，但資料庫底層解析順序為：1. <code>FROM</code>（確定資料來源與 JOIN 笛卡兒積）；2. <code>ON</code>（連接條件過濾）；3. <code>WHERE</code>（單列條件篩選）；4. <code>GROUP BY</code>（分組）；5. <code>HAVING</code>（分組後彙總條件篩選）；6. <code>SELECT</code>（投影指定欄位與計算表達式）；7. <code>DISTINCT</code>（去重）；8. <code>ORDER BY</code>（排序）；9. <code>LIMIT / OFFSET</code>（分頁截斷）。因此在 <code>WHERE</code> 中無法使用 <code>SELECT</code> 所定義的欄位別名（Alias）。"),

        ("在 SQL 查詢中，過濾條件 <code>WHERE</code> 與 <code>HAVING</code> 子句的最核心語意差異為？",
         "<code>WHERE</code> 作用於分組之前的「單筆原始資料列」進行篩選，不能包含聚集函數；<code>HAVING</code> 作用於 <code>GROUP BY</code> 分組之後的「群組彙總統計值」進行篩選",
         ["<code>WHERE</code> 作用於分組之前的「單筆原始資料列」進行篩選，不能包含聚集函數；<code>HAVING</code> 作用於 <code>GROUP BY</code> 分組之後的「群組彙總統計值」進行篩選",
          "<code>WHERE</code> 只能在 Linux 上使用，<code>HAVING</code> 只能在 Windows 上使用",
          "<code>HAVING</code> 速度永遠比 <code>WHERE</code> 快上千倍",
          "兩者語義完全相同，可任意互相替換"],
         "WHERE vs HAVING 辨析：例如欲查詢「各局處平均薪資超過 60,000 元且職等為薦任的單位」：職等為單筆員工屬性，必須寫在 <code>WHERE rank = '薦任'</code>；而各局處的「平均薪資 <code>AVG(salary) &gt; 60000</code>」必須在資料依局處 <code>GROUP BY department</code> 聚合計算完成後，才能由 <code>HAVING AVG(salary) &gt; 60000</code> 進行分組篩選。若將 <code>AVG(salary)</code> 寫入 WHERE 語法將直接報錯。"),

        ("在 SQL 聚集函數運算中，若表格 <code>Scores</code> 之 <code>score</code> 欄位包含數值：<code>100, 80, NULL, 60</code>，則執行 <code>SELECT COUNT(*), COUNT(score), AVG(score) FROM Scores;</code> 所獲得之計算結果分別為何？",
         "<code>COUNT(*) = 4</code>；<code>COUNT(score) = 3</code>；<code>AVG(score) = 80</code>",
         ["<code>COUNT(*) = 4</code>；<code>COUNT(score) = 3</code>；<code>AVG(score) = 80</code>",
          "<code>COUNT(*) = 4</code>；<code>COUNT(score) = 4</code>；<code>AVG(score) = 60</code>",
          "<code>COUNT(*) = 3</code>；<code>COUNT(score) = 3</code>；<code>AVG(score) = 80</code>",
          "<code>COUNT(*) = 4</code>；<code>COUNT(score) = 3</code>；<code>AVG(score) = NULL</code>"],
         "SQL 聚集函數對 NULL 之處理原則：1. <code>COUNT(*)</code>：統計「總列數」，包含任何含有 NULL 的列，故總共 4 列；2. <code>COUNT(column)</code>：統計該欄位中「非 NULL 的列數」，排除 NULL，故為 3；3. <code>AVG(column)</code>：計算平均值時「自動忽略 NULL 值」，分母為非 NULL 個數，即 $\\frac{100 + 80 + 60}{3} = \\frac{240}{3} = 80$。不會將 NULL 視為 0 去除以 4。"),

        ("在 SQL JOIN 運算中，若欲查詢「所有公務人員的姓名與其配發之公務筆電編號，且即使某同仁尚未配發任何筆電，該同仁姓名依然必須完整列出於報表中」，應採用何種 JOIN 語法？",
         "<code>LEFT OUTER JOIN</code>（左外部結合）",
         ["<code>LEFT OUTER JOIN</code>（左外部結合）",
          "<code>INNER JOIN</code>（內部結合）",
          "<code>CROSS JOIN</code>（交叉結合）",
          "<code>NATURAL JOIN</code>（自然結合）"],
         "JOIN 類型比較：1. <code>INNER JOIN</code>：僅保留兩表關聯欄位匹配成功之列，若同仁無筆電則直接被過濾排除；2. <code>LEFT OUTER JOIN</code>：以左表（員工表）為主體，保留左表「所有」列；若右表（筆電表）無對應紀錄，右表之欄位自動以 <code>NULL</code> 填補輸出，完全符合題意「尚未配發筆電之同仁依然完整列出」之公務報表需求。"),

        ("在 SQL 中合併兩個查詢結果集時，比較 <code>UNION</code> 與 <code>UNION ALL</code> 之運作機制與執行效能，下列何者正確？",
         "<code>UNION</code> 會自動過濾剔除重複資料列，底層需進行額外的排序或雜湊運算；<code>UNION ALL</code> 不檢查重複直接合併，執行效能遠高於 <code>UNION</code>",
         ["<code>UNION</code> 會自動過濾剔除重複資料列，底層需進行額外的排序或雜湊運算；<code>UNION ALL</code> 不檢查重複直接合併，執行效能遠高於 <code>UNION</code>",
          "<code>UNION ALL</code> 會自動加密資料，<code>UNION</code> 不會",
          "<code>UNION</code> 只能合併兩個表格，<code>UNION ALL</code> 可合併無限個",
          "兩者效能與結果完全相同"],
         "UNION vs UNION ALL 效能差異：若已確定兩個查詢的資料來源絕無重複（例如合併 114 年與 115 年的獨立公文歸檔歷史表），或業務上允許保留重複列，強烈推薦使用 <code>UNION ALL</code>。因為 <code>UNION</code> 為去除重複資料，必須將兩份龐大資料載入記憶體進行昂貴的 Sort / Hash Unique 去重運算，在大數據環境下會造成嚴重的 CPU 與暫存磁碟（TempDB）負擔。"),

        ("資料庫交易管理（Transaction Management）必須嚴格遵循之「ACID」四大特性，其中「確保交易包含的所有資料庫操作要麼全部成功執行永久生效，要麼完全失敗回滾（All-or-Nothing）」之特性為？",
         "不可分割性 / 原子性（Atomicity）",
         ["不可分割性 / 原子性（Atomicity）",
          "一致性（Consistency）",
          "隔離性（Isolation）",
          "持久性（Durability）"],
         "ACID 四大特性解析：1. 原子性（Atomicity）：交易為最小工作單元，要麼全做，要麼全不做（All or Nothing）。如銀行轉帳，扣款與入帳必須同時成功，若入帳中途斷電，系統藉由 Undo Log 自動 Rollback 回滾扣款；2. 一致性（Consistency）：交易執行前後資料庫必須滿足所有預設完整性限制；3. 隔離性（Isolation）：多個並行交易互不干擾；4. 持久性（Durability）：交易一旦 COMMIT，其修改永久保存在磁碟，即使隨後立即停電資料亦不遺失。"),

        ("在多人並行存取資料庫時，若交易 $T_1$ 修改了某筆資料但尚未執行 COMMIT，此時並行的交易 $T_2$ 卻讀取了該筆未經確認的髒資料，隨後 $T_1$ 發生錯誤執行 ROLLBACK，此並行衝突現象稱為？",
         "髒讀（Dirty Read）",
         ["髒讀（Dirty Read）",
          "不可重複讀（Non-Repeatable Read）",
          "幻讀（Phantom Read）",
          "遺失更新（Lost Update）"],
         "資料庫並行讀取衝突：1. 髒讀（Dirty Read）：讀到了別人尚未 Commit 且隨後被 Rollback 的幽靈資料；2. 不可重複讀（Non-Repeatable Read）：$T_1$ 在同一個交易內讀取兩次同一筆資料，但在兩次讀取之間 $T_2$ 執行了 UPDATE 並 COMMIT，導致 $T_1$ 兩次讀到的數值不同；3. 幻讀（Phantom Read）：$T_1$ 依條件查詢一批範圍資料（如薪水 > 50000），$T_2$ 中途 INSERT 了一筆新員工並 COMMIT，導致 $T_1$ 再次查詢時憑空多出一列資料。"),

        ("SQL-92 標準定義了四種交易隔離等級（Transaction Isolation Levels），其中「能完全杜絕髒讀、不可重複讀與幻讀，達到最高安全性但並行效能最低」之隔離等級為？",
         "可序列化（Serializable）",
         ["可序列化（Serializable）",
          "可重複讀（Repeatable Read）",
          "讀取已認可（Read Committed）",
          "讀取未認可（Read Uncommitted）"],
         "交易隔離等級對照（安全性由低到高）：1. Read Uncommitted（最低）：容許髒讀、不可重複讀、幻讀；2. Read Committed（多數資料庫預設，如 Oracle/PostgreSQL）：防髒讀，但容許不可重複讀與幻讀；3. Repeatable Read（MySQL InnoDB 預設）：防髒讀與不可重複讀，結合 MVCC 與 Next-Key Lock 可基本防幻讀；4. Serializable（最高）：強行將所有並行交易序列化依序排隊執行，徹底杜絕所有並行衝突，但鎖定競爭劇烈、吞吐量暴跌。"),

        ("在資料庫並行鎖定機制中，「共享鎖（Shared Lock / S 鎖）」與「互斥鎖（Exclusive Lock / X 鎖）」之相容性規則何者完全正確？",
         "多個交易可以同時對同一筆資料持有「共享鎖（S 鎖）」進行讀取；但任一交易若欲持有「互斥鎖（X 鎖）」進行修改，其他任何交易皆不得持有任何 S 鎖或 X 鎖",
         ["多個交易可以同時對同一筆資料持有「共享鎖（S 鎖）」進行讀取；但任一交易若欲持有「互斥鎖（X 鎖）」進行修改，其他任何交易皆不得持有任何 S 鎖或 X 鎖",
          "互斥鎖與互斥鎖相容，兩者可同時修改同一筆資料",
          "共享鎖不能與任何鎖共存",
          "資料庫永遠只能使用單一鎖定模式"],
         "鎖定相容性矩陣（Lock Compatibility）：\n- S 鎖（讀鎖）：允許多個交易同時讀取同一列（S 與 S 相容）；\n- X 鎖（寫鎖）：當交易進行 INSERT/UPDATE/DELETE 時申請 X 鎖。X 鎖與任何鎖（無論 S 還是 X）皆「完全互斥不相容」。若已有交易持有 S 鎖，申請 X 鎖者必須阻塞等待所有 S 鎖釋放；反之若已有交易持有 X 鎖，任何申請 S 鎖或 X 鎖的其他交易均必須排隊等待。"),

        ("為保證並行排程達到「可序列化（Serializability）」，資料庫交易普遍遵循「兩階段鎖定協定（2PL, Two-Phase Locking）」，其兩階段之規則限制為？",
         "交易分為擴展階段（Growing Phase，只能申請鎖定，不能釋放鎖定）與收縮階段（Shrinking Phase，只能釋放鎖定，不能再申請新鎖）",
         ["交易分為擴展階段（Growing Phase，只能申請鎖定，不能釋放鎖定）與收縮階段（Shrinking Phase，只能釋放鎖定，不能再申請新鎖）",
          "先由管理員手動核准鎖定，再由系統自動扣款",
          "白天只能加共享鎖，夜間才能加互斥鎖",
          "每隔兩秒鐘強制釋放一次所有鎖定"],
         "兩階段鎖定協定（2PL）：1. 成長階段（Growing Phase）：交易可以獲取任何所需的鎖，但不能釋放任何鎖；2. 萎縮階段（Shrinking Phase）：一旦交易釋放了第一個鎖，即進入收縮期，從此之後「絕對不能再申請任何新的鎖」。數學證明遵循 2PL 協定可保證衝突可序列化（Conflict Serializability），但 2PL「無法防止死結（Deadlock）」，仍需依賴死結偵測或預防機制。"),

        ("在主流關聯式資料庫（如 MySQL InnoDB、Oracle、PostgreSQL）中，實體索引普遍採用「B+ 樹（B+ Tree）」而非二元搜尋樹或一般 B 樹，其最關鍵之技術優勢為？",
         "所有實際資料列或主鍵指標均集中存放在「最底層葉節點（Leaf Nodes）」，且葉節點之間以雙向鏈結串列相連，支援極高效率之範圍查詢（Range Query）與循序掃描",
         ["所有實際資料列或主鍵指標均集中存放在「最底層葉節點（Leaf Nodes）」，且葉節點之間以雙向鏈結串列相連，支援極高效率之範圍查詢（Range Query）與循序掃描",
          "B+ 樹的節點只能儲存偶數，無法儲存奇數",
          "B+ 樹只佔用 1 個 Byte 的記憶體空間",
          "B+ 樹能自動將資料庫密碼解密"],
         "B+ Tree 索引核心架構優勢：1. 非葉節點（內部節點）僅儲存搜尋鍵（Key）而不儲存資料列資料，因此單一 16KB 磁碟分頁能塞入更多路由鍵，樹高極低（通常 3~4 層即可支撐千萬筆資料），磁碟 I/O 次數極少；2. 所有資料純粹位於葉節點，查詢穩定度極高；3. 葉節點以雙向指標串連，遇到 <code>WHERE age BETWEEN 20 AND 30</code> 時，只需搜尋到 20 的節點後沿著鏈結串列向後循序讀取，無需在樹中上下折返。"),

        ("在資料庫索引設計中，比較「聚集索引（Clustered Index）」與「非聚集索引（Non-Clustered Index / 二級索引）」之實體結構差異，下列何者完全正確？",
         "聚集索引之葉節點即為「表格實體資料列本身」，資料在硬碟中的實體物理存放順序與該索引順序完全一致，故每個表格「最多只能有一個聚集索引」",
         ["聚集索引之葉節點即為「表格實體資料列本身」，資料在硬碟中的實體物理存放順序與該索引順序完全一致，故每個表格「最多只能有一個聚集索引」",
          "每個表格可以建立多達 50 個聚集索引",
          "非聚集索引的查詢速度永遠比聚集索引快 100 倍",
          "非聚集索引不佔用任何磁碟儲存空間"],
         "聚集 vs 非聚集索引：1. 聚集索引（Clustered Index）：如同字典的正文，按拼音字母由 A 到 Z 實體印刷。因為實體物理排列順序只有一種，每張表格「僅能有一個」聚集索引（通常預設為主鍵）。查詢範圍極快，無需回表；2. 非聚集索引（Secondary Index）：如同字典最後面的部首檢字表。葉節點存放的是索引鍵與「對應的聚集索引鍵或列指標（RID）」，查詢非索引涵蓋欄位時需額外執行一次「回表查詢（Bookmark Lookup）」。"),

        ("在關聯式資料庫中建立「視圖（View / 檢視表）」，下列何者「不是」使用視圖所帶來之主要優勢？",
         "在硬碟中額外建立完整的資料實體複本，大幅提高資料庫寫入效能",
         ["在硬碟中額外建立完整的資料實體複本，大幅提高資料庫寫入效能",
          "簡化複雜的跨多表關聯（JOIN）與聚集查詢，提高使用者開發效率",
          "提供欄位級之資料安全隔離，限制使用者僅能存取非敏感性欄位",
          "提供邏輯資料獨立性，底層表格變更時不影響外部應用程式查詢介面"],
         "視圖（View）本質與特性：View 是「虛擬表格（Virtual Table）」，其定義僅是一段已儲存的 SQL SELECT 查詢敘述。一般視圖在硬碟中「完全不儲存任何實體資料列」（除非是經過特殊設計的具化視圖 Materialized View）。使用視圖不但不會提高寫入效能，反而因基底表格寫入時的約束檢驗可能略微增加負擔。選項一完全背離 View 的虛擬特性。"),

        ("在關聯式代數（Relational Algebra）之基本運算子中，用以「依據指定條件篩選出符合條件之『資料列（Tuples / Rows）』」之運算符號為？",
         "選擇（Selection，以希臘字母 $\\sigma$ 表示）",
         ["選擇（Selection，以希臘字母 $\\sigma$ 表示）",
          "投影（Projection，以希臘字母 $\\pi$ 表示）",
          "聯集（Union，以符號 $\\cup$ 表示）",
          "笛卡兒積（Cartesian Product，以符號 $\\times$ 表示）"],
         "關聯式代數基礎運算子：1. 選擇（Selection, $\\sigma_{condition}(R)$）：水平篩選出滿足條件的「列（Rows）」，對應 SQL 之 <code>WHERE</code> 子句；2. 投影（Projection, $\\pi_{attributes}(R)$）：垂直選取特定的「欄位（Columns）」，對應 SQL 之 <code>SELECT col1, col2</code>；3. 笛卡兒積（Cartesian Product, $R \\times S$）：兩表所有列兩兩配對組合；4. 自然結合（Natural Join, $R \\bowtie S$）。"),

        ("在分散式系統與大數據資料庫理論中，「CAP 定理（Brewer's Theorem）」明確指出在面對網路分區（Network Partition）時，任何分散式資料存儲系統最多只能同時滿足下列哪兩項特性？",
         "一致性（Consistency）與可用性（Availability）",
         ["一致性（Consistency）與可用性（Availability）",
          "相容性（Compatibility）與即時性（Agility）",
          "機密性（Confidentiality）與不可否認性（Non-repudiation）",
          "可攜性（Portability）與可維護性（Maintainability）"],
         "CAP 定理核心思維：分散式系統中三大特性：1. C（Consistency 一致性）：所有節點在同一時間看到完全相同的最新資料；2. A（Availability 可用性）：每次請求都能收到非錯誤回應（不保證最新）；3. P（Partition Tolerance 分區容忍性）：網路節點發生封包中斷或延遲時系統仍能運作。在現實分散式網路中，P 是必然客觀存在的物理條件，因此架構師只能在 CP（犧牲可用性，保證強一致）或 AP（犧牲強一致性，保證高可用與最終一致性 Eventual Consistency）之間二選一。"),

        ("在 NoSQL 資料庫類型分類中，常被用於政府快取層（Cache）與使用者工作階段管理（Session Store），支援記憶體高速讀寫之代表性資料庫為？",
         "Redis（鍵值型資料庫，Key-Value Store）",
         ["Redis（鍵值型資料庫，Key-Value Store）",
          "PostgreSQL（關聯式資料庫）",
          "Neo4j（圖形資料庫）",
          "Apache Cassandra（寬欄位資料庫）"],
         "NoSQL 四大分類與典型代表：1. Key-Value（鍵值型）：Redis, Memcached。資料結構駐留於記憶體，讀寫吞吐達十萬 QPS，極適合快取、排行榜、Session 存放；2. Document（文件型）：MongoDB, CouchDB。以 JSON/BSON 格式存放無綱要（Schema-less）資料；3. Column-Family（寬欄位型）：Cassandra, HBase。適合海量分散式時間序列日誌大數據；4. Graph（圖形資料庫）：Neo4j。適合社群網路好友關係、反洗錢金流關聯分析。"),

        ("在資料庫查詢最佳化（Query Optimization）實務中，下列哪一種 SQL 撰寫方式「最容易導致既有索引失效」，進而引發全表掃描（Full Table Scan）拖垮資料庫效能？",
         "在 <code>WHERE</code> 子句中對有建立索引的欄位進行運算或函式轉換（如 <code>WHERE YEAR(create_date) = 2026</code>）",
         ["在 <code>WHERE</code> 子句中對有建立索引的欄位進行運算或函式轉換（如 <code>WHERE YEAR(create_date) = 2026</code>）",
          "使用主鍵精確查詢單筆資料（如 <code>WHERE id = 1001</code>）",
          "使用 <code>WHERE status IN ('A', 'B')</code> 查詢",
          "使用 <code>INNER JOIN</code> 連接兩張具備外鍵之表格"],
         "索引失效之常見盲點：B+ Tree 索引樹上儲存的是「原始未加工的欄位值」。若在 SQL 條件中對欄位套用函式（如 <code>WHERE YEAR(create_date) = 2026</code>、<code>WHERE SUBSTRING(name, 1, 1) = '陳'</code> 或 <code>WHERE salary * 12 &gt; 600000</code>），資料庫無法直接在 B+ 樹上對照查找，被迫逐列取出計算，導致索引失效而引發 Full Table Scan。正確寫法應改寫為範圍查詢：<code>WHERE create_date &gt;= '2026-01-01' AND create_date &lt; '2027-01-01'</code>。"),

        ("公務機關資訊人員在進行資料庫效能調優時，常在 SQL 查詢語句前加上何種關鍵字，以檢視資料庫最佳化工具所產生的「執行計畫（Execution Plan）」，確認是否成功走索引（Index Range Scan）或全表掃描（Seq Scan）？",
         "<code>EXPLAIN</code>（或 <code>EXPLAIN ANALYZE</code>）",
         ["<code>EXPLAIN</code>（或 <code>EXPLAIN ANALYZE</code>）", "<code>HELP</code>", "<code>DEBUG</code>", "<code>CHECK</code>"],
         "<code>EXPLAIN</code> 指令功能：<code>EXPLAIN</code>（在 MySQL/PostgreSQL/Oracle 中）是 SQL 效能診斷第一利器。輸出包含：存取類型（type: const/ref/range/ALL）、可能使用的索引（possible_keys）、實際選用的索引（key）、預估掃描列數（rows）與額外過濾資訊（Extra: Using index / Using filesort / Using temporary）。網管與工程師藉此精準判斷是否有不必要的暫存表建立或全表掃描。")
    ]
