# -*- coding: utf-8 -*-
"""
Generator for 03-local3/bank.html - Part 2 (81 questions)
Topics: 地方政府大數據分析、空間地理資訊 (GIS) 與分散式資料庫實務
"""

def get_local3_part2_questions():
    qs = []

    # Dataset 1: GIS 空間資訊系統、PostGIS 空間函數、OGC 標準與國土測繪圖資套疊 (27 questions)
    gis_spatial_data = [
        ("某縣市都市發展局在 WebGIS 系統中，欲以空間資料庫查詢「位於特定淹水潛勢多邊形區域（Flood Polygon）內的所有合法建物點位（Building Points）」，PostGIS 中最標準且能善用空間索引（GiST）之 SQL 函數為？",
         "<code>ST_Contains(flood_geom, building_geom)</code> 或 <code>ST_Within(building_geom, flood_geom)</code>",
         ["<code>ST_Contains(flood_geom, building_geom)</code> 或 <code>ST_Within(building_geom, flood_geom)</code>",
          "<code>ST_Distance(flood_geom, building_geom) = 0</code>",
          "<code>ST_Union(flood_geom, building_geom)</code>",
          "<code>ST_Buffer(flood_geom, 100)</code>"],
         "PostGIS 空間拓撲關係查詢：<code>ST_Contains(A, B)</code> 回傳 true 當且僅當幾何物件 B 完全落在幾何物件 A 之內部（且兩者內部交集非空）。此類空間述詞（Spatial Predicates）完全支援 PostGIS 的 GiST（R-Tree）空間索引，資料庫優化器會先比對邊界框（Bounding Box, <code>&&</code> 運算子）快速過濾候選幾何，再計算精確拓撲，大幅優化百萬筆建物空間過濾。"),

        ("地方政府地政局建置「全縣市地籍圖資查詢系統」，當多個局處需要將「都市計畫土地使用分區圖」與「地籍宗地圖」進行空間套疊以釐清特定地號是否屬於公共設施保留地時，空間運算所依賴的拓撲幾何運算為？",
         "空間交集（Spatial Intersection，<code>ST_Intersection</code>）與空間相交判斷（<code>ST_Intersects</code>）",
         ["空間交集（Spatial Intersection，<code>ST_Intersection</code>）與空間相交判斷（<code>ST_Intersects</code>）",
          "空間差集（<code>ST_Difference</code>）完全排除所有相交部分",
          "空間外積運算（Cross Product）將所有坐標軸反轉",
          "空間平移運算（<code>ST_Translate</code>）將地圖向右位移 50 公里"],
         "空間圖資套疊（Overlay Analysis）：都市計畫與地籍套疊是地政與建管之核心業務。透過 <code>ST_Intersects(A, B)</code> 先行判定地籍宗地是否觸碰分區邊界，再透過 <code>ST_Intersection(A, B)</code> 計算幾何交集多邊形以精確得出該地號座落於「公共設施保留地」之重疊面積與形狀。"),

        ("某市水利局欲在河川兩岸繪製「河道中心線兩側各 20 公尺之防汛管制保護區」，在空間資訊處理中，產生此保護區多邊形之標準 GIS 運算為何？",
         "環域分析（Buffer Analysis，<code>ST_Buffer(centerline, 20)</code>）",
         ["環域分析（Buffer Analysis，<code>ST_Buffer(centerline, 20)</code>）",
          "凸包分析（Convex Hull，<code>ST_ConvexHull</code>）",
          "簡化分析（Simplification，<code>ST_Simplify</code>）",
          "質心計算（Centroid，<code>ST_Centroid</code>）"],
         "空間環域分析（Buffer Analysis）：環域運算係以幾何實體（點、線、多邊形）為基準，向外（或向內）延伸特定指定距離所形成之影響範圍多邊形。防汛管制區、噪音管制區、學校周邊禁設電子遊戲場（如周邊 200 公尺環域）皆為典型之 Buffer 應用。"),

        ("地方政府空間資訊系統在提供跨平台地圖圖磚服務時，開放地理空間協會（OGC）制定了多種標準協定。下列何者專門用於提供「預先切片完成之靜態快取地圖圖磚」，具備極高效能？",
         "WMTS（Web Map Tile Service）標準",
         ["WMTS（Web Map Tile Service）標準",
          "WFS（Web Feature Service）標準",
          "WCS（Web Coverage Service）標準",
          "CSW（Catalog Service for the Web）標準"],
         "OGC 地圖服務標準體系：WMS（Web Map Service）係每次由伺服器動態渲染整張圖片，並發效能低；WFS 回傳向量向量要素（GML/GeoJSON）原始資料，傳輸量大。WMTS（Web Map Tile Service）將世界地圖預先依照金字塔模型切片為 256x256 靜態圖磚（PNG/JPEG），支援 CDN 邊緣快取，能承受千萬級並發瀏覽。"),

        ("某縣市交通局欲查詢「離特定交通事故發生地點最近的 3 座路口監視器（CCTV）」，若資料庫包含數萬支監視器坐標，PostGIS 中結合空間索引求取 K-最近鄰（K-Nearest Neighbors, KNN）最有效率之寫法為？",
         "使用 <code><-></code> 幾何距離運算子結合 <code>ORDER BY geom <-> point LIMIT 3</code>",
         ["使用 <code><-></code> 幾何距離運算子結合 <code>ORDER BY geom <-> point LIMIT 3</code>",
          "對全表計算 <code>ST_Distance</code> 後在前端 JavaScript 進行冒泡排序",
          "使用二元搜尋樹在經度維度排序，完全忽略緯度",
          "隨機選取 3 筆資料回傳"],
         "PostGIS KNN 空間索引加速：傳統 <code>ORDER BY ST_Distance(geom, point) LIMIT K</code> 會導致全表掃描（Seq Scan）計算每筆實體距離。PostGIS 提供的 <code><-></code> 運算子直接在 GiST R-Tree 空間索引樹上執行優先佇列分支限界法（Branch and Bound），僅需遍歷最鄰近之索引外框即可返回前 K 個最近鄰，查詢速度從數百毫秒縮短至數毫秒。"),

        ("在台灣地方政府地籍測量與工程圖資中，最常使用的二度分帶高斯-克呂格投影坐標系統為何？其對應之 EPSG 空間參考識別碼（SRID）為何？",
         "TWD97 121 分帶（台灣本島常用），對應 EPSG:3826",
         ["TWD97 121 分帶（台灣本島常用），對應 EPSG:3826",
          "WGS84 經緯度球體坐標，對應 EPSG:4326 且單位為公尺",
          "Web 墨卡托投影（Web Mercator），對應 EPSG:3857 且無任何面積變形",
          "TWD67 澎湖分帶，對應 EPSG:9999"],
         "台灣空間參考系統（CRS / SRID）標準：台灣本島工程、地籍與都市計畫圖資標準為 TWD97 二度分帶（中央經線 121 度），坐標單位為公尺（公制），EPSG 代碼為 3826（澎湖地區為 119 分帶，EPSG:3824）。全球 GPS 衛星定位為 WGS84 經緯度（EPSG:4326，單位為度）；Google Maps / OSM 等 WebGIS 底圖則為 Web Mercator（EPSG:3857）。跨系統套疊必須以 <code>ST_Transform()</code> 正確投影轉換。"),

        ("某市消防局救災指揮系統需規劃消防車到達火災現場的最短路徑。若路網資料已建立於 PostgreSQL/PostGIS 中，最適合用來進行「路網拓撲最短路徑與等時圈分析」之專用開源套件為？",
         "pgRouting，提供 Dijkstra、A*、Turn Restriction Shortest Path 等多種路網演算法",
         ["pgRouting，提供 Dijkstra、A*、Turn Restriction Shortest Path 等多種路網演算法",
          "NumPy，僅支援矩陣乘法運算",
          "Apache Lucene，僅支援純文字全文檢索",
          "SQLite，不支援任何網路功能"],
         "pgRouting 空間拓撲路網分析：pgRouting 是 PostGIS 的官方延伸套件，專責於有向加權圖（Directed Weighted Graph）空間路網運算。它支援轉向限制（Turn Restrictions）、單行道（One-way）、速限加權（Speed Limit Cost）及坡度懲罰，能精確求解消防救災在真實城市道路上的最短行車時間路徑。"),

        ("地方政府地政事務所管理宗地地籍資料時，宗地與宗地之間在法理上「不得有重疊（Overlap）或間隙（Gap）」。在 GIS 空間拓撲規則（Topology Rules）中，此項約束稱之為？",
         "面要素不得重疊（Must Not Overlap）且面要素之間不得有縫隙（Must Not Have Gaps）",
         ["面要素不得重疊（Must Not Overlap）且面要素之間不得有縫隙（Must Not Have Gaps）",
          "所有宗地面積必須完全相等",
          "宗地必須全部為標準正方形且邊長固定",
          "宗地邊界線必須為完全封閉之同心圓"],
         "地籍空間拓撲完整性約束（Topological Integrity）：地籍圖資為土地產權之法定憑證。相鄰地號宗地之間必須具備嚴密拓撲一致性：公有地與私有地面多邊形不得相互侵入重疊（避免一地二賣），相鄰多邊形共享邊之節點必須完全吻合（Snapping），且全行政區土地應無縫鋪滿（Tessellation），防止產生無主隙地。"),

        ("某縣市工務局利用無人機（UAV）拍攝市區道路以進行路面破損巡查。數百張空拍重疊照片經由何種電腦視覺技術可重構出地面的「數值高程模型（DEM）」與「正射影像（Orthomosaic）」？",
         "運動推斷結構技術（SfM, Structure from Motion）結合多視角立體視覺（MVS）",
         ["運動推斷結構技術（SfM, Structure from Motion）結合多視角立體視覺（MVS）",
          "單純以 Photoshop 進行圖片亮度與對比度自動調整",
          "將照片直接轉換為灰階點陣圖以節省儲存空間",
          "利用 JPEG 壓縮演算法丟棄高頻像素"],
         "無人機空拍航測與 SfM 原理：無人機航拍藉由相鄰相片間 70%~80% 之航向與旁向重疊率，利用 SfM 演算法比對各視角影像中之特徵點（SIFT/ORB），反算相機拍攝瞬間之外方位元素（攝影位置與姿態）與地表特徵三維坐標，生成緻密點雲（Dense Point Cloud），進而產製正射影像圖與高程模型。"),

        ("在空間資料庫中，為數百萬筆點位或多邊形資料建立空間索引時，最普遍採用且效能優異的樹狀空間索引結構為？",
         "R-Tree（R 樹）及其變形（如 R* 樹或 GiST 實作之 R-Tree）",
         ["R-Tree（R 樹）及其變形（如 R* 樹或 GiST 實作之 R-Tree）",
          "紅黑樹（Red-Black Tree）僅依據單一緯度數值排序",
          "B 樹（B-Tree）僅依據經度大小排序",
          "二元搜尋樹（BST）且完全不平衡"],
         "R-Tree 空間索引原理：傳統 B-Tree 只能對單一維度的純量數據（如整數、時間）建立一維全序索引，無法直接處理二維/三維空間資料。R-Tree 透過階層式的「最小外接矩形（MBR, Minimum Bounding Box）」將空間實體分群包覆，當進行範圍查詢或相交查詢時，可先過濾不相交的 MBR 子樹，大幅降低幾何計算成本。"),

        ("某市環保局欲查詢「全市民眾檢舉工廠空污案件中，距離任何合法工業區邊界超過 500 公尺之異常違規件數」，PostGIS 中最適當之空間過濾條件為？",
         "<code>NOT ST_DWithin(complaint_geom, industrial_zone_geom, 500)</code>",
         ["<code>NOT ST_DWithin(complaint_geom, industrial_zone_geom, 500)</code>",
          "<code>ST_Area(complaint_geom) > 500</code>",
          "<code>ST_Length(complaint_geom) = 500</code>",
          "<code>ST_Perimeter(complaint_geom) < 500</code>"],
         "PostGIS 空間距離條件運算：<code>ST_DWithin(geom1, geom2, distance)</code> 能在指定距離閥值內判斷兩幾何體是否相鄰，且能高效使用空間索引加速過濾。相較於 <code>ST_Distance() > 500</code>，<code>ST_DWithin</code> 會先利用 MBR 建立外擴矩形縮小候選集，效能顯著優於暴力計算全表實體歐幾里得距離。"),

        ("地方政府建置「土石流防災警戒監控系統」，整合全縣市數值地形模型（DTM）。在水文分析中，欲從高程資料自動推導出地表雨水流動方向與匯流累積量，第一步不可或缺之預處理為？",
         "窪地填平處理（Sink Filling / Depressional Storage Filling），消除微地形雜訊以確保水流連續性",
         ["窪地填平處理（Sink Filling / Depressional Storage Filling），消除微地形雜訊以確保水流連續性",
          "將所有山脈高程直接除以二以降低坡度",
          "強制將所有河流坐標平移至海平面以下 100 公尺",
          "隨機刪除 50% 的網格數據以減少檔案大小"],
         "水文分析之填平窪地（Sink Fill）：原始 DTM/DEM 網格常因量測誤差或微地形存在局部低窪點（Sinks）。在執行 D8 水流方向（Flow Direction）演算法時，水流一旦流入未填平的窪地便會中斷而無法流向出水口（Outlet）。因此必須先執行 Fill 演算法填平非真實地表蓄水池，始能正確計算地表逕流與集水區邊界。"),

        ("某市農業局調查特定山坡地是否涉嫌違法超限利用，將農林航測遙測影像計算「常態化差值植生指標（NDVI）」。NDVI 數值計算公式所依賴之光譜波段組合為何？",
         "近紅外光（NIR）與紅光（Red）波段，公式為 (NIR - Red) / (NIR + Red)",
         ["近紅外光（NIR）與紅光（Red）波段，公式為 (NIR - Red) / (NIR + Red)",
          "藍光（Blue）與綠光（Green）波段相加",
          "熱紅外光除以紫外線波段",
          "可見光紅綠藍三原色之平均值"],
         "遙測植生指標 NDVI 原理：健康綠色植物的葉綠素強烈吸收可見光紅光（Red，約 0.66 μm）進行光合作用，同時植物葉肉海綿組織的多重反射使得近紅外光（NIR，約 0.86 μm）具有極高反射率。NDVI 介於 -1 到 +1 之間，茂密健康植被 NDVI 接近 0.6~0.9，裸地或非植被接近 0 或負值，是山坡地開墾監測利器。"),

        ("地方政府都市更新處在計算基地容積獎勵時，需取得基地宗地多邊形之幾何中心以進行建築線標註，PostGIS 中計算幾何實體面積中心點之函數為？",
         "<code>ST_Centroid(geom)</code>",
         ["<code>ST_Centroid(geom)</code>",
          "<code>ST_StartPoint(geom)</code>",
          "<code>ST_EndPoint(geom)</code>",
          "<code>ST_Envelope(geom)</code>"],
         "PostGIS 質心計算：<code>ST_Centroid()</code> 依據幾何實體計算質量幾何中心（Center of mass）。注意若幾何為 C 字型或凹多邊形，質心可能落在多邊形外部；若需保證回傳點必定落在多邊形內部，可改用 <code>ST_PointOnSurface()</code>。"),

        ("某縣市地政局進行舊地籍圖數位化數化作業時，發現掃描圖檔存在非線性伸縮變形。為將圖紙坐標校正貼合至 TWD97 國家實體坐標系統，最適當之坐標轉換模型為？",
         "仿射轉換（Affine Transformation）或多項式幾何校正（Polynomial Rectification），利用地面控制點（GCP）求解變換矩陣",
         ["仿射轉換（Affine Transformation）或多項式幾何校正（Polynomial Rectification），利用地面控制點（GCP）求解變換矩陣",
          "直接手動拖曳放大縮小圖片，完全不比對任何控制點",
          "將圖片隨機旋轉 180 度後直接入庫",
          "強制忽略所有變形，直接以未校正坐標登記產權"],
         "地籍圖幾何校正（Georeferencing）：紙圖經年受溫濕度影響會產生各向異性伸縮與扭曲。透過量測已知地表控制點（Ground Control Points, GCP），利用一階仿射變換（平移、旋轉、尺度縮放、剪切）或高階多項式迴歸求解最小平方誤差矩陣，完成幾何糾正與坐標配準（Registration）。"),

        ("在 WebGIS 地圖圖資展示中，相較於傳統光柵點陣圖磚（Raster Tiles，如 PNG），現代地圖服務普遍轉向「向量圖磚（Vector Tiles，如 Mapbox Vector Tiles - MVT）」，向量圖磚的核心優勢為何？",
         "客戶端可動態套用樣式風格（Style）、任意旋轉地圖文字保持清晰、支援互動點擊要素，且傳輸體積大幅縮小",
         ["客戶端可動態套用樣式風格（Style）、任意旋轉地圖文字保持清晰、支援互動點擊要素，且傳輸體積大幅縮小",
          "伺服器端永遠不需要建立任何空間索引",
          "完全不支援任何網頁瀏覽器，只能在專屬主機螢幕觀看",
          "圖資將永久固定為黑白色彩，無法顯示彩色"],
         "向量圖磚（Vector Tiles）優勢：Raster Tile 是在後端渲染為像素圖片，前端無法修改標籤字型、道路顏色或進行屬性點擊；Vector Tile 將向量幾何點線面經過壓縮（Protobuf 編碼）傳送至前端瀏覽器，由客戶端 WebGL 即時著色渲染，可動態換膚（深色模式）、無損縮放與高解析螢幕自適應，節省頻寬並提升互動性。"),

        ("某市水利局為預警低窪地下道淹水，建置即時 3D 智慧防汛數位分生（Digital Twin）模型。在 WebGIS 中展示全縣市三維建物白模與地表 3D 模型時，最主流且獲 OGC 認可之 3D 串流格式為？",
         "3D Tiles（由 Cesium 提出並成為 OGC 社群標準）",
         ["3D Tiles（由 Cesium 提出並成為 OGC 社群標準）",
          "純文字 TXT 檔記錄三維點位",
          "傳統點陣圖 BMP 格式",
          "微軟 Excel 檔案"],
         "3D 地理空間串流標準 3D Tiles：海量 3D 建築模型（BIM）、傾斜攝影點雲（Point Cloud）若一次性下載會癱瘓網路與瀏覽器記憶體。OGC 3D Tiles 採用空間階層包圍盒（Bounding Volume Hierarchy, BVH）金字塔架構，依相機視距動態 LOD（Level of Detail）非同步載入目前可見的細節，實現大規模三維場景流暢渲染。"),

        ("地方政府地政空間資料庫儲存地籍宗地多邊形時，幾何欄位宣告為 <code>POLYGON</code>。依據 OGC Simple Features Specification 標準，一個合法的有效多邊形（Valid Polygon）必須滿足何項條件？",
         "外環必須封閉（起點等於終點）、邊線不可自我相交（Self-intersecting），且內部洞（Holes）必須嚴格落在外環之內",
         ["外環必須封閉（起點等於終點）、邊線不可自我相交（Self-intersecting），且內部洞（Holes）必須嚴格落在外環之內",
          "多邊形內角總和必須嚴格等於 180 度",
          "所有邊長必須為偶數公尺",
          "頂點數目不可超過 3 個"],
         "空間幾何有效性（Spatial Validity）：在 GIS 空間運算中，若多邊形成為自我相交的「8 字形（Bowtie）」或邊界重疊，會導致 <code>ST_Area</code> 計算錯誤或空間拓撲運算崩潰。PostGIS 提供 <code>ST_IsValid(geom)</code> 檢查合法性，並可透過 <code>ST_MakeValid(geom)</code> 自動將違規多邊形修復或拆分為 MultiPolygon。"),

        ("某縣市衛生局在登革熱疫情期間，需統計「各里確診案例之空間空間群聚程度（Spatial Clustering）」，以找出疫情熱區。空間統計學中最經典用來評估全域空間自我相關性（Spatial Autocorrelation）之指標為？",
         "莫蘭指數（Moran's I）",
         ["莫蘭指數（Moran's I）",
          "皮爾森相關係數（Pearson Correlation）僅考慮非空間屬性",
          "費雪精確檢定（Fisher's Exact Test）",
          "學生 t 檢定（Student's t-test）"],
         "空間自我相關性與 Moran's I：空間統計核心公理為「第一地理定律（Tobler's First Law of Geography）：任何事物都相關，近處的事物比遠處更相關」。Moran's I 介於 -1 到 +1 之間：正值表示空間正相關（高值與高值群聚，如疫情群聚熱區），0 表示隨機分佈，負值表示空間負相關（棋盤狀分散），為公衛與犯罪熱區分析標準工具。"),

        ("某市政府地政局提供民眾透過地號查詢土地公告現值，系統後端資料庫以地號（段代碼 + 地號母子號）為主鍵建置 B+ 樹索引。當民眾查詢「中正段一小段 100 號」時，B+ 樹索引查找的時間複雜度為？",
         "O(log N)",
         ["O(log N)",
          "O(N^2)",
          "O(1) 且完全不受樹高影響",
          "O(N!)"],
         "B+ 樹索引時間複雜度：B+ 樹為多路平衡搜尋樹，所有資料紀錄均存放於葉節點，非葉節點僅儲存鍵值作為路由導航。對於包含 N 個節點的資料表，B+ 樹高度通常僅為 3~4 層，等值或範圍查詢皆保證在 O(log N) 次磁碟 I/O 內定位資料，具備極度穩定的高效能表現。"),

        ("地方政府「1999 市民派工系統」需將市民陳情事件地址文字（如「台北市信義區市府路 1 號」）轉換為數值經緯度坐標（如 121.5654, 25.0375），此項技術服務稱之為？",
         "門牌地址地理編碼（Geocoding）",
         ["門牌地址地理編碼（Geocoding）",
          "反向地理編碼（Reverse Geocoding）",
          "地圖投影變換（Map Projection）",
          "光學字元辨識（OCR）"],
         "地理編碼（Geocoding）機制：Geocoding 係將非結構化之文字門牌地址或地名，透過文字正規化、斷詞、比對門牌號碼資料庫或道路路段線性內插（Linear Referencing/Interpolation），解析為精確之空間幾何點位坐標。反向地理編碼（Reverse Geocoding）則是將經緯度反查為門牌地址。"),

        ("某市交通局分析公車行駛軌跡大數據，需將公車 GPS 回傳之一連串帶有誤差的離散經緯度點位，校正並匹配至真實道路網中心線上。此項關鍵演算法稱為？",
         "地圖匹配（Map Matching）演算法（如基於隱藏馬可夫模型 HMM 之匹配）",
         ["地圖匹配（Map Matching）演算法（如基於隱藏馬可夫模型 HMM 之匹配）",
          "快速傅立葉轉換（FFT）",
          "主成分分析（PCA）",
          "二元搜尋法（Binary Search）"],
         "地圖匹配（Map Matching）技術：民用 GPS 存在 5~15 公尺定位誤差，在立體高架橋、多線道平行道路或高樓峽谷時常漂移至建築物或對向車道。Map Matching 演算法考量空間鄰近距離（幾何發射機率）與路網拓撲連通性（轉移機率），利用動態規劃（Viterbi 演算法）尋找全局最合理的真實行駛路線。"),

        ("地方政府觀光大數據分析中，欲從數百萬筆打卡坐標中自動發現任意形狀的「遊客高密度聚集核心區」，並過濾孤立噪音點，最適合之密度分群演算法為？",
         "DBSCAN（Density-Based Spatial Clustering of Applications with Noise）",
         ["DBSCAN（Density-Based Spatial Clustering of Applications with Noise）",
          "K-Means（K 平均演算法），只能發現凸狀球形分群且對噪音極為敏感",
          "線性迴歸分析（Linear Regression）",
          "決策樹分類（Decision Tree）"],
         "密度分群演算法 DBSCAN：K-Means 演算法必須預先指定群數 K，且預設各群為均勻球狀，容易將非凹多邊形旅遊景點切割錯誤。DBSCAN 依據核心點鄰域半徑（Eps）與最小點數（MinPts）成長分群，能靈活發現沿著街道或海岸線延伸的任意幾何形狀熱點，並將偏遠離島離群點標記為噪聲（Noise），極契合空間大數據。"),

        ("某縣市稅捐稽徵處在稽核「房屋稅籍資料庫」時，需比對房屋起造人、房屋建號、座落基地與所有權人身分證號。若欲在關聯式資料庫中消除傳遞相依（Transitive Dependency）以達到第三正規化（3NF），必須符合何項條件？",
         "已符合 2NF，且每個非主鍵屬性均不得傳遞相依於候選鍵（即不得存在 A → B 且 B → C，其中 A 為鍵，C 為非主屬性）",
         ["已符合 2NF，且每個非主鍵屬性均不得傳遞相依於候選鍵（即不得存在 A → B 且 B → C，其中 A 為鍵，C 為非主屬性）",
          "資料表中所有數值欄位必須自動相加為零",
          "資料表必須包含至少 100 個欄位與 1,000 萬筆紀錄",
          "所有外鍵必須強制設定為 NULL"],
         "資料庫正規化 3NF 原則：第一正規化（1NF）要求屬性具備原子性（Atomic Values）；第二正規化（2NF）消除部分相依（Partial Dependency，非主鍵屬性完全相依於複合主鍵）；第三正規化（3NF）則進一步消除傳遞相依（X → Y 且 Y → Z）。達到 3NF 能消除資料重複儲存，防範新增異常、修改異常與刪除異常。"),

        ("某市交通大數據平台維運 Apache Spark 叢集，每日處理數億筆悠遊卡/一卡通刷卡扣款紀錄。在執行大量資料關聯（JOIN）時，若發現少數熱門捷運站（如台北車站/高鐵站）的資料量遠高於其他站，導致特定 Spark Task 執行時間異常漫長甚至發生記憶體溢位（OOM），此現象稱為？如何解決？",
         "資料傾斜（Data Skew）；可透過加鹽（Salting，對熱點鍵加上隨機前綴）打散資料或使用廣播關聯（Broadcast Hash Join）",
         ["資料傾斜（Data Skew）；可透過加鹽（Salting，對熱點鍵加上隨機前綴）打散資料或使用廣播關聯（Broadcast Hash Join）",
          "死結現象；應更換機房電源線",
          "磁碟壞軌；應將 Spark 叢集關機報廢",
          "網路迴圈；應將所有交換器改為集線器（Hub）"],
         "Spark 分散式計算資料傾斜（Data Skew）：在 Shuffle 階段，相同 Key 的紀錄會被雜湊分派至同一個 Reducer Task。當特定 Key（如大站流量）佔據 50% 以上資料時，該單一節點負擔過重引發「木桶效應」拖慢整體作業。解法包含：(1) Salting：為熱點 Key 加上隨機後綴打散到不同分區，二次聚合再消除後綴；(2) 小表廣播（Broadcast Join）徹底避免 Shuffle。"),

        ("地方政府「市民大數據倉儲系統」在星狀綱要（Star Schema）設計中，紀錄市民各項繳費與洽公紀錄的資料表屬於下列何者？",
         "事實資料表（Fact Table）",
         ["事實資料表（Fact Table）",
          "維度資料表（Dimension Table）",
          "視圖（View）",
          "暫存暫存資料表（Scratch Table）"],
         "資料倉儲星狀綱要架構：星狀綱要為維度模型（Dimensional Modeling）核心。中間由「事實資料表（Fact Table）」組成，儲存數值性量度（Measures，如繳費金額、等待秒數）與指向周邊維度的外鍵；周圍放射狀連結「維度資料表（Dimension Table）」，儲存文字描述屬性（如時間維度、機關維度、行政區維度、案件類別），優化 OLAP 多維度分析切片切塊（Slice and Dice）。"),

        ("在地方政府大數據分析中，為確保 Open Data 釋出時保護民眾個資，若採用「差分隱私（Differential Privacy）」機制，其數學本質之核心保障為何？",
         "在查詢回傳結果中加入特定尺度之校準雜訊（如拉普拉斯雜訊 Laplace Noise），使得「資料集中是否包含某個特定個人的資料」，對輸出機率分佈的影響在數學上有界（ε-差分隱私）",
         ["在查詢回傳結果中加入特定尺度之校準雜訊（如拉普拉斯雜訊 Laplace Noise），使得「資料集中是否包含某個特定個人的資料」，對輸出機率分佈的影響在數學上有界（ε-差分隱私）",
          "直接將資料庫密碼重設為長度 128 碼之隨機文字",
          "完全不釋出任何數據，永久封鎖所有對外網路連線",
          "保證資料查詢結果 100% 絕對精確且無任何一毫誤差"],
         "差分隱私（Differential Privacy）嚴格數學保障：傳統去識別化易遭受輔助資訊攻擊（Linkage Attack）。差分隱私由 Dwork 提出，透過加入受控隨機雜訊，確保任何單一資料主體存在或不存在於資料庫中，查詢輸出的機率比值不超過 e^ε（隱私預算 ε 越小保護越強）。這使得攻擊者無論握有何種背景知識，皆無法推斷特定個體之機敏特徵。")
    ]

    # Dataset 2: 地方巨量資料治理、大數據運算 (Spark/Hadoop)、資料湖與 ETL/ELT 資料管道 (27 questions)
    bigdata_etl_data = [
        ("某市政府資訊局建置全府「智慧數據中台」，每日自戶政、地政、交通、水利等 20 個局處資料庫抽取異質資料。在現代雲原生大數據架構中，相較於傳統 ETL，改採「ELT（Extract-Load-Transform）」流程的最主要技術優勢為何？",
         "直接將海量原始資料（Raw Data）高速載入分散式資料倉儲或資料湖後，利用現代雲端分散式算力（如 BigQuery/Snowflake/Spark）並行轉換，彈性與處理速度大幅提升",
         ["直接將海量原始資料（Raw Data）高速載入分散式資料倉儲或資料湖後，利用現代雲端分散式算力（如 BigQuery/Snowflake/Spark）並行轉換，彈性與處理速度大幅提升",
          "完全不需要進行任何資料清洗即可保證資料品質 100% 正確",
          "可以在完全無電力的環境下自動執行運算",
          "強制所有局處統一使用微軟 Access 作為唯一資料庫"],
         "ETL 與 ELT 架構演進：傳統 ETL 在載入前依賴中介獨立伺服器進行繁重的清洗與轉換（Transform），運算瓶頸受限且丟失原始資料細節。現代 ELT 藉由巨量分散式計算引擎的崛起，先將原始資料完整保存在 Data Lake 中（保留歷史全貌），後續依各業務局處不同分析需求在內部靈活並行執行 SQL 轉換，開發迭代效率顯著。"),

        ("地方政府在建置「資料湖（Data Lake）」以彙整非結構化與半結構化市政大數據時，為防範資料湖淪為「資料沼澤（Data Swamp）」，資料治理團隊最核心之管控機制為？",
         "落實中繼資料管理（Metadata Management）、資料品質監控（Data Quality Check）與嚴格之資料目錄（Data Catalog）盤點",
         ["落實中繼資料管理（Metadata Management）、資料品質監控（Data Quality Check）與嚴格之資料目錄（Data Catalog）盤點",
          "禁止任何局處上傳超過 1KB 的資料檔案",
          "每晚定時將資料湖內所有檔案隨機重新命名",
          "取消所有檔案的標籤與欄位說明文件"],
         "資料湖治理與防止資料沼澤：資料湖允許儲存原生格式資料，若缺乏治理，大量無中繼資料（Metadata）、無資料血緣（Lineage）、無綱要定義（Schema）、無擁有者與品質低劣的殭屍檔案堆積，將使使用者無法檢索與信任資料，淪為廢棄之「資料沼澤」。必須透過主動式 Data Catalog、資料探勘與存取審計來確保資產健康。"),

        ("某市交通局之「即時公車行車安全監控系統」，每 10 秒接收數千輛公車之急加速、急煞車與胎壓感測器數據。若欲以串流運算即時偵測司機異常疲勞駕駛行為，在 Lambda 架構（Lambda Architecture）中，此項任務應由哪一層（Layer）承擔？",
         "速度層（Speed Layer / Streaming Layer），以串流引擎即時低延遲處理增量數據",
         ["速度層（Speed Layer / Streaming Layer），以串流引擎即時低延遲處理增量數據",
          "批次層（Batch Layer），每月底執行一次批次 MapReduce 運算",
          "服務層（Serving Layer），僅負責儲存歷史預先計算視圖",
          "歸檔層（Cold Archive Layer），以磁帶進行永久保存"],
         "Lambda 架構分層運作：Lambda 架構包含三層：(1) Batch Layer 保存原始不可變資料並定時計算高精確度視圖；(2) Speed Layer 針對最新增量資料利用串流處理器（如 Flink/Storm）進行低延遲即時運算以彌補批次延遲；(3) Serving Layer 同時查詢兩層結果進行合併。疲勞駕駛警示屬於秒級即時決策，由 Speed Layer 處理。"),

        ("某縣市地政局空間資料庫在儲存土地界址點時，經緯度數值欄位應採用何種資料型態以防止浮點數精度捨入誤差（Rounding Error）導致土地界址產生公分級位移？",
         "精確數值型態（如 <code>NUMERIC(10, 6)</code> 或 <code>DECIMAL</code>），而非二進位浮點數（<code>FLOAT</code> / <code>DOUBLE</code>）",
         ["精確數值型態（如 <code>NUMERIC(10, 6)</code> 或 <code>DECIMAL</code>），而非二進位浮點數（<code>FLOAT</code> / <code>DOUBLE</code>）",
          "二進位浮點數 <code>FLOAT</code>，因為其完全不會產生任何誤差",
          "短整數 <code>SMALLINT</code> 並將小數點全部無條件捨去",
          "布林型態 <code>BOOLEAN</code>"],
         "數值精度與地籍坐標安全：IEEE 754 浮點數（FLOAT/DOUBLE）在電腦內部以二進位科學記號表示，無法精確表示所有十進位小數（如 0.1 會產生無窮循環小數誤差）。土地產權涉及民眾鉅額資產，界址公分誤差易引發產權訴訟，必須採用以字串/BCD 陣列實作的任意精度 DECIMAL/NUMERIC 型態，或原生 PostGIS 幾何點結構。"),

        ("地方政府主計處建置「全府總預算與會計系統」，資料庫要求具備 ACID 交易保證。其中「一致性（Consistency）」在關聯式資料庫交易中的確切含義為何？",
         "交易執行前後，資料庫都必須嚴格滿足所有預先定義的完整性條件約束（Integrity Constraints，如主鍵唯一、外鍵參照、CHECK 約束）",
         ["交易執行前後，資料庫都必須嚴格滿足所有預先定義的完整性條件約束（Integrity Constraints，如主鍵唯一、外鍵參照、CHECK 約束）",
          "所有使用者的電腦螢幕必須同時顯示完全相同之畫面色彩",
          "伺服器運算效能必須在任何負載下永遠維持 100%",
          "資料庫連線必須使用完全相同的網路卡傳輸封包"],
         "ACID 之 Consistency（一致性）定義：在資料庫交易理論中，Atomicity 保證全做或全不做，Isolation 保證並發交易互不干擾，Durability 保證提交後持久化。Consistency 則指交易將資料庫從一個「合法有效狀態」轉移到另一個「合法有效狀態」，任何違反實體完整性、參照完整性或使用者定義業務規則（如帳戶總額守恆、餘額不得為負）的交易皆會被強迫回滾。"),

        ("某市觀光局分析跨年晚會人流停留時間，需對悠遊卡進出站數據執行視窗分析（Window Functions）。SQL 中計算「各進站乘客依出站時間排序之累計乘客人數（Running Total）」時，標準寫法應包含何項關鍵字？",
         "<code>SUM(passenger_count) OVER (PARTITION BY station_id ORDER BY exit_time)</code>",
         ["<code>SUM(passenger_count) OVER (PARTITION BY station_id ORDER BY exit_time)</code>",
          "<code>GROUP BY station_id, exit_time</code> 且不使用任何 OVER 子句",
          "<code>ORDER BY passenger_count DESC</code> 且禁止使用 SUM",
          "<code>HAVING passenger_count > 0</code>"],
         "SQL 視窗函數（Window Functions）：傳統 <code>GROUP BY</code> 會將多列資料聚合壓縮為單一列，無法保留原始明細。視窗函數使用 <code>OVER(PARTITION BY ... ORDER BY ...)</code>，在不折疊原始資料列的前提下，在特定視窗劃分內進行滾動累計計算（Running Total、移動平均、分組排名 ROW_NUMBER/RANK），極適合時間序列大數據分析。"),

        ("地方政府「防汛降雨大數據平台」採用分散式資料庫儲存全縣市 200 個自動雨量站過去 10 年每 5 分鐘回報的觀測值（逾數億筆時序紀錄）。相較於傳統關聯式 DB，改採專用「時序資料庫（Time Series Database，如 InfluxDB/TimescaleDB）」的核心效能優勢為何？",
         "具備極高的高並發時間戳記寫入吞吐量、專門針對時序壓縮之演算法（如 Gorilla/Delta-of-Delta 演算法）與自動化按時間降採樣（Downsampling）",
         ["具備極高的高並發時間戳記寫入吞吐量、專門針對時序壓縮之演算法（如 Gorilla/Delta-of-Delta 演算法）與自動化按時間降採樣（Downsampling）",
          "完全不支援任何 SQL 語法，只能以紙筆手動記錄",
          "會自動將所有降雨數據全部修改為零以節省空間",
          "只能在單一核心 CPU 上以單執行緒運行"],
         "時序資料庫（TSDB）核心優化機制：時序數據具備「 append-only 寫入無修改、以時間為第一維度、查詢多為時間範圍聚合」之鮮明特性。TSDB 採用按時間區間自動分區（Chunk/Partitioning）、針對連續時間戳記與浮點測值進行專屬壓縮（壓縮率高達 90% 以上），並內建自動滾動降取樣（如 5 分鐘數據保存 1 年後降採樣為 1 小時平均值），儲存與查詢效率遠勝傳統 DB。"),

        ("某縣市交通局分析智慧路口攝影機辨識出的「汽機車車流速度」大數據，若欲排除極端異常離群值（如傳回時速 500 公里或負數）以計算可靠的平均車速，統計分析中最抗離群值干擾（Robust）之指標為？",
         "中位數（Median）或四分位距（IQR, Interquartile Range）修剪平均數",
         ["中位數（Median）或四分位距（IQR, Interquartile Range）修剪平均數",
          "標準算術平均數（Arithmetic Mean），因其極易受單一極端值拉偏",
          "全距（Range，最大值減最小值）",
          "幾何平均數（Geometric Mean）"],
         "強健統計指標（Robust Statistics）：感測器在強光反射或硬體故障時常回傳離譜的異常極端值。傳統算術平均數（Mean）極易被單一極大值顯著扭曲；中位數（Median）不受極端尾端數據影響，四分位距（IQR = Q3 - Q1）結合 1.5*IQR 判定離群值，能有效清洗感測器髒數據，反映真實道路交通狀況。"),

        ("在地方政府大數據平台中，為避免重複開發相似的資料特徵（如「過去 30 天市民線上申辦次數」、「各里近 1 年火災通報總數」），在現代機器學習與大數據架構中，專門負責特徵集中管理、版本控制與低延遲在線Serving的組件為？",
         "特徵市集（Feature Store，如 Feast）",
         ["特徵市集（Feature Store，如 Feast）",
          "程式碼倉庫（Git）",
          "防毒軟體隔離區",
          "網域名稱伺服器（DNS）"],
         "機器學習特徵市集（Feature Store）：在大型政府智慧治理團隊中，資料工程師常為不同 AI 專案重複運算相同特徵，甚至造成訓練特徵與在線推論特徵不一致（Training-Serving Skew）。Feature Store 提供統一的特徵定義、註冊與管道，兼具離線訓練批次存取（Offline Store）與線上預測毫秒級 Key-Value 存取（Online Store Redis），是 MLOps 之關鍵元件。"),

        ("某市環保局建立全縣市機車排氣定檢大數據模型，預測哪些車齡超過 10 年之機車有極高機率未定檢或排放超標。資料集中「正常合格機車」佔 98%，「嚴重超標機車」僅佔 2%（極度不平衡資料集）。在評估模型預測效能時，下列何項指標最不具備參考價值？",
         "整體準確率（Accuracy），因為即使模型盲猜全數為合格，準確率亦高達 98%",
         ["整體準確率（Accuracy），因為即使模型盲猜全數為合格，準確率亦高達 98%",
          "精確率（Precision，查準率）",
          "召回率（Recall，查全率）",
          "PR-AUC（Precision-Recall 曲線下面積）或 F1-Score"],
         "不平衡分類資料集評估指標陷阱：在極度不平衡（Imbalanced Dataset）情境下，若模型採取樸素策略預測全部為多數類，Accuracy 仍高達 98%，但少數關鍵類別（超標機車）識別率卻為 0%。必須改採關心少數類別的 Precision、Recall、F1-Score 或 PR-AUC，方能真實衡量稽查篩檢效益。"),

        ("地方政府「智慧市政戰情室」展示即時各區人口移動與就業熱圖。在資料倉儲設計中，若採用「慢變維度（SCD, Slowly Changing Dimensions）」之「SCD Type 2（新增版本歷史紀錄）」處理市民搬遷行政區之歷程，其核心作法為？",
         "當市民遷徙時，保留舊有紀錄並新增一筆新紀錄，利用有效起始日期（Effective Date）、結束日期與當前版本標記（Current Flag）記錄變更歷程",
         ["當市民遷徙時，保留舊有紀錄並新增一筆新紀錄，利用有效起始日期（Effective Date）、結束日期與當前版本標記（Current Flag）記錄變更歷程",
          "直接以新地址強制覆蓋覆寫舊地址，永久抹除所有歷史搬遷痕跡（此為 SCD Type 1）",
          "在舊紀錄中新增額外欄位，但最多只能記錄一次變更（此為 SCD Type 3）",
          "直接將該市民之所有過往戶籍紀錄全部從資料庫中徹底刪除"],
         "慢變維度 SCD Type 2 歷史溯源：在維度模型中，實體屬性隨時間變更（如市民換地址、公務員調部門）。SCD Type 1 直接覆寫無歷史；SCD Type 2 是數倉最重要之標準設計，每當屬性變更即插入一筆新資料列，並維護 <code>start_date</code> 與 <code>end_date</code>。這使得報表分析既能精確重現「歷史時點當下（Point-in-time）」的統計數據，又能掌握最新現狀。"),

        ("某縣市衛生局為防範登革熱，利用地理空間資料庫對數萬筆病媒蚊密度調查資料建立「克里金空間內插法（Kriging Interpolation）」以繪製全區連續風險地圖。克里金法相較於單純距離倒數加權法（IDW）的最主要統計學優勢為何？",
         "利用半變異圖（Semivariogram）量化空間結構自相關性，不僅能估計未知點數值，還能提供「估計值的不確定性/變異數（Error Variance）」",
         ["利用半變異圖（Semivariogram）量化空間結構自相關性，不僅能估計未知點數值，還能提供「估計值的不確定性/變異數（Error Variance）」",
          "不需要任何已知的樣點數據即可憑空推算全區數值",
          "計算複雜度為常數時間 O(1)，適合單晶片微電腦運算",
          "計算過程完全不涉及任何數學運算"],
         "克里金內插法（Kriging）地統計優勢：IDW 僅依據幾何距離次方進行機械式加權，缺乏理論統計依據。克里金（地統計學核心）透過實驗半變異圖（Semivariogram）分析不同距離與方向下的空間變異結構，求得無偏最佳線性估計（BLUE），並能產製「預測標準差圖」，明確標註哪些採樣不足區域估計誤差較大，供決策者評估增設監測點。"),

        ("地方政府戶政系統資料庫在日常維運中，資料庫管理員（DBA）執行 SQL <code>VACUUM FULL</code>（以 PostgreSQL 為例）之主要目的為何？",
         "回收因頻繁 UPDATE/DELETE 產生之死亡元組（Dead Tuples）所佔據的磁碟空間，重建表格並消除資料表膨脹（Table Bloat）",
         ["回收因頻繁 UPDATE/DELETE 產生之死亡元組（Dead Tuples）所佔據的磁碟空間，重建表格並消除資料表膨脹（Table Bloat）",
          "將所有市民之密碼自動變更為空白",
          "強制關閉整個縣市政府之所有網路連線",
          "將關聯式資料庫轉換為微軟 Excel 試算表"],
         "MVCC 與 VACUUM 垃圾回收：PostgreSQL 實作多版本並發控制（MVCC），UPDATE 與 DELETE 僅將舊列標記為不可見（Dead Tuple），並不立即自磁碟抹除。長時間未清理會造成 Table Bloat，浪費磁碟並降低緩衝快取效率。Autovacuum 在背景釋放空間供重用；而 <code>VACUUM FULL</code> 透過排他鎖重寫整張表，徹底將物理磁碟空間釋放返還作業系統。"),

        ("某市交通局之「即時路況號誌最佳化系統」需儲存動態車流矩陣。若資料庫表格包含 5,000 萬筆紀錄，下列何種情況下關聯式資料庫會「放棄使用 B+ 樹索引」而退化為代價昂貴的全表掃描（Full Table Scan）？",
         "查詢條件在被索引的欄位上套用了函數計算或型態隱式轉換，如 <code>WHERE SUBSTRING(plate_no, 1, 3) = 'ABC'</code> 或 <code>WHERE record_date + 1 > ...</code>",
         ["查詢條件在被索引的欄位上套用了函數計算或型態隱式轉換，如 <code>WHERE SUBSTRING(plate_no, 1, 3) = 'ABC'</code> 或 <code>WHERE record_date + 1 > ...</code>",
          "查詢條件為標準的前綴精確比對，如 <code>WHERE plate_no = 'ABC-1234'</code>",
          "使用主鍵進行單筆等值查找，如 <code>WHERE id = 12345</code>",
          "資料庫伺服器硬碟剩餘空間大於 1TB 時"],
         "索引失效之經典模式：B+ 樹索引是依據欄位「原始值」排序建立樹狀節點。若在 SQL 的 WHERE 子句中對索引欄位進行數學運算、字串函數操作（如 <code>UPPER()</code>、<code>SUBSTR()</code>）或發生隱式型態轉換（如字串欄位比對整數），優化器無法直接在樹上進行二元二分比對，導致索引失效並退化為全表循序掃描。解法為改寫條件或建立函式索引（Functional Index）。"),

        ("地方政府「市民陳情反映系統」欲提供全文檢索功能，讓承辦人可搜尋陳情內文中包含「路面坑洞」或「路燈不亮」的案件。相較於 SQL 之 <code>LIKE '%關鍵字%'</code>，導入專用搜尋引擎（如 Elasticsearch / Solr）的核心優勢為何？",
         "利用反向索引（Inverted Index）進行單詞詞典比對，查詢時間為毫秒級且支援中文斷詞（分詞）與相關度權重排序（TF-IDF / BM25）",
         ["利用反向索引（Inverted Index）進行單詞詞典比對，查詢時間為毫秒級且支援中文斷詞（分詞）與相關度權重排序（TF-IDF / BM25）",
          "<code>LIKE '%關鍵字%'</code> 在任何百萬筆資料庫中皆能在 0.001 毫秒內完成",
          "Elasticsearch 不需要消耗任何伺服器記憶體即可運作",
          "完全禁止使用任何中文進行檢索"],
         "反向索引（Inverted Index）與全文檢索：SQL 中以左萬用字元開頭的 <code>LIKE '%abc%'</code> 無法利用 B+ 樹索引，必須執行昂貴的全表文字逐字掃描。全文檢索引擎透過分詞器（如結巴分詞/IK 分詞）建立「單詞 → 包含該詞之文件編號清單」的反向索引表，並藉由 BM25 演算法動態評估詞頻（TF）與逆向文件頻率（IDF）計算相關度分數，秒級響應百萬篇公文搜尋。"),

        ("某縣市環保局建置「全縣工廠污染排放大數據預警平台」，若欲分析兩處不同河流流域的重金屬檢測值是否存在顯著統計差異，在兩組資料均符合常態分佈且變異數齊一的前提下，應採用何種假設檢定方法？",
         "獨立樣本雙樣本 t 檢定（Two-sample Independent Student's t-test）",
         ["獨立樣本雙樣本 t 檢定（Two-sample Independent Student's t-test）",
          "卡方獨立性檢定（Chi-square Test），專門用於類別變數",
          "單一母體比例檢定",
          "隨機森林分類法"],
         "雙樣本 t 檢定適用條件：當欲檢定兩個獨立群體（如 A 河流 vs B 河流）的連續型數值平均數是否存在顯著差異時，在滿足常態性（Normality）與變異數同質性（Homogeneity of Variance）假設下，採用獨立雙樣本 t 檢定計算 t 值與 p 值。若不符合常態分佈，則應退回採用無母數檢定（曼-惠特尼 U 檢定，Mann-Whitney U Test）。"),

        ("地方政府工務局進行公共工程建設計畫管理時，需儲存工程進度日誌。在關聯式資料庫中，為確保「工程日誌表」中的「承包商編號」必須合法存在於「廠商登記表」中，應於資料表定義中加入何種約束？",
         "外鍵條件約束（Foreign Key Constraint），強制落實參照完整性（Referential Integrity）",
         ["外鍵條件約束（Foreign Key Constraint），強制落實參照完整性（Referential Integrity）",
          "唯一性約束（UNIQUE Constraint）",
          "非空約束（NOT NULL Constraint）",
          "預設值約束（DEFAULT Constraint）"],
         "資料庫參照完整性（Referential Integrity）：外鍵約束保證子資料表（工程日誌）中參照的鍵值必須存在於父資料表（廠商主檔）之主鍵或唯一鍵中，或設為 NULL。這能防止產生孤兒紀錄（Orphan Records），並在父表資料遭刪除或修改時透過 <code>ON DELETE RESTRICT/CASCADE</code> 規範級聯動作，確保資料關聯一致性。"),

        ("某市資訊局建置市政資料交換平台，採用關聯式資料庫進行異動審計。為自動記錄所有資料表被 INSERT、UPDATE 或 DELETE 的操作時間、舊值與新值，資料庫層級最標準的自動化實作機制為？",
         "資料庫觸發程序（Database Trigger）結合審計日誌資料表（Audit Log Table）",
         ["資料庫觸發程序（Database Trigger）結合審計日誌資料表（Audit Log Table）",
          "每晚由工讀生以電話逐一詢問承辦人今天修改了哪些資料",
          "由應用程式完全省略日誌記錄以提升寫入效能",
          "每 10 秒執行一次全資料庫 DROP TABLE 再重建"],
         "資料庫觸發器（Trigger）審計機制：資通安全稽核規範要求機敏個資變更必須具備稽核軌跡。Trigger 在資料庫層級與資料異動交易綁定（<code>AFTER INSERT OR UPDATE OR DELETE ON table</code>），直接在資料庫底層擷取 <code>NEW</code> 與 <code>OLD</code> 虛擬列狀態並原子寫入稽核表記錄，即使外部程式遭繞過直接由 DB 工具修改亦能完整留存紀錄。"),

        ("地方政府衛生局在新冠疫情期間，需統計全市民眾疫苗施打「第一劑、第二劑、第三劑」之人數交叉分析報表。SQL 中將多列資料轉置為多欄展示（行轉列）之標準進階語法為？",
         "<code>CASE WHEN</code> 條件聚合或資料庫原生 <code>PIVOT</code> 運算子",
         ["<code>CASE WHEN</code> 條件聚合或資料庫原生 <code>PIVOT</code> 運算子",
          "<code>UNION ALL</code> 垂直堆疊資料",
          "<code>DROP DATABASE</code> 刪除整個資料庫",
          "<code>SELECT * FROM table LIMIT 1</code>"],
         "SQL 行轉列（Pivot / Conditional Aggregation）：在產製交叉統計矩陣時，經常需要將儲存在資料列中的分類標籤（如 dose_number = 1, 2, 3）轉置為表格的獨立行欄位（如劑次 1 人數、劑次 2 人數）。標準做法為結合聚合函數與條件陳述式：<code>SUM(CASE WHEN dose_number = 1 THEN 1 ELSE 0 END) AS dose1_count</code>，或使用支援的 PIVOT 語法。"),

        ("某縣市交通局之「停車場即時剩餘車位 API」，每日面臨高達 2,000 萬次之頻繁讀取請求，但停車位數值僅每 30 秒更新一次。在資料庫架構上，為保護後端關聯式資料庫免於讀取過載，最佳快取替換演算法（Cache Replacement Policy）為？",
         "LRU（Least Recently Used，最近最少使用演算法），動態淘汰最久未被存取的冷門停車場快取鍵",
         ["LRU（Least Recently Used，最近最少使用演算法），動態淘汰最久未被存取的冷門停車場快取鍵",
          "隨機丟棄演算法，隨機刪除快取中所有的即時車位資料",
          "FIFO（先進先出），不管資料熱度為何固定強制清除",
          "永久不允許釋放記憶體，直至伺服器核心發生記憶體溢位"],
         "快取置換策略（Cache Eviction Policies）：記憶體容量有限，當快取池滿載時需依策略淘汰資料。LRU 依據時間局部性（Temporal Locality）原理，優先淘汰最長時間未被讀取的鍵，保證最熱門的停車場數據常駐記憶體，命中率（Cache Hit Rate）最高且記憶體利用最優。"),

        ("地方政府民政局在建置「市民數位族譜查詢系統」時，戶籍資料庫中「親屬血緣關係（父母、子女）」屬於階層式樹狀結構。在 SQL:1999 標準中，查詢某人向上所有直系血親祖先之標準查詢語法為？",
         "遞迴通用資料表表達式（Recursive CTE，<code>WITH RECURSIVE ancestor AS (...)</code>）",
         ["遞迴通用資料表表達式（Recursive CTE，<code>WITH RECURSIVE ancestor AS (...)</code>）",
          "在單一 SELECT 中手動連續 JOIN 100 次相同的資料表",
          "完全無法以 SQL 實現，必須將資料庫全部匯出至 Excel 手動繪圖",
          "使用 <code>SELECT * FROM table ORDER BY RAND()</code>"],
         "遞迴通用資料表表達式（Recursive CTE）：自參考關係（Self-referencing Foreign Key，如 <code>parent_id -> person_id</code>）的深度未知階層遍歷，傳統 SQL 難以用固定次數 JOIN 表達。Recursive CTE 由錨定查詢（Anchor Member）與遞迴成員（Recursive Member）以 <code>UNION ALL</code> 組合，引擎會反覆執行直到工作集為空，優雅遍歷任意深度之樹狀或圖狀親屬關係。"),

        ("某市主計處為防止內部人員偽造採購發票報銷，利用大數據分析比對發票金額首位數字之分佈規律。在自然產生的真實財務數據中，首位數字為 1 的出現機率遠高於首位數字為 9 的統計學定律為？",
         "班佛法則（Benford's Law，第一位數定律）",
         ["班佛法則（Benford's Law，第一位數定律）",
          "大數法則（Law of Large Numbers）",
          "中央極限定理（Central Limit Theorem）",
          "二項式分佈定律"],
         "班佛法則（Benford's Law）與舞弊鑑識：Benford's Law 指出在未經人工操弄的自然多維尺度數據（如人口數、發票金額、地籍面積、水費帳單）中，首位有效數字 d（1 到 9）出現機率服從對數分佈 <code>P(d) = log10(1 + 1/d)</code>，其中數字 1 出現機率高達約 30.1%，而數字 9 僅有 4.6%。若特定單位報銷發票之首位數字分佈嚴重背離此曲線，為審計機關查核人為造假發票之重要紅旗指標。"),

        ("某縣市地政局進行地籍大數據分析時，發現資料庫中有 10 萬筆老舊建物缺乏明確經緯度坐標，但記載有土地段名與地號。若欲在資料庫中自動補充坐標，最根本之資料補全（Imputation）途徑為？",
         "空間關聯（Spatial Join）或屬性介接：透過「段代碼 + 地號」與地籍圖宗地多邊形進行主外鍵關聯，以該地號多邊形之質心坐標（<code>ST_Centroid</code>）作為建物近似坐標",
         ["空間關聯（Spatial Join）或屬性介接：透過「段代碼 + 地號」與地籍圖宗地多邊形進行主外鍵關聯，以該地號多邊形之質心坐標（<code>ST_Centroid</code>）作為建物近似坐標",
          "隨機填入全台灣各地的任意經緯度坐標",
          "將所有缺乏坐標之老舊建物資料全部永久刪除",
          "強制填入 (0, 0) 坐標使其全部標記在非洲幾內亞灣赤道外海"],
         "資料缺漏值補全與地籍圖資關聯：空間資料庫實務中，點位（建物）與面（宗地土地）具有強烈從屬關係。當點坐標遺失但持有產權地號時，利用關聯式索引關聯對應的地籍圖宗地多邊形，計算幾何多邊形中心點賦予該建物，既符合地理業務合理性，又避免引入虛假的 (0,0)「Null Island」地理髒數據。"),

        ("地方政府「智慧交通車流監控大數據平台」每日產出 1 億筆車速資料，若欲建立資料倉儲以利市長與局處長即時查詢「各行政區每小時平均車速」，在實體資料表設計上，應採用何種技術以加速特定日期範圍之查詢效能？",
         "資料表分區（Table Partitioning，如按日期範圍 Range Partitioning），查詢時觸發分區剪枝（Partition Pruning）",
         ["資料表分區（Table Partitioning，如按日期範圍 Range Partitioning），查詢時觸發分區剪枝（Partition Pruning）",
          "將所有 1 億筆資料存放在單一無分區的文字檔案中",
          "取消所有欄位的資料型態，全部以 VARCHAR(1) 儲存",
          "每小時自動刪除前一小時的歷史紀錄"],
         "資料表分區（Partitioning）與分區剪枝：對於巨型歷史事實表，將單一邏輯大表按時間維度（如依月份或日期）拆分為多個物理子表。當 SQL 查詢指定 <code>WHERE date BETWEEN '2026-10-01' AND '2026-10-07'</code> 時，優化器透過分區剪枝（Partition Pruning）直接略過其餘 99% 無關子表之磁碟掃描，大幅減少 I/O 並提升查詢速度。"),

        ("某市衛生局建置「全市民眾慢性病大數據風險預測模型」，訓練機器學習隨機森林（Random Forest）分類器。在超參數調優（Hyperparameter Tuning）時，為避免「過度擬合（Overfitting）」並公平評估泛化能力，最標準的交叉驗證方式為？",
         "K 折交叉驗證（K-Fold Cross-Validation），將資料隨機分為 K 份輪流作為驗證集",
         ["K 折交叉驗證（K-Fold Cross-Validation），將資料隨機分為 K 份輪流作為驗證集",
          "直接使用 100% 的全部訓練資料同時作為測試集來計算準確率",
          "僅使用單一筆受試者資料進行模型評估",
          "完全不劃分任何驗證集，隨機猜測預測成果"],
         "機器學習 K 折交叉驗證（K-Fold CV）：若直接以訓練集評估模型，模型只需死記訓練資料特徵即可獲得虛假之 100% 準確率，但在實際未見過之新病患上表現極差（過度擬合）。K-Fold 將數據分為 K 份（如 5 折），訓練 5 次取平均驗證表現，能充分利用有限公衛樣本並客觀衡量模型泛化穩定性。"),

        ("地方政府在推動大數據專案時，經常需要執行「資料剖析（Data Profiling）」以評估各機關匯入資料庫的品質。資料剖析的核心檢驗指標通常「不包括」下列何者？",
         "伺服器主機風扇轉速與冷氣機出風口溫度",
         ["伺服器主機風扇轉速與冷氣機出風口溫度",
          "欄位缺漏值比率（Null Percentage）與空白字串分佈",
          "數值欄位之基數（Cardinality）、最大值、最小值與常態分佈分位數",
          "資料格式符合度（如身分證字號長度與正則表達式檢驗）"],
         "資料剖析（Data Profiling）之核心關注維度：Data Profiling 係對資料集內部之結構、內容與規則進行統計與語意健康檢查。核心指標包含：Completeness（完整性/缺漏率）、Uniqueness（唯一性/重複率）、Validity（合法性/符合 Regex 規格）、Consistency（一致性/範圍極值分佈）。伺服器風扇轉速屬硬體基礎設施監控範疇，與資料內容治理無涉。"),

        ("某縣市觀光局整合各景點人流大數據，需將多元異質系統中的「日期時間」欄位進行標準化轉換。國際標準化組織（ISO）定義之全球標準日期時間表達格式為？",
         "ISO 8601 標準格式（如 <code>2026-10-07T14:30:00+08:00</code>）",
         ["ISO 8601 標準格式（如 <code>2026-10-07T14:30:00+08:00</code>）",
          "民國年份無分隔符號純文字（如 <code>1151007</code>）且不帶任何時區資訊",
          "美式月日年斜線格式（如 <code>10/07/26</code>）容易引發月與日之判讀混淆",
          "羅馬數字書寫之鐘點符號"],
         "ISO 8601 國際標準時間格式：跨機關系統交換資料時，日期格式混亂（如民國年、美式 MM/DD/YYYY、歐式 DD/MM/YYYY）是引發資料轉換錯誤與時序顛倒的主要根源。ISO 8601 採用 <code>YYYY-MM-DDThh:mm:ss±hh:mm</code>，具備字典序可直接排序、年與月日定義明確且自帶 UTC 時區偏移量（Timezone Offset），為政府 API 交換標準。")
    ]

    # Dataset 3: 分散式資料庫、分表分庫 Sharding、一致性雜湊、Open Data 治理與差分隱私/去識別化 (27 questions)
    db_sharding_privacy_data = [
        ("某市政府戶政大數據庫儲存超過 300 萬全體市民的各項生活資料，當單一資料表筆數膨脹至數億筆導致單機 I/O 成為極限瓶頸時，架構師決定採用「水平分表分庫（Sharding）」。下列何項欄位最適合作為分片鍵（Sharding Key）？",
         "市民身分證號之雜湊值（Hash-based Sharding Key），使資料均勻散列於各分片節點並避免特定節點過載",
         ["市民身分證號之雜湊值（Hash-based Sharding Key），使資料均勻散列於各分片節點並避免特定節點過載",
          "市民的性別欄位（僅有男、女兩個值），導致全部分片僅能有 2 台伺服器且嚴重資料傾斜",
          "固定寫死的常數值 1，使得所有資料全部流入同一個資料庫分片中",
          "隨機時間戳記之秒數，導致依身分證查詢時必須對所有分片發動廣播查詢（Scatter-Gather）"],
         "Sharding Key 選擇原則：Sharding Key 決定資料在分散式節點上的物理分佈。理想的 Sharding Key 應具備高基數（High Cardinality）與均勻分佈特性（如身分證號雜湊），防止熱點分片（Hotspot）。若以性別分片會導致只有兩台節點承載流量且無法橫向擴充；以時間分片則在查詢特定市民時必須全分片廣播，大幅拉高查詢延遲。"),

        ("在分散式資料庫快取或分片架構中，當動態新增或移除一個資料庫伺服器節點時，為避免「傳統取餘數雜湊演算法（<code>Hash(key) % N</code>）」導致全網 90% 以上快取瞬間全部失效（Cache Stampede），應採用何種雜湊演算法？",
         "一致性雜湊（Consistent Hashing），將節點與資料鍵對應至圓環（Hash Ring），節點異動時僅影響相鄰局部區段",
         ["一致性雜湊（Consistent Hashing），將節點與資料鍵對應至圓環（Hash Ring），節點異動時僅影響相鄰局部區段",
          "傳統取餘數演算法，每次節點增減皆強制將整座快取叢集清空重啟",
          "固定所有資料只存放在第一台伺服器中",
          "隨機數雜湊且每次查詢均重新擲骰子決定節點"],
         "一致性雜湊（Consistent Hashing）核心原理：在傳統 <code>hash(key) % N</code> 中，當節點數由 N 變為 N+1 時，幾乎所有 key 的餘數均發生變化，引發全局資料重分配與快取雪崩。一致性雜湊將 0~2^32-1 組織為封閉圓環，節點與 Key 均雜湊至環上順時針尋找最近節點。當增減節點時，僅需重分配環上相鄰區間的資料（約 1/N），配合虛擬節點（Virtual Nodes）更能防止負載不均。"),

        ("地方政府在推動「政府資料開放（Open Data）」政策中，依據國際 Open Data 五星級評等標準（5-Star Open Data），達到「五星級（Five-Star）」資料之最關鍵特質為何？",
         "將結構化開放格式之資料透過語意網（Linked Data / RDF）標準發布，並與其他相關外部資料集相互鏈結（Linked）",
         ["將結構化開放格式之資料透過語意網（Linked Data / RDF）標準發布，並與其他相關外部資料集相互鏈結（Linked）",
          "以掃描之 PDF 圖檔格式直接上傳供民眾下載（一星級）",
          "將資料儲存於微軟 Excel 專屬格式 .xlsx 中發布（二星級）",
          "僅限政府機關內部以紙本公文方式流轉，對外完全保密"],
         "Tim Berners-Lee 開放資料五星評等體系：\n1 星：在開放授權下以任何格式上傳（如 PDF 圖檔）；\n2 星：以結構化機器可讀格式發布，但為專有軟體格式（如 Excel .xls）；\n3 星：使用開放非專有格式發布（如 CSV/JSON/XML）；\n4 星：使用 W3C 開放標準（如 RDF/SPARQL）標註 URI 成為語意網；\n5 星：鏈結資料（Linked Open Data, LOD），主動與其他機關或維基數據之資料相互關聯，釋放資料互連最大價值。"),

        ("某市觀光局公開全市立案合法民宿名冊與座標資料，為鼓勵民間加值開發並避免法律授權爭議，依據行政院「政府資料開放授權條款（OGDL）」，民間業者使用該開放資料時主要之法定義務為何？",
         "標示出處（Attribution）：顯著標明資料來源機關名稱與開放資料網址",
         ["標示出處（Attribution）：顯著標明資料來源機關名稱與開放資料網址",
          "必須將所賺取之營業利潤 50% 強制繳納給地方政府作為規費",
          "開發完成之商業 APP 必須永久免費且禁止放置任何商業廣告",
          "禁止任何民間企業使用該資料，僅限非營利學術研究使用"],
         "政府資料開放授權條款（OGDL）：台灣「政府資料開放授權條款」類似國際 Creative Commons Attribution (CC BY 4.0)，高度尊重加值創新。使用者享有廣泛權利：得為商業或非商業目的自由散布、修改、重混與衍生創作，無須個別申請或繳納授權費，唯一核心義務為「標示出處（Attribution）」，明確告知公眾資料由何公務機關開放提供。"),

        ("在地方政府個資去識別化實務中，若某張釋出的公衛就診統計表中，特定年齡與郵遞區號的組合在資料庫中僅對應到「單一一位」特定市民，該名市民即面臨被重新識別之風險。滿足「K-匿名性（K-Anonymity）」要求之核心準則為何？",
         "任何一組準識別碼（Quasi-identifiers，如年齡、性別、郵遞區號）的組合，在資料集中必須至少存在 K 筆相同的紀錄",
         ["任何一組準識別碼（Quasi-identifiers，如年齡、性別、郵遞區號）的組合，在資料集中必須至少存在 K 筆相同的紀錄",
          "資料庫必須包含至少 K 個不同的資料表",
          "每個欄位名稱長度必須嚴格等於 K 個英文字母",
          "所有數值必須乘以 K 倍之後才能對外公布"],
         "K-匿名性（K-Anonymity）原理：Sweeney 提出的 K-Anonymity 旨在防範連結攻擊（Linkage Attack）。透過抑制（Suppression，如將部分個資塗黑）與泛化（Generalization，如將年齡 32 歲改為「30-39 歲區間」），使任一由準識別碼構成的等價類（Equivalence Class）大小至少為 K。此時攻擊者即便握有外部輔助選民名冊，重新識別個人的機率上限僅為 1/K。"),

        ("儘管資料集滿足了 K-Anonymity（如某等價類包含 5 筆紀錄），但若這 5 筆紀錄在機敏屬性（Sensitive Attribute，如確診疾病）上全部都是「肺癌」，攻擊者仍能百分之百確定該市民罹患肺癌（同質性攻擊 Homogeneity Attack）。為克服此缺陷而提出的改進模型為？",
         "L-多樣性（L-Diversity），要求每個等價類中的機敏屬性必須至少包含 L 個不同且分佈合理的取值",
         ["L-多樣性（L-Diversity），要求每個等價類中的機敏屬性必須至少包含 L 個不同且分佈合理的取值",
          "完全刪除資料集中的所有資料",
          "將資料庫的通訊埠（Port）修改為 8080",
          "要求查詢者必須背誦出整部中華民國憲法條文"],
         "L-多樣性（L-Diversity）之演進：K-Anonymity 僅保證準識別碼分組人數至少為 K，未限制機敏屬性內容。當同組人全罹患相同疾病（同質性攻擊），或攻擊者具備嚴重偏好背景知識（背景知識攻擊），K-Anonymity 即告失效。L-Diversity 要求每個等價類內敏感屬性具有「多樣性」，即至少有 L 個相異取值，進一步強化隱私邊界。"),

        ("某縣市交通局之「停車收費清冊資料庫」採用關聯式資料庫叢集架構。當系統發生網路中斷形成腦裂（Split-Brain）風險時，為確保叢集不會出現兩個 Master 主節點各自接受寫入，多數分散式共識演算法（如 Raft、Paxos）所依賴的投票仲裁準則為？",
         "法定多數決（Quorum，即獲得超過半數 <code>N/2 + 1</code> 節點投票贊同者方能成為合法 Leader）",
         ["法定多數決（Quorum，即獲得超過半數 <code>N/2 + 1</code> 節點投票贊同者方能成為合法 Leader）",
          "由目前網路線傳輸速度最慢的單一節點自動成為 Master",
          "兩邊分區各自獨立成為 Master 並隨意寫入，不管資料衝突",
          "隨機挑選任意一台電腦關閉電源"],
         "分散式共識與 Quorum 機制：腦裂（Split-Brain）是分散式系統的致命殺手。若網路分區時兩半部各自推選 Master，會引發資料雙重寫入且無法融合之重大災難。Raft/Paxos 要求任何 Leader 當選或日誌提交必須取得過半數（Quorum = ⌊N/2⌋ + 1）贊成。因為在 N 個節點的系統中，不可能同時存在兩個彼此獨立且皆過半數的集合，從數學上根除腦裂。"),

        ("地方政府在建置「地籍資料庫多節點主從同步（Replication）」時，若希望保證資料「零遺失（RPO = 0）」，但代價是客戶端寫入延遲會受到最慢從庫網路延遲的拖累，應設定何種複製模式？",
         "同步複製（Synchronous Replication），Master 必須等待至少一個或全部指定 Slave 完成日誌寫入並回傳確認後始回傳成功",
         ["同步複製（Synchronous Replication），Master 必須等待至少一個或全部指定 Slave 完成日誌寫入並回傳確認後始回傳成功",
          "非同步複製（Asynchronous Replication），Master 寫入本地磁碟後立即回傳成功，完全不等待 Slave",
          "延遲複製（Delayed Replication），故意讓 Slave 延遲 24 小時後才開始同步",
          "手動複製，每週五下班由專人以隨身碟手動拷貝一次資料庫檔案"],
         "同步複製 vs 非同步複製權衡：非同步複製（Asynchronous）效能最高且延遲最低，但若 Master 剛寫入本地 WAL 尚未送至 Slave 瞬間硬體燒毀，該筆交易在 Slave 遺失（RPO > 0）。同步複製（Synchronous）強制寫入交易必須等 Slave 確認收訖並落盤始提交，保證故障切換（Failover）時資料絕對不遺失，為金融繳費與產權主檔必選。"),

        ("某市水利局建置「全縣智慧防汛水位感測數據庫」，若採用 Cassandra / ScyllaDB 等基於 Bigtable 與 Dynamo 架構之 NoSQL 資料庫，其底層儲存引擎採用 LSM-Tree（Log-Structured Merge-Tree）的主要優勢為何？",
         "將隨機寫入轉換為順序磁碟附加寫入（Sequential Append-only），提供極高之寫入吞吐量並透過背景 Compaction 壓縮整理資料",
         ["將隨機寫入轉換為順序磁碟附加寫入（Sequential Append-only），提供極高之寫入吞吐量並透過背景 Compaction 壓縮整理資料",
          "完全不支援任何硬碟儲存，資料只短暫保存在 CPU 暫存器中",
          "完全禁止進行任何資料讀取，只能寫入",
          "使得資料庫檔案大小永遠固定為 100MB 不增不減"],
         "LSM-Tree 儲存引擎優勢：傳統 B+ 樹直接在磁碟各處進行原地更新（In-place Update），會引發大量隨機 I/O 尋道延遲。LSM-Tree 寫入時先順序追加寫入 WAL 日誌並寫入記憶體 MemTable，滿載後以不可變有序字串表（SSTable）順序刷盤至磁碟，將隨機寫入轉為循序 I/O，大幅釋放磁碟頻寬，極適合 IoT 高頻寫入情境。"),

        ("在分散式資料庫系統中，若兩筆交易同時存取「市民帳戶餘額」資料表，交易 A 讀取了交易 B「尚未提交（Uncommitted）」之修改數值，隨後交易 B 發生例外執行了回滾（Rollback），導致交易 A 讀取到無效之幽靈數值，此並發異常現象稱之為？",
         "髒讀（Dirty Read）",
         ["髒讀（Dirty Read）",
          "不可重複讀（Non-repeatable Read）",
          "幻讀（Phantom Read）",
          "更新遺失（Lost Update）"],
         "SQL 交易隔離等級與並發異常：髒讀（Dirty Read）發生於最低隔離等級「讀未提交（Read Uncommitted）」中，讀取到未經最終確認且可能被回滾之髒資料。為防止髒讀，交易隔離等級至少必須提升至「讀已提交（Read Committed）」以上。"),

        ("地方政府「市民線上申辦繳納規費系統」，在多個局處間進行金流扣款交易時，若採用「BASE 模型（Basically Available, Soft state, Eventual consistency）」取代傳統 ACID 強一致性，其核心設計哲學為何？",
         "接受短期內系統內部狀態可能不一致（軟狀態），但透過非同步補償與重試機制，保證在一定時間窗口後最終達到一致性（最終一致性）",
         ["接受短期內系統內部狀態可能不一致（軟狀態），但透過非同步補償與重試機制，保證在一定時間窗口後最終達到一致性（最終一致性）",
          "完全放棄資料庫的任何資料備份機制",
          "資料庫在任何情況下皆保證 100% 絕對強一致性，即使系統永久當機亦在所不惜",
          "強制所有金流交易必須以現金面交完成"],
         "BASE 模型與最終一致性：在大型跨機關分散式高可用系統中，強一致性（ACID/2PC）因各節點阻塞等待容易造成系統極高延遲與脆弱性。BASE 遵循：基本可用（Basically Available）、軟狀態（Soft State，允許中途短暫不一致）、最終一致性（Eventual Consistency）。例如市民繳費後系統顯示「處理中」，背景非同步核銷成功後狀態最終轉為「已繳納」，兼顧高可用與業務安全。"),

        ("某市資訊局推動「資料治理品質衡量指標（Data Quality Framework）」，評估全府資料資產時，國際標準通常定義之六大核心資料品質維度「不包括」下列何者？",
         "資料庫主機螢幕面板之長寬比（Aspect Ratio）",
         ["資料庫主機螢幕面板之長寬比（Aspect Ratio）",
          "完整性（Completeness，資料是否齊全無缺失）",
          "準確性（Accuracy，資料是否真實反映現實世界實體）",
          "一致性（Consistency，不同資料庫間同一數據是否無矛盾衝突）"],
         "資料品質六大核心維度（Data Quality Dimensions）：DAMA-DMBOK 定義核心維度包含：(1) Completeness 完整性（必填欄位非空）；(2) Accuracy 準確性（真實性）；(3) Consistency 一致性（各系統無衝突）；(4) Validity 合法性（符合定義格式）；(5) Timeliness 時效性（資料新鮮度）；(6) Uniqueness 唯一性（無重複冗餘）。螢幕外觀硬體參數完全與資料內容品質無關。"),

        ("地方政府地政空間資料庫儲存地籍界址點，若需評估數千個點位空間分佈之「空間自相關程度」，利用空間權重矩陣（Spatial Weight Matrix, W）定義空間鄰近關係時，最常用之鄰近定義方式為？",
         "K 最近鄰（KNN）或基於固定距離門檻（Fixed Distance Band）之權重矩陣",
         ["K 最近鄰（KNN）或基於固定距離門檻（Fixed Distance Band）之權重矩陣",
          "完全隨機為所有點位指定鄰居關係",
          "依據所有權人姓氏筆畫順序決定相鄰關係",
          "依據土地公告現值金額大小排序決定鄰居關係"],
         "空間權重矩陣（Spatial Weight Matrix）建構：空間統計（如 Moran's I、GWR）必須數學化「空間鄰近度」。對於面要素（行政區）常用 Rook（邊相鄰）或 Queen（邊與頂點相鄰）拓撲矩陣；對於離散點要素（如界址點、觀測井），則採用距離門檻法（Distance Band，距離內 w_ij = 1）或 K 最近鄰法（KNN，確保每個點有固定數量的鄰居），是空間計量之基礎。"),

        ("某縣市交通局之「即時公車動態大數據分析平台」，每日接收數千萬筆 GPS 軌跡。在資料儲存格式上，相較於行導向（Row-oriented，如 CSV）儲存格式，改採「欄導向（Column-oriented，如 Apache Parquet）」之核心分析優勢為何？",
         "針對特定少數欄位（如 <code>SELECT AVG(speed)</code>）查詢時僅需讀取該欄之磁碟區塊，且同欄位同型態資料具備極高之壓縮比，大幅減少 I/O",
         ["針對特定少數欄位（如 <code>SELECT AVG(speed)</code>）查詢時僅需讀取該欄之磁碟區塊，且同欄位同型態資料具備極高之壓縮比，大幅減少 I/O",
          "Parquet 格式只能儲存最多 100 筆資料，超過會自動格式化硬碟",
          "可以在完全沒有任何作業系統的裸機上以純文字查看內容",
          "強制所有資料查詢必須花費至少 10 小時以確保嚴謹"],
         "欄式儲存（Columnar Storage）於 OLAP 分析之絕對優勢：在巨量資料分析中，查詢通常涉及數十個欄位中的少數幾個（如彙總速度與時間），但資料列數高達數千萬。Row-oriented 格式每次查詢必須載入整行所有無關欄位；Parquet/ORC 欄式儲存將同一欄之數據連續存放，利用 Snappy/ZSTD 與字典編碼高度壓縮，並支援下推過濾（Predicate Pushdown），使 OLAP 查詢效能提升數十倍。"),

        ("在地方政府跨機關「主資料管理（MDM, Master Data Management）」專案中，當戶政局之「戶籍地址」與稅捐處之「房屋稅籍地址」在格式上存在細微差異（如「台北市」vs「臺北市」、「一段」vs「1 段」）時，進行資料對齊清洗之關鍵技術為？",
         "實體解析（Entity Resolution）與模糊字串比對演算法（如 Levenshtein 編輯距離、Jaro-Winkler 距離）",
         ["實體解析（Entity Resolution）與模糊字串比對演算法（如 Levenshtein 編輯距離、Jaro-Winkler 距離）",
          "直接隨機刪除其中一個機關的所有地址資料",
          "強制要求所有市民必須在 24 小時內搬遷至新戶籍地址",
          "禁止任何機關在資料庫中儲存任何地址資料"],
         "實體解析（Entity Resolution）與模糊比對：跨機關資料整合常面臨同義異詞與輸入習慣歧異。主資料管理（MDM）利用文字正規化規則替換異體字（臺/台），結合字串相似度演算法（Levenshtein 編輯距離、Jaro-Winkler 演算法）計算相似係數，並結合機器學習模型或地址編碼標準庫，將不同來源之多筆異構紀錄判定為指向現實世界的同一個實體（Record Linkage）。"),

        ("某市工務局針對全縣市橋樑安全監測物聯網系統，資料庫需承載數千組應變規感測器每秒 100Hz 的高頻振動訊號。若欲在前端網頁以 60FPS 流暢呈現即時波形，資料庫與前端傳輸架構應採取何種降載策略？",
         "在邊緣端或中台進行降取樣（Downsampling，如 LTTB 最具代表性三桶演算法）以保持波形視覺特徵，僅傳輸適合螢幕解析度之資料點數",
         ["在邊緣端或中台進行降取樣（Downsampling，如 LTTB 最具代表性三桶演算法）以保持波形視覺特徵，僅傳輸適合螢幕解析度之資料點數",
          "將每秒數萬點之原始數值未經處理直接透過 HTTP JSON 傳送至瀏覽器 DOM 渲染",
          "強制所有工程師以慢動作每分鐘觀察一個點位",
          "將所有橋樑的感測器立即拔除以保護伺服器安全"],
         "時序波形可視化降取樣演算法 LTTB：前端螢幕解析度（如 1920 像素寬度）有限，將每秒數萬點全部傳送至瀏覽器會造成 JSON 膨脹與 Canvas/WebGL 渲染崩潰。LTTB（Largest-Triangle-Three-Buckets）演算法在分桶中尋找面積最大的三角形點，能以極小取樣數（如僅取 1,000 點）完美保留原始波形的高低峰值與視覺特徵，是物聯網時序可視化標準。"),

        ("地方政府水利局在建立水庫防洪決策支援系統時，欲模擬颱風侵襲期間的極端降雨逕流。若採用的水文數值模型（如 HEC-HMS）其輸出結果受輸入降雨參數之不確定性影響極大，水利工程師應採用何種分析方法以估計未來淹水機率分佈？",
         "蒙地卡羅模擬（Monte Carlo Simulation），透過大量隨機抽樣評估不同降雨情境下之淹水機率分佈",
         ["蒙地卡羅模擬（Monte Carlo Simulation），透過大量隨機抽樣評估不同降雨情境下之淹水機率分佈",
          "單一確定性計算，假設未來 100 年的降雨量完全固定為整數 100 毫米",
          "直接由輪值工程師以擲硬幣決定是否開水門",
          "完全放棄預測，等淹水發生後再由里長通報"],
         "蒙地卡羅模擬（Monte Carlo Simulation）不確定性分析：極端天氣事件具備高度隨機性與不確定性。蒙地卡羅模擬透過對輸入變數（如降雨強度、土壤含水量、入流量）之機率分佈進行數千次至數萬次隨機抽樣推演，產製出洪水發生機率分佈曲線與信賴區間（Confidence Interval），為首長防汛決策提供風險機率依據。"),

        ("某市環保局規劃全市民眾垃圾分類智慧回收桶，回收桶內建重量與容積感測器。若希望感測器在電池供電下連續運作 3 年且每天定時回傳數據，最適合之物聯網低功耗廣域通訊技術為？",
         "NB-IoT（窄頻物聯網）或 LoRaWAN，具備長距離、低功耗、低頻寬開銷與深層穿透力",
         ["NB-IoT（窄頻物聯網）或 LoRaWAN，具備長距離、低功耗、低頻寬開銷與深層穿透力",
          "高速 Wi-Fi 6（802.11ax），因其耗電極高且傳輸距離僅數十公尺",
          "藍牙經典模式（Bluetooth Classic），需持續保持高功率配對",
          "光纖寬頻網路，需為每個路邊垃圾桶拉設專屬實體地下光纜"],
         "低功耗廣域網路（LPWAN）特性：智慧城市各類戶外感測器（垃圾桶、路燈、水表、地磁）受限於無市電供應，需仰賴電池長期供電。LPWAN 技術（NB-IoT 使用電信授權頻段，LoRaWAN 使用非授權 ISM 頻段）傳輸速率低（數十 kbps），但待機電流極微（微安培等級），通訊距離可達 5~15 公里，且具備優異地下室穿透力，最符市政需求。"),

        ("在分散式資料庫系統中，若欲防止「分散式鎖（Distributed Lock）」因業務執行時間過長導致鎖提前超時釋放（Lease Expiry），進而造成另一並發客戶端重複獲取鎖引發並發衝突，標準之容錯防護機制為？",
         "看門狗機制（Watchdog）自動為鎖續期（Renewal），或結合漸增版本號防護權杖（Fencing Token）",
         ["看門狗機制（Watchdog）自動為鎖續期（Renewal），或結合漸增版本號防護權杖（Fencing Token）",
          "將鎖的過期時間直接設定為永久永不過期（Infinity）以致死結",
          "完全不設置分散式鎖，由各客戶端隨機搶寫資料庫",
          "在程式碼中加入固定 <code>sleep(60000)</code> 強迫所有執行緒睡眠"],
         "分散式鎖之 Fencing Token 與自動續期：分散式鎖（如基於 Redis Redlock 或 Zookeeper）常因 GC 停頓（Stop-the-World）或網路延遲導致業務尚未執行完畢鎖即過期釋放，產生並發穿透。Martin Kleppmann 提出之安全機制包含：(1) Watchdog 在背景定期檢查並非同步延長 TTL；(2) 儲存端要求客戶端攜帶單調遞增的 Fencing Token，底層資料庫拒絕小於當前最大 Token 的寫入，徹底杜絕舊鎖搶寫。"),

        ("地方政府戶政系統在執行定期資料庫索引維護時，DBA 發現若在大型關聯式資料庫（如 Oracle / PostgreSQL）正式營運期間直接執行 <code>CREATE INDEX</code> 會鎖定全表導致民眾線上申辦掛起。為避免阻斷在線業務，應使用何項指令選項？",
         "<code>CREATE INDEX CONCURRENTLY</code>（並行建構索引），在背景建立索引而不阻塞並行寫入與更新交易",
         ["<code>CREATE INDEX CONCURRENTLY</code>（並行建構索引），在背景建立索引而不阻塞並行寫入與更新交易",
          "直接執行 <code>DROP DATABASE</code> 後再重新建立",
          "在上班尖峰時間直接強制重開資料庫主機",
          "要求全體承辦人員在當天下午全部停止辦公"],
         "並行建構索引（Concurrent Indexing）：在含有數千萬筆紀錄的生產環境核心表上，標準 <code>CREATE INDEX</code> 會獲取 ShareLock，阻塞所有 <code>INSERT/UPDATE/DELETE</code> 交易，嚴重時引發連鎖崩潰。PostgreSQL 提供 <code>CONCURRENTLY</code> 選項（Oracle 為 <code>ONLINE</code>），透過兩次資料表掃描在背景非同步構建索引，全程不阻塞業務讀寫。"),

        ("某市交通局之「市區路口違規科技執法車牌影像資料庫」，每日寫入 50 萬筆高畫質照片記錄。為確保硬碟儲存空間不會在數月內耗盡，依據法規保存期限，資料庫架構應如何設計自動清理策略？",
         "建立基於時間分區之自動化滾動清理腳本，針對保存期滿（如法規規定舉發完成或保存 3 個月）之分區執行高效 <code>DROP TABLE partition</code> 快速釋放實體空間",
         ["建立基於時間分區之自動化滾動清理腳本，針對保存期滿（如法規規定舉發完成或保存 3 個月）之分區執行高效 <code>DROP TABLE partition</code> 快速釋放實體空間",
          "在單一資料表上逐筆執行 <code>DELETE FROM table WHERE date < ...</code> 造成極度龐大交易日誌與鎖定",
          "完全不清理任何資料，等到硬碟爆滿當機再行人工處理",
          "將所有照片直接修改副檔名為 .txt 以節省空間"],
         "大數據生命週期與高效分區刪除：對數億筆的大表執行 <code>DELETE WHERE date < ...</code> 會產生數億條 WAL 日誌，引發長時間 Row-level 鎖定並造成嚴重的 Table Bloat。若資料庫依時間進行了 Partitioning，清理到期歷史資料僅需執行中繼資料操作 <code>DROP TABLE partition_name</code>，可在數毫秒內瞬間完成並完整釋放磁碟空間，不產生任何交易日誌負擔。"),

        ("某縣市地政局進行地籍大數據治理時，欲評估各鄉鎮地籍圖形之「幾何拓撲平滑度與複雜度」。在計算多邊形複雜度（Shape Complexity）時，最標準之幾何指標通常為？",
         "週長面積比（Perimeter-to-Area Ratio）或緊湊度指數（Compactness / Polsby-Popper Score）",
         ["週長面積比（Perimeter-to-Area Ratio）或緊湊度指數（Compactness / Polsby-Popper Score）",
          "地政事務所所長之年齡數值",
          "該筆土地之公告現值除以所有權人數",
          "地籍圖掃描時之印表機型號代碼"],
         "多邊形形狀複雜度指標：地籍宗地若邊界破碎曲折（如選區劃分中的傑利蠑螈 Gerrymandering 或山坡畸零地），會具備較高之形狀複雜度。緊湊度指數（Compactness，如 <code>4 * π * Area / Perimeter^2</code>）評估多邊形接近標準圓形之程度，數值介於 0 到 1 之間，越接近 0 代表形狀越狹長破碎，常用於土地碎化評估與都市形態學分析。"),

        ("地方政府「市民服務儀表板」在設計資料模型時，為加速多維度 OLAP 聚合查詢（如「各月 × 各區 × 各陳情類別之總件數」），預先計算並儲存多維度聚合結果之實體化結構稱之為？",
         "實體化視圖（Materialized View）或 OLAP 多維資料集（Data Cube）",
         ["實體化視圖（Materialized View）或 OLAP 多維資料集（Data Cube）",
          "標準普通視圖（View），因每次查詢仍需即時全表計算",
          "資料庫連線池（Connection Pool）",
          "暫存記憶體快照"],
         "實體化視圖（Materialized View）加速 OLAP：普通 View 僅為儲存的 SQL 查詢別名，每次調用均需重新執行昂貴的聚合與 JOIN。實體化視圖將查詢結果物理儲存於磁碟並支援建立專屬索引，查詢時直接讀取預先計算的彙總結果（秒級響應），並可設定排程（或增量刷新 Fast Refresh）定期同步基礎資料表。"),

        ("在地方政府大數據分析中，若需對全縣市各鄉鎮之「長照需求人口密度」繪製空間分級統計地圖（Choropleth Map）。在統計分類方法中，旨在「最小化組內變異（Within-group variance）且最大化組間變異（Between-group variance）」的最經典自然分級演算法為？",
         "簡克斯自然斷點法（Jenks Natural Breaks Classification）",
         ["簡克斯自然斷點法（Jenks Natural Breaks Classification）",
          "等距分級法（Equal Interval），容易受極端離群值影響造成部分區間完全無數據",
          "等量分級法（Quantile），可能將數值非常相近的數據強行分拆至不同級別",
          "隨機猜測分級法"],
         "統計分圖 Jenks 自然斷點法：製作主題地圖時，分類斷點選擇直接影響視覺認知。Jenks 最佳化演算法類似一維 K-Means，透過反覆迭代計算，尋找方差契合優度（Goodness of Variance Fit, GVF）最大的分組邊界，使同組內的行政區數值盡可能相似，不同組間差異最大，是 GIS 統計製圖最推崇之黃金標準。"),

        ("某市觀光大數據系統分析「歷年燈會期間遊客於各景點之移動路徑鏈（A 景點 → B 景點 → C 景點）」。在資料採礦（Data Mining）領域中，專門用來挖掘此類具有先後次序關係之頻繁樣式演算法為？",
         "序列樣式探勘（Sequential Pattern Mining，如 GSP 或 PrefixSpan 演算法）",
         ["序列樣式探勘（Sequential Pattern Mining，如 GSP 或 PrefixSpan 演算法）",
          "Apriori 關聯規則演算法，僅考慮無序項目集購物籃分析",
          "K-Means 分群演算法",
          "主成分分析（PCA）"],
         "序列樣式探勘（Sequential Pattern Mining）：傳統關聯規則（如 Apriori / FP-Growth）僅分析同一交易或購物籃內「同時購買」的商品，不考慮時間先後次序。序列樣式探勘（如 PrefixSpan、GSP）將時間時序納入評估，專門發掘跨時間序列事件鏈（如民眾辦理結婚登記後，下週常接續申辦生育補助），有助於市府精準規劃便民服務推薦路徑。"),

        ("某縣市主計處建置「公務採購防弊關聯圖譜」，需在數萬家投標廠商、評選委員、得標金額之關係網路中，找出「與特定爭議廠商具備多重複雜借牌人頭關係之核心實體」。圖形資料庫演算法中，用以衡量節點在整個網路中充當「資訊橋樑/樞紐關鍵度」之指標為？",
         "中介中心性（Betweenness Centrality）",
         ["中介中心性（Betweenness Centrality）",
          "度數中心性（Degree Centrality），僅計算直接相連的鄰居數量",
          "親近中心性（Closeness Centrality），計算至其他所有節點之平均最短距離",
          "分頁排名（PageRank）僅考慮連入連結權重"],
         "圖形網路中介中心性（Betweenness Centrality）：在社會網絡與反貪腐調查中，中介中心性衡量「全圖所有節點對之間的最短路徑中，經過該特定節點的次數佔比」。中介中心性極高的節點即便直接連線數不多，亦扮演控制資源流通、人脈轉介與借牌串供之關鍵「掮客（Broker）」角色，為圖演算法舞弊偵測首要標的。"),

        ("地方政府戶政系統在執行大量跨縣市戶籍資料同步時，為防止系統故障重啟時重複執行相同的扣款或登記邏輯，系統設計必須嚴格具備「等冪性（Idempotence）」。在 RESTful API 設計中，下列何種 HTTP 方法天生不具備等冪性？",
         "POST 方法",
         ["POST 方法",
          "GET 方法",
          "PUT 方法",
          "DELETE 方法"],
         "HTTP 等冪性（Idempotence）定義：等冪性指「執行一次與連續執行 N 次所產生的伺服器端系統狀態完全相同」。\n- GET：安全且等冪（單純讀取）；\n- PUT：等冪（替換指定資源，多次執行狀態一致）；\n- DELETE：等冪（刪除指定資源，首次刪除後再次刪除皆不存在）；\n- POST：非等冪（每次調用通常在資料庫新增一筆獨立紀錄，多次重複提交會產生多筆重複紀錄）。在金流扣款中若使用 POST，必須於標頭附加 <code>Idempotency-Key</code> 進行防重防護。")
    ]

    all_datasets = [
        ("GIS 空間資訊系統、PostGIS 空間函數、OGC 標準與國土測繪圖資套疊", gis_spatial_data),
        ("地方巨量資料治理、大數據運算 (Spark/Hadoop)、資料湖與 ETL/ELT 資料管道", bigdata_etl_data),
        ("分散式資料庫、分表分庫 Sharding、一致性雜湊、Open Data 治理與差分隱私/去識別化", db_sharding_privacy_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": "資料庫與空間資訊大數據",
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【地方特考三等實務情境、系統架構與法規深度解析】</strong><br>
<div class="step-box">
  <div class="step-title">🗺️ 地方空間圖資套疊、巨量資料治理與分散式儲存架構推導</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立空間拓撲關係、大數據運算特性（批次/串流）與資料一致性約束</strong><br>
      ‧ 本題依據 OGC 開放地理空間標準、PostGIS 核心拓撲函數及分散式資料庫理論嚴格推導。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>效能瓶頸突破、空間索引機制與最佳軟體工程實務決策</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（空間拓撲運算選用失當、資料庫正規化觀念混淆或引發嚴重效能退化）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（極端不合常理之架構設計或完全失去地理空間分析意義）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非業界主流標準規範或存在重大統計分析偏差）。<br><br>
<strong>地特加分角度</strong>：地方特考三等常結合<strong>地政謄本</strong>、<strong>都市計畫使用分區</strong>、<strong>智慧交通車流</strong>與<strong>防汛淹水潛勢圖</strong>出題。考生作答時應精準寫出 <strong>PostGIS 函數名稱（如 ST_Contains、ST_Intersects、ST_Buffer）</strong> 與 <strong>空間索引（GiST / R-Tree）</strong> 之運作原理，並展現對<strong>資料去識別化（K-Anonymity/差分隱私）</strong>之嚴謹法遵思維。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_local3_part2_questions()
    print(f"Total Part 2 questions generated: {len(qs)}")
