# -*- coding: utf-8 -*-
"""
Part 4 of Programming Fundamentals Bank (程式設計概要題庫擴充 - 第四部分)
主題：物件導向程式設計（OOP）、封裝繼承多型抽象、vtable/vptr 虛擬函式表、虛擬解構子、運算子重載與例外處理
題數：74 題高品質全解析
"""

def get_prog_part4_questions():
    qs = []

    # 1. OOP 四大特性、存取修飾詞與繼承存取控制 (18 題)
    oop_basic_data = [
        ("物件導向程式設計（OOP）的四大核心基礎支柱為何？",
         "封裝（Encapsulation）、繼承（Inheritance）、多型（Polymorphism）與抽象（Abstraction）",
         ["封裝（Encapsulation）、繼承（Inheritance）、多型（Polymorphism）與抽象（Abstraction）",
          "變數、迴圈、條件分支與陣列",
          "指標、堆疊、堆積與快取",
          "類別、結構體、聯合體與列舉"],
         "OOP 四大基石定義：<br>1. 封裝：將資料（屬性）與操作資料的方法（行為）綑綁在一起，透過存取權限隱藏內部實作細節；<br>2. 繼承：子類別可重用父類別的程式碼並進行擴充，建立 is-a 層級關係；<br>3. 多型：同一介面在不同衍生型態實體上展現出不同的具體行為（動態綁定）；<br>4. 抽象：抽出實體的核心特徵而忽略非本質細節，以抽象類別或介面定義契約規範。"),
        ("在 C++ 類別中，成員變數若宣告為 <code>private</code>，則下列何者「可以直接存取」該成員？",
         "僅限該類別內部的成員函式與宣告為 friend 的友善函式或友善類別",
         ["僅限該類別內部的成員函式與宣告為 friend 的友善函式或友善類別",
          "所有繼承該類別的子類別成員函式",
          "main 函式中的任何物件實體",
          "同一命名空間中的所有其他函式"],
         "private 封裝邊界：private 成員具有最嚴格的封裝保護，即使是公開繼承（public inheritance）的衍生子類別亦無法直接存取父類別的 private 成員（子類別必須透過父類別的 public/protected 方法間接存取）。唯一的外力特權例外是類別明確宣告的 <code>friend</code>。"),
        ("在物件導向繼承中，若希望某個父類別成員「不允許外部物件直接存取，但允許子類別繼承並存取」，應使用何種存取修飾詞？",
         "protected（保護存取）",
         ["protected（保護存取）",
          "private（私有存取）",
          "public（公開存取）",
          "static（靜態存取）"],
         "protected 存取修飾詞定位：<code>protected</code> 專為繼承架構量身打造。對外部一般使用者而言它等同於 private（對外封閉防止任意竄改）；對子類別衍生類別而言它等同於 public（對內開放便於程式碼擴充與重用），是框架設計中最關鍵的中介存取層。"),
        ("在 C++ 中，當子類別以「公開繼承（<code>class Derived : public Base</code>）」方式繼承父類別時，父類別中的 public 與 protected 成員在子類別中的存取權限分別變為？",
         "public 成員維持 public，protected 成員維持 protected",
         ["public 成員維持 public，protected 成員維持 protected",
          "全部降級為 private",
          "全部升級為 public",
          "全部變為 protected"],
         "C++ 繼承存取控制矩陣（公有繼承）：<br>‧ public 繼承：父類別 public -> 子類別 public；父類別 protected -> 子類別 protected；父類別 private -> 子類別不可見。<br>公有繼承代表嚴格的「is-a（是一種）」概念，完全符合里斯科夫替換原則（LSP）。"),
        ("在 C++ 中，當子類別以「保護繼承（<code>class Derived : protected Base</code>）」方式繼承時，父類別中的 public 成員在子類別中會轉變為？",
         "protected 成員",
         ["protected 成員",
          "public 成員",
          "private 成員",
          "不可存取的成員"],
         "保護繼承規則：在 <code>protected</code> 繼承下，父類別原本的所有 public 與 protected 成員在衍生類別中全部被壓制降級為 <code>protected</code>。這意味著外部使用者無法再透過子類別物件呼叫父類別的 public 介面，阻斷了對外的 is-a 關係。"),
        ("在 C++ 中，<code>class</code> 與 <code>struct</code> 的最核心唯一語法语意差異為何？",
         "class 的成員與繼承預設存取權限皆為 private；struct 的成員與繼承預設存取權限皆為 public",
         ["class 的成員與繼承預設存取權限皆為 private；struct 的成員與繼承預設存取權限皆為 public",
          "struct 不能包含任何成員函式，class 可以",
          "class 配置在堆積區，struct 配置在堆疊區",
          "struct 不能使用建構子與解構子"],
         "C++ class vs struct 本質：在 C++ 中，struct 已經完全物件導向化，能擁有成員函式、建構子、繼承與多型。兩者唯一的差別在於「預設存取級別」：未加修飾時，class 預設為 <code>private</code>（強調封裝），struct 預設為 <code>public</code>（向 C 語言純資料結構保持向下相容）。"),
        ("在 Java 語言中，若一個類別的成員變數「未加註任何存取修飾詞」（Default / Package-private），其可見度範圍為何？",
         "僅在「同一個 Package（套件）」內的類別可直接存取",
         ["僅在「同一個 Package（套件）」內的類別可直接存取",
          "等同於 public，全世界所有程式碼皆可存取",
          "等同於 private，只有該類別自身可存取",
          "等同於 protected，所有子類別皆可存取"],
         "Java 存取修飾詞四層級：1. <code>public</code>（無限制）；2. <code>protected</code>（同包 + 跨包子類別）；3. <code>default（無修飾詞，包私有）</code>（僅同包內可見）；4. <code>private</code>（僅同類別可見）。注意 Java 的 default 修飾詞限制嚴格於 protected。"),
        ("物件導向設計原則（SOLID）中，「單一職責原則（<span class=\"en\">Single Responsibility Principle, SRP</span>）」的核心精義為？",
         "一個類別應該只有一個引起其改變的原因，意即一個類別只負責一項特定的業務職責",
         ["一個類別應該只有一個引起其改變的原因，意即一個類別只負責一項特定的業務職責",
          "一個專案中只能宣告一個主要類別",
          "每個函式內部只能包含一行敘述",
          "一個類別只能有一個子類別繼承"],
         "SRP 單一職責原則：若一個類別同時負責「訂單計算業務」與「將訂單輸出為 PDF / 寫入資料庫」，則每當報表格式變更或稅率變更時都需要修改該類別，產生高度耦合。拆分為 OrderCalculator 與 OrderPdfExporter 能大幅提高模組內聚力（Cohesion）並降低脆弱性。"),
        ("SOLID 原則中的「開閉原則（<span class=\"en\">Open/Closed Principle, OCP</span>）」指軟體實體應當具備何種特質？",
         "對擴充開放（Open for extension），對修改關閉（Closed for modification）",
         ["對擴充開放（Open for extension），對修改關閉（Closed for modification）",
          "所有原始碼必須開源，編譯後的執行檔必須加密關閉",
          "類別建構子必須開放，解構子必須關閉",
          "隨時允許修改現有程式碼，禁止新增任何新的類別"],
         "OCP 開閉原則：當需求新增時（例如支援新的付款方式：LINE Pay），優秀的設計應當透過「繼承基礎介面新增 LinePayService 子類別（對擴充開放）」來達成，而不是在原本的 PaymentProcessor 核心類別中狂寫無數個 <code>if-else</code>（對修改關閉），從根本避免修改舊代碼引發連帶 Regression Bug。"),
        ("SOLID 原則中的「里斯科夫替換原則（<span class=\"en\">Liskov Substitution Principle, LSP</span>）」核心要求為何？",
         "任何基底類別可以出現的地方，衍生子類別必須能夠透明地無縫替換，且不破壞程式的正確性",
         ["任何基底類別可以出現的地方，衍生子類別必須能夠透明地無縫替換，且不破壞程式的正確性",
          "子類別必須將父類別的所有方法全部重新覆寫一遍",
          "父類別指標必須永遠強制轉型為子類別指標",
          "所有物件實體必須在編譯時由垃圾回收器替換"],
         "LSP 里斯科夫原則：經典的反面教材是「正方形繼承長方形（Square extends Rectangle）」。數學上正方形是長方形，但若長方形提供 <code>setWidth</code> 與 <code>setHeight</code> 獨立設定，在正方形中修改寬會連帶改變高，破壞了呼叫端對長方形行為的預期，違反 LSP。此原則規範了繼承體系必須保證行為相容性。"),
        ("SOLID 原則中的「介面隔離原則（<span class=\"en\">Interface Segregation Principle, ISP</span>）」主張？",
         "不應強迫客戶端依賴它們不需要的肥大介面；應將龐大介面拆分為多個專注的小介面",
         ["不應強迫客戶端依賴它們不需要的肥大介面；應將龐大介面拆分為多個專注的小介面",
          "一個類別不允許實作超過一個以上的介面",
          "介面內部不允許定義任何抽象方法",
          "所有介面必須隔離在獨立的伺服器上執行"],
         "ISP 介面隔離原則：避免建立「胖介面（Fat Interface）」。例如定義了 <code>Worker</code> 介面包含 <code>work()</code> 與 <code>eat()</code>，若有 <code>RobotWorker</code>（機器人工作者）實作該介面，被迫實作空的 <code>eat()</code> 方法。應拆分為 <code>Workable</code> 與 <code>Feedable</code> 兩個專注介面，由實作者按需實作。"),
        ("SOLID 原則中的「依賴反轉原則（<span class=\"en\">Dependency Inversion Principle, DIP</span>）」倡導高階模組與低階模組應如何依賴？",
         "高階模組不應直接依賴低階模組，兩者皆應依賴於抽象（介面）；抽象不應依賴細節，細節應依賴抽象",
         ["高階模組不應直接依賴低階模組，兩者皆應依賴於抽象（介面）；抽象不應依賴細節，細節應依賴抽象",
          "高階模組必須直接呼叫低階模組的具體類別實體",
          "將所有變數依賴關係顛倒排列",
          "取消所有抽象介面，全面改採具體實體直接依賴"],
         "DIP 依賴反轉原則：傳統由高層直接 new 出低層具體類別（如 <code>OrderService</code> 直接 new <code>MySQLDatabase</code>），導致高層與特定底層資料庫緊密死綁。DIP 透過依賴抽象介面 <code>DatabaseInterface</code>，並藉由控制反轉（IoC）與依賴注入（Dependency Injection, DI）在執行期注入實體，達成真正的模組解耦。"),
        ("在物件導向關係中，「組合（<span class=\"en\">Composition</span>）」相較於「繼承（<span class=\"en\">Inheritance</span>）」被設計模式大師倡導「多用組合，少用繼承（Favor object composition over class inheritance）」，其核心優勢為？",
         "組合具備更弱的耦合度（鬆耦合），可以在執行期動態替換內部元件，且不會暴露內部實作細節（黑箱復用）",
         ["組合具備更弱的耦合度（鬆耦合），可以在執行期動態替換內部元件，且不會暴露內部實作細節（黑箱復用）",
          "繼承比組合消耗更少的記憶體且執行速度快 100 倍",
          "組合只能在 C 語言中使用，物件導向語言不支援組合",
          "組合會自動將所有變數轉換為全域變數"],
         "組合 vs 繼承：繼承是編譯期決定的靜態「白箱復用」，子類別深度暴露於父類別實作細節中，父類別一改動子類別牽一髮動全身；組合是「has-a」關係的黑箱復用，物件僅持有其他介面的指標或參照，可在執行時動態置換實體（如策略模式 Strategy Pattern），彈性與維護性遠勝深層繼承鏈。"),
        ("在 C++ 中，關鍵字 <code>friend</code> 的功能與其對封裝的影響為何？",
         "允許外部特定函式或類別直接存取本類別的 private 與 protected 成員；友善關係「不具對稱性」亦「不具傳遞性」",
         ["允許外部特定函式或類別直接存取本類別的 private 與 protected 成員；友善關係「不具對稱性」亦「不具傳遞性」",
          "若 A 是 B 的 friend，則 B 自動成為 A 的 friend",
          "若 A 是 B 的 friend 且 B 是 C 的 friend，則 A 自動是 C 的 friend",
          "friend 關係會被子類別自動無條件繼承"],
         "friend 規則三不原則：1. 單向性（不對稱）：A 宣告 B 是 friend，B 可以看 A 的私有成員，但 A 不能看 B 的私有成員；2. 不傳遞：朋友的朋友不是朋友；3. 不繼承：父類別的朋友不能直接看子類別的私有成員。friend 提供了受控的特權通道（如重載 <code>operator<<</code> 輸出串流），但濫用會削弱封裝性。"),
        ("在類別設計中，「建構子（Constructor）」的核心任務為何？下列敘述何者完全正確？",
         "在建立物件實體時自動被呼叫，負責初始化物件的成員變數與配置必要資源；建構子名稱必須與類別相同且「絕對沒有任何回傳型態（連 void 都不能寫）」",
         ["在建立物件實體時自動被呼叫，負責初始化物件的成員變數與配置必要資源；建構子名稱必須與類別相同且「絕對沒有任何回傳型態（連 void 都不能寫）」",
          "建構子的回傳型態預設為 int，回傳 0 代表建構成功",
          "每個類別只能有一個建構子，不允許任何重載",
          "建構子只能手動以一般函式方式顯式呼叫，無法自動執行"],
         "建構子語法規範：建構子伴隨物件出生而生，語法上不得宣告任何回傳型態（寫 <code>void ClassName()</code> 會被編譯器視為普通函式而非建構子）。支援重載（預設無參建構子、帶參數建構子、複製建構子等）。C++ 推薦使用成員初始化清單（Member Initializer List）進行高效賦值。"),
        ("在類別設計中，「解構子（Destructor）」的主要特徵與任務為何？",
         "在物件生命週期結束銷毀時自動被呼叫，負責釋放動態記憶體、關閉檔案與清理系統資源；名稱為波浪號加類別名（~ClassName），無參數且不可重載",
         ["在物件生命週期結束銷毀時自動被呼叫，負責釋放動態記憶體、關閉檔案與清理系統資源；名稱為波浪號加類別名（~ClassName），無參數且不可重載",
          "解構子可以接收整數參數以指定清理等級",
          "一個類別可以定義多個不同參數簽章的解構子",
          "解構子只會在程式被作業系統強制當機時才會執行"],
         "解構子特性：解構子是 RAII 理念的核心執行者。物件離開範疇（離開大括號或呼叫 delete）時，解構子由系統自動逆序觸發。因為沒有參數，一個類別「有且僅能有一個解構子（不可重載）」。"),
        ("當存在繼承關係時，建立衍生類別物件與銷毀衍生類別物件時，基底類別與衍生類別之「建構子與解構子執行順序」為何？",
         "建構時「基底類別先執行，衍生類別後執行」；銷毀時「衍生類別先執行，基底類別後執行」",
         ["建構時「基底類別先執行，衍生類別後執行」；銷毀時「衍生類別先執行，基底類別後執行」",
          "建構與銷毀皆是基底類別先執行",
          "建構與銷毀皆是衍生類別先執行",
          "建構時衍生類別先執行，銷毀時基底類別先執行"],
         "建構與解構時序對稱原則：<br>1. 建構順序（先有父後有子）：先呼叫 Base 建構子完成地基建設，再呼叫 Derived 建構子擴充。<br>2. 解構順序（先拆子後拆父）：先呼叫 Derived 解構子釋放子類別專屬動態資源，最後呼叫 Base 解構子拆除基礎結構。嚴格遵循先進後出（LIFO）對稱哲學。"),
        ("在 C++ 中宣告類別時，若未手動撰寫任何建構子與解構子，編譯器預設會自動合成哪四個特殊成員函式（Special Member Functions，C++03 標準）？",
         "預設無參建構子、預設解構子、複製建構子（Copy Constructor）與賦值運算子（Copy Assignment Operator）",
         ["預設無參建構子、預設解構子、複製建構子（Copy Constructor）與賦值運算子（Copy Assignment Operator）",
          "列印函式、排序函式、比較函式與重開機函式",
          "虛擬函式表、記憶體配置器、加密解密器與日誌記錄器",
          "編譯器不會自動合成任何成員函式"],
         "編譯器自動合成四大家族：若使用者未自訂，編譯器按需合成預設建構子、解構子、複製建構子（逐成員淺拷貝）與賦值重載 <code>operator=</code>。在 C++11 中又額外增加了移動建構子（Move Constructor）與移動賦值運算子（Move Assignment）。若手動宣告了任何帶參建構子，編譯器便不再自動產生預設無參建構子。")
    ]

    # 2. 虛擬函式、vtable、多型與動態綁定 (19 題)
    poly_data = [
        ("在 C++ 物件導向中，「多型（<span class=\"en\">Polymorphism</span>）」的微觀核心實現依賴哪一項關鍵機制？",
         "虛擬函式（virtual function）與虛擬函式表（vtable / vptr）實現的「動態延遲綁定（Late / Dynamic Binding）」",
         ["虛擬函式（virtual function）與虛擬函式表（vtable / vptr）實現的「動態延遲綁定（Late / Dynamic Binding）」",
          "純文字巨集替換",
          "goto 標籤無條件跳轉",
          "編譯時期將所有類別代碼複製展開"],
         "多型機制剖析：靜態多型（如函式覆載、模板）在編譯期決定呼叫目標（早期綁定 Early Binding）；動態多型（Subtype Polymorphism）允許透過「基底類別指標或參照」指向不同的衍生類別實體，並在執行期根據物件內部真實的 <code>vptr</code> 查詢 <code>vtable</code>，精確呼叫到對應子類別的實作。"),
        ("執行以下包含虛擬函式的 C++ 程式碼：<br><code>class Animal { public: virtual void sound() { cout << \"A\"; } };<br>class Dog : public Animal { public: void sound() override { cout << \"D\"; } };<br>int main() { Animal *p = new Dog(); p->sound(); return 0; }</code><br>終端機輸出的字元為何？",
         "D",
         ["D",
          "A",
          "AD",
          "編譯錯誤"],
         "虛擬函式多型分派追蹤：因為 <code>sound()</code> 在基底類別中被宣告為 <code>virtual</code>，編譯器不會在編譯期綁定 Animal::sound。在執行期，指針 p 指向的實體是 Dog 物件，其記憶體頭部的 vptr 指向 Dog 的虛擬表（包含 Dog::sound 函式位址）。透過指標呼叫時觸發動態綁定，精確執行 Dog::sound() 印出 D。"),
        ("承上題，若將父類別 Animal 中的 <code>virtual</code> 關鍵字移除，維持其他程式碼不變，輸出結果會變為？",
         "A",
         ["A",
          "D",
          "AD",
          "編譯錯誤"],
         "非虛擬函式的靜態早期綁定：若無 <code>virtual</code>，編譯器在編譯階段依據「指標本身的靜態型態（Animal*）」直接將呼叫寫死為 <code>Animal::sound()</code> 的固定二進位位址。即使執行期 p 指向的是 Dog 物件，依然只能執行父類別的非虛擬函式，印出 A。這展示了虛擬函式的根本決定性影響。"),
        ("在 C++ 物件模型中，當一個類別內部宣告了至少一個 <code>virtual</code> 函式時，其物件記憶體實體內部會額外增加何種微觀資料結構？佔用多少記憶體空間？",
         "虛擬函式表指標（vptr），在 64 位元系統下佔用 8 位元組（32 位元下佔 4 位元組）",
         ["虛擬函式表指標（vptr），在 64 位元系統下佔用 8 位元組（32 位元下佔 4 位元組）",
          "會將所有虛擬函式的原始碼字串完整儲存在物件內部",
          "不會增加任何記憶體開銷",
          "額外佔用 1024 位元組快顯記憶體"],
         "vptr 與 vtable 物件模型：每個包含虛擬函式的類別在唯讀資料區擁有一張唯一的「虛擬函式表（vtable）」，儲存各虛擬函式的函式指標清單。該類別的每一個物件實體在建立時，編譯器會在物件的最前端隱含置入一個「vptr（虛擬指標）」，指向該類別的 vtable。因此 <code>sizeof(EmptyClassWithVirtual)</code> 等於一個指標的大小（64-bit 系統下為 8 位元組）。"),
        ("在物件導向設計中，若一個基底類別預期會被其他子類別繼承並透過父類別指標進行多型銷毀，則該基底類別的「解構子」必須宣告為？若漏宣告會導致何種嚴重後果？",
         "必須宣告為虛擬解構子（virtual ~Base()）；若漏宣告，透過父類別指標 delete 子類別物件時只會呼叫父類別解構子，子類別特有動態資源未被釋放導致記憶體洩漏",
         ["必須宣告為虛擬解構子（virtual ~Base()）；若漏宣告，透過父類別指標 delete 子類別物件時只會呼叫父類別解構子，子類別特有動態資源未被釋放導致記憶體洩漏",
          "必須宣告為 private 解構子；漏宣告會引發編譯器語法錯誤",
          "必須宣告為純虛擬解構子且不提供實作；漏宣告會當機",
          "解構子不需要任何修飾，編譯器會自動處理"],
         "虛擬解構子黃金法則：<code>Base *p = new Derived(); delete p;</code>。若 Base 解構子非 virtual，delete 採用靜態綁定只呼叫 <code>~Base()</code>，衍生類別的 <code>~Derived()</code> 根本不會被執行！若 Derived 內部有 malloc 或檔案控制代碼，將永久滯留洩漏。宣告 <code>virtual ~Base() {}</code> 後，delete 透過 vtable 動態分派，先正確呼叫 <code>~Derived()</code> 再呼叫 <code>~Base()</code>，保證完整析構。"),
        ("在 C++ 中，「純虛擬函式（<span class=\"en\">Pure Virtual Function</span>）」的宣告語法為何？包含至少一個純虛擬函式的類別被稱為什麼？",
         "語法為 virtual void func() = 0; 該類別被稱為「抽象類別（Abstract Class）」且無法直接實例化物件",
         ["語法為 virtual void func() = 0; 該類別被稱為「抽象類別（Abstract Class）」且無法直接實例化物件",
          "語法為 void func() = NULL; 該類別被稱為靜態類別",
          "語法為 pure virtual void func(); 該類別被稱為介面類別且只能包含整數",
          "語法為 virtual void func() {} 該類別被稱為模板類別"],
         "純虛擬函式與抽象類別：<code>virtual void draw() = 0;</code> 表明該類別僅定義統一規格介面，不提供預設實作，強制所有具體子類別必須明確覆寫實作該方法。只要含有純虛擬函式，該類別即成為抽象類別，直接嘗試 <code>Shape s;</code> 或 <code>new Shape()</code> 會引發編譯錯誤。但可以合法宣告抽象類別的指標或參照：<code>Shape *p = new Circle();</code>。"),
        ("在 Java 語言中，所有非靜態（Non-static）且非私有（Non-private）的方法，其預設之多型分派行為為何？與 C++ 有何不同？",
         "Java 所有一般方法預設「自動具備虛擬函式（virtual）行為」；而在 C++ 中必須明確手動加上 virtual 關鍵字才具備多型性",
         ["Java 所有一般方法預設「自動具備虛擬函式（virtual）行為」；而在 C++ 中必須明確手動加上 virtual 關鍵字才具備多型性",
          "Java 完全不支援動態多型",
          "Java 必須在方法前加上 virtual 關鍵字",
          "兩者行為完全相同，皆必須手動聲明 virtual"],
         "Java 動態分派哲學：Java 設計時為了降低初學者漏寫 virtual 導致的 bug，規範所有普通方法預設皆為虛擬函式，採用 <code>invokevirtual</code> 字節碼動態分派。若在 Java 中希望禁止子類別覆寫該方法（取消虛擬性），必須手動加上 <code>final</code> 關鍵字修飾。"),
        ("在 C++11 中，引入的兩個關鍵字 <code>override</code> 與 <code>final</code> 的用途分別為？",
         "override 明確指示該方法為覆寫父類別虛擬函式，若簽章不匹配則編譯報錯；final 禁止該虛擬函式被後續子類別覆寫，或禁止類別被繼承",
         ["override 明確指示該方法為覆寫父類別虛擬函式，若簽章不匹配則編譯報錯；final 禁止該虛擬函式被後續子類別覆寫，或禁止類別被繼承",
          "override 用於宣告變數，final 用於重載運算子",
          "override 提高執行速度，final 釋放記憶體",
          "兩者皆為廢除的舊特性"],
         "override 與 final 守衛語意：在大型架構中，若工程師在子類別覆寫父類別虛擬函式時手滑打錯了參數型態（如 <code>virtual void draw(int)</code> 寫成 <code>void draw(long)</code>），若未加 override，編譯器會誤以為這是一個全新的重載函式而靜默通過編譯，導致執行期多型失效。加上 <code>override</code> 讓編譯器強制核對簽章，杜絕低級 Bug。"),
        ("在 C++ 多重繼承（Multiple Inheritance）中，著名的「菱形繼承問題（<span class=\"en\">Diamond Problem</span>）」產生的根本原因與標準解決之道為何？",
         "底層子類別透過兩條不同繼承路徑同時繼承了最頂層父類別的兩份重複成員實體，造成二義性（Ambiguity）；解決方案為中介父類別改採「虛擬繼承（virtual inheritance）」",
         ["底層子類別透過兩條不同繼承路徑同時繼承了最頂層父類別的兩份重複成員實體，造成二義性（Ambiguity）；解決方案為中介父類別改採「虛擬繼承（virtual inheritance）」",
          "類別名稱為菱形時編譯器無法解析語法；解決方案為重新命名類別",
          "多重繼承會耗盡記憶體；解決方案為加大實體記憶體",
          "C++ 嚴格禁止任何多重繼承語法"],
         "菱形繼承與虛擬基礎類別：若 A 為頂層，B 與 C 繼承 A，D 同時繼承 B 與 C。D 實體內會包含兩份獨立的 A 子物件，存取 <code>d.a_member</code> 時編譯器拋出二義性錯誤。若 B 與 C 宣告為 <code>class B : virtual public A</code>，編譯器透過虛擬基底指標（vbptr）共享同一份 A 實體，徹底消解衝突。Java 則透過禁用多重類別繼承、改採多重介面實作（implements Interfaces）從架構層面直接根除該問題。"),
        ("執行以下包含靜態成員變數的 C++ 程式碼片段：<br><code>class Counter { public: static int count; Counter() { count++; } };<br>int Counter::count = 0;<br>int main() { Counter c1, c2, c3; cout << Counter::count; return 0; }</code><br>終端機輸出的數值為何？",
         "3",
         ["3",
          "1",
          "0",
          "編譯錯誤"],
         "靜態成員變數共用性追蹤：<code>static int count;</code> 屬於類別全體物件共享的單一變數（存放在全域資料區，必須在類別外單獨定義初始化 <code>int Counter::count = 0;</code>）。每次建立物件實體時建構子累加 1。建立了 c1, c2, c3 共 3 個實體，count 累計為 3。可透過類別名稱直接存取 <code>Counter::count</code>。"),
        ("下列關於類別「靜態成員函式（<code>static member function</code>）」的特徵與限制，何者完全正確？",
         "靜態成員函式可以直接透過類別名稱呼叫，其內部「不存在 this 指標」，因此無法直接存取非靜態成員變數",
         ["靜態成員函式可以直接透過類別名稱呼叫，其內部「不存在 this 指標」，因此無法直接存取非靜態成員變數",
          "靜態成員函式內部可以隨意存取一般非靜態成員變數",
          "靜態成員函式可以宣告為 virtual 虛擬函式以實現多型",
          "靜態成員函式必須在每個物件實體中各佔一份記憶體"],
         "靜態成員函式特點：一般成員函式底層隱含傳入 <code>this</code> 指標（代表當前物件實體位址）。而 <code>static void foo()</code> 是獨立的類別方法，無需實例即可呼叫，因此編譯器不傳遞 this 指標。因為沒有 this，它無從得知該存取哪一個具體物件的成員變數，故「嚴格禁止存取非 static 成員」，且因無物件實體亦無法成為 virtual 虛擬函式。"),
        ("在 C++ 中，類別成員函式內部的 <code>this</code> 指標之型態與其本質為何？",
         "指向當前物件實體的常數指標（型態為 ClassName * const this）",
         ["指向當前物件實體的常數指標（型態為 ClassName * const this）",
          "指向父類別物件的指標",
          "指向虛擬函式表的雙重指標",
          "全域唯一的作業系統進程指標"],
         "this 指標本質：當呼叫 <code>obj.set(10);</code> 時，編譯器在底層將其轉換為 <code>ClassName::set(&obj, 10);</code>。在函式內部，<code>this</code> 儲存了呼叫物件 <code>&obj</code> 的位址。若成員函式宣告為常數成員函式（<code>void get() const</code>），this 指標的型態進一步收緊為 <code>const ClassName * const this</code>，禁止修改任何成員變數。"),
        ("在 C++ 運算子重載（Operator Overloading）中，若要重載串流輸出運算子 <code>cout << obj</code>，為何該重載函式通常必須實作為「非成員全域函式（常搭配 friend）」而不能是類別的成員函式？",
         "因為串流輸出運算子的左側運算元是 std::ostream（cout），若是成員函式則其左側運算元必須強制為本類別物件",
         ["因為串流輸出運算子的左側運算元是 std::ostream（cout），若是成員函式則其左側運算元必須強制為本類別物件",
          "因為 C++ 語法嚴格禁止重載 << 運算子",
          "因為成員函式執行速度無法跟上螢幕輸出的時脈",
          "因為 ostream 類別無法被繼承"],
         "重載 << 運算子實作準則：雙目運算子若寫成類別成員函式，左運算元必定是呼叫物件 <code>this</code>。若寫成成員函式，使用時必須反人類地寫為 <code>obj << cout;</code>。為了符合標準語法習慣 <code>cout << obj;</code>，第一個參數必須是 <code>ostream&</code>，因此必須實作為全域函式 <code>ostream& operator<<(ostream& os, const MyClass& obj)</code>，並在類別內部加上 friend 授權存取私有變數。"),
        ("下列 C++ 運算子中，哪一組運算子依據語言標準「絕對不允許被重載」？",
         "成員存取點運算子 .、範疇解析運算子 ::、三元條件運算子 ?: 與 sizeof 運算子",
         ["成員存取點運算子 .、範疇解析運算子 ::、三元條件運算子 ?: 與 sizeof 運算子",
          "加減運算子 + -、乘除運算子 * /",
          "比較運算子 == !=、賦值運算子 =",
          "下標運算子 []、函式呼叫運算子 ()"],
         "C++ 不可重載之運算子五虎將：1. <code>.</code>（物件成員存取）；2. <code>.*</code>（成員指標存取）；3. <code>::</code>（作用域解析）；4. <code>?:</code>（三元條件運算子）；5. <code>sizeof</code>（型態大小計算）；外加 <code>typeid</code>。禁止重載這些運算子是為了維護語言核心語法的確定性與安全性。"),
        ("在 C++ 物件導向中，「三法則（<span class=\"en\">Rule of Three</span>）」指當類別涉及動態資源管理時，若手動定義了下列三個函式中的任何一個，通常必須同時明確定義其餘兩個？",
         "解構子（Destructor）、複製建構子（Copy Constructor）與複製賦值運算子（Copy Assignment Operator）",
         ["解構子（Destructor）、複製建構子（Copy Constructor）與複製賦值運算子（Copy Assignment Operator）",
          "建構子、print 函式與 get 函式",
          "靜態成員、虛擬函式與友善函式",
          "main 函式、例外處理器與模板函式"],
         "Rule of Three 深度解析：若類別在堆積中 malloc 了記憶體，解構子中必有 <code>free()</code>。若未自行實作複製建構子與 <code>operator=</code>，編譯器預設的淺拷貝只會複製指標數值，當兩個物件銷毀時會對同一塊記憶體連續呼叫兩次 free，引發致命的 Double Free 崩潰。因此必須同時實作深拷貝複製建構子與防自我賦值的賦值運算子。（C++11 擴充為 Rule of Five，納入移動語意）。"),
        ("執行以下包含 C++ 例外處理（Exception Handling）的程式碼片段：<br><code>try { throw 20; } catch (int e) { cout << e + 5; } catch (...) { cout << \"ERR\"; }</code><br>終端機輸出的數值為何？",
         "25",
         ["25",
          "20",
          "ERR",
          "程式未捕獲例外而崩潰"],
         "try-catch 匹配機制追蹤：<code>throw 20;</code> 拋出一個整數型態的例外物件。執行流程中斷並由上而下掃描 catch 區塊。第一個 catch <code>catch (int e)</code> 精確匹配 int 型態，進入捕獲區塊計算 20 + 5 = 25 並輸出。隨後的萬能捕獲 <code>catch (...)</code> 被略過。"),
        ("在 C++ 例外處理中，萬能捕獲語法 <code>catch (...)</code> 的功能與其在 catch 鏈中的位置規範為何？",
         "捕獲任意型態的所有例外；必須放置在所有具體 catch 區塊的最末尾作為最後防線兜底",
         ["捕獲任意型態的所有例外；必須放置在所有具體 catch 區塊的最末尾作為最後防線兜底",
          "只捕獲字串例外；可以放在最開頭",
          "自動將所有例外消除並重新執行 try 區塊",
          "拋出全新的系統錯誤"],
         "catch(...) 兜底捕獲：三個點 <code>...</code> 代表可匹配任何型態的例外（無論是 int、std::exception 還是自訂型態）。因為 catch 依序匹配，若將 <code>catch(...)</code> 放置於開頭，後續所有的專用 catch 區塊將永遠無法被執行，編譯器會發出警告或報錯。因此它必須作為安全網放在最後。"),
        ("資源取得即初始化（<span class=\"en\">RAII, Resource Acquisition Is Initialization</span>）是 C++ 最核心的資源管理習慣用法，其核心設計哲學為？",
         "在物件的建構子中獲取資源（如記憶體、鎖、檔案控制代碼），並在物件的解構子中自動釋放資源，利用局部物件出棧必然呼叫解構子的特性確保零洩漏",
         ["在物件的建構子中獲取資源（如記憶體、鎖、檔案控制代碼），並在物件的解構子中自動釋放資源，利用局部物件出棧必然呼叫解構子的特性確保零洩漏",
          "在程式啟動時預先將整顆硬碟的資料讀入記憶體",
          "將所有資源全部設定為 public 方便全域存取",
          "強制所有物件在生命週期結束前寫入日誌檔"],
         "RAII 哲學：傳統寫法在 malloc 後若中間程式碼拋出例外或提早 return，很容易忘記呼叫 free 造成洩漏。RAII 將資源生命週期與局部堆疊物件的生命週期死死綁定在一起（例如 <code>std::unique_ptr</code>、<code>std::lock_guard</code>）。即使函式中途拋出例外引發堆疊展開（Stack Unwinding），局部物件的解構子依舊保證 100% 被呼叫釋放資源，從根本根除洩漏。"),
        ("執行以下包含動態多型指標的程式碼：<br><code>class Base { public: virtual void show() { cout << \"B\"; } };<br>class Sub : public Base { public: void show() override { cout << \"S\"; } };<br>void print_it(Base &b) { b.show(); }<br>int main() { Sub s; print_it(s); return 0; }</code><br>終端機輸出的字元為何？",
         "S",
         ["S",
          "B",
          "BS",
          "編譯錯誤"],
         "參照多型（Polymorphism via Reference）：多型動態綁定不僅適用於「父類別指標（Base*）」，同樣完美適用於「父類別參照（Base&）」。在 <code>print_it(Base &b)</code> 中傳入 Sub 物件實體 s，參照底層繫結的是 Sub 的真實實體，呼叫虛擬函式 <code>b.show()</code> 時正確分派執行 <code>Sub::show()</code>，印出 S。")
    ]

    # 3. 建構複製賦值與進階 OOP 概念 (18 題)
    advanced_oop_data = [
        ("在 C++ 中，當類別成員包含「參考型態成員（Reference member）」或「const 常數成員」時，這些成員「必須」在何處進行初始化？",
         "必須在建構子的成員初始化清單（Member Initializer List）中初始化",
         ["必須在建構子的成員初始化清單（Member Initializer List）中初始化",
          "在建構子大括號主體內部使用賦值運算子賦值",
          "在解構子內部進行動態綁定",
          "在 main 函式中宣告全域變數綁定"],
         "成員初始化清單強制場景：因為 <code>const</code> 變數與「參考 <code>&</code>」在語言規範中「一旦建立就必須立即初始化且一生不可再被重新賦值」。建構子大括號內部的代碼屬於「賦值（Assignment）階段」，此時變數早已建立完畢。若未在初始化清單中進行真正的一階初始化，編譯器會強制報錯。"),
        ("執行以下初始化清單順序考題：<br><code>class A { int y; int x; public: A(int val) : x(val), y(x + 1) {} void print() { cout << x << \", \" << y; } };</code><br>在上述類別中，成員變數初始化的真實順序取決於？",
         "取決於成員變數在類別中「宣告的先後順序」（先宣告 y，故先初始化 y），與初始化清單中的書寫順序無關",
         ["取決於成員變數在類別中「宣告的先後順序」（先宣告 y，故先初始化 y），與初始化清單中的書寫順序無關",
          "取決於初始化清單中書寫的順序（先寫 x 故先初始化 x）",
          "由編譯器隨機決定順序",
          "嚴格按照變數名稱的英文字母順序初始化"],
         "成員初始化順序陷阱：C++ 標準規定，類別成員變數的初始化順序「永遠只嚴格依賴於其在 class 內部宣告的先後順序」！在類別中先宣告了 <code>int y;</code> 後宣告 <code>int x;</code>。初始化時會先初始化 y，但此時計算 <code>y(x + 1)</code> 時 x 根本尚未初始化（內容為隨機垃圾值），隨後才初始化 x。這會導致 y 得到未定義的垃圾數據。現代編譯器（-Wall）會對此順序不一致發出警告。"),
        ("在 C++ 類別中，常數成員函式（<code>void display() const;</code>）末尾的 <code>const</code> 修飾詞的核心語意與限制為何？",
         "承諾該函式絕不修改本物件的任何成員變數（除非成員被宣告為 mutable），且常數物件（const object）只能呼叫常數成員函式",
         ["承諾該函式絕不修改本物件的任何成員變數（除非成員被宣告為 mutable），且常數物件（const object）只能呼叫常數成員函式",
          "表示該函式的回傳值永遠為常數",
          "表示該函式只能在多執行緒環境下被常數指標呼叫",
          "將該成員函式轉為靜態成員函式"],
         "const 成員函式與 const 正確性：<code>void get() const;</code> 向使用者保證該方法為唯讀操作。在內部嘗試 <code>x = 10;</code> 會直接被編譯器攔截報錯。若外部建立了一個 <code>const MyClass obj;</code> 常數物件，編譯器為了安全，禁止該物件呼叫任何「非常數成員函式」，只能呼叫標記為 <code>const</code> 的成員函式。"),
        ("在 C++ 類別成員變數前加上 <code>mutable</code> 關鍵字，其最主要用途為何？",
         "允許該成員變數即使在 const 成員函式內部，依然可以被合法修改（常用於執行緒互斥鎖或快取計數器）",
         ["允許該成員變數即使在 const 成員函式內部，依然可以被合法修改（常用於執行緒互斥鎖或快取計數器）",
          "將變數轉換為全域靜態變數",
          "使變數自動具備不可分割的原子性",
          "使變數可以跨網路進行遠端程序呼叫"],
         "mutable 關鍵字特權：在邏輯上物件是唯讀的（對外狀態不變），但底層內部可能需要維護日誌、快取記憶（Cache）或持有執行緒鎖 <code>std::mutex</code>。在 <code>const</code> 函式中上鎖必須修改 mutex 狀態，將其修飾為 <code>mutable std::mutex mtx;</code> 即可在維持介面 const 正確性的同時合法進行內部狀態更新。"),
        ("在 C++ 中，智慧指標（<span class=\"en\">Smart Pointer</span>）<code>std::unique_ptr</code> 的核心所有權語意為何？",
         "獨佔所有權（Exclusive Ownership），同一時間點只能有一個 unique_ptr 擁有該物件，嚴格禁止複製（Copy-disabled）但支援移動（Move-enabled）",
         ["獨佔所有權（Exclusive Ownership），同一時間點只能有一個 unique_ptr 擁有該物件，嚴格禁止複製（Copy-disabled）但支援移動（Move-enabled）",
          "共享所有權，可以任意無限次複製，並維護參照計數",
          "弱引用所有權，隨時可能被作業系統強制回收",
          "不需要管理記憶體，底層由 Java 虛擬機接管"],
         "unique_ptr 語意：<code>std::unique_ptr<T></code> 是零開銷抽象（Zero-cost Abstraction）。建構時擁有，解構時自動 delete。為了防止多重指標指向同實體引發 Double Free，其複製建構子與複製賦值被明確標記為 <code>= delete</code> 禁止複製。若要轉移所有權，必須透過移動語意 <code>std::move(p1)</code> 顯式轉交，兼顧極致效能與現代記憶體絕對安全。"),
        ("在 C++ 智慧指標中，<code>std::shared_ptr</code> 與 <code>std::weak_ptr</code> 的協同運作機制與其解決的核心難題為何？",
         "shared_ptr 透過原子參照計數（Reference Counting）實現共享所有權；weak_ptr 為不增加計數的弱引用，專門用於解決 shared_ptr 彼此互相參照引發的「循環參照（Circular Reference）」記憶體洩漏難題",
         ["shared_ptr 透過原子參照計數（Reference Counting）實現共享所有權；weak_ptr 為不增加計數的弱引用，專門用於解決 shared_ptr 彼此互相參照引發的「循環參照（Circular Reference）」記憶體洩漏難題",
          "shared_ptr 用於整數，weak_ptr 用於浮點數",
          "weak_ptr 執行速度比 shared_ptr 快十倍",
          "兩者皆為廢除的 C++98 舊指標"],
         "循環參照破壞術：若物件 A 持有物件 B 的 <code>shared_ptr</code>，同時物件 B 也持有物件 A 的 <code>shared_ptr</code>。兩者計數永遠為 1，即使外部所有指針皆離開作用域，兩者也永遠無法降為 0，形成死鎖性的記憶體洩漏。將其中一方改為 <code>std::weak_ptr</code>，存取時透過 <code>lock()</code> 臨時升級，打破閉環，確保參照計數歸零正常析構。"),
        ("在物件導向設計模式中，「工廠方法模式（<span class=\"en\">Factory Method Pattern</span>）」的核心價值為？",
         "定義一個建立物件的介面，但讓子類別決定要實例化哪一個具體類別，將物件的實例化過程延遲到子類別",
         ["定義一個建立物件的介面，但讓子類別決定要實例化哪一個具體類別，將物件的實例化過程延遲到子類別",
          "在編譯時將工廠的所有員工名單寫入資料庫",
          "防止程式碼被反組譯工具破解",
          "直接由硬體工廠晶片執行程式碼"],
         "工廠方法設計模式：消除直接耦合的 <code>new ConcreteProduct()</code>。客戶端只需呼叫工廠介面的 <code>createProduct()</code>，若日後新增產品類別，只需擴充對應的工廠子類別即可，完全符合開閉原則（OCP）。"),
        ("在設計模式中，「單例模式（<span class=\"en\">Singleton Pattern</span>）」保證一個類別在整個應用程式中「只有一個實體」，在 C++ 中實現執行緒安全單例的最經典簡潔寫法為？",
         "邁爾斯單例（Meyers' Singleton）：在靜態方法內部定義一個靜態局部變數（static local variable），利用 C++11 保證的靜態變數初始化執行緒安全特性直接回傳",
         ["邁爾斯單例（Meyers' Singleton）：在靜態方法內部定義一個靜態局部變數（static local variable），利用 C++11 保證的靜態變數初始化執行緒安全特性直接回傳",
          "將類別宣告為全域變數並在 main 函式中 new 一百次",
          "將所有建構子公開為 public 讓所有人隨意建立",
          "每次呼叫時建立新物件並隨後刪除"],
         "Meyers' Singleton 典範：<br><code>class Singleton { public: static Singleton& getInstance() { static Singleton instance; return instance; } private: Singleton() {} Singleton(const Singleton&) = delete; };</code><br>將建構子設為 private，禁用複製。C++11 規範靜態局部變數的初始化在多執行緒併發下保證完全線程安全，無需任何昂貴的雙重檢查鎖定（DCLP），優雅且極度高效。"),
        ("在物件導向中，「介面（Interface）」與「抽象類別（Abstract Class）」在現代語言設計中的核心概念區別為？",
         "抽象類別可包含成員變數與具體實作方法（表示 is-a 骨架），僅支援單一繼承；介面純粹定義行為契約（表示 can-do 功能），支援多重實作",
         ["抽象類別可包含成員變數與具體實作方法（表示 is-a 骨架），僅支援單一繼承；介面純粹定義行為契約（表示 can-do 功能），支援多重實作",
          "抽象類別只能在 C 語言使用，介面只能在 Python 使用",
          "介面可以包含狀態變數，抽象類別完全不可包含變數",
          "兩者在概念與實作上完全無任何區別"],
         "介面 vs 抽象類別定位：抽象類別強調「代碼重用與共用繼承狀態骨架（如 <code>Animal</code> 擁有 weight 屬性與 default sleep 實作）」；介面強調「能力的規範與解耦（如 <code>Flyable</code>, <code>Serializable</code>）」。一個類別只能有一個親生父親（單一抽象類別繼承），但可具備多種能力（同時 implements 多個介面）。"),
        ("在 C++ 中，運算子 <code>dynamic_cast</code> 在向下轉型（Downcasting，將父類別指標轉為子類別指標）時，其工作原理與安全性保障為何？",
         "利用執行期型別資訊（RTTI）檢查物件的真實型態，若型態不相容，對指標轉型會傳回 NULL，對參照轉型會拋出 std::bad_cast 例外",
         ["利用執行期型別資訊（RTTI）檢查物件的真實型態，若型態不相容，對指標轉型會傳回 NULL，對參照轉型會拋出 std::bad_cast 例外",
          "在編譯期進行強制暴力位元組轉換，速度極快但可能造成崩潰",
          "自動將父類別物件在記憶體中擴充為子類別大小",
          "只能用於整數與浮點數之間的數值型態轉換"],
         "dynamic_cast 與 RTTI：要使用 <code>dynamic_cast</code>，父類別必須含有至少一個虛擬函式（使物件具備 vtable 與 RTTI 類型描述元）。若執行 <code>Derived *d = dynamic_cast<Derived*>(base_ptr);</code>，系統在執行時查詢 vptr 確認該物件是否真的是 Derived 或其子類。若不是，安全回傳 <code>nullptr</code>，防範非法記憶體越界存取。"),
        ("在 C++ 類型轉換運算子中，<code>static_cast</code>、<code>reinterpret_cast</code> 與 <code>const_cast</code> 的各自專屬用途何者完全正確？",
         "static_cast 用於良性相關型態轉換；reinterpret_cast 用於低階無關型態二進位指標重解釋；const_cast 專門用於移除或增添 const 屬性",
         ["static_cast 用於良性相關型態轉換；reinterpret_cast 用於低階無關型態二進位指標重解釋；const_cast 專門用於移除或增添 const 屬性",
          "const_cast 用於動態多型檢查，static_cast 用於移除 const",
          "reinterpret_cast 是唯一安全的轉型方式，其他皆已被廢除",
          "四種轉型運算子在編譯器底層行為完全相同"],
         "C++ 四大顯式轉型運算子：摒棄 C 風格粗暴的 <code>(Type)expr</code>：1. <code>static_cast</code>（隱式轉換逆過程，如 int 轉 double、向上轉型）；2. <code>dynamic_cast</code>（帶安全檢查的 RTTI 多型向下轉型）；3. <code>const_cast</code>（唯一能剝離 const 唯讀屬性的轉型）；4. <code>reinterpret_cast</code>（底層危險位元組重解釋，如將記憶體位址整數轉為指標）。"),
        ("在 Java/C++ 中，若子類別覆寫父類別的方法，但試圖縮小該方法的存取控制權限（例如父類別方法為 public，子類別覆寫時改為 private），編譯器的處理策略為何？",
         "編譯錯誤；子類別覆寫方法時的存取權限只能擴大或維持，絕對不可縮小，以遵守里斯科夫替換原則（LSP）",
         ["編譯錯誤；子類別覆寫方法時的存取權限只能擴大或維持，絕對不可縮小，以遵守里斯科夫替換原則（LSP）",
          "完全合法，編譯器會自動隱藏父類別方法",
          "編譯器會將該方法自動轉為 protected",
          "程式在執行期拋出 SecurityException"],
         "覆寫存取權限不可變窄法則：若允許子類別將 public 方法改為 private，當外部程式碼透過父類別多型指標 <code>Base b = new Derived(); b.publicMethod();</code> 呼叫時，將發生「介面承諾公開但實體私有拒絕存取」的致命邏輯矛盾，嚴重破壞 LSP 原則。因此物件導向語言強制規範覆寫時可見度只能更開放（如 protected 覆寫為 public），絕不可收緊。"),
        ("執行以下包含拷貝建構子的追蹤題：<br><code>class Box { public: static int count; Box() { count++; } Box(const Box &b) { count += 2; } };<br>int Box::count = 0;<br>void foo(Box b) {}<br>int main() { Box b1; foo(b1); cout << Box::count; return 0; }</code><br>終端機輸出的數值為何？",
         "3",
         ["3",
          "2",
          "1",
          "4"],
         "複製建構子觸發追蹤：1. <code>Box b1;</code> 呼叫預設建構子，count 累加為 1；2. 呼叫 <code>foo(b1)</code> 時，參數為傳值呼叫（Pass by Value），系統會呼叫「複製建構子」將 b1 複製給函式內部參數 b；3. 複製建構子執行 <code>count += 2</code>，count 變為 1 + 2 = 3。印出 3。"),
        ("在 C++ 中，移動語意（Move Semantics，C++11）利用右值參照（Rvalue Reference，<code>Type&&</code>）實現的最根本效能飛躍為？",
         "直接將臨時物件內部的堆積記憶體指標所有權「竊取/移交」給新物件，將深拷貝 O(n) 開銷降為指標賦值的 O(1) 零拷貝極速轉移",
         ["直接將臨時物件內部的堆積記憶體指標所有權「竊取/移交」給新物件，將深拷貝 O(n) 開銷降為指標賦值的 O(1) 零拷貝極速轉移",
          "將物件自動從 CPU 暫存器移動到顯示卡記憶體中",
          "消除所有物件導向類別的建構子",
          "使程式不再需要進行任何編譯直接執行"],
         "右值引用與移動語意：傳統傳回龐大 vector 或字串時，會觸發深拷貝（配置新記憶體、逐元素複製舊內容、釋放舊記憶體）。右值（即將銷毀的臨時物件）透過 <code>std::move</code> 標記，移動建構子只需直接接管舊物件的指標指針（<code>p = other.p; other.p = nullptr;</code>），耗時從毫秒級驟降至納秒級。"),
        ("執行以下 C++ 多型物件指標陣列程式碼：<br><code>class Base { public: virtual int val() { return 1; } };<br>class D1 : public Base { public: int val() override { return 2; } };<br>class D2 : public Base { public: int val() override { return 3; } };<br>int main() { Base *arr[3] = {new Base(), new D1(), new D2()}; int sum = 0; for(int i=0; i<3; i++) sum += arr[i]->val(); cout << sum; return 0; }</code><br>終端機輸出的數值為何？",
         "6",
         ["6",
          "3",
          "5",
          "9"],
         "多型指標陣列巡訪追蹤：透過基底類別指標陣列統一管理異質物件（Heterogeneous Collection）。迴圈巡訪：arr[0] 為 Base 實體，val() 回傳 1；arr[1] 為 D1 實體，多型分派回傳 2；arr[2] 為 D2 實體，多型分派回傳 3。總和 sum = 1 + 2 + 3 = 6。"),
        ("在 Java 中，關鍵字 <code>final</code> 修飾類別（Class）、方法（Method）與變數（Variable）時的語意分別為何？",
         "final 類別禁止被繼承；final 方法禁止被子類別覆寫；final 變數為常數不可再次賦值修改",
         ["final 類別禁止被繼承；final 方法禁止被子類別覆寫；final 變數為常數不可再次賦值修改",
          "final 類別只能在程式最後執行；final 方法傳回值必須為 0；final 變數為全域變數",
          "final 代表該實體即將被垃圾回收器銷毀",
          "三者皆代表對象必須以二進位加密儲存"],
         "Java final 三位一體語意：1. <code>final class String</code>：不可繼承，保證字串不可變性（Immutability）與安全性；2. <code>final void lock()</code>：子類別不可重寫覆寫；3. <code>final int MAX = 100;</code>：常數，一旦初始化便不可再更改參照或數值。"),
        ("在 C++ 中，當自訂類別實作了複製賦值運算子 <code>operator=</code> 時，第一行通常必須撰寫 <code>if (this == &rhs) return *this;</code>，其最關鍵的防護目的為？",
         "自我賦值安全防護（Self-assignment Check）：防止物件在賦值給自己時（如 a = a;），因預先釋放了舊資源而導致讀取到已銷毀的無效記憶體",
         ["自我賦值安全防護（Self-assignment Check）：防止物件在賦值給自己時（如 a = a;），因預先釋放了舊資源而導致讀取到已銷毀的無效記憶體",
          "加速賦值運算子的執行速度十倍",
          "檢查物件是否為 NULL 指標",
          "強制物件必須擁有相同的類別名稱"],
         "自賦值安全陷阱：典型的賦值運算子步驟為：1. 釋放自身的舊動態記憶體（<code>delete[] data;</code>）；2. 根據傳入的 rhs 重新配置空間並複製資料。若發生 <code>a = a;</code> 且無自我賦值檢查，第一步釋放自己的同時也直接摧毀了 rhs 的資料！第二步拷貝時讀取的是懸置野指針垃圾數據，引發致命崩潰。"),
        ("在物件導向程式中，為何推薦優先使用「多型（Polymorphism）」取代程式碼中大量散落的 <code>switch(type) / if(type == TYPE_A)</code> 條件分支判斷？",
         "消除條件分歧硬編碼，將邏輯分散到各子類別實體中，符合開閉原則（新增型態只需增加新子類別，無需修改所有呼叫端的 switch 語句）",
         ["消除條件分歧硬編碼，將邏輯分散到各子類別實體中，符合開閉原則（新增型態只需增加新子類別，無需修改所有呼叫端的 switch 語句）",
          "因為 switch 語句在所有現代 CPU 上都無法被編譯執行",
          "多型會完全消除程式中的所有記憶體佔用",
          "多型能保證所有子類別的執行速度皆為常數時間 O(1)"],
         "Replace Conditional with Polymorphism 重構手法：若使用 switch(shape_type) 分別處理繪圖、面積計算、邊界碰撞，一旦新增一個 Triangle，必須手動找出散落在專案各處的十幾個 switch 語句並全部加上 case，極易遺漏出錯。使用多型 <code>shape->draw();</code>，只需繼承 Shape 實現 Triangle 類別，既有程式碼完全零改動，可維護性產生質的飛躍。")
    ]

    # Combine datasets (18 + 19 + 18 + 19 = 74 questions)
    # Wait, currently 18 + 19 + 18 = 55 questions. Let's add 19 more in advanced_oop_data or another dataset!
    # Let's count advanced_oop_data: 18 items. 18 + 19 + 18 = 55. We need 19 more to reach 74!
    # Let's add dataset 4: python_java_oop_data with 19 questions!

    python_java_oop_data = [
        ("在 Java 物件導向中，所有類別若未明確宣告繼承父類別，其預設之隱含最頂層祖先類別為何？該類別提供的核心方法包含哪些？",
         "java.lang.Object；包含 equals()、hashCode()、toString()、clone() 與 getClass()",
         ["java.lang.Object；包含 equals()、hashCode()、toString()、clone() 與 getClass()",
          "java.lang.Class；包含 main()、start() 與 run()",
          "java.util.Root；包含 add()、get() 與 remove()",
          "Java 不存在單一最頂層祖先類別"],
         "Java 單一根層次架構（Single-rooted Hierarchy）：Java 中一切皆繼承自 <code>Object</code>。這保證了任何物件都可以被向上轉型為 Object，使通用容器（如早期的 ArrayList）能夠容納任意型態物件。<code>equals()</code> 預設比對記憶體位址，通常需與 <code>hashCode()</code> 一同覆寫以支援雜湊容器正確查找。"),
        ("在 Java 中，重寫（Override）<code>equals()</code> 方法時，為何「必須同時重寫 <code>hashCode()</code> 方法」？",
         "遵守物件等價性合約：若兩物件 equals() 判定為相等，則其 hashCode() 傳回之雜湊碼必須完全一致，否則在 HashMap/HashSet 中將無法正確查找",
         ["遵守物件等價性合約：若兩物件 equals() 判定為相等，則其 hashCode() 傳回之雜湊碼必須完全一致，否則在 HashMap/HashSet 中將無法正確查找",
          "若不重寫編譯器會直接拒絕編譯",
          "hashCode() 是作業系統硬體位址，不重寫會導致記憶體溢位",
          "為了加快字串比較的排序速度"],
         "equals 與 hashCode 綁定鐵則：HashMap 依賴 <code>hashCode()</code> 決定資料放在哪個桶子（Bucket），再用 <code>equals()</code> 比對具體物件。若只重寫 equals 而未重寫 hashCode，兩個邏輯相等的物件可能算出生產出不同的 hashCode 散落在不同桶子，導致 <code>map.get(key)</code> 永遠找不到已經存入的資料，破壞集合框架根本運作。"),
        ("在 Python 物件導向中，類別方法的第一個參數慣用命名為 <code>self</code>，其本質意義為？",
         "指向目前正在呼叫該方法的具體物件實體（等同於 C++/Java 中的 this 指標），Python 透過顯式參數傳遞該實體",
         ["指向目前正在呼叫該方法的具體物件實體（等同於 C++/Java 中的 this 指標），Python 透過顯式參數傳遞該實體",
          "Python 語言的核心全域解釋器鎖（GIL）",
          "指向該類別所屬的模組檔案名稱",
          "代表該方法只能由當前檔案存取"],
         "Python self 機制：在 C++/Java 中 <code>this</code> 是隱式傳入的常數指標；而 Python 遵循「顯式優於隱式（Explicit is better than implicit）」哲學，規定物件實體方法的第一個參數必須顯式接收物件實體（慣用命名為 self，但名稱可自訂）。呼叫 <code>obj.foo(10)</code> 時，Python 解釋器底層自動轉換為 <code>MyClass.foo(obj, 10)</code>。"),
        ("在 Python 類別中，魔術方法（Dunder Methods）<code>__init__</code> 與 <code>__new__</code> 的分工關係為何？",
         "__new__ 負責建立並傳回該類別的全新物件實體（建構物件）；__init__ 負責接收已建立的實體並對其成員變數進行初始化",
         ["__new__ 負責建立並傳回該類別的全新物件實體（建構物件）；__init__ 負責接收已建立的實體並對其成員變數進行初始化",
          "__init__ 負責建立物件，__new__ 負責銷毀物件",
          "__init__ 只能在多執行緒下使用，__new__ 只能在單執行緒下使用",
          "兩者語意完全相同，純為版本升級產生的別名"],
         "__new__ vs __init__：<code>__new__(cls)</code> 是一個靜態方法，負責在記憶體中真正分配空間並傳回物件實體（實作單例模式或繼承不可變物件如 int/tuple 時必須重寫 __new__）。一旦 __new__ 傳回該實體，Python 才會自動呼叫 <code>__init__(self, ...)</code> 初始化其內部屬性。"),
        ("在 Python 中，若屬性名稱以「雙底線開頭（如 <code>__private_var</code>）」，Python 解釋器會進行何種處理以防止名稱衝突或外部隨意存取？",
         "名稱修飾（Name Mangling），內部自動將該屬性重新命名為 _ClassName__private_var",
         ["名稱修飾（Name Mangling），內部自動將該屬性重新命名為 _ClassName__private_var",
          "將該變數直接從記憶體中加密為 256 位元雜湊",
          "禁止任何子類別載入該原始檔",
          "在終端機強制拋出 SyntaxError 語法錯誤"],
         "Python 私有屬性偽裝機制：Python 沒有像 C++/Java 那樣硬性的 <code>private</code> 關鍵字。雙底線開頭屬性會觸發 Name Mangling，被解釋器重寫為 <code>_類別名__屬性名</code>。外部若直接存取 <code>obj.__var</code> 會報錯 AttributeError，但若寫 <code>obj._MyClass__var</code> 依然能強行存取。Python 哲學強調「我們都是成年人（We are all consenting adults here）」，以約定代替強制。"),
        ("在 Java 垃圾回收（Garbage Collection, GC）體系中，判定一個物件是否「存活可達」的標準演算法為何？相較於引用計數法（Reference Counting）解決了何種重大弊端？",
         "根節點可達性分析演算法（GC Roots Tracing）；徹底解決了「循環參照（Circular Reference）」無法被自動釋放的記憶體洩漏問題",
         ["根節點可達性分析演算法（GC Roots Tracing）；徹底解決了「循環參照（Circular Reference）」無法被自動釋放的記憶體洩漏問題",
          "冒泡標記演算法；解決了硬碟碎片問題",
          "二分搜尋演算法；加快了 CPU 運算時脈",
          "引用計數演算法；解決了陣列越界問題"],
         "可達性分析與循環參照：引用計數法（如 Python/早期 COM）每個物件記錄被引用次數，但兩物件互相參照時計數永不為 0 造成洩漏。Java 採用根可達性演算法：從一組明確活躍的 <code>GC Roots</code>（執行緒堆疊上的局部變數、靜態全域變數、JNI 引用）開始沿著引用鏈深度優先搜尋。任何從 GC Roots 無法抵達的物件（哪怕它們內部互相參照成死循環），一律被視為垃圾安全回收。"),
        ("在 Java 中，字串類別 <code>String</code> 被設計為「不可變（Immutable）」的核心安全與效能理由為何？",
         "支援字串常數池（String Pool）共享以節省記憶體、保證執行緒安全（Thread-safe）無需加鎖，並防止作為網路連線或檔案路徑參數時被惡意篡改",
         ["支援字串常數池（String Pool）共享以節省記憶體、保證執行緒安全（Thread-safe）無需加鎖，並防止作為網路連線或檔案路徑參數時被惡意篡改",
          "加快字串在硬碟中的寫入速度",
          "使字串可以像整數一樣直接進行加減乘除",
          "強制所有字串長度不得超過 256 個字元"],
         "String 不可變性價值：String 內部 char 陣列為 <code>final private</code> 且無任何修改方法。字串不可變才能安全放進字串池重複複用；作為 HashMap 的 Key 時，其 <code>hashCode</code> 只需計算一次即可永久快取（不必每次重算）；在安全領域，傳入 ClassLoader 或資料庫連線字串時，不用擔心方法執行到一半參數被背景執行緒意外掉包。若需頻繁修改字串應使用 <code>StringBuilder</code>。"),
        ("在 Python 中，方法解析順序（<span class=\"en\">MRO, Method Resolution Order</span>）在多重繼承下用以決定屬性與方法的搜尋優先級，現代 Python 3 採用的演算法為？",
         "C3 線性化演算法（C3 Linearization Algorithm）",
         ["C3 線性化演算法（C3 Linearization Algorithm）",
          "單純深度優先搜尋（DFS）",
          "單純廣度優先搜尋（BFS）",
          "隨機排列演算法"],
         "Python MRO 與 C3 演算法：早期 Python 採深度優先（DFS），在菱形繼承中會先拜訪頂層父類別才拜訪平行子類別，破壞繼承局部優先性。Python 2.3 起全面導入 C3 演算法（可透過 <code>Class.__mro__</code> 查看），保證了「子類別永遠先於父類別檢查」與「保持各繼承宣告的單調性（Monotonicity）」，消除了複雜多重繼承下的解析歧義。"),
        ("在 Python 物件導向中，函式 <code>super()</code> 在呼叫父類別方法時的最核心運作原理為？",
         "依照當前實體的 MRO（方法解析順序）鏈，動態尋找並呼叫下一個相鄰的類別方法，確保在多重繼承中各父類別方法恰好被執行一次",
         ["依照當前實體的 MRO（方法解析順序）鏈，動態尋找並呼叫下一個相鄰的類別方法，確保在多重繼承中各父類別方法恰好被執行一次",
          "永遠固定呼叫代碼中寫在最前面的第一個父類別",
          "重新啟動 Python 解釋器並載入新環境",
          "跳過父類別直接執行作業系統底層 API"],
         "super() 協同多重繼承：在多重繼承中，若每個子類別都硬編碼寫 <code>ParentA.__init__(self)</code>，菱形頂層父類別會被重複執行多次。使用 <code>super().__init__()</code> 是委派給 MRO 佇列中的下一個節點，各層形成一條協同鏈，保證整個菱形樹中每個類別的建構方法精確只被執行一次。"),
        ("在 Java 中，介面（interface）在 Java 8 之後允許定義哪兩種具有「具體程式碼實作」的方法？",
         "預設方法（default method）與靜態方法（static method）",
         ["預設方法（default method）與靜態方法（static method）",
          "私有建構子與抽象解構子",
          "原生組合語言方法與虛擬暫存方法",
          "Java 8 依然嚴格禁止介面包含任何程式碼實作"],
         "Java 8 介面預設方法（Default Methods）：傳統介面一旦發布，若後續要在介面中新增方法，所有成千上萬個舊實作類別全部會編譯報錯（破壞向後相容性）。Java 8 引入 <code>default void forEach(...) { ... }</code> 允許在介面提供預設實作，使舊類別無痛獲得新能力（如集合框架無縫支援 Stream API 與 Lambda 運算）。"),
        ("在 Python 中，裝飾器（<code>@property</code>）的核心用途與軟體工程價值為？",
         "將類別內部的 getter 方法偽裝成一般屬性存取語法，兼顧 Pythonic 的簡潔語法（obj.attr）與封裝校驗邏輯（資料驗證與唯讀保護）",
         ["將類別內部的 getter 方法偽裝成一般屬性存取語法，兼顧 Pythonic 的簡潔語法（obj.attr）與封裝校驗邏輯（資料驗證與唯讀保護）",
          "將屬性自動加密為區塊鏈智能合約",
          "強制所有呼叫端只能透過網路 API 讀取屬性",
          "將變數轉換為硬體唯讀暫存器"],
         "@property 語法糖美學：傳統 Java 寫法到處是 <code>obj.getAge()</code> 與 <code>obj.setAge(20)</code>，代碼冗長。Python 使用 <code>@property</code> 讓呼叫端自然寫 <code>obj.age</code>，而底層自動呼叫對應函式；配合 <code>@age.setter</code> 可以在賦值時執行 <code>if val < 0: raise ValueError</code> 邊界校驗，實現優雅的封裝。"),
        ("在 Java 中，靜態內部類別（static nested class）與非靜態內部類別（inner class）的最核心差別為？",
         "非靜態內部類別隱含持有外部類別實體的參照（Outer.this），可直接存取外部類別的私有成員；靜態內部類別不持有外部實體參照，無法直接存取外部非靜態成員",
         ["非靜態內部類別隱含持有外部類別實體的參照（Outer.this），可直接存取外部類別的私有成員；靜態內部類別不持有外部實體參照，無法直接存取外部非靜態成員",
          "靜態內部類別只能包含靜態變數，無法建立實體",
          "非靜態內部類別只能在 main 函式中宣告",
          "兩者在記憶體配置與語意上完全一致"],
         "內部類別與記憶體洩漏風險：非靜態內部類別物件內部隱含綁定了外部物件實體 <code>Outer.this</code>。若在 Android 開發中將非靜態內部類別（如 Handler 或異步執行緒）傳遞給長生命週期物件，會導致外部 Activity 被隱含參照霸佔而無法被 GC 回收，引發嚴重記憶體洩漏。故最佳實踐通常推薦使用靜態內部類別搭配弱參照 <code>WeakReference</code>。"),
        ("在 Python 物件導向中，魔術方法 <code>__str__</code> 與 <code>__repr__</code> 的設計目標受眾與語意差異為何？",
         "__str__ 是面向終端使用者，追求簡潔美觀與可讀性（print 預設呼叫）；__repr__ 是面向開發者與除錯工具，追求精確與無歧義，理想上其輸出字串應可作為代碼重新 eval() 重建該物件",
         ["__str__ 是面向終端使用者，追求簡潔美觀與可讀性（print 預設呼叫）；__repr__ 是面向開發者與除錯工具，追求精確與無歧義，理想上其輸出字串應可作為代碼重新 eval() 重建該物件",
          "__str__ 只能輸出英文，__repr__ 只能輸出中文",
          "__repr__ 會在物件銷毀時自動呼叫，__str__ 在建立時呼叫",
          "兩者語意完全相同，純屬歷史相容別名"],
         "str vs repr 設計準則：例如日期物件 <code>d = datetime.date(2026, 10, 7)</code>：<br>‧ <code>str(d)</code> 輸出優美的 <code>'2026-10-07'</code> 供使用者閱讀；<br>‧ <code>repr(d)</code> 輸出精確無歧義的 <code>'datetime.date(2026, 10, 7)'</code> 供工程師除錯，並滿足 <code>eval(repr(d)) == d</code>。若類別未實作 __str__，Python 會自動退回呼叫 __repr__。"),
        ("在 Java 異常處理架構中，「受檢異常（Checked Exception）」與「非受檢異常（Unchecked Exception / RuntimeException）」的核心區別為？",
         "Checked Exception（繼承自 Exception 且非 RuntimeException）強制要求程式碼必須明確使用 try-catch 捕獲或 throws 宣告拋出；Unchecked Exception（繼承自 RuntimeException 或 Error）不強制要求顯式處理",
         ["Checked Exception（繼承自 Exception 且非 RuntimeException）強制要求程式碼必須明確使用 try-catch 捕獲或 throws 宣告拋出；Unchecked Exception（繼承自 RuntimeException 或 Error）不強制要求顯式處理",
          "Checked Exception 必定導致系統崩潰，Unchecked Exception 自動被忽略",
          "Checked Exception 只能在編譯器開發時使用，執行時無法使用",
          "所有異常皆為 Checked Exception，Java 不存在非受檢異常"],
         "Java 例外二元分類：Checked Exception（如 <code>IOException</code>, <code>SQLException</code>）代表可預期的環境異常，編譯器在編譯期嚴格監督工程師必須撰寫容錯代碼；Unchecked Exception（如 <code>NullPointerException</code>, <code>ArrayIndexOutOfBoundsException</code>）通常代表程式碼本身的邏輯漏洞（Bug），強行每行都加 try-catch 會破壞代碼乾淨度，故不作編譯強制要求。"),
        ("在 Python 中，類別屬性（Class Attribute）與實體屬性（Instance Attribute）的關鍵作用域差別為何？",
         "類別屬性定義在類別本體內，被該類別的所有物件實體共同共享；實體屬性定義在 __init__ 內（通常以 self.attr 綁定），每個物件實體各自獨立擁有專屬副本",
         ["類別屬性定義在類別本體內，被該類別的所有物件實體共同共享；實體屬性定義在 __init__ 內（通常以 self.attr 綁定），每個物件實體各自獨立擁有專屬副本",
          "類別屬性只能是字串型態，實體屬性只能是整數型態",
          "修改實體屬性會連帶自動修改所有其他實體的屬性值",
          "類別屬性在程式執行結束後自動寫入硬碟"],
         "類別屬性陷阱：若類別屬性是可變物件（如 <code>class Dog: tricks = []</code>），當呼叫 <code>d1.tricks.append('roll')</code> 時，修改的是全體共用的同一個 list，會導致 <code>d2.tricks</code> 也莫名奇妙學會了 'roll'！因此可變容器屬性必須嚴格在 <code>__init__</code> 中以 <code>self.tricks = []</code> 作為實體屬性獨立初始化。"),
        ("在 C++ 中，何謂「抽象類別的純虛擬解構子（Pure Virtual Destructor）」？其在語法上的特殊要求為何？",
         "語法宣告為 virtual ~AbstractBase() = 0; 且「必須在類別外部單獨提供一份函式實作定義」，否則子類別物件在解構時會引發鏈結錯誤",
         ["語法宣告為 virtual ~AbstractBase() = 0; 且「必須在類別外部單獨提供一份函式實作定義」，否則子類別物件在解構時會引發鏈結錯誤",
          "絕不允許提供任何函式實作定義",
          "子類別不允許繼承含有純虛擬解構子的類別",
          "純虛擬解構子會自動取消子類別的解構行為"],
         "純虛擬解構子特殊性：有時希望一個類別成為抽象類別，但類別內部沒有任何合適的業務方法可設為純虛擬，可將解構子設為純虛擬 <code>virtual ~Base() = 0;</code>。但注意：衍生類別析構時，編譯器會自動由下而上連鎖呼叫父類別解構子，若父類別解構子沒有實體代碼，鏈結器會報錯找不到符號。因此即便標記了 <code>= 0</code>，類別外「依然必須寫 <code>Base::~Base() {}</code> 提供空實體」。"),
        ("在物件導向程式碼重構中，「繼承破壞封裝（Inheritance breaks encapsulation）」這句名言的深刻意涵為？",
         "子類別嚴重依賴父類別的具體內部實作細節，父類別任何微小的實作異動（即使介面未改）都極易意外破壞子類別原本正常的業務邏輯",
         ["子類別嚴重依賴父類別的具體內部實作細節，父類別任何微小的實作異動（即使介面未改）都極易意外破壞子類別原本正常的業務邏輯",
          "繼承會使父類別的所有 private 成員全部變成 public",
          "繼承會使編譯器取消所有型態檢查功能",
          "繼承會使程式碼隨機洩漏給網路駭客"],
         "脆弱基類問題（Fragile Base Class Problem）：經典案例：子類別 HashSet 重寫 <code>addAll</code> 計算加入元素總數，而父類別的 <code>addAll</code> 內部實作是逐一呼叫 <code>add</code>。若子類別同時也重寫了 <code>add</code>，會導致元素計數被重複累加兩次！父類別自作主張的內部轉發直接引爆子類別錯誤。因此 Effective Java 強烈建議：除非是專門為繼承而設計且文件規範完備的類別，否則一律使用組合（Composition）包裝。"),
        ("在 Java 虛擬機（JVM）中，類別載入機制採用的「雙親委派模型（<span class=\"en\">Parents Delegation Model</span>）」其核心流程與安全防護目標為何？",
         "當類別載入器收到載入請求時，先委派給父類別載入器處理，逐層向上直至頂層 Bootstrap ClassLoader，只有父載入器無法載入時才自己載入；防止核心 API（如 java.lang.Object）被自訂惡意類別竄改替代",
         ["當類別載入器收到載入請求時，先委派給父類別載入器處理，逐層向上直至頂層 Bootstrap ClassLoader，只有父載入器無法載入時才自己載入；防止核心 API（如 java.lang.Object）被自訂惡意類別竄改替代",
          "強制所有類別必須同時由兩個作業系統執行緒並行載入",
          "使子類別可以隨意重寫 JVM 核心字節碼",
          "將所有載入的類別自動複製到家長控制軟體中"],
         "雙親委派安全屏障：若無雙親委派，駭客可在專案自訂一個名為 <code>java.lang.String</code> 的惡意類別，並植入後門。雙親委派保證任何嘗試載入 <code>java.lang.*</code> 的請求都會先傳送給最頂層的啟動類別載入器（Bootstrap ClassLoader），始終載入 JRE 原裝的核心函式庫，自訂的偽造同名類別直接被忽略，捍衛 Java 沙箱安全性。"),
        ("在 Python 中，「鴨子型別（<span class=\"en\">Duck Typing</span>）」的核心動態多型哲學為？",
         "「如果一隻鳥走起來像鴨子、叫起來像鴨子，那它就是鴨子」；不依賴顯式的繼承繼承關係或型態宣告，只關注物件是否具備所需的特定方法或屬性",
         ["「如果一隻鳥走起來像鴨子、叫起來像鴨子，那它就是鴨子」；不依賴顯式的繼承繼承關係或型態宣告，只關注物件是否具備所需的特定方法或屬性",
          "所有物件導向類別必須以動物名稱命名",
          "動態多型只能在 Python 繪圖套件中實現",
          "Python 在執行期會將所有變數強制造冊登記為抽象類別"],
         "Duck Typing 動態特質：靜態語言（C++/Java）要求多型呼叫必須共享同一繼承父類別或介面。Python 的動態多型只看行為：只要物件實作了 <code>read()</code> 方法，不管它是 <code>File</code> 物件、<code>StringIO</code> 物件、還是 <code>Socket</code> 物件，都可以直接傳入原本處理檔案的函式中無縫運作，賦予動態語言無與倫比的靈活性與泛用性。")
    ]

    all_datasets = [
        ("物件導向四大基礎、存取控制與繼承特性", oop_basic_data),
        ("虛擬函式、vtable 多型分派與解構機制", poly_data),
        ("建構初始化、運算子重載與進階 OOP 概念", advanced_oop_data),
        ("現代多語言物件模型、垃圾回收與設計模式", python_java_oop_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【物件導向程式設計、多型分派機制與現代物件模型深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 物件模型微觀結構、動態綁定時序與軟體架構推導</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立物件導向設計原則（SOLID）、語言規範與虛擬函式表結構</strong><br>
      ‧ 本題依據 C++/Java/Python 物件模型、ISO/IEC 程式語言標準與公職命題大綱嚴格展開。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>執行期狀態追蹤、虛擬指標查表推演與安全性架構剖析</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（存取控制權限混淆或多型分派機制理解偏差）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（繼承結構語意顛倒或解構順序矛盾）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非現代物件導向標準規範之行為或結論錯誤）。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_prog_part4_questions()
    print(f"Total Part 4 questions generated: {len(qs)}")
