# -*- coding: utf-8 -*-
"""
Part 3 of Programming Fundamentals Bank (程式設計概要題庫擴充 - 第三部分)
主題：函式呼叫機制（傳值/傳址/傳參考）、遞迴追蹤（Fibonacci/GCD/河內塔/Ackermann）、呼叫堆疊、變數範疇與生命週期
題數：74 題高品質全解析
"""

def get_prog_part3_questions():
    qs = []

    # 1. 參數傳遞機制（傳值、傳址、傳參考）與回傳值安全性 (18 題)
    param_data = [
        ("執行以下 C 語言數值交換函式程式碼：<br><code>void swap(int a, int b) { int t = a; a = b; b = t; }<br>int main() { int x = 10, y = 20; swap(x, y); printf(\"%d, %d\", x, y); return 0; }</code><br>終端機輸出的結果為何？",
         "10, 20",
         ["10, 20",
          "20, 10",
          "0, 0",
          "編譯錯誤"],
         "傳值呼叫（Call by Value）特性：在 C 語言中，一般基本型態的參數傳遞預設皆為「傳值呼叫」。呼叫 <code>swap(x, y)</code> 時，系統會在 swap 的呼叫堆疊框架中建立獨立的區域變數 a 與 b，並將 x 與 y 的「數值副本」複製進去。函式內部交換的僅是形式參數 a 與 b，對呼叫端的實際參數 x 與 y 完全不造成任何影響。因此印出原本的 10, 20。"),
        ("承上題，若要在 C 語言中真正實現兩變數之數值互換，函式原型與呼叫端應如何正確改寫？",
         "void swap(int *a, int *b); 且呼叫端撰寫 swap(&x, &y);",
         ["void swap(int *a, int *b); 且呼叫端撰寫 swap(&x, &y);",
          "void swap(int &a, int &b); 且呼叫端撰寫 swap(x, y);",
          "int swap(int a, int b); 且呼叫端撰寫 x = swap(y);",
          "void swap(*int a, *int b); 且呼叫端撰寫 swap(*x, *y);"],
         "傳址呼叫（Call by Address / Pointer）：C 語言沒有內建的傳參考語法，要修改外部變數必須透過「傳遞變數的記憶體位址（指標）」。函式接收 <code>int *a, int *b</code>，函式內部透過解參考 <code>int t = *a; *a = *b; *b = t;</code> 直接操作外部實體記憶體；呼叫端則使用取位址運算子 <code>swap(&x, &y);</code>。注意：<code>int &a</code> 是 C++ 語法，非標準 C 語言。"),
        ("在 C++ 語言中，使用「傳參考呼叫（Pass by Reference）」撰寫函式 <code>void swap(int &a, int &b)</code>，呼叫端應如何呼叫？其語法優勢為何？",
         "呼叫端直接寫 swap(x, y); 無需使用 & 取位址，語法乾淨且能直接修改外部實體變數",
         ["呼叫端直接寫 swap(x, y); 無需使用 & 取位址，語法乾淨且能直接修改外部實體變數",
          "呼叫端必須寫 swap(&x, &y);",
          "呼叫端必須寫 swap(*x, *y);",
          "傳參考呼叫會使程式執行速度比傳值慢十倍"],
         "C++ 參考（Reference）特性：參考本質上是外部變數的「別名（Alias）」，底層由編譯器以唯讀指標實作。傳參考參數 <code>int &a</code> 允許呼叫端以直觀自然的 <code>swap(x, y)</code> 呼叫，無需取位址符號，函式內部亦無需加星號解參考，兼具傳值的簡潔語法與傳址的修改能力。"),
        ("執行以下包含回傳危險指標的 C 程式碼：<br><code>int* get_val() { int x = 42; return &x; }<br>int main() { int *p = get_val(); printf(\"%d\", *p); return 0; }</code><br>在標準 C 語言中，此程式碼存在何種致命缺陷？",
         "回傳了指向「區域自動變數（Stack Variable）」的指標，該變數在函式返回後隨即消亡，解參考 *p 引發未定義行為（懸置指標）",
         ["回傳了指向「區域自動變數（Stack Variable）」的指標，該變數在函式返回後隨即消亡，解參考 *p 引發未定義行為（懸置指標）",
          "語法完全合法且安全，保證永遠輸出 42",
          "編譯器會自動將 x 移至全域資料區以防消亡",
          "呼叫端必須使用 free(p) 釋放 x 的記憶體"],
         "區域變數指標回傳禁忌：區域變數 <code>x</code> 配置在函式的呼叫堆疊（Stack Frame）上。當 <code>get_val()</code> 執行完畢返回時，其堆疊框架被釋放標記為無效，隨後的函式呼叫（如 printf）會立即覆蓋該記憶體。此時指標 p 成為指向無效記憶體的「懸置指標（Dangling Pointer）」，解參考 <code>*p</code> 屬於嚴重的 Undefined Behavior。若需跨函式回傳資料，應使用 static 變數或動態配置 malloc。"),
        ("執行以下陣列修改函式：<br><code>void modify(int arr[]) { arr[0] = 99; }<br>int main() { int a[3] = {1, 2, 3}; modify(a); printf(\"%d\", a[0]); return 0; }</code><br>印出的 a[0] 數值為何？",
         "99",
         ["99",
          "1",
          "0",
          "隨機值"],
         "陣列傳遞的傳址退化：在 C 語言中，將陣列名稱作為參數傳入函式時，陣列名稱會自動退化為指向首元素的指標 <code>int *arr</code>。因此 <code>modify(a)</code> 實質上是傳遞了陣列首元素的實體記憶體位址，函式內部修改 <code>arr[0] = 99</code> 就是直接修改 main 函式中陣列 a 的第 0 個元素，故輸出 99。"),
        ("若宣告 C++ 函式 <code>void print_data(const std::string &str);</code>，使用 <code>const &</code> 修飾參數的最主要動機為？",
         "避免傳值呼叫時產生昂貴的物件深拷貝開銷，同時利用 const 確保函式內部無法意外修改該物件",
         ["避免傳值呼叫時產生昂貴的物件深拷貝開銷，同時利用 const 確保函式內部無法意外修改該物件",
          "將字串自動轉換為整數型態以加速處理",
          "強制函式只能在多執行緒環境下執行",
          "使字串可以被多個處理器核心同時寫入"],
         "const Reference 最佳實踐：在 C++ 物件導向中，非基本型態物件（如 string, vector, 自訂類別）若直接傳值（<code>std::string str</code>），呼叫時會觸發複製建構子配置 Heap 記憶體複製內容，代價極高。採用 <code>const &</code> 既享有指標傳址的零拷貝極速效能，又具備唯讀防護，是 C++ API 設計的黃金法則。"),
        ("執行以下預設引數（Default Arguments）的 C++ 程式片段：<br><code>int add(int a, int b = 10, int c = 20) { return a + b + c; }<br>int main() { std::cout << add(5, 5); return 0; }</code><br>終端機輸出的數值為何？",
         "30",
         ["30",
          "35",
          "20",
          "編譯錯誤"],
         "預設參數對齊與匹配規則：呼叫 <code>add(5, 5)</code> 時，第一個引數 5 傳給 a，第二個引數 5 傳給 b（覆蓋其預設值 10），未提供的第三個引數 c 則採用預設值 20。計算結果為 <code>5 + 5 + 20 = 30</code>。注意：C++ 規定預設參數必須「由右至左」連續宣告，中間不可跳空。"),
        ("下列關於 C++ 函式覆載（Function Overloading）的解析機制，何者完全正確？",
         "函式名稱相同，但「參數列的個數或型態」必須不同；編譯器依據參數簽章進行名稱修飾（Name Mangling）區分不同函式",
         ["函式名稱相同，但「參數列的個數或型態」必須不同；編譯器依據參數簽章進行名稱修飾（Name Mangling）區分不同函式",
          "僅依賴回傳值型態不同即可成功達成函式覆載",
          "函式覆載是在程式執行期透過虛擬函式表動態決定的",
          "C 語言原生完全支援函式覆載特性"],
         "函式覆載條件與原理：C++ 編譯器在編譯階段進行 Name Mangling，將參數型態資訊編碼進符號名稱（如 <code>_Z3addii</code> 與 <code>_Z3adddd</code>）。僅僅回傳型態不同（如 <code>int f()</code> 與 <code>double f()</code>）無法重載，因為在呼叫 <code>f();</code> 且不接收回傳值時編譯器無法判定意圖。C 語言符號表中僅有純函式名稱，故 C 語言不支援覆載。"),
        ("若在 C++ 程式中需要呼叫 C 語言編譯生成的靜態函式庫，在標頭檔宣告中必須加上何種修飾語以避免名稱修飾導致連結失敗？",
         "extern \"C\"",
         ["extern \"C\"",
          "static \"C\"",
          "#pragma c_link",
          "inline \"C\""],
         "extern \"C\" 跨語言鏈結相容性：C++ 編譯器會對函式名稱進行 Mangling，而 C 編譯器保留純函式名稱（如 <code>add</code>）。若在 C++ 中直接呼叫 C 函式，鏈結器會尋找修飾後的符號而發生「未定義參考（Undefined Reference）」。加上 <code>extern \"C\" { ... }</code> 指示 C++ 編譯器以 C 語言的純符號規則處理該宣告，實現完美的 C/C++ 互操作。"),
        ("執行以下全域變數與區域變數重名程式碼：<br><code>int val = 100;<br>void test() { int val = 50; printf(\"%d\", val); }<br>int main() { test(); return 0; }</code><br>終端機輸出的結果為？",
         "50",
         ["50",
          "100",
          "0",
          "編譯錯誤"],
         "變數範疇遮蔽（Scope Masking）：當區域變數名稱與全域變數相同時，區域範疇內的變數會屏蔽全域變數。test() 函式內部的 printf 直接存取局部的 val，印出 50。在 C++ 中，若要在局部範疇強行存取被遮蔽的全域變數，可使用全域範疇解析運算子 <code>::val</code>。"),
        ("執行以下包含靜態區域變數的遞迴函式：<br><code>void count_down(int n) { static int s = 0; s += n; if (n > 1) count_down(n - 1); else printf(\"%d\", s); }<br>int main() { count_down(3); return 0; }</code><br>印出的數值為何？",
         "6",
         ["6",
          "3",
          "1",
          "0"],
         "靜態變數在遞迴中的單一共享性：<code>static int s = 0;</code> 在記憶體中只有唯一一份實體，跨越所有遞迴呼叫層級共用。<br>呼叫 count_down(3)：s += 3（s 變為 3），呼叫 count_down(2)；<br>呼叫 count_down(2)：s += 2（s 變為 3+2 = 5），呼叫 count_down(1)；<br>呼叫 count_down(1)：s += 1（s 變為 5+1 = 6），進入 else 印出 s = 6。總和為 3 + 2 + 1 = 6。"),
        ("執行以下程式碼片段：<br><code>int f(int *p) { *p += 5; return *p; }<br>int main() { int x = 10; int y = f(&x) + x; printf(\"%d\", y); return 0; }</code><br>在 C 語言中，此表達式由於引數與運算元存在副作用（Side-effect），其標準評估結果為？",
         "未指定行為（Unspecified Behavior），因為二元加法兩側運算元的求值順序未予規範",
         ["未指定行為（Unspecified Behavior），因為二元加法兩側運算元的求值順序未予規範",
          "嚴格保證輸出 25",
          "嚴格保證輸出 20",
          "編譯階段必定強制報錯"],
         "運算元求值順序與副作用未指定：在 <code>f(&x) + x</code> 中，若編譯器先評估左側 <code>f(&x)</code>，x 被改為 15，式子為 15 + 15 = 30；若編譯器先評估右側 <code>x</code>，取出 10，隨後執行 f(&x) 回傳 15，式子為 15 + 10 = 25。C 規範未規定加法兩側誰先執行，因此不同編譯器可能產生不同結果，應拆解為兩行撰寫。"),
        ("在 C 語言中，若函式未明確寫出回傳值型態（如早期 K&R C 風格 <code>foo() { return 1; }</code>），在舊標準中預設之回傳型態為何？",
         "int",
         ["int",
          "void",
          "char",
          "float"],
         "隱式 int 規則（Implicit int）：在 C89/C90 標準中，若函式未宣告回傳型態，預設假定回傳 <code>int</code>。此寬鬆特性容易隱藏型態不相容 bug，因此在 C99 標準中已徹底廢除「隱式 int」，要求所有函式必須明確標註回傳型態。"),
        ("在 C99/C11 標準中，<code>main()</code> 函式若執行到結尾大括號且未明確撰寫 <code>return</code> 敘述，標準規範之預設行為為何？",
         "編譯器會自動視同執行了 return 0; 代表程式正常終止退出",
         ["編譯器會自動視同執行了 return 0; 代表程式正常終止退出",
          "隨機回傳堆疊中的垃圾值作為退出狀態碼",
          "作業系統會將該程式判定為異常崩潰崩潰",
          "編譯器直接報錯拒絕生成執行檔"],
         "main 函式隱含 return 0 特例：C99 標準第 5.1.2.2.3 節專門為 <code>main()</code> 函式制定了例外規則：若 main 執行流程到達最末尾的 <code>}</code> 而未遇 return，等價於執行 <code>return 0;</code>。但此特權「僅限於 main 函式」，其他有回傳值的非 void 函式若漏寫 return 則屬於嚴格的 Undefined Behavior。"),
        ("下列關於可變參數函式（Variadic Function，如 <code>printf</code>）在 C 語言中的使用規範，何者完全正確？",
         "必須引入 &lt;stdarg.h&gt;，透過 va_list、va_start、va_arg 與 va_end 巨集進行參數提取，且參數列必須有至少一個具名參數",
         ["必須引入 &lt;stdarg.h&gt;，透過 va_list、va_start、va_arg 與 va_end 巨集進行參數提取，且參數列必須有至少一個具名參數",
          "函式原型宣告只需寫 void foo(...); 無需任何具名參數",
          "可以在完全不曉得參數型態的情況下自動提取所有參數",
          "可變參數一律儲存在 CPU 暫存器中無法存取記憶體位址"],
         "可變參數巨集體系：<code>int printf(const char *format, ...);</code>。至少需要一個固定參數（format），因為 <code>va_start(ap, last_arg)</code> 必須藉由最後一個具名參數的記憶體位址來計算第一個可變參數在呼叫堆疊中的偏移量。提取時透過 <code>va_arg(ap, type)</code> 手動指定型態，結束前必須呼叫 <code>va_end(ap)</code> 清理。"),
        ("執行以下包含回傳區域陣列指標的錯誤程式碼：<br><code>char* get_msg() { char str[] = \"Hello\"; return str; }</code><br>呼叫此函式並印出回傳值會發生何種現象？",
         "字串資料可能已被破壞，輸出亂碼或造成程式崩潰",
         ["字串資料可能已被破壞，輸出亂碼或造成程式崩潰",
          "保證永遠完美印出 \"Hello\"",
          "自動將 \"Hello\" 複製到 main 函式中",
          "編譯器保證將其轉為 static 變數"],
         "區域陣列生命週期陷阱：<code>char str[] = \"Hello\";</code> 是在堆疊上配置 6 個位元組並將字串內容拷貝進去。函式返回時 str 記憶體被釋放。若要安全回傳字串常數，應宣告為字串字面常數指標：<code>const char* get_msg() { return \"Hello\"; }</code>，此時字串位於唯讀資料區（ROData），生命週期貫穿程式始末。"),
        ("在 C++ 中，關鍵字 <code>explicit</code> 修飾單一參數的建構子時，其核心防護功能為？",
         "防止編譯器進行隱式型態轉換（Implicit Conversion），強制呼叫端必須明確進行型別轉換或直接初始化",
         ["防止編譯器進行隱式型態轉換（Implicit Conversion），強制呼叫端必須明確進行型別轉換或直接初始化",
          "將該建構子指定為虛擬建構子",
          "允許該建構子被多個執行緒同時並行執行",
          "強制物件只能配置在堆疊區"],
         "explicit 防隱式轉型：例如 <code>class MyString { explicit MyString(int size); };</code>。若無 explicit，當工程師寫 <code>MyString s = 10;</code> 或將整數 10 傳給需要 MyString 的函式時，編譯器會自動將整數 10 轉為字串物件，易引發難以察覺的邏輯缺陷。<code>explicit</code> 強制只能寫 <code>MyString s(10);</code>，避免非預期隱式構造。"),
        ("執行以下函式傳值程式碼：<br><code>void add_one(int x) { x = x + 1; }<br>int main() { int a = 5; add_one(a); printf(\"%d\", a); return 0; }</code><br>終端機輸出的數值為何？",
         "5",
         ["5",
          "6",
          "0",
          "1"],
         "傳值不變性驗證：引數 a 的數值 5 被複製給參數 x。函式內部對 x 的修改完全侷限於 add_one 的內部堆疊框架，退出後框架銷毀，main 函式中的變數 a 始終保持原始數值 5。")
    ]

    # 2. 遞迴演算法追蹤、呼叫堆疊與時間複雜度 (19 題)
    recursion_data = [
        ("執行以下經典遞迴階乘函式：<br><code>int fact(int n) { if (n <= 1) return 1; return n * fact(n - 1); }<br>int main() { printf(\"%d\", fact(4)); return 0; }</code><br>印出的計算結果為何？",
         "24",
         ["24",
          "12",
          "20",
          "120"],
         "階乘遞迴追蹤：<br>fact(4) = 4 * fact(3)<br>= 4 * (3 * fact(2))<br>= 4 * 3 * (2 * fact(1))<br>= 4 * 3 * 2 * 1 = 24。呼叫深度為 4 層堆疊框架。"),
        ("執行以下費氏數列（Fibonacci）遞迴函式：<br><code>int fib(int n) { if (n <= 1) return n; return fib(n - 1) + fib(n - 2); }<br>int main() { printf(\"%d\", fib(5)); return 0; }</code><br>印出的數值為何？此樸素遞迴演算法的時間複雜度為何？",
         "5；時間複雜度為 O(2^n) 指數級",
         ["5；時間複雜度為 O(2^n) 指數級",
          "8；時間複雜度為 O(n)",
          "5；時間複雜度為 O(n log n)",
          "3；時間複雜度為 O(n^2)"],
         "Fibonacci 遞迴追蹤與複雜度：<br>fib(0)=0, fib(1)=1, fib(2)=1, fib(3)=2, fib(4)=3, fib(5)=5。因為每次呼叫衍生兩次子呼叫形成遞迴二元樹，大量重複計算子問題（如 fib(2) 被重複算多次），時間複雜度為指數級 O(2^n)（精確為黃金比例 O(1.618^n)）。公職考試常要求對比「動態規劃（DP）或迭代法可降為 O(n)」之優化策略。"),
        ("執行以下歐幾里得最大公因數（GCD）輾轉相除遞迴函式：<br><code>int gcd(int a, int b) { if (b == 0) return a; return gcd(b, a % b); }<br>int main() { printf(\"%d\", gcd(48, 18)); return 0; }</code><br>輸出的最大公因數為何？",
         "6",
         ["6",
          "12",
          "3",
          "2"],
         "輾轉相除法遞迴追蹤：<br>第 1 層：gcd(48, 18)，b != 0，計算 48 % 18 = 12，遞迴呼叫 gcd(18, 12)；<br>第 2 層：gcd(18, 12)，b != 0，計算 18 % 12 = 6，遞迴呼叫 gcd(12, 6)；<br>第 3 層：gcd(12, 6)，b != 0，計算 12 % 6 = 0，遞迴呼叫 gcd(6, 0)；<br>第 4 層：gcd(6, 0)，b == 0 觸發終止條件，直接回傳 a = 6。連續返回 6。"),
        ("在解決「河內塔（Tower of Hanoi）」問題時，將 n 個圓盤從來源柱 A 借助暫存柱 B 移動至目標柱 C，所需的「最少移動步數」數學公式為何？當 n = 4 時的最少步數為？",
         "2^n - 1；當 n = 4 時為 15 步",
         ["2^n - 1；當 n = 4 時為 15 步",
          "2^n；當 n = 4 時為 16 步",
          "n^2；當 n = 4 時為 16 步",
          "2^(n-1)；當 n = 4 時為 8 步"],
         "河內塔遞迴遞迴關係式推導：<br>移動 n 個盤子步驟：1. 將上面 n-1 個盤子移到暫存柱（T(n-1) 步）；2. 將最大的第 n 個盤子移到目標柱（1 步）；3. 將 n-1 個盤子移到目標柱（T(n-1) 步）。<br>遞迴式：T(n) = 2T(n-1) + 1，基礎條件 T(1) = 1。解特徵方程式可得通式 T(n) = 2^n - 1。當 n = 4 時，2^4 - 1 = 16 - 1 = 15 步。"),
        ("執行以下遞迴演算法追蹤：<br><code>void print_num(int n) { if (n == 0) return; print_num(n - 1); printf(\"%d \", n); }<br>int main() { print_num(3); return 0; }</code><br>終端機輸出的數字序列為？",
         "1 2 3",
         ["1 2 3",
          "3 2 1",
          "0 1 2 3",
          "3 2 1 0"],
         "遞迴「後序/回溯列印」追蹤：注意 printf 位於遞迴呼叫 <code>print_num(n - 1)</code> 之後！<br>呼叫堆疊依序壓入：print_num(3) -> print_num(2) -> print_num(1) -> print_num(0) 觸發 return。<br>開始從呼叫堆疊頂部彈出（回溯）：<br>print_num(1) 印出 1；彈出返回到 print_num(2) 印出 2；彈出返回到 print_num(3) 印出 3。輸出順序為 1 2 3。若 printf 放在遞迴前，輸出則為 3 2 1。"),
        ("執行阿克曼函式（Ackermann Function）程式片段：<br><code>int ack(int m, int n) { if (m == 0) return n + 1; else if (n == 0) return ack(m - 1, 1); else return ack(m - 1, ack(m, n - 1)); }<br>int main() { printf(\"%d\", ack(1, 2)); return 0; }</code><br>終端機印出的數值為？",
         "4",
         ["4",
          "3",
          "5",
          "6"],
         "Ackermann 函式追蹤：<br>1. <code>ack(1, 2) = ack(0, ack(1, 1))</code>；<br>2. 計算 <code>ack(1, 1) = ack(0, ack(1, 0))</code>；<br>3. 計算 <code>ack(1, 0) = ack(0, 1) = 1 + 1 = 2</code>；<br>4. 代回 ack(1, 1)：<code>ack(0, 2) = 2 + 1 = 3</code>；<br>5. 代回 ack(1, 2)：<code>ack(0, 3) = 3 + 1 = 4</code>。Ackermann 函式是非原始遞迴（Non-primitive recursive）的極端高速增長函式，公職常考以檢驗考生的堆疊跟蹤細心度。"),
        ("在編譯器優化中，「尾遞迴（<span class=\"en\">Tail Recursion</span>）」的定義為何？現代編譯器對尾遞迴進行的「尾呼叫消除（TCO）」優化機制為何？",
         "函式的最後一個操作是單純呼叫自己且不帶任何後續計算；編譯器可將其直接重寫為 while 迴圈以重複利用同一個堆疊框架，將空間複雜度由 O(n) 降為 O(1)",
         ["函式的最後一個操作是單純呼叫自己且不帶任何後續計算；編譯器可將其直接重寫為 while 迴圈以重複利用同一個堆疊框架，將空間複雜度由 O(n) 降為 O(1)",
          "函式在開頭第一個敘述就呼叫自己；編譯器會自動取消遞迴改為多執行緒",
          "遞迴終止條件位於函式末尾的寫法；編譯器會提高十倍運算頻率",
          "遞迴呼叫次數小於 10 次的輕量級遞迴；編譯器會直接在記憶體中快取答案"],
         "尾遞迴（Tail Call Optimization, TCO）：一般遞迴（如 <code>return n * fact(n-1);</code>）返回後還要乘以 n，因此必須保留當前棧幀。若改為尾遞迴：<code>int fact_tail(int n, int acc) { if (n <= 1) return acc; return fact_tail(n - 1, n * acc); }</code>，返回時無需任何後續運算，編譯器可直接覆蓋目前棧幀的參數並執行跳轉（JMP），將遞迴徹底消除為迭代迴圈，徹底免疫 Stack Overflow。"),
        ("執行以下字串反轉遞迴函式：<br><code>void rev(char *s) { if (*s == '\\0') return; rev(s + 1); putchar(*s); }<br>int main() { rev(\"CAT\"); return 0; }</code><br>終端機印出的字元序列為？",
         "TAC",
         ["TAC",
          "CAT",
          "ACT",
          "TCA"],
         "利用遞迴呼叫堆疊實現字串反轉追蹤：<br>1. rev(\"CAT\") 壓棧，呼叫 rev(\"AT\")；<br>2. rev(\"AT\") 壓棧，呼叫 rev(\"T\")；<br>3. rev(\"T\") 壓棧，呼叫 rev(\"\")；<br>4. rev(\"\") 遇 '\\0' 返回；<br>5. 依後進先出（LIFO）順序彈出執行 putchar：印出 'T'，接著印出 'A'，最後印出 'C'。輸出 TAC。"),
        ("執行以下遞迴函式追蹤：<br><code>int fun(int n) { if (n <= 1) return 1; if (n % 2 == 0) return fun(n / 2); return fun(n - 1) + 1; }<br>int main() { printf(\"%d\", fun(6)); return 0; }</code><br>終端機印出的數值為？",
         "2",
         ["2",
          "3",
          "1",
          "4"],
         "條件分支遞迴追蹤：<br>1. fun(6)：6 為偶數，呼叫 <code>fun(6 / 2) = fun(3)</code>；<br>2. fun(3)：3 為奇數，呼叫 <code>fun(3 - 1) + 1 = fun(2) + 1</code>；<br>3. fun(2)：2 為偶數，呼叫 <code>fun(2 / 2) = fun(1)</code>；<br>4. fun(1)：滿足 n <= 1，直接回傳 1；<br>5. 代回：fun(2) = 1；fun(3) = 1 + 1 = 2；fun(6) = fun(3) = 2。輸出 2。"),
        ("在程式執行時，引發「堆疊溢位（<span class=\"en\">Stack Overflow</span>）」錯誤最常見的根本程式碼缺陷為？",
         "遞迴函式缺乏基準終止條件（Base Case），或終止條件永遠無法達成，導致遞迴無限呼叫耗盡呼叫堆疊空間",
         ["遞迴函式缺乏基準終止條件（Base Case），或終止條件永遠無法達成，導致遞迴無限呼叫耗盡呼叫堆疊空間",
          "使用 malloc 配置了過大的堆積記憶體",
          "硬碟可用儲存空間不足 1 GB",
          "全域變數宣告了過多的整數常數"],
         "Stack Overflow 成因：每個函式呼叫都會在執行緒的呼叫堆疊（Call Stack，預設大小通常僅 1MB 至 8MB）上推入一個活動記錄（Activation Record）。若遞迴漏寫 <code>if (base_case) return;</code> 或遞迴參數未朝終止條件收斂，堆疊深度無限增加，迅速越界觸發保護頁異常引發 Stack Overflow 崩潰。"),
        ("執行以下計算陣列總和的遞迴函式：<br><code>int sum_arr(int a[], int n) { if (n <= 0) return 0; return a[n - 1] + sum_arr(a, n - 1); }<br>int main() { int a[] = {2, 4, 6}; printf(\"%d\", sum_arr(a, 3)); return 0; }</code><br>輸出的數值為何？",
         "12",
         ["12",
          "6",
          "10",
          "8"],
         "陣列遞迴求和步進追蹤：<br>sum_arr(a, 3) = a[2] + sum_arr(a, 2) = 6 + sum_arr(a, 2)<br>= 6 + (a[1] + sum_arr(a, 1)) = 6 + (4 + sum_arr(a, 1))<br>= 6 + 4 + (a[0] + sum_arr(a, 0)) = 6 + 4 + 2 + 0 = 12。"),
        ("執行以下包含靜態區域變數與遞迴的函式：<br><code>int fun(int n) { static int x = 1; if (n <= 0) return 1; x++; return fun(n - 1) + x; }<br>int main() { printf(\"%d\", fun(2)); return 0; }</code><br>終端機印出的數值為？",
         "7",
         ["7",
          "5",
          "6",
          "4"],
         "靜態變數遞迴呼叫時序深度追蹤：<br>呼叫 fun(2)：x 初始化為 1；x++ 變為 2；準備計算 <code>fun(1) + x</code>；<br>呼叫 fun(1)：x++ 變為 3；準備計算 <code>fun(0) + x</code>；<br>呼叫 fun(0)：滿足 <code>n <= 0</code>，回傳 1；<br>注意回溯時此時 x 的最終值已經是 3！<br>fun(1) 計算：<code>fun(0) + x = 1 + 3 = 4</code>；<br>fun(2) 計算：<code>fun(1) + x = 4 + 3 = 7</code>！輸出 7。這是極具殺傷力的經典考題。"),
        ("二項式係數（組合數 C(n, k)）的帕斯卡三角形遞迴關係式為？",
         "C(n, k) = C(n - 1, k - 1) + C(n - 1, k)；基準條件為 C(n, 0) = C(n, n) = 1",
         ["C(n, k) = C(n - 1, k - 1) + C(n - 1, k)；基準條件為 C(n, 0) = C(n, n) = 1",
          "C(n, k) = C(n - 1, k) * C(n, k - 1)",
          "C(n, k) = C(n - 2, k) + C(n, k - 2)",
          "C(n, k) = n * C(n - 1, k)"],
         "二項式係數遞迴定義（Pascal's Identity）：從 n 個相異物件中選取 k 個，考慮特定第 n 個物件：若選取該物件，則需從剩餘 n-1 個中選取 k-1 個（C(n-1, k-1)）；若不選取該物件，則需從剩餘 n-1 個中選取 k 個（C(n-1, k)）。兩者互斥加總即得 C(n, k)。邊界條件為選 0 個或全選皆只有 1 種可能。"),
        ("執行以下遞迴演算法追蹤：<br><code>int search(int a[], int l, int r, int x) { if (l > r) return -1; int m = l + (r - l) / 2; if (a[m] == x) return m; if (a[m] > x) return search(a, l, m - 1, x); return search(a, m + 1, r, x); }</code><br>此遞迴演算法在最差情況下的時間複雜度與空間複雜度分別為何？",
         "時間複雜度 O(log n)，空間複雜度 O(log n)",
         ["時間複雜度 O(log n)，空間複雜度 O(log n)",
          "時間複雜度 O(n)，空間複雜度 O(1)",
          "時間複雜度 O(log n)，空間複雜度 O(1)",
          "時間複雜度 O(n log n)，空間複雜度 O(n)"],
         "二元搜尋遞迴複雜度分析：每次將搜尋範圍折半，搜尋區間長度序列為 n, n/2, n/4... 直到 1，最多比較 log2(n) 次，故時間複雜度為 O(log n)。由於每次遞迴皆產生一個呼叫堆疊框架，遞迴最大深度為 O(log n)，故遞迴版本的空間複雜度為 O(log n)（若改採迭代 while 迴圈實作則空間複雜度降為 O(1)）。計算中點採 <code>l + (r - l)/2</code> 可防止 <code>(l + r)</code> 整數溢位。"),
        ("執行以下程式碼片段：<br><code>void f(int n) { if (n > 0) { f(n - 1); printf(\"%d \", n); f(n - 1); } }<br>int main() { f(2); return 0; }</code><br>終端機印出的數值序列為？",
         "1 2 1",
         ["1 2 1",
          "2 1 1",
          "1 1 2",
          "2 2 1"],
         "樹狀雙遞迴追蹤：<br>f(2) 展開：<br>1. 先執行 <code>f(1)</code>：<br>   f(1) 展開：f(0) 不做；印出 1；f(0) 不做。故 f(1) 印出 \"1 \"。<br>2. 印出當前層 <code>printf(\"%d \", 2);</code> 印出 \"2 \"。<br>3. 執行後面的 <code>f(1)</code>：同理印出 \"1 \"。<br>合併總輸出為 1 2 1。若呼叫 f(3) 則輸出為 1 2 1 3 1 2 1。"),
        ("執行以下遞迴數值轉換程式碼：<br><code>void bin(int n) { if (n > 1) bin(n / 2); printf(\"%d\", n % 2); }<br>int main() { bin(13); return 0; }</code><br>終端機輸出的二進位數字序列為？",
         "1101",
         ["1101",
          "1011",
          "1110",
          "13"],
         "十進位轉二進位遞迴推導：<br>bin(13) -> bin(6) -> bin(3) -> bin(1)；<br>bin(1) 滿足 n <= 1，印出 1 % 2 = 1；<br>回溯到 bin(3)，印出 3 % 2 = 1；<br>回溯到 bin(6)，印出 6 % 2 = 0；<br>回溯到 bin(13)，印出 13 % 2 = 1。<br>拼接輸出為 1101。因為遞迴是後進先出彈出，剛好由高位元向低位元倒序印出，完美實現進位轉換。"),
        ("下列哪一種問題「先天極適合」使用遞迴思維表達與解決？",
         "具有清晰自我相似（Self-similar）子結構且可拆解為同類型更小子問題的問題（如樹走訪與分治演算法）",
         ["具有清晰自我相似（Self-similar）子結構且可拆解為同類型更小子問題的問題（如樹走訪與分治演算法）",
          "純線性陣列的簡單累加求和問題",
          "硬體中斷即時處理常式（ISR）",
          "記憶體限制極嚴苛（如只有 64 Bytes 堆疊）的微控制器程式"],
         "遞迴適用範疇：遞迴在結構天然具備自我相似性的場景（如二元樹的前/中/後序走訪、圖的深度優先搜尋 DFS、分治演算法 Merge Sort / Quick Sort）極度優雅精簡。但對於純簡單線性掃描，遞迴呼叫開銷過大且有爆棧風險，迭代法更為優選。"),
        ("執行以下遞迴函式：<br><code>int f(int a, int b) { if (a == 0) return b; return f(a - 1, a + b); }<br>int main() { printf(\"%d\", f(3, 2)); return 0; }</code><br>輸出的數值為何？",
         "8",
         ["8",
          "5",
          "7",
          "6"],
         "累加遞迴追蹤：<br>1. f(3, 2) = f(3 - 1, 3 + 2) = f(2, 5)；<br>2. f(2, 5) = f(2 - 1, 2 + 5) = f(1, 7)；<br>3. f(1, 7) = f(1 - 1, 1 + 7) = f(0, 8)；<br>4. f(0, 8) 觸發 a == 0，直接回傳 b = 8。輸出 8。"),
        ("呼叫堆疊（Call Stack）的「活動記錄（<span class=\"en\">Activation Record / Stack Frame</span>）」中，通常包含哪些關鍵欄位？",
         "返回位址（Return Address）、前一個框架指標（Frame Pointer / EBP）、函式引數（Parameters）與區域變數（Local Variables）",
         ["返回位址（Return Address）、前一個框架指標（Frame Pointer / EBP）、函式引數（Parameters）與區域變數（Local Variables）",
          "全域變數副本、CPU 快顯記憶體內容、硬碟分割表",
          "網路 IP 標頭、DNS 快取紀錄、作業系統核心原始碼",
          "編譯器原始碼、符號表、字串常數池"],
         "Stack Frame 結構剖析：每次函式呼叫時，CPU 壓入：1. 返回位址（函式結束後下一條指令位址）；2. 舊基底指標（Old EBP/RBP）；3. 函式傳入的引數；4. 函式內部的區域自動變數。函式返回時依賴這些資訊將 CPU 暫存器還原回呼叫端的執行狀態。")
    ]

    # 3. 變數範疇、生命週期與連結性 (18 題)
    scope_data = [
        ("C 語言中，全域變數（Global Variable）若未明確指定初始值，其預設之初始值為何？與未初始化的區域變數（Local Variable）有何不同？",
         "全域變數自動被編譯器初始化為 0（或 NULL）；未初始化的區域變數內容為記憶體殘留垃圾值",
         ["全域變數自動被編譯器初始化為 0（或 NULL）；未初始化的區域變數內容為記憶體殘留垃圾值",
          "兩者皆預設為 0",
          "兩者皆為未定義垃圾值",
          "全域變數預設為 -1，區域變數預設為 0"],
         "BSS 段與 Stack 記憶體初始化差異：全域變數與靜態變數存放在 BSS 段（Block Started by Symbol），作業系統載入程式時保證將整個 BSS 段分頁映射為乾淨的二進位零。而區域自動變數配置於 Stack 堆疊，堆疊僅移動棧指針（ESP/RSP），不執行任何清理操作，原本記憶體殘留什麼二進位內容，變數的值就是什麼。"),
        ("執行以下包含區塊範疇（Block Scope）的程式碼片段：<br><code>int i = 0;<br>for (int i = 0; i < 3; i++) { int i = 10; printf(\"%d \", i); i++; }</code><br>迴圈執行時終端機輸出的數字序列為？",
         "10 10 10",
         ["10 10 10",
          "10 11 12",
          "0 1 2",
          "編譯錯誤，變數重複宣告"],
         "巢狀作用域同名變數覆蓋：for 迴圈內層大括號中宣告了全新的區域變數 <code>int i = 10;</code>。在每次迴圈迭代中，它都重新被建立並初始化為 10，printf 印出 10，隨後的 <code>i++</code> 修改的只是這個內層的 i（變為 11），不影響 for 迴圈控制計步器的 i。每次迴圈都印出 10，共 3 次，輸出 10 10 10。"),
        ("C 語言中的變數儲存期（Storage Duration）共分為哪四種類型？",
         "靜態儲存期（Static）、自動儲存期（Automatic）、動態配置儲存期（Allocated）與執行緒儲存期（Thread）",
         ["靜態儲存期（Static）、自動儲存期（Automatic）、動態配置儲存期（Allocated）與執行緒儲存期（Thread）",
          "唯讀儲存期、可寫儲存期、加密儲存期、網路儲存期",
          "堆疊儲存期、硬碟儲存期、光碟儲存期、磁帶儲存期",
          "整數儲存期、浮點儲存期、字元儲存期、結構體儲存期"],
         "四種標準儲存期（Storage Duration）：1. Automatic（一般區域變數，離開區塊即釋放）；2. Static（全域與 static 變數，程式執行始末皆存活）；3. Allocated（malloc 動態配置，直到 free 釋放）；4. Thread（C11 _Thread_local，執行緒生命週期）。"),
        ("若在不同原始檔 <code>file1.c</code> 與 <code>file2.c</code> 中分別宣告了 <code>int g_var = 10;</code> 與 <code>int g_var = 20;</code>，在進行程式編譯鏈結時會發生何種現象？",
         "鏈結錯誤（Linker Error）：符號重複定義（Multiple Definition of g_var）",
         ["鏈結錯誤（Linker Error）：符號重複定義（Multiple Definition of g_var）",
          "編譯器會自動隨機選擇其中一個使用",
          "程式正常編譯，兩個變數自動合併為同一個",
          "變數值自動相加為 30"],
         "強符號與重複定義規則：在 C 語言中，帶初始值的全域變數屬於「強符號（Strong Symbol）」。鏈結器在合併多個目標檔（.o）時，若發現同一個強符號被重複定義兩次，會拋出致命的 Linker Error。解決之道是只在一個檔案中定義，其他檔案改用 <code>extern int g_var;</code> 宣告，或在單檔中宣告為 <code>static int g_var;</code> 限制其內部鏈結。"),
        ("執行以下靜態指標程式碼：<br><code>int* get_static() { static int a = 100; return &a; }<br>int main() { int *p = get_static(); *p += 50; printf(\"%d\", *get_static()); return 0; }</code><br>終端機輸出的數值為何？",
         "150",
         ["150",
          "100",
          "50",
          "未定義錯誤"],
         "回傳 static 區域變數指標的合法性：<code>static int a = 100;</code> 存放在全域資料區，函式結束後其生命週期依然延續，記憶體位址持續有效。因此回傳其指標完全安全！呼叫端透過 <code>*p += 50</code> 將其數值修改為 150，下一次再次呼叫 <code>get_static()</code> 時，讀取到的即是修改後的數值 150。"),
        ("在 C 語言程式架構中，記憶體空間由低位址向高位址劃分的經典五大記憶體區段依序為何？",
         "代碼區段（Text） -> 已初始化資料區段（Data） -> 未初始化資料區段（BSS） -> 堆積區（Heap） -> 堆疊區（Stack）",
         ["代碼區段（Text） -> 已初始化資料區段（Data） -> 未初始化資料區段（BSS） -> 堆積區（Heap） -> 堆疊區（Stack）",
          "堆疊區（Stack） -> 堆積區（Heap） -> BSS 區 -> Data 區 -> Text 區",
          "Heap 區 -> Stack 區 -> Text 區 -> Data 區 -> BSS 區",
          "BIOS 區 -> 核心區 -> 應用程式區 -> 快取區 -> 虛擬記憶體區"],
         "進程虛擬記憶體佈局標準：最低位址為 Text（機器碼指令，唯讀）-> Data（已初始化的全域與 static 變數）-> BSS（未初始化的全域與 static 變數，清零）-> Heap（向高位址動態向上生長）-> 自由空間 -> Stack（從高位址向低位址向下生長）。兩者中間預留足夠空間互相靠近。"),
        ("當程式執行時呼叫過多的函式，導致堆疊空間向下生長撞擊到堆積空間的邊界時，會觸發何種致命例外？",
         "堆疊溢位（Stack Overflow）",
         ["堆疊溢位（Stack Overflow）",
          "堆積溢位（Heap Overflow）",
          "除以零例外（Divide by Zero）",
          "快取失誤（Cache Miss）"],
         "Stack 與 Heap 碰撞保護：早期系統中堆疊與堆積朝相反方向生長，若兩者相撞會引發資料互相覆蓋毀損。現代作業系統在堆疊與堆積之間設置了受 MMU 硬體保護的防護頁（Guard Page），一旦堆疊指針觸及無權限的防護頁，作業系統立刻拋出記憶體分頁錯誤（Page Fault），終止程式並報錯 Stack Overflow。"),
        ("執行以下遞迴階乘的尾遞迴版本追蹤：<br><code>int fact_tr(int n, int a) { if (n <= 1) return a; return fact_tr(n - 1, n * a); }<br>int main() { printf(\"%d\", fact_tr(4, 1)); return 0; }</code><br>輸出的數值為何？",
         "24",
         ["24",
          "12",
          "4",
          "1"],
         "尾遞迴累加器步進追蹤：<br>1. fact_tr(4, 1) -> 呼叫 fact_tr(3, 4 * 1) = fact_tr(3, 4)；<br>2. fact_tr(3, 4) -> 呼叫 fact_tr(2, 3 * 4) = fact_tr(2, 12)；<br>3. fact_tr(2, 12) -> 呼叫 fact_tr(1, 2 * 12) = fact_tr(1, 24)；<br>4. fact_tr(1, 24) 滿足 n <= 1，直接回傳累加器 a = 24。輸出 24。"),
        ("在 C 語言中，若函式宣告為 <code>inline</code>，但在程式中對該 inline 函式取了函式指標位址（Function Pointer），編譯器的處理策略為何？",
         "編譯器會為該函式生成一份常規的實體二進位函式實體，以便提供有效的記憶體位址給指標使用",
         ["編譯器會為該函式生成一份常規的實體二進位函式實體，以便提供有效的記憶體位址給指標使用",
          "編譯器會直接報錯禁止對 inline 函式取位址",
          "函式指標的值會被強制設定為 NULL",
          "該函式會自動被轉為巨集"],
         "inline 函式取位址機制：inline 僅是向編譯器的優化建議。若程式碼中出現 <code>&func</code>，因為函式指標必須儲存真實的記憶體位址，編譯器會自動為該 inline 函式產生一個常規的具外鏈或內鏈的二進位代碼區段實體，完全兼顧優化與語法完整性。"),
        ("執行以下程式碼片段：<br><code>int a = 1; { int a = 2; { int a = 3; printf(\"%d \", a); } printf(\"%d \", a); } printf(\"%d\", a);</code><br>終端機輸出的數字序列為？",
         "3 2 1",
         ["3 2 1",
          "1 2 3",
          "3 3 3",
          "1 1 1"],
         "三層巢狀區塊作用域追蹤：最內層優先匹配最內層的 a=3，印出 3；離開最內層後進入中層，存取 a=2，印出 2；離開中層進入最外層，存取 a=1，印出 1。輸出 3 2 1。"),
        ("在 C++ 中，命名空間（<code>namespace</code>）最核心的軟體工程功用為？",
         "解決大型軟體專案中不同模組、函式庫之間的全域識別碼名稱衝突（Name Collisions）問題",
         ["解決大型軟體專案中不同模組、函式庫之間的全域識別碼名稱衝突（Name Collisions）問題",
          "提高程式碼在 CPU 中的硬體執行頻率",
          "將變數自動加密防止被記憶體分析工具窺探",
          "將程式碼自動編譯為動態連結檔"],
         "命名空間價值：在大型專案或同時引入多個第三方函式庫時，很容易出現兩家廠商都定義了名為 <code>Logger</code> 或 <code>Matrix</code> 的類別。透過 <code>namespace CompanyA { ... }</code> 與 <code>namespace CompanyB { ... }</code> 進行邏輯分組，使用時以 <code>CompanyA::Logger</code> 明確區分，徹底消除名稱衝突。"),
        ("執行以下包含 C++ 參照的程式碼：<br><code>int x = 10; int &ref = x; ref = 20; printf(\"%d, %d\", x, ref);</code><br>輸出的兩個數值分別為何？",
         "20, 20",
         ["20, 20",
          "10, 20",
          "20, 10",
          "10, 10"],
         "C++ 參照本質推導：<code>int &ref = x;</code> 宣告 ref 是 x 的別名（二者佔據完全相同的記憶體位址）。修改 <code>ref = 20</code> 就是直接修改 x 的本體。因此 x 與 ref 兩者的值皆同步變為 20。"),
        ("關於 C++ 參考（Reference）與 C 語言指標（Pointer）的對比，下列敘述何者完全正確？",
         "參考在宣告時必須立即初始化且一生不可再改綁定其他物件，且不存在「空參考（Null Reference）」；指標可以不初始化、可隨時改指他處且可為 NULL",
         ["參考在宣告時必須立即初始化且一生不可再改綁定其他物件，且不存在「空參考（Null Reference）」；指標可以不初始化、可隨時改指他處且可為 NULL",
          "參考所佔的記憶體大小保證永遠為 0，指標佔 8 位元組",
          "可以建立「參考的陣列（Array of References）」",
          "參考可以使用 ++ 運算子改變其自身指向的記憶體位址"],
         "參考 vs 指標六大鐵則：1. 參考必須初始化（<code>int &r = a;</code>），指標不必；2. 參考無法重綁定（<code>r = b</code> 只是把 b 的值賦給 a，而非改綁定 b）；3. 無法建立 <code>int& arr[5]</code> 參考陣列；4. 不存在 NULL 參考；5. 不需要加星號解參考；6. 語意上更安全，不易發生懸置指標。"),
        ("在 C 語言中，函式宣告與定義時若省略參數清單寫為 <code>void foo();</code>，其與 <code>void foo(void);</code> 的嚴格語意差異為？",
         "foo() 表示接受「任意數量且未指定型態」的參數；foo(void) 則嚴格表示「絕不接受任何參數」",
         ["foo() 表示接受「任意數量且未指定型態」的參數；foo(void) 則嚴格表示「絕不接受任何參數」",
          "兩者在 C 語言中語意完全相同",
          "foo() 表示回傳 void，foo(void) 表示回傳 int",
          "foo(void) 是 C++ 特有語法，C 語言不支援"],
         "C 語言空參數清單陷阱：在 C 語言（C89/C99/C11）中，<code>int f();</code> 屬於舊式原型宣告，代表參數型態未指定（Unspecified parameters），呼叫 <code>f(1, 2, 3);</code> 編譯器不會報錯！只有嚴格寫成 <code>int f(void);</code>，編譯器才會在傳入任何參數時報錯。而在 C++ 中，<code>f()</code> 與 <code>f(void)</code> 語意相同，皆表示不接受任何參數。C23 標準已正式統一此規則。"),
        ("執行以下程式碼片段：<br><code>int a = 10; void change(int *p) { p = malloc(sizeof(int)); *p = 20; }<br>int main() { int *ptr = &a; change(ptr); printf(\"%d\", *ptr); return 0; }</code><br>終端機輸出的結果為？",
         "10",
         ["10",
          "20",
          "未定義垃圾值",
          "0"],
         "指標傳值的常見陷阱（傳遞指標本身）：在 <code>change(ptr)</code> 中，指標 ptr 的位址值被複製給參數 p。在 change 內部執行 <code>p = malloc(...)</code> 修改的僅僅是局部參數 p 的指向，使其指向 Heap 新空間，呼叫端的 ptr 依舊指向原本的變數 a！函式退出後 malloc 的記憶體發生洩漏，ptr 指向的 a 內容仍為 10。若要在函式內修改外部指標的指向，必須傳入雙重指標 <code>void change(int **p)</code>。"),
        ("執行以下遞迴函式：<br><code>int f(int n) { if (n <= 1) return 1; return f(n - 1) + f(n - 1); }<br>int main() { printf(\"%d\", f(4)); return 0; }</code><br>輸出的數值為何？",
         "8",
         ["8",
          "16",
          "4",
          "12"],
         "二分倍增遞迴追蹤：<br>f(1) = 1；<br>f(2) = f(1) + f(1) = 1 + 1 = 2 = 2^1；<br>f(3) = f(2) + f(2) = 2 + 2 = 4 = 2^2；<br>f(4) = f(3) + f(3) = 4 + 4 = 8 = 2^3。實質計算 2^(n-1)，故 f(4) = 8。"),
        ("在 C 語言中，將靜態函式庫（Static Library, .a / .lib）與動態連結函式庫（Dynamic Library, .so / .dll）鏈結進執行檔的時機與記憶體特性對比，何者完全正確？",
         "靜態庫在「編譯鏈結時期」將代碼完整拷貝融入執行檔中；動態庫在「程式載入或執行時期」動態映射，多個行程可共用同一份記憶體代碼",
         ["靜態庫在「編譯鏈結時期」將代碼完整拷貝融入執行檔中；動態庫在「程式載入或執行時期」動態映射，多個行程可共用同一份記憶體代碼",
          "動態庫必須將原始碼直接附在執行檔後方才能執行",
          "靜態庫執行速度永遠比動態庫慢十倍",
          "靜態庫生成的執行檔體積永遠小於動態庫生成的執行檔"],
         "靜態連結 vs 動態連結核心對比：靜態庫（Static Linking）將需要的函式二進位碼打包進可執行檔，執行檔獨立無依賴，但檔案體積大且更新庫時必須全部重新編譯。動態庫（Dynamic Linking）執行檔體積小，函式庫升級無需重編譯應用程式，且作業系統透過虛擬記憶體讓多個行程共享同一個 .so 唯讀代碼頁，大幅節省實體 RAM 空間。"),
        ("執行以下包含靜態區域變數的函式呼叫：<br><code>int calc(int x) { static int r = 0; r += x; return r; }<br>int main() { calc(2); calc(3); printf(\"%d\", calc(4)); return 0; }</code><br>印出的數值為何？",
         "9",
         ["9",
          "4",
          "7",
          "0"],
         "靜態累加器狀態追蹤：<br>1. calc(2)：r 變為 0 + 2 = 2；<br>2. calc(3)：r 變為 2 + 3 = 5；<br>3. calc(4)：r 變為 5 + 4 = 9，回傳 9。輸出 9。")
    ]

    # 4. 呼叫約定、堆疊指針、現代特性與函式進階 (19 題)
    stack_inline_data = [
        ("在 x86 架構常見的函式呼叫約定中，「cdecl」與「stdcall」在清理呼叫堆疊（Stack Cleanup）上的最主要差異為？",
         "cdecl 由呼叫端（Caller）負責平衡清理堆疊，因此支援可變參數；stdcall 由被呼叫端（Callee）負責清理堆疊",
         ["cdecl 由呼叫端（Caller）負責平衡清理堆疊，因此支援可變參數；stdcall 由被呼叫端（Callee）負責清理堆疊",
          "cdecl 由被呼叫端清理，stdcall 由呼叫端清理",
          "兩者皆不清理堆疊，由作業系統每小時定期垃圾回收",
          "cdecl 只能在 Linux 上使用，stdcall 只能在 macOS 上使用"],
         "呼叫約定（Calling Conventions）核心原理：<br>1. <code>cdecl</code>：C 語言預設約定。參數由右至左壓棧，因為只有 Caller 知道具體傳了多少個參數（如 printf(\"%d %d\", a, b)），所以必須由 Caller 在函式返回後執行 <code>add esp, 8</code> 平衡堆疊。<br>2. <code>stdcall</code>：Windows API 標準約定。Callee 在返回時使用 <code>ret 8</code> 自行清理堆疊，產生二進位代碼體積較小，但無法支援可變參數函式。"),
        ("在 x86-64 組合語言與 C 語言底層運行時中，暫存器 <code>RBP</code>（或 32 位元 <code>EBP</code>）與 <code>RSP</code>（或 <code>ESP</code>）的主要職責分工為？",
         "RBP 為堆疊框架基底指標（Frame Pointer），固定標記當前函式局部變數的基底位址；RSP 為堆疊頂端指標（Stack Pointer），動態指向堆疊目前最頂端",
         ["RBP 為堆疊框架基底指標（Frame Pointer），固定標記當前函式局部變數的基底位址；RSP 為堆疊頂端指標（Stack Pointer），動態指向堆疊目前最頂端",
          "RBP 專門儲存乘法運算結果，RSP 專門儲存除法餘數",
          "RBP 為指令指標指向下一條要執行的指令，RSP 為狀態旗標暫存器",
          "兩者職責完全相同，交替使用以分擔硬體負載"],
         "呼叫堆疊雙指標架構：當函式執行時，RSP 隨著 <code>push/pop</code> 或區域變數動態配置而不斷上下浮動；為了能夠以穩定的相對偏移量存取參數與區域變數，編譯器在函式前導序（Prologue）中執行 <code>push rbp; mov rbp, rsp;</code>，將 RBP 固定住。參數位於 <code>[RBP + offset]</code>，局部變數位於 <code>[RBP - offset]</code>。"),
        ("在二分搜尋演算法中，給定長度為 n 的已排序陣列，其在最成功情況（Best Case）與最差情況（Worst Case）下的時間複雜度分別為何？",
         "最佳情況 O(1)，最差情況 O(log n)",
         ["最佳情況 O(1)，最差情況 O(log n)",
          "最佳情況 O(log n)，最差情況 O(n)",
          "最佳與最差皆為 O(log n)",
          "最佳情況 O(1)，最差情況 O(n)"],
         "二分搜尋複雜度：Best Case 為第一次計算中點 <code>mid</code> 時該元素恰好就是目標值，僅需比較 1 次，複雜度為 O(1)。Worst Case 為目標值在最邊緣或根本不存在於陣列中，必須連續折半直到區間為空，最多比較 ⌊log2(n)⌋ + 1 次，複雜度為 O(log n)。"),
        ("合併排序（Merge Sort）的遞迴分治時間複雜度遞迴關係式為 <code>T(n) = 2T(n/2) + O(n)</code>，根據主定理（Master Theorem），其嚴格時間複雜度為何？",
         "O(n log n)",
         ["O(n log n)",
          "O(n^2)",
          "O(n)",
          "O(log n)"],
         "Merge Sort 遞迴複雜度推導：將長度為 n 的問題拆解為 2 個長度為 n/2 的子問題（2T(n/2)），子問題排序完畢後呼叫 Merge 函式以 O(n) 時間進行線性合併。遞迴樹共有 log2(n) 層，每一層所有節點合併花費總和皆為 cn。總工作量為 cn × log2(n) = O(n log n)。且該複雜度在最佳、最差、平均情況下皆穩定為 O(n log n)。"),
        ("快速排序（Quick Sort）在何種極端資料分佈狀況下會退化至最差時間複雜度 O(n^2)？如何有效避免此退化？",
         "陣列已經完全排序（或完全逆序），且固定選取第一個或最後一個元素作為基準值（Pivot）；防範策略為採用隨機化 Pivot 或三數中值法（Median-of-three）",
         ["陣列已經完全排序（或完全逆序），且固定選取第一個或最後一個元素作為基準值（Pivot）；防範策略為採用隨機化 Pivot 或三數中值法（Median-of-three）",
          "陣列元素全部為偶數時；防範為先全部加 1 變奇數",
          "陣列長度為 2 的冪次方時；防範為補入一個虛擬元素",
          "陣列含有負數時；防範為取絕對值"],
         "Quick Sort 最差情況退化剖析：若每次劃分（Partition）產生的兩個子數組長度分別為 0 與 n-1，遞迴式退化為 <code>T(n) = T(n-1) + O(n)</code>，遞迴樹退化成單鏈，時間複雜度暴增至 1+2+...+(n-1) = O(n^2)，呼叫堆疊深度達 O(n) 引發爆棧。透過三數取中（頭、尾、中間三數取中位數）作為 Pivot，能極高機率逼近平衡二分，維持 O(n log n)。"),
        ("在 C 語言標頭檔中定義小型工具函式時，通常推薦標記為 <code>static inline</code>，其最關鍵考量為？",
         "inline 提示編譯器原地展開以消除函式呼叫開銷，static 限制為內部鏈結以防止標頭檔被多個 .c 檔引入時發生符號重複定義（Multiple Definition）",
         ["inline 提示編譯器原地展開以消除函式呼叫開銷，static 限制為內部鏈結以防止標頭檔被多個 .c 檔引入時發生符號重複定義（Multiple Definition）",
          "強制函式只能在多執行緒下呼叫",
          "使函式不能存取任何全域變數",
          "將函式代碼加密為二進位保護智財權"],
         "static inline 標頭檔慣用法：若在標頭檔定義常規函式（如 <code>int max(int a, int b) { ... }</code>），當被多個 .c 檔案 <code>#include</code> 時，每個 .c 都會生成一個名為 max 的全域符號，鏈結時直接報錯重複定義。加上 <code>static</code> 賦予各編譯單元獨立副本，加上 <code>inline</code> 促使編譯器消除實體直接展開，零鏈結負擔。"),
        ("函式型式設計中，「純函式（<span class=\"en\">Pure Function</span>）」在軟體工程與平行運算中的兩大核心特徵為？",
         "相同的輸入必定永遠產生相同的輸出（無隨機或外部依賴），且執行過程中「絕無任何副作用（No Side Effects）」（不修改全域狀態或 I/O）",
         ["相同的輸入必定永遠產生相同的輸出（無隨機或外部依賴），且執行過程中「絕無任何副作用（No Side Effects）」（不修改全域狀態或 I/O）",
          "函式內部不使用任何 if 條件判斷，且行數嚴格少於 5 行",
          "函式完全不接受任何參數且傳回 void",
          "只能用 C 語言撰寫，不可用 C++ 或 Python 撰寫"],
         "純函式與引用透明性（Referential Transparency）：純函式不讀寫全域變數、不進行網路/磁碟 I/O、不修改指標實體內容。因結果僅由引數決定，編譯器可放心進行常數折疊（Constant Folding）、記憶化（Memoization / 快取）與無鎖高度平行運算，是現代高併發與函式語言程式設計（Functional Programming）之核心基礎。"),
        ("在 C++11 標準中，關鍵字 <code>auto</code> 的語意發生了何種根本變革？",
         "廢除了原有的「自動儲存類別」舊語意，轉變為根據初始化表達式由編譯器進行「自動變數型態推導（Type Deduction）」",
         ["廢除了原有的「自動儲存類別」舊語意，轉變為根據初始化表達式由編譯器進行「自動變數型態推導（Type Deduction）」",
          "強制所有變數在執行期自動被垃圾回收器銷毀",
          "自動為變數加上執行緒互斥鎖（Mutex）",
          "自動將整數變數放大為 64 位元"],
         "C++11 auto 革命：在 C89 中 <code>auto</code> 表示區域自動變數（因所有區域變數預設皆為 auto，故極少人寫）。C++11 賦予其全新使命：編譯期型態推導。例如 <code>auto it = my_map.begin();</code> 替代了冗長繁瑣的 <code>std::map<std::string, std::vector<int>>::iterator</code>，大幅提升可讀性與泛型程式設計維護效率。"),
        ("在 C++11 Lambda 運算式中，捕獲列表（Capture List）寫為 <code>[&]</code> 與 <code>[=]</code> 的語意差別為？",
         "[&] 代表以「傳參考（By Reference）」捕獲外層範疇的所有區域變數；[=] 代表以「傳值複製（By Value）」捕獲所有區域變數",
         ["[&] 代表以「傳參考（By Reference）」捕獲外層範疇的所有區域變數；[=] 代表以「傳值複製（By Value）」捕獲所有區域變數",
          "[&] 代表只捕獲指標，[=] 代表只捕獲字串",
          "[&] 代表忽略所有變數，[=] 代表拋出例外",
          "兩者語意完全相同，純屬語法糖"],
         "C++ Lambda 捕獲機制：Lambda 閉包（Closure）若需存取外層局部變數：<br>1. <code>[=]</code>：將外層變數值複製一份進入閉包內部（預設唯讀，需加 <code>mutable</code> 才能修改複本）；<br>2. <code>[&]</code>：以引用的方式直接存取外層原始變數，內部修改會直接反映到外層，但需注意若 Lambda 存活期長於外層變數（如異步回呼）可能造成懸置參照野指針崩潰。"),
        ("在軟體架構中，「函式指標陣列（<span class=\"en\">Jump Table / Dispatch Table</span>）」相較於大型 <code>switch-case</code> 結構的核心技術優勢為？",
         "將多路條件分支跳轉的時間複雜度由 O(n) 線性搜尋降低為 O(1) 陣列下標直接索引跳轉，且符合開閉原則（OCP），新增指令無需修改核心分派邏輯",
         ["將多路條件分支跳轉的時間複雜度由 O(n) 線性搜尋降低為 O(1) 陣列下標直接索引跳轉，且符合開閉原則（OCP），新增指令無需修改核心分派邏輯",
          "完全不需要消耗任何記憶體空間",
          "只能處理字串匹配，無法處理整數指令",
          "自動將所有函式轉換為組合語言以提高十倍頻寬"],
         "Jump Table 分派表優勢：例如 CPU 虛擬機或封包協定解析器（包含 256 種 Opcode）。寫 256 個 case 會產生長篇龐大分支；使用函式指標陣列 <code>void (*handlers[256])(Context*);</code>，收到 opcode 直接執行 <code>handlers[opcode](ctx);</code>，指令週期固定為 O(1)，代碼模組化極高。"),
        ("在非同步（Asynchronous）或事件驅動（Event-driven）系統中，「回呼函式（<span class=\"en\">Callback Function</span>）」的最主要運作模式為？",
         "呼叫端將自訂函式的指標傳入底層 API，當特定事件發生或耗時 I/O 任務完成時，由底層系統自動回頭呼叫該函式以處理結果",
         ["呼叫端將自訂函式的指標傳入底層 API，當特定事件發生或耗時 I/O 任務完成時，由底層系統自動回頭呼叫該函式以處理結果",
          "程式每秒鐘自動呼叫作業系統核心十萬次",
          "使用者在終端機手動輸入指令觸發程式重啟",
          "強制所有函式必須按照字母順序依次執行"],
         "Callback 機制本質：傳統同步呼叫（Blocking）會讓執行緒卡住等待網路回應。事件驅動架構中，發起非同步請求時攜帶回呼函式指標（及使用者上下文指針），當封包到達時由 Event Loop 自動觸發回呼執行。GUI 按鈕點擊監聽、網路伺服器 epoll / libuv 事件機制皆以此為核心。"),
        ("在 C 語言中模擬物件導向的「動態多型（Polymorphism）」行為，最經典的設計慣用法為？",
         "在結構體（struct）內部宣告函式指標成員（如 vtable 概念），不同的具體實體在初始化時將函式指標指向各自專屬的實作函式",
         ["在結構體（struct）內部宣告函式指標成員（如 vtable 概念），不同的具體實體在初始化時將函式指標指向各自專屬的實作函式",
          "在 C 語言中直接撰寫 class 與 virtual 關鍵字",
          "強制所有變數宣告為 void* 並進行暴力轉型",
          "使用 #define 巨集在編譯時重複複製代碼"],
         "C 語言實現 OOP 多型（如 Linux 驅動 file_operations）：Linux 核心中 <code>struct file_operations { int (*read)(...); int (*write)(...); };</code>。鍵盤驅動、滑鼠驅動、硬碟驅動各自定義自己的 read/write 函式並掛載進該結構體。高層通用 VFS 系統只需呼叫 <code>file->f_op->read(...)</code> 即可達成動態多型分派。"),
        ("執行以下遞迴數值累加函式追蹤：<br><code>int f(int n) { if (n <= 0) return 0; return n + f(n - 2); }<br>int main() { printf(\"%d\", f(6)); return 0; }</code><br>輸出的數值為何？",
         "12",
         ["12",
          "6",
          "21",
          "8"],
         "偶數步進累加追蹤：<br>f(6) = 6 + f(4)<br>= 6 + 4 + f(2)<br>= 6 + 4 + 2 + f(0)<br>= 6 + 4 + 2 + 0 = 12。"),
        ("執行以下包含靜態變數的複合函式追蹤：<br><code>int sub(int x) { static int c = 5; c -= x; return c; }<br>int main() { printf(\"%d \", sub(1)); printf(\"%d\", sub(2)); return 0; }</code><br>輸出的兩個數值依序為何？",
         "4 2",
         ["4 2",
          "4 3",
          "4 4",
          "5 3"],
         "靜態變數遞減追蹤：c 初始為 5。<br>第 1 次呼叫 sub(1)：c = 5 - 1 = 4，回傳並印出 4；<br>第 2 次呼叫 sub(2)：c = 4 - 2 = 2，回傳並印出 2。輸出 4 2。"),
        ("執行以下字串長度遞迴計算函式：<br><code>int my_len(const char *s) { if (*s == '\\0') return 0; return 1 + my_len(s + 1); }<br>int main() { printf(\"%d\", my_len(\"TEST\")); return 0; }</code><br>印出的長度數值為何？",
         "4",
         ["4",
          "5",
          "3",
          "0"],
         "遞迴求字串長度步進追蹤：<br>my_len(\"TEST\") = 1 + my_len(\"EST\") = 1 + 1 + my_len(\"ST\") = 1 + 1 + 1 + my_len(\"T\") = 1 + 1 + 1 + 1 + my_len(\"\") = 4 + 0 = 4。每次將指針向前移動一個字元（s + 1），直到遇到結尾空字元 <code>\\0</code> 返回 0。"),
        ("在軟體工程中，「高階函式（<span class=\"en\">Higher-Order Function</span>）」的精準定義為？",
         "接受一個或多個函式作為引數，或者將一個函式作為回傳值的函式",
         ["接受一個或多個函式作為引數，或者將一個函式作為回傳值的函式",
          "執行時間複雜度達到 O(n^3) 以上的複雜演算法函式",
          "只有作業系統核心層級才能呼叫的特權函式",
          "完全由組合語言手工撰寫的高效能函式"],
         "高階函式定義：例如 C 語言的 <code>qsort(base, num, size, cmp)</code> 接收比較器函式指標作為參數；或函式傳回一個函式指標（如柯里化 Currying 概念）。高階函式將函式視為「一等公民（First-class citizen）」，大幅提高演算法重用度與抽象能力。"),
        ("執行以下二分次方快速冪（Fast Power）遞迴演算法追蹤：<br><code>long long power(int x, int n) { if (n == 0) return 1; long long half = power(x, n / 2); if (n % 2 == 0) return half * half; return half * half * x; }</code><br>計算 <code>power(2, 10)</code> 的回傳值與遞迴時間複雜度分別為何？",
         "1024；時間複雜度為 O(log n)",
         ["1024；時間複雜度為 O(log n)",
          "1024；時間複雜度為 O(n)",
          "512；時間複雜度為 O(log n)",
          "2048；時間複雜度為 O(n log n)"],
         "快速冪演算法分析：一般循環相乘計算 x^n 需相乘 n 次，時間複雜度為 O(n)。快速冪藉由折半遞迴：若 n 為偶數，x^n = (x^(n/2))^2；若為奇數，x^n = (x^(n/2))^2 * x。每次將指數 n 除以 2，遞迴深度僅為 ⌈log2(n)⌉ 層。計算 2^10 = 1024 僅需 4 次相乘，極具效能優勢。"),
        ("執行以下陣列最大值遞迴查詢函式：<br><code>int get_max(int a[], int n) { if (n == 1) return a[0]; int m = get_max(a, n - 1); return (a[n - 1] > m) ? a[n - 1] : m; }<br>int main() { int a[] = {3, 9, 2, 5}; printf(\"%d\", get_max(a, 4)); return 0; }</code><br>終端機輸出的數值為何？",
         "9",
         ["9",
          "5",
          "3",
          "2"],
         "遞迴找最大值追蹤：<br>get_max(a, 1) 回傳 a[0] = 3；<br>get_max(a, 2) 比較 a[1]=9 與 3，回傳 9；<br>get_max(a, 3) 比較 a[2]=2 與 9，回傳 9；<br>get_max(a, 4) 比較 a[3]=5 與 9，回傳 9。輸出 9。"),
        ("在軟體建置系統中，將函式的宣告放在 <code>.h</code> 標頭檔，而將其實作放在 <code>.c</code> 來源檔的最關鍵好處為？",
         "支援「分離編譯（Separate Compilation）」與「增量編譯（Incremental Compilation）」，修改單一實作時僅需重編譯該 .c 檔而無需重新編譯整個專案",
         ["支援「分離編譯（Separate Compilation）」與「增量編譯（Incremental Compilation）」，修改單一實作時僅需重編譯該 .c 檔而無需重新編譯整個專案",
          "使生成的二進位執行檔體積縮小 100 倍",
          "強制所有函式自動變成 inline 內嵌函式",
          "完全消除所有執行期記憶體洩漏風險"],
         "模組化與分離編譯價值：若將所有實作都寫在標頭檔，一旦修改幾行程式碼，所有引用該標頭檔的數百個 .c 檔案全部必須重新編譯（編譯時間長達數小時）。透過標頭檔暴露穩定介面宣告，實作隔離在各個獨立編譯單元（Translation Unit），make/ninja 等建置工具只重編譯受影響的 .c 目標檔再進行快速鏈結，是工程化架構核心。")
    ]

    # Combine datasets
    all_datasets = [
        ("參數傳遞機制、傳值傳址傳參考與安全性", param_data),
        ("遞迴演算法追蹤、呼叫堆疊與時間複雜度", recursion_data),
        ("變數範疇、生命週期與記憶體區段解析", scope_data),
        ("呼叫約定、堆疊指針與現代語言進階特性", stack_inline_data)
    ]

    for tag, dataset in all_datasets:
        for stem, ans_s, opts, expl in dataset:
            choices = [("A", opts[0]), ("B", opts[1]), ("C", opts[2]), ("D", opts[3])]
            qs.append({
                "tag": tag,
                "stem": stem,
                "choices": choices,
                "ans": "A",
                "ans_text": f"(A) {ans_s}",
                "explanation": f"""<strong>【函式呼叫機制、遞迴演算法與堆疊生命週期深度步進解析】</strong><br>
<div class="step-box">
  <div class="step-title">📝 呼叫堆疊框架、遞迴樹回溯追蹤與變數作用域狀態推演</div>
  <ul class="step-list">
    <li class="step-item"><span class="step-badge formula">步驟 1</span><strong>確立函式呼叫約定（Calling Convention）、參數傳遞語意與終止條件</strong><br>
      ‧ 本題依據 C/C++ 標準呼叫堆疊模型、遞迴關係式數學推演與變數存儲期規範嚴格展開。
    </li>
    <li class="step-item"><span class="step-badge check">步驟 2</span><strong>執行期狀態追蹤、遞迴壓棧回溯計算與安全性分析</strong><br>
      ‧ {expl}
    </li>
  </ul>
</div>
<br><strong>【各選項詳細對錯解析】</strong><br>
‧ <strong>(A) 正確</strong>：{opts[0]}。<br>
‧ <strong>(B) 錯誤</strong>：{opts[1]}（遞迴步數計算錯誤或參數傳遞語意混淆）。<br>
‧ <strong>(C) 錯誤</strong>：{opts[2]}（堆疊生命週期判斷失誤或邊界條件不符）。<br>
‧ <strong>(D) 錯誤</strong>：{opts[3]}（非 C/C++ 標準之正確行為或結論推導錯誤）。"""
            })

    return qs

if __name__ == '__main__':
    qs = get_prog_part3_questions()
    print(f"Total Part 3 questions generated: {len(qs)}")
