-- 自動排班系統 — Supabase 資料表結構
--
-- 用法:Supabase 後台 > SQL Editor > New query,把整份貼上去按 Run。
-- 這份跟程式啟動時自動建表的內容完全一樣,可重複執行不會出錯。
--
-- 想確認有沒有成功,回到 Table Editor 應該會看到 6 張表。

CREATE TABLE IF NOT EXISTS employees (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT    NOT NULL,
    employee_no         TEXT,
    phone               TEXT    DEFAULT '',
    line_user_id        TEXT,
    role                TEXT    NOT NULL DEFAULT 'staff',
    skills              TEXT    NOT NULL DEFAULT '',
    max_shifts_per_week INTEGER NOT NULL DEFAULT 5,
    min_shifts_per_week INTEGER NOT NULL DEFAULT 0,
    active              INTEGER NOT NULL DEFAULT 1,
    created_at          TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'Asia/Taipei','YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_emp_line ON employees(line_user_id)
    WHERE line_user_id IS NOT NULL AND line_user_id <> '';

CREATE TABLE IF NOT EXISTS shift_types (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT    NOT NULL,
    code               TEXT    NOT NULL DEFAULT '',
    start_time         TEXT    NOT NULL,
    end_time           TEXT    NOT NULL,
    required_headcount INTEGER NOT NULL DEFAULT 1,
    required_skill     TEXT    NOT NULL DEFAULT '',
    color              TEXT    NOT NULL DEFAULT '#D98E5A',
    sort_order         INTEGER NOT NULL DEFAULT 0,
    active             INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS leave_requests (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    start_date  TEXT    NOT NULL,
    end_date    TEXT    NOT NULL,
    leave_type  TEXT    NOT NULL DEFAULT '特休',
    reason      TEXT    NOT NULL DEFAULT '',
    status      TEXT    NOT NULL DEFAULT 'pending',
    source      TEXT    NOT NULL DEFAULT 'web',
    created_at  TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'Asia/Taipei','YYYY-MM-DD HH24:MI:SS'),
    decided_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_leave_emp ON leave_requests(employee_id, start_date);

CREATE TABLE IF NOT EXISTS assignments (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date     TEXT    NOT NULL,
    shift_type_id INTEGER NOT NULL REFERENCES shift_types(id) ON DELETE CASCADE,
    employee_id   INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    locked        INTEGER NOT NULL DEFAULT 0,
    status        TEXT    NOT NULL DEFAULT 'draft',
    note          TEXT    NOT NULL DEFAULT '',
    created_at    TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'Asia/Taipei','YYYY-MM-DD HH24:MI:SS'),
    UNIQUE(work_date, shift_type_id, employee_id)
);
CREATE INDEX IF NOT EXISTS idx_assign_date ON assignments(work_date);
CREATE INDEX IF NOT EXISTS idx_assign_emp ON assignments(employee_id, work_date);

CREATE TABLE IF NOT EXISTS swap_requests (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id        INTEGER NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    requester_id         INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    target_shift_type_id INTEGER REFERENCES shift_types(id) ON DELETE SET NULL,
    target_date          TEXT,
    reason               TEXT    NOT NULL DEFAULT '',
    status               TEXT    NOT NULL DEFAULT 'pending',
    source               TEXT    NOT NULL DEFAULT 'web',
    created_at           TEXT    NOT NULL DEFAULT to_char(now() AT TIME ZONE 'Asia/Taipei','YYYY-MM-DD HH24:MI:SS'),
    decided_at           TEXT
);

CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 打開 Row Level Security 但不建任何 policy。
-- 效果:Supabase 對外的 anon / authenticated 金鑰完全讀不到這些表,
-- 我們用資料庫帳號直連則不受影響(該角色會略過 RLS)。
-- 員工姓名電話是個資,不該讓拿到前端金鑰的人直接撈走。
ALTER TABLE employees      ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_types    ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments    ENABLE ROW LEVEL SECURITY;
ALTER TABLE swap_requests  ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings       ENABLE ROW LEVEL SECURITY;
